### ISSUE TITLE
SmartShift control for MX Anywhere 3

### ISSUE THREAD

**Issue by prurigro** [pwr-Solaar/Solaar#1048]
First, thanks for Solaar-- I honestly don't think I could use this mouse without it :)

**Information**
- Solaar version: 1.0.4-67-g1c6f289
- Distribution: Arch Linux
- Kernel version: Linux 5.10.7-arch1-1 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
Wired Devices
  1: MX Anywhere 3
     Device path  : /dev/hidraw4
     USB id       : 046d:B025
     Codename     : MX Anywhere 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: ?
     Model ID:      B02540900000
     Unit ID:       0DDCDCA5
        Bootloader: BL1 13.00.B0014
          Firmware: MPM 24.00.B0014
             Other: 
     Supports 30 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 13.00.B0014 000095D7D19A
            Firmware: Firmware MPM 24.00.B0014 B02595D7D19A
            Firmware: Other   
            Unit ID: 0DDCDCA5  Model ID: B02540900000  Transport IDs: {'btleid': 'B025', 'wpid': '4090'}
         3: DEVICE NAME            {0005}   
            Name: MX Anywhere 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
         8: UNIFIED BATTERY        {1004}   
         9: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '196': 196}
            Key/Button Diversion: {'82': 0, '83': 0, '86': 0, '196': 0, '215': 0}
        10: CHANGE HOST            {1814}   
            Change Host: 1:command
        11: unknown:2250           {2250}   
        12: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI): 4000
        13: unknown:2111           {2111}   
        14: HIRES WHEEL            {2121}   
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            Low resolution mode
            HID notification
            Scroll Wheel Direction: False
            Scroll Wheel Resolution: False
        15: unknown:2251           {2251}   
        16: DFUCONTROL SIGNED      {00C2}   
        17: DEVICE RESET           {1802}   internal, hidden
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: unknown:1812           {1812}   internal, hidden
        21: OOBSTATE               {1805}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:18A1           {18A1}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1861           {1861}   internal, hidden
        27: unknown:9300           {9300}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9205           {9205}   internal, hidden
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         6: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 90%, discharging.
```
</details>

**Is your feature request related to a problem? Please describe.**

The logitech website shows an option for controlling SmartShift on the MX Anywhere 3 [here](https://support.logi.com/hc/en-us/articles/360053831734-Getting-Started-MX-Anywhere-3), but the configuration option isn't currently available in Solaar.

**Describe the solution you'd like**

Getting the option working in Solaar would be amazing. I can help test if necessary.

**Describe alternatives you've considered**

I noticed that other mice seem to use `2110`, which the MX Anywhere 3 doesn't have. It does have a `2111` which I suspect is the same feature but expecting different parameters. I tried patching Solaar to use 2111 for SmartShift and attempted to configure it using that, but attempting to change the value didn't work.

I also tried the other two unknown values that aren't internal/hidden, and 2250 similarly failed to adjust the value while 2251 crashed Solaar.

**Additional context**

Thanks again!

**Comment by pfps** [comment]
Solaar has this for feature 2110.  Feature 2111 appears to be new, and is not even in the list of HID++ features in Solaar.  It may be possible to get information from Logitech on this feature.  Stay tuned.

**Comment by pfps** [comment]
PR #1109 should add the ability to change how scrolling works on the MX Anywhere 3.  It's  not exactly the same as in Logitech Options, but should provide equivalent functionality.  Give it a try and report back how it works.

To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1109, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1109/head:pull_1109
git checkout pull_1109
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1109
git fetch origin pull/1109/head
git reset --hard FETCH_HEAD
```

**Comment by prurigro** [comment]
Hey, thanks for putting this together! this definitely works! When the value is 0 there's no resistance, and when it's 49 the resistance is quite hard.

One thing I noticed is that it seems to disable the logic that moves between 0 resistance and whatever the currently configured resistance when you scroll quickly, and there's no way to re-enable this so maybe there's a separate option, or maybe that's `50` which I can't test (see below).

When you select 50 a loading spinner appears that never goes away, the setting doesn't change and the following error appears:

```
12:21:30,955     INFO [AsyncUI] solaar.configuration: saved {'000000000000:00000000': {'_modelId': '000000000000', '_name': 'MX Anywhere 3', '_unitId': '00000000', 'dpi': 4000}, '000000000000:120D0000': {'_modelId': '000000000000', '_name': 'MX Anywhere 3', '_unitId': '120D0000', 'dpi': 4000}, 'B02540900000:0DDCDCA5': {'_modelId': 'B02540900000', '_name': 'MX Anywhere 3', '_sensitive': {'dpi': False, 'smart-shift': True}, '_unitId': '0DDCDCA5', 'divert-keys': {'196': 0, '215': 0, '82': 0, '83': 0, '86': 0}, 'dpi': 4000, 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': {'196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 50}, '_version': '1.0.5'} to /home/prurigro/.config/solaar/config.json
12:21:31,180    ERROR [AsyncUI] logitech_receiver.base: (20) device 0 error on feature request {0D2D}: 2 = invalid argument
12:21:31,181    ERROR [AsyncUI] solaar.tasks: calling <function _write_async.<locals>._do_write at 0x7f600eb60e50>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/tasks.py", line 67, in run
    function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/solaar/ui/config_panel.py", line 50, in _do_write
    v = setting.write(v)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings.py", line 166, in write
    reply = self._rw.write(self._device, data_bytes)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 345, in write
    return super(_SmartShiftRW, self).write(device, data)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings.py", line 551, in write
    reply = device.feature_request(self.feature, self.write_fnid, data_bytes, no_reply=self.no_reply)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/device.py", line 441, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params, no_reply=no_reply)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/hidpp20.py", line 1026, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params, no_reply=no_reply)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/device.py", line 430, in request
    return _base.request(
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 435, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 0, 'request': 3373, 'error': 2, 'params': b'\x02\xff\xff'}
```

when you restart solaar the following error appears (even without debug mode enabled):

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/ui/__init__.py", line 153, in <lambda>
    application.connect('startup', lambda app, startup_hook: _startup(app, startup_hook, use_tray, show_window), startup_hook)
  File "/usr/lib/python3.9/site-packages/solaar/ui/__init__.py", line 113, in _startup
    startup_hook()
  File "/usr/lib/python3.9/site-packages/solaar/listener.py", line 301, in start_all
    _process_receiver_event('add', device_info)
  File "/usr/lib/python3.9/site-packages/solaar/listener.py", line 381, in _process_receiver_event
    _start(device_info)
  File "/usr/lib/python3.9/site-packages/solaar/listener.py", line 286, in _start
    receiver.status.changed(True)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/status.py", line 310, in changed
    s.apply()
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings.py", line 182, in apply
    self.write(value, save=False)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings.py", line 166, in write
    reply = self._rw.write(self._device, data_bytes)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 345, in write
    return super(_SmartShiftRW, self).write(device, data)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings.py", line 551, in write
    reply = device.feature_request(self.feature, self.write_fnid, data_bytes, no_reply=self.no_reply)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/device.py", line 441, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params, no_reply=no_reply)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/hidpp20.py", line 1026, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params, no_reply=no_reply)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/device.py", line 430, in request
    return _base.request(
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 435, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 0, 'request': 3372, 'error': 2, 'params': b'\x02\xff\xff'}
```

Let me know if you need any additional testing!

**Comment by prurigro** [comment]
I realized it does disengage on 49, you just have to spin it really really fast so I assume the default is probably something less than 49. In that respect, maybe the "50" value is just above what the spec allows for?

**Comment by pfps** [comment]
I need to chase down the but you reported yet.

The values should range from 1 to 255, from the documentation, but the reasonable range is probably just up to 50, so getting disengagement at 49 requires a very fast spin.  The software is supposed to turn 50 to 255 but maybe that's not working for your mouse.

**Comment by pfps** [comment]
I forgot to make one change that I wanted to, resulting in incorrectly-formed commands for the MX Anywhere 3.   Please test again, using the download method described above.

**Comment by prurigro** [comment]
Hey, sorry about the delay-- I just tested and 50 now works perfectly! No errors, and unlike 49 I can't seem to spin it fast enough to have it disengage. I'd call this a win- thanks so much!

I'm not sure if you prefer to close issues once support is in or if you'd rather keep them open until they've made it into a release, but I'd consider this solved at this point if you want to close it.

Thanks again!

**Comment by prurigro** [comment]
I realized the PR you created could probably replace this issue as far as searchability is concerned, and since the PR now works perfectly (tested heavily for a couple of days now) I'll close this issue. Thanks again!
