### ISSUE TITLE
Logitech Zone Wireless Unifying receiver not detected

### ISSUE THREAD

**Issue by rogelioperez000** [pwr-Solaar/Solaar#1060]
**Information**
- Solaar version: `1.0.4`
- Distribution: `Ubuntu 18.04`
- Kernel version: `Linux 5.4.0-60-generic x86_64 GNU/Linux`
- Output of `solaar show`:
```
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 195, in run
    raise Exception('No devices found')
Exception: No devices found
```

**Describe the bug**
[Logitech Zone Wireless](https://www.logitech.com/en-us/products/headsets/zone-wireless-bluetooth.html) Unifying receiver is not being detected.

**To Reproduce**
1. Plug Logitech Zone Wireless Unifying receiver in
2. Run solaar show 
3. Device no detected

**Additional context**
If I run lsusb I get this: 
```
Bus 001 Device 006: ID 046d:0a90 Logitech, Inc.
```

**Comment by pfps** [comment]
Unifying receivers have to be added explicitly to Solaar and yours might not be present.

But there might be another problem.  The USB ID for your receiver looks unusual, and may indicate that your receiver is in firmware-update mode.  The remedy for this should be to unplug and replug the receiver.  If that changes its USB ID then that is likely to be the problem and Solaar should then work with your receiver.

If not, then what you should do is to download Solaar from this repository and add the receiver yourself.  The file that needs to be changed is lib/logitech_receiver/base_usb.py.  Two lines need to be added - one after line 113 to define your receiver and one after line 144 to add your receiver to the list of recognized receivers.  The needed code should be fairly obvious.

But it also might be that Linux doesn't understand this receiver very well.  To diagnose this possibility run `usb-devices` (hopefully it is installed) and see what driver is being used for your receiver.  You should see multiple interfaces with driver usbhid.  If only audio drivers are shown then it is likely that the problem is with Linux.

**Comment by pfps** [comment]
See #1046 for more information about a firmware update mode problem.

**Comment by rogelioperez000** [comment]
Thanks for your response!

When I run `usb-devices` I can see one interface with driver usbhid:
```
T:  Bus=01 Lev=01 Prnt=01 Port=01 Cnt=02 Dev#= 15 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=046d ProdID=0a90 Rev=36.06
S:  Manufacturer=Logitech
S:  Product=Zone Wireless
S:  SerialNumber=1923ML0021D8
C:  #Ifs= 4 Cfg#= 1 Atr=80 MxPwr=96mA
I:  If#= 0 Alt= 0 #EPs= 0 Cls=01(audio) Sub=01 Prot=00 Driver=snd-usb-audio
I:  If#= 1 Alt= 0 #EPs= 0 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
I:  If#= 2 Alt= 1 #EPs= 1 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
I:  If#= 3 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
```
Now trying fwdupmgr...

**Comment by rogelioperez000** [comment]
So far I tried:
- Unplugged and replugged the receiver
- Added lines:
```
114: UNIFYING_RECEIVER_0A90 = _unifying_receiver(0x0a90)
144: UNIFYING_RECEIVER_0A90,
```
- Ran `fwupdmgr get-devices`, saw the receiver listed there, ran `fwupdmgr get-udpates` then `fwupdmgr udpate`, then rebooted, but the USB ID remains the same. Now I run `fwupdmgr get-devices` and I don't see the device listed anymore.

Anything else I can do?

**Comment by pfps** [comment]
I forgot to mention that you probably need to update the udev rule.  For more information see https://pwr-solaar.github.io/Solaar/installation
Then unplug and replug your receiver.
Run `ls -l /dev/hidraw*`.  There should be one or more entries that have a + after the access bits.  If not, then Solaar's udev rule will need to be updated.  In any case run `bin/solaar -dd` and post the output.

But I expect that there is still another problem.  Please run `lsusb -v -s b:d` where b and d are the bus and device numbers for the receiver and post the output.  I expect that this receiver is using a different interface number for the HID++ interface that Solaar uses.  With luck, a simple change to Solaar will get this receiver to work but it may be that there needs to be some changes to Linux drivers before Solaar can work on it.

**Comment by rogelioperez000** [comment]
Updates:
- I copied `rules.d/42-logitech-unify-permissions.rules` from Solaar to `/etc/udev/rules.d/`
- I reloaded udev rules with `sudo udevadm control --reload-rules`
- I ran `ls -l /dev/hidraw*` 
```crw-rw----+ 1 root root 240, 0 Jan 29 11:15 /dev/hidraw0
crw-------  1 root root 240, 1 Jan 29 01:36 /dev/hidraw1
crw-rw----+ 1 root root 240, 2 Jan 29 10:50 /dev/hidraw2
crw-rw----+ 1 root root 240, 3 Jan 29 10:50 /dev/hidraw3
crw-rw----+ 1 root root 240, 5 Jan 29 10:50 /dev/hidraw5
```
- I ran `sudo solaar -dd`:
```11:37:48,277     INFO [MainThread] root: language en_US (UTF-8), translations path None
11:37:48,389  WARNING [MainThread] logitech_receiver.diversion: X11 not available - rules will not be activated
11:37:48,392    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
11:37:48,397     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
11:37:48,503    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
11:37:48,504    DEBUG [AsyncUI] solaar.tasks: started
11:37:48,504     INFO [MainThread] solaar.ui.notify: starting desktop notifications
11:37:48,507    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/share/solaar/lib
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/rogelio/.local/share/solaar/icons
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/lib/share/solaar/icons
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
11:37:48,508    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/rogelio/.local/share/icons', '/home/rogelio/.icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps']
11:37:48,540     INFO [MainThread] solaar.listener: starting receiver listening threads
11:37:48,542    DEBUG [MainThread] solaar.ui: activate
```
- I ran `lsusb -v -s 046d:0a90` and there's no output 
- I ran `lsusb -v` and extracted the device info (attached)

[lsusb.txt](https://github.com/pwr-Solaar/Solaar/files/5894419/lsusb.txt)

**Comment by pfps** [comment]
You need the USB bus and device numbers (1:9) in your attached output, not the manufacturer and product numbers.

**Comment by pfps** [comment]
It appears that you are using Wayland so the new Solaar rule feature won't be used.  That is independent of your problem, of course.

**Comment by pfps** [comment]
Once you have the udev rule installed you should not be using `sudo` to run Solaar.  Instead go to the clone directory and run `bin/solaar -dd`.

Your output looks rather unusual.  What happens when you run Solaar?  Does the main window appear?  Is there a receiver or device there?  You may need to terminate an existing Solaar process.

Please run `bin/Solaar -dd show` (after terminating any existing Solaar processes) and post the output.  That will provide information on the receivers and devices Solaar can access.

**Comment by pfps** [comment]
I expect that the remaining problem is that this receiver uses interface number 3, which is not what Solaar expects.   But I want to rule out other potential problems before trying to fix this one.

**Comment by rogelioperez000** [comment]
Updates:
- I cloned the repo (I was using a binary installed from a package before)
- I ran `pkill solaar` to terminate existing Solaar process
- I ran `bin/solaar -dd` and I can see the main window without any receivers:
![image](https://user-images.githubusercontent.com/78165926/106290374-29d5f100-6229-11eb-85a7-55f0e771cebc.png)
- I ran `pkill solaar` again to terminate existing Solaar process
- I ran `bin/solaar -dd show`:
```11:58:27,210    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
solaar: error: Traceback (most recent call last):
  File "/home/rogelio/repo/Solaar/lib/solaar/cli/__init__.py", line 195, in run
    raise Exception('No devices found')
Exception: No devices found
```

**Comment by pfps** [comment]
OK, one problem is the mismatch of interface numbers.  To fix that in base_usb.py add 
```
_unifying_receiver_3 = lambda product_id: {
    'vendor_id': 0x046d,
    'product_id': product_id,
    'usb_interface': 3,
    'hid_driver': _DRIVER,  # noqa: F821
    'name': 'Zone Unifying Receiver'
}
```
after line 50 and change
```
UNIFYING_RECEIVER_0A90 = _unifying_receiver(0x0a90)
```
to
```
UNIFYING_RECEIVER_0A90 = _unifying_receiver_3(0x0a90)
```

Try `bin/solaar -dd show`

**Comment by rogelioperez000** [comment]
I'm back to this!
I applied the changes from the previous comment and now I can see the receiver in the Solaar UI!

![Selection_998](https://user-images.githubusercontent.com/78165926/107471133-65d35500-6b4b-11eb-8b10-a9282bf387a5.png)

However the "Pair new device" button is greyed out.
Also, that's the solar binary that's installed, the one cloned still doesn't recognizes it.
I get similar results in the CLI:

```rogelio@9n902z2:~/repo/Solaar$ bin/solaar -dddddd show
02:48:54,890    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
solaar: error: Traceback (most recent call last):
  File "/home/rogelio/repo/Solaar/lib/solaar/cli/__init__.py", line 195, in run
    raise Exception('No devices found')
Exception: No devices found

rogelio@9n902z2:~/repo/Solaar$ solaar -dddddd show
02:51:45,888    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
02:51:45,900    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B5 030000]
02:51:47,702  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B5} params [03]
02:51:47,702    DEBUG [MainThread] solaar.cli: [/dev/hidraw0] => <ZoneUnifyingReceiver(/dev/hidraw0,10)>
02:51:47,782    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
02:51:48,684  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
Zone Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:0A90
  Serial       : None
02:51:48,684    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 81F1 010000]
02:51:49,586  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {81F1} params [01]
  Has 0 paired device(s) out of a maximum of 1.
02:51:49,586    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
02:51:50,489  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
02:51:50,489    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8100 000000]
02:51:51,392  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8100} params []
02:51:51,392    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B3 000000]
02:51:53,195  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B3} params []
02:51:53,196    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
02:51:54,098  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
```
Is there anything else I should try before giving up?
Has anyone ever used this receiver with Solaar before?

**Comment by pfps** [comment]
If you changed the udev rule then that would affect both the installed Solaar and the modified cloned Solaar.  But I don't see how the installed Solaar recognizes the receiver at all.

So please provide output of `solaar -dd show` from outside the cloned directory and output of `bin/solaar -dd show` from the cloned directory.

**Comment by rogelioperez000** [comment]
I'm sorry, I just realized all this time I was modifying the installed version of base_usb.py `/usr/share/solaar/lib/logitech_receiver/base_usb.py` instead of the cloned version of it `/home/rogelio/repo/Solaar/lib/logitech_receiver/base_usb.py`.
Now I updated the cloned version with the same content and I get the same behavior with both binaries, the receiver is recognized but the `Pair new device` button is greyed out.
The outputs of `solaar -dddddd show` for both versions seem to be identical as well.

```rogelio@9n902z2:~/repo/Solaar$ bin/solaar -dddddd show
23:58:05,544    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
23:58:05,556    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B5 030000]
23:58:07,359  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B5} params [03]
23:58:07,359    DEBUG [MainThread] solaar.cli: [/dev/hidraw0] => <ZoneUnifyingReceiver(/dev/hidraw0,10)>
23:58:07,364    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
23:58:08,267  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
Zone Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:0A90
  Serial       : None
23:58:08,267    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 81F1 010000]
23:58:09,169  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {81F1} params [01]
  Has 0 paired device(s) out of a maximum of 1.
23:58:09,170    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
23:58:10,073  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
23:58:10,073    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8100 000000]
23:58:10,975  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8100} params []
23:58:10,976    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B3 000000]
23:58:12,779  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B3} params []
23:58:12,779    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
23:58:13,682  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []

rogelio@9n902z2:~/repo/Solaar$ cd ~
rogelio@9n902z2:~$ solaar -dddddd show
23:58:22,826    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
23:58:22,837    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B5 030000]
23:58:24,640  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B5} params [03]
23:58:24,641    DEBUG [MainThread] solaar.cli: [/dev/hidraw0] => <ZoneUnifyingReceiver(/dev/hidraw0,10)>
23:58:24,646    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
23:58:25,548  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
Zone Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:0A90
  Serial       : None
23:58:25,549    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 81F1 010000]
23:58:26,451  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {81F1} params [01]
  Has 0 paired device(s) out of a maximum of 1.
23:58:26,452    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
23:58:27,354  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
23:58:27,355    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8100 000000]
23:58:28,257  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8100} params []
23:58:28,257    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B3 000000]
23:58:30,060  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B3} params []
23:58:30,061    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
23:58:30,963  WARNING [MainThread] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8102} params []
```

**Comment by pfps** [comment]
OK, there must be something wrong with the pairing logic.  I'll investigate.

**Comment by pfps** [comment]
Do you have a keyboard or mouse paired with the receiver?   

Please also post the output of `lsusb` and  `lsusb -t`.

**Comment by pfps** [comment]
And also `lsusb -vv -d 046d:0a90`

**Comment by rogelioperez000** [comment]
Hello Peter,

I don't have a keyboard or mouse paired with the receiver.
Here's the output of those commands:

```rogelio@9n902z2:~$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 413c:81d7 Dell Computer Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0bda:58fd Realtek Semiconductor Corp. 
Bus 001 Device 002: ID 046d:0a90 Logitech, Inc. 
Bus 001 Device 005: ID 8087:0029 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
rogelio@9n902z2:~$ lsusb -t
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 10000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
    |__ Port 4: Dev 2, If 0, Class=Communications, Driver=cdc_mbim, 5000M
    |__ Port 4: Dev 2, If 1, Class=CDC Data, Driver=cdc_mbim, 5000M
    |__ Port 4: Dev 2, If 2, Class=Vendor Specific Class, Driver=option, 5000M
    |__ Port 4: Dev 2, If 3, Class=Vendor Specific Class, Driver=option, 5000M
    |__ Port 4: Dev 2, If 4, Class=Vendor Specific Class, Driver=option, 5000M
    |__ Port 4: Dev 2, If 5, Class=Vendor Specific Class, Driver=option, 5000M
    |__ Port 4: Dev 2, If 6, Class=Vendor Specific Class, Driver=, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
    |__ Port 2: Dev 2, If 2, Class=Audio, Driver=snd-usb-audio, 12M
    |__ Port 2: Dev 2, If 0, Class=Audio, Driver=snd-usb-audio, 12M
    |__ Port 2: Dev 2, If 3, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 2: Dev 2, If 1, Class=Audio, Driver=snd-usb-audio, 12M
    |__ Port 6: Dev 4, If 2, Class=Video, Driver=uvcvideo, 480M
    |__ Port 6: Dev 4, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 6: Dev 4, If 3, Class=Video, Driver=uvcvideo, 480M
    |__ Port 6: Dev 4, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 10: Dev 5, If 0, Class=Wireless, Driver=btusb, 12M
    |__ Port 10: Dev 5, If 1, Class=Wireless, Driver=btusb, 12M
rogelio@9n902z2:~$ lsusb -vv -d 046d:0a90

Bus 001 Device 002: ID 046d:0a90 Logitech, Inc. 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x046d Logitech, Inc.
  idProduct          0x0a90 
  bcdDevice           36.06
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength          218
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower               96mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      1 Control Device
      bInterfaceProtocol      0 
      iInterface              0 
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      1 (HEADER)
        bcdADC               1.00
        wTotalLength           71
        bInCollection           2
        baInterfaceNr( 0)       1
        baInterfaceNr( 1)       2
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             1
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bNrChannels             2
        wChannelConfig     0x0003
          Left Front (L)
          Right Front (R)
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 2
        bSourceID               1
        bControlSize            1
        bmaControls( 0)      0x03
          Mute Control
          Volume Control
        bmaControls( 1)      0x00
        bmaControls( 2)      0x00
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             3
        wTerminalType      0x0402 Headset
        bAssocTerminal          0
        bSourceID               2
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             4
        wTerminalType      0x0402 Headset
        bAssocTerminal          0
        bNrChannels             1
        wChannelConfig     0x0001
          Left Front (L)
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 5
        bSourceID               4
        bControlSize            1
        bmaControls( 0)      0x03
          Mute Control
          Volume Control
        bmaControls( 1)      0x00
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             6
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bSourceID               5
        iTerminal               0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           6
        bDelay                  0 frames
        wFormatTag              1 PCM
      AudioStreaming Interface Descriptor:
        bLength                11
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             1
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            1 Discrete
        tSamFreq[ 0]        16000
        AudioControl Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x00
          bLockDelayUnits         2 Decoded PCM samples
          wLockDelay              0 Decoded PCM samples
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           1
        bDelay                  0 frames
        wFormatTag              1 PCM
      AudioStreaming Interface Descriptor:
        bLength                11
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             2
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            1 Discrete
        tSamFreq[ 0]        48000
        AudioControl Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x81
            Sampling Frequency
            MaxPacketsOnly
          bLockDelayUnits         2 Decoded PCM samples
          wLockDelay              0 Decoded PCM samples
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x00c0  1x 192 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     253
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
```

**Comment by pfps** [comment]
Thanks.   I'm still not sure whether interface 3 can talk HID++, but it's the only reasonable choice.
I'm trying to get some information about what this receiver talks.  Stay tuned.

**Comment by pfps** [comment]
I now have a Zone Wireless Unifying Plus, which appears to be what you have plus a Unifying Receiver (USB product ID c52b) combined with the headset receiver (USB product ID 0aa8, different from yours but probably the same functionality).  This leads me to believe that your receiver might not be able to pair.

Anyway, I'm going to see what can be done on the headset side for this device.

**Comment by rogelioperez000** [comment]
Thanks @pfps , please keep me posted!

**Comment by pfps** [comment]
It's not looking good.   The headset side of the receiver has an HID interface but it doesn't seem to talk HID++.  Neither does the headset when connected via Bluetooth.  It may be that I'm not checking out all the possibilities, so I've asked Logitech for more information.   But there doesn't even seem to be an hidraw node created for the headset under bluetooth.

If your receiver has the orange Unifying logo on it, then there should be USB device node that is the Unifying part of the receiver.   What I see with `lsusb` is

```
Bus 003 Device 026: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 025: ID 046d:0aa8 Logitech, Inc. Integrated Camera
Bus 003 Device 024: ID 1a40:0101 Terminus Technology Inc. Hub
```

The first node is the unifying receiver, the second the headset interface (not a camera!), and the third is USB hub that connects to both of them.   Please try `lsusb` on your system and provide the output.

**Comment by rogelioperez000** [comment]
`Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 413c:81d7 Dell Computer Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0bda:58fd Realtek Semiconductor Corp. 
Bus 001 Device 005: ID 046d:0a90 Logitech, Inc. 
Bus 001 Device 003: ID 8087:0029 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`

**Comment by pfps** [comment]
It looks as if the difference is that your receiver doesn't have the Unifying part.  So unless Logitech provides some information Solaar won't do anything for you.

On https://www.logitech.com/en-us/products/headsets/zone-wireless-bluetooth.html there are illustrations of three receivers, of different sizes.   Mine appears to be the one lower down the page, and has the Unifying logo on it.  The other two probably don't have a Unifying portion.

**Comment by Klap-in** [comment]
You both have a Logitech zone wireless plus? Or a Logitech zone wireless?

**Comment by pfps** [comment]
Mine is a plus.  It looks as if the main difference between them is that the plus includes a Unifying portion in its receiver.  (The Logitech page doesn't show a Unifying logo on either receiver.)

**Comment by rogelioperez000** [comment]
I guess that explains it, mine is the smaller one that just says logitech and no Unifying logo, so to be able to pair devices I should get the Zone Wireless Plus which support Unifying capabilities.
Thanks so much for guiding me through this, much appreciated.

**Comment by f1lipe** [comment]
> Mine is a plus. It looks as if the main difference between them is that the plus includes a Unifying portion in its receiver. (The Logitech page doesn't show a Unifying logo on either receiver.)

Hello, I found this issue looking for solaar/linux compatibility to Logitech Zone Wireless Plus. Is it linux/solaar compatible? How does the "headset portion" of the receiver work on linux? As an external usb sound card? What about the Unifying portion of the receiver? Does it work as a regular Unifying adapter on Solaar/linux? Thanks!

**Comment by pfps** [comment]
The receiver appears to be two devices in one - a unifying receiver and an audio device, plus a hub to glue them together.  The unifying part works fine in Solaar but the audio part isn't recognized by Solaar at all.  The headset part is a regular audio device that works fine under Solaar.

Here is the lsusb output for the receiver:
```
Bus 003 Device 025: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 024: ID 046d:0aa8 Logitech, Inc. Zone Wireless Plus
Bus 003 Device 023: ID 1a40:0101 Terminus Technology Inc. Hub
```

There might be a way to get Solaar to interact with the audio part but I haven't been able to make this work.

**Comment by pfps** [comment]
I managed to find out the HID reports that the Zone headsets support.  It looks as if they do not support the HID++ reports, so there is no way for Solaar to support them as HID++ devices.

**Comment by nathancurry** [comment]
@pfps, I'm confused by this, is this a typo:

>The unifying part works fine in Solaar but the audio part isn't recognized by Solaar at all. The headset part is a regular audio device that works fine under Solaar.

Clarifying question:  do we know if a Wireless Plus headset is able to pair with the receiver and transmit and receive audio in Linux? It's my understanding that the audio portion of this receiver is supposed to be plug and play, but there's precious little information about it online.

It's made all the more confusing by the fact that there are three models:
- Bluetooth-only (what OP has?): UC Zone Wireless: 981-000913 
- Bluetooth+Unifying (what you have?): UC Zone Wireless Plus: 981-000805
- Unclear, but I believe Bluetooth-only: MSFT Zone Wireless: 981-000853

Thanks!

**Comment by pfps** [comment]
The headset part of the Wireless Plus headset isn't an HID++ device, so Solaar doesn't affect it at all.  It just works fine but Solaar can't re-pair it the headsets with different receives.  (The second `Solaar` bit in your quote is a bit misleading - I'm going to change that to Linux.)
