### ISSUE TITLE
'no module psutil' error  on manual install

### ISSUE THREAD

**Issue by bwanaaa** [pwr-Solaar/Solaar#1065]
**Information**
1.0.1
ubuntu 20.04
-kernel Linux 5.8.0-41-generic x86_64 GNU/Linux
solaar show
solaar: error: Logitech receiver not found

```
OUTPUT HERE
```

**Describe the bug**
Followed manual installation here:
https://pwr-solaar.github.io/Solaar/installation
After copying 42-logitech-unify-permissions.rules to my /etc/udev/rules.d
I went into solaar-master and typed
`sudo bin/solaar`
and got
```
solaar: error: Traceback (most recent call last):
  File "/home/stefan/Downloads/Solaar-master/lib/solaar/gtk.py", line 157, in main
    import solaar.ui as ui
  File "/home/stefan/Downloads/Solaar-master/lib/solaar/ui/__init__.py", line 96, in <module>
    from . import notify, tray, window  # isort:skip  # noqa: E402
  File "/home/stefan/Downloads/Solaar-master/lib/solaar/ui/tray.py", line 37, in <module>
    from .window import popup as _window_popup
  File "/home/stefan/Downloads/Solaar-master/lib/solaar/ui/window.py", line 40, in <module>
    from .diversion_rules import show_window as _show_diversion_window
  File "/home/stefan/Downloads/Solaar-master/lib/solaar/ui/diversion_rules.py", line 28, in <module>
    from logitech_receiver import diversion as _DIV
  File "/home/stefan/Downloads/Solaar-master/lib/logitech_receiver/diversion.py", line 27, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```
So I cannot install solaar manually.

**To Reproduce**
see above

**Comment by pfps** [comment]
You need to install the pustil system package, whose name depends on which distribution you are using.  If you did install the packages (perhaps via `sudo dnf install python3-psutil`) there is something amiss, but I expect that the appropriate system install will fix the problem.

**Comment by bwanaaa** [comment]
thank you. that fixed it - the installation that is. But solaar cant let me do much with this keyboard even tho it sees it
