### ISSUE TITLE
Missing python dependency: pyyaml - Fails to open on new install

### ISSUE THREAD

**Issue by mil1i** [pwr-Solaar/Solaar#1098]
Just wanted to post this here before I head to sleep. I just wiped and reinstalled my OS.

This fails to launch after installation. Launching from cli it produces the following error:

```shell
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/gtk.py", line 159, in main
    import solaar.ui as ui
  File "/usr/lib/python3.9/site-packages/solaar/ui/__init__.py", line 96, in <module>
    from . import notify, tray, window  # isort:skip  # noqa: E402
  File "/usr/lib/python3.9/site-packages/solaar/ui/tray.py", line 37, in <module>
    from .window import popup as _window_popup
  File "/usr/lib/python3.9/site-packages/solaar/ui/window.py", line 40, in <module>
    from .diversion_rules import show_window as _show_diversion_window
  File "/usr/lib/python3.9/site-packages/solaar/ui/diversion_rules.py", line 28, in <module>
    from logitech_receiver import diversion as _DIV
  File "/usr/lib/python3.9/site-packages/logitech_receiver/diversion.py", line 30, in <module>
    from yaml import add_representer as _yaml_add_representer
ModuleNotFoundError: No module named 'yaml'
```

After running the following, it resolves the issue. Missing dependency.
```shell
pip install --user pyyaml
```

**Comment by pfps** [comment]
How are you installing Solaar?   
In 1.0.5 setup.py requires PyYAML, so the yaml module should be available to Solaar after installation.

**Comment by mil1i** [comment]
Ah yeah sorry been up a while. Must be an issue with the AUR install then. 

https://aur.archlinux.org/packages/solaar-git/

Which looks like someone already posted about as well.

**Comment by pfps** [comment]
A dependency on yaml was added in November 2020.   If the package isn't providing yaml somehow then Solaar isn't going to work.   

Where is the other post?

**Comment by pfps** [comment]
Never mind, I see the comment.
