### ISSUE TITLE
Solaar complains about missing packages at program startup

### ISSUE THREAD

**Issue by lukasmichel** [pwr-Solaar/Solaar#1114]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.0.5-8-gdc3f70f
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 5.11.7-arch1-1 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/cli/__init__.py", line 198, in run
    c = list(_receivers(hidraw_path))
  File "/usr/lib/python3.9/site-packages/solaar/cli/__init__.py", line 104, in _receivers
    from logitech_receiver import Receiver
  File "/usr/lib/python3.9/site-packages/logitech_receiver/__init__.py", line 36, in <module>
    from . import listener, status  # noqa: F401
  File "/usr/lib/python3.9/site-packages/logitech_receiver/listener.py", line 28, in <module>
    from . import base as _base
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 35, in <module>
    from .base_usb import ALL as _RECEIVER_USB_IDS
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base_usb.py", line 32, in <module>
    from .descriptors import DEVICES as _DEVICES
  File "/usr/lib/python3.9/site-packages/logitech_receiver/descriptors.py", line 27, in <module>
    from .settings_templates import FeatureSettings as _FS
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 26, in <module>
    from solaar.ui import notify as _notify
  File "/usr/lib/python3.9/site-packages/solaar/ui/__init__.py", line 25, in <module>
    import gi  # isort:skip
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/libgirepository-1.0.so.1: undefined symbol: g_memdup2
```
</details>

**Describe the bug**
`solaar` does not start. Upon launching, it shows `Solaar: missing required system package python3-gi or python3-gobject`, although `python-gobject` from Archlinux repos is installed (version 3.40.0-1). `solaar show` displays the error above. Using starting solaar with `-dd` does not show more output.

**To Reproduce**
run `solaar show` and `solaar`.

**Screenshots**

**Additional context**
This might not be a solaar bug, but I am unsure about where else I should report it.
The version of `gobject-introspection-runtime` which provides `/usr/lib/libgirepository-1.0.so.1`  is `1.68.0`.

**Comment by pfps** [comment]
Solaar version 1.0.5 needs more system packages.  If you installed Solaar from a packaging system the maintainer of the package should update it.   If you installed Solaar yourself, please read the installation instructions.

See #1110

**Comment by lukasmichel** [comment]
Sorry for the noise, the problem was caused by a package version mismatch. No packages were missing. 
Just as a note: I had updated (on archlinux, from official repos) `gobject-introspection` and `gobject-introspection-runtime` to their latest version `1.68.0-1`, however, the `glib2` package was not updated together with these packages (due to a partially out-of-sync mirror), causing my problem.
