### ISSUE TITLE
tray disappered

### ISSUE THREAD

**Issue by osito17** [pwr-Solaar/Solaar#1117]
**Information**

- Solaar version : Solaar version 1.0.5-9
- Distribution: Solus 4.2 Fortitude
- Kernel version (ex. `uname -srmo`): `Linux 5.10.15-172.current x86_64 GNU/Linux`
- Output of `solaar show`:

$ solaar show
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/solaar/cli/__init__.py", line 198, in run
    c = list(_receivers(hidraw_path))
  File "/usr/lib/python3.7/site-packages/solaar/cli/__init__.py", line 104, in _receivers
    from logitech_receiver import Receiver
  File "/usr/lib/python3.7/site-packages/logitech_receiver/__init__.py", line 36, in <module>
    from . import listener, status  # noqa: F401
  File "/usr/lib/python3.7/site-packages/logitech_receiver/listener.py", line 28, in <module>
    from . import base as _base
  File "/usr/lib/python3.7/site-packages/logitech_receiver/base.py", line 35, in <module>
    from .base_usb import ALL as _RECEIVER_USB_IDS
  File "/usr/lib/python3.7/site-packages/logitech_receiver/base_usb.py", line 32, in <module>
    from .descriptors import DEVICES as _DEVICES
  File "/usr/lib/python3.7/site-packages/logitech_receiver/descriptors.py", line 27, in <module>
    from .settings_templates import FeatureSettings as _FS
  File "/usr/lib/python3.7/site-packages/logitech_receiver/settings_templates.py", line 26, in <module>
    from solaar.ui import notify as _notify
  File "/usr/lib/python3.7/site-packages/solaar/ui/__init__.py", line 96, in <module>
    from . import notify, tray, window  # isort:skip  # noqa: E402
  File "/usr/lib/python3.7/site-packages/solaar/ui/tray.py", line 37, in <module>
    from .window import popup as _window_popup
  File "/usr/lib/python3.7/site-packages/solaar/ui/window.py", line 40, in <module>
    from .diversion_rules import show_window as _show_diversion_window
  File "/usr/lib/python3.7/site-packages/solaar/ui/diversion_rules.py", line 28, in <module>
    from logitech_receiver import diversion as _DIV
  File "/usr/lib/python3.7/site-packages/logitech_receiver/diversion.py", line 28, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
<details>

```
OUTPUT HERE
```
</details>

**Describe the bug**

no gui tray and cli produce above output

**Comment by pfps** [comment]
The installation document https://pwr-solaar.github.io/Solaar/installation says:

> Solaar requires Python 3.6+ and the python3-pyudev package. The Solaar GUI requires the python3-psutil, python3-xlib, and python3-yaml or python3-pyyaml packages. 

That's slightly wrong as even the cli needs almost all the packages.

**Comment by osito17** [comment]
it was working perfectly till i got update.

**Comment by pfps** [comment]
The error that you are reporting from `solaar show` appears to be caused by the missing dependency.   This is a new dependency.  If you installed from a packaged version of Solaar then the packager needs to update the pakage.

The GUI problem is likely to be a separate issue.  If you have recently updated your windowing system (in particular if you are using Wayland or Gnome 3) then you might not have a working GTK system tray.   That is not a problem with Solaar, per se.  Issue #1116 might be relevant here.

**Comment by osito17** [comment]
after installing

python3-psutil
python3-xliband 
python3-yaml

everything works fine! thx!
