### ISSUE TITLE
Solaar not recognizing K780 keyboard on ubuntu 18.04

### ISSUE THREAD

**Issue by ssingh28** [pwr-Solaar/Solaar#1202]
Hey Team,

I am new on Ubuntu and currently struggling to make my logitech k780 wireless keyboard work. 
I have installed the Solaar package and when I insert the unifying receiver that comes with the keyboard and click on the UI of the Solaar icon I can only see Logitech M585/M590 and it doesn't recognize the K780. Even when i replace the unifying receiver with that of the mouse the result is the same. 

I did go through this bug https://github.com/pwr-Solaar/Solaar/issues/298
but the details there don't help.

I am on Solaar 0.9.2. Can you please help me here. Below is the screenshot with added details. Please let me know if there is anything else which is needed!

FYI @pfps 

![solaar issue](https://user-images.githubusercontent.com/11782656/125204481-2c8a4700-e29b-11eb-9500-ad3f9992b1d5.png)

**Comment by pfps** [comment]
Solaar 0.9.2 is ancient.  You need to install a newer version.  

I suggest trying to install the current release of Solaar using the Solaar stable ppa, as described in https://github.com/pwr-Solaar/Solaar

**Comment by ssingh28** [comment]
Hey @pfps I have removed that older version of solaar and downloaded code from this repo instead: https://github.com/pwr-Solaar/Solaar.git. Now when I execute bin/solaar below is the error that I get:

solaar: error: Traceback (most recent call last):
  File "/home/singh.saurabh/Solaar/lib/solaar/gtk.py", line 159, in main
    import solaar.ui as ui
  File "/home/singh.saurabh/Solaar/lib/solaar/ui/__init__.py", line 29, in <module>
    from logitech_receiver.status import ALERT  # NOQA: E402 # isort:skip
  File "/home/singh.saurabh/Solaar/lib/logitech_receiver/__init__.py", line 36, in <module>
    from . import listener, status  # noqa: F401
  File "/home/singh.saurabh/Solaar/lib/logitech_receiver/listener.py", line 28, in <module>
    from . import base as _base
  File "/home/singh.saurabh/Solaar/lib/logitech_receiver/base.py", line 35, in <module>
    from .base_usb import ALL as _RECEIVER_USB_IDS
  File "/home/singh.saurabh/Solaar/lib/logitech_receiver/base_usb.py", line 32, in <module>
    from .descriptors import DEVICES as _DEVICES
  File "/home/singh.saurabh/Solaar/lib/logitech_receiver/descriptors.py", line 27, in <module>
    from .settings_templates import FeatureSettings as _FS
  File "/home/singh.saurabh/Solaar/lib/logitech_receiver/settings_templates.py", line 38, in <module>
    from .settings import BitFieldSetting as _BitFieldSetting
  File "/home/singh.saurabh/Solaar/lib/logitech_receiver/settings.py", line 27, in <module>
    from time import time_ns as _time_ns
ImportError: cannot import name 'time_ns
