### ISSUE TITLE
Solaar not recognizing K780 keyboard on ubuntu 18.04

### ISSUE THREAD

**Issue by ssingh28** [pwr-Solaar/Solaar#1203]
Hey @pfps I have removed that older version of solaar and downloaded code from this repo instead: https://github.com/pwr-Solaar/Solaar.git. Now when I execute bin/solaar below is the error that I get. Can you please share what I need to do to make it work

solaar: error: Traceback (most recent call last):
File "/home/singh.saurabh/Solaar/lib/solaar/gtk.py", line 159, in main
import solaar.ui as ui
File "/home/singh.saurabh/Solaar/lib/solaar/ui/init.py", line 29, in
from logitech_receiver.status import ALERT # NOQA: E402 # isort:skip
File "/home/singh.saurabh/Solaar/lib/logitech_receiver/init.py", line 36, in
from . import listener, status # noqa: F401
File "/home/singh.saurabh/Solaar/lib/logitech_receiver/listener.py", line 28, in
from . import base as _base
File "/home/singh.saurabh/Solaar/lib/logitech_receiver/base.py", line 35, in
from .base_usb import ALL as _RECEIVER_USB_IDS
File "/home/singh.saurabh/Solaar/lib/logitech_receiver/base_usb.py", line 32, in
from .descriptors import DEVICES as _DEVICES
File "/home/singh.saurabh/Solaar/lib/logitech_receiver/descriptors.py", line 27, in
from .settings_templates import FeatureSettings as _FS
File "/home/singh.saurabh/Solaar/lib/logitech_receiver/settings_templates.py", line 38, in
from .settings import BitFieldSetting as _BitFieldSetting
File "/home/singh.saurabh/Solaar/lib/logitech_receiver/settings.py", line 27, in
from time import time_ns as _time_ns
ImportError: cannot import name 'time_ns

**Comment by pfps** [comment]
When you download the git repository you need to install the dependencies, as described in https://pwr-solaar.github.io/Solaar/installation
It is easier to install from the PPA repository.
