### ISSUE TITLE
macOS port

### ISSUE THREAD

**Issue by Miss-Volpe** [pwr-Solaar/Solaar#1244]
See PR #1971 for more information.

**Description**

Hello, I stumbled upon this project while looking for a replacement to Logi Options in Linux. I was wondering if it is possible to request porting it to macOS as this is more versatile, stable and performant than the official Logi Options.

Thank you!

**Comment by mischievous** [comment]
I have a project similar to this one not on github yet for Macs.   Its written in c++/obj-c.   If you want any help I can give possibly help you, or if yu want to test what I can send me a message.

**Comment by VandrerenErik** [comment]
That sounds great mate. I will checkout your repos later today.

**Comment by mischievous** [comment]
@VandrerenErik it's NOT on github yet.  You can PM me using mischievous.demon AT gmail.

**Comment by VandrerenErik** [comment]
> @VandrerenErik it's NOT on github yet.  You can PM me using mischievous.demon AT gmail.  

read my full message

**Comment by elesto** [comment]
Are there any other apps like this but for macos? I really dont want to install that logitech bloat

**Comment by pfps** [comment]
Like Solaar?  I don't know of any.

**Comment by elesto** [comment]
> Like Solaar? I don't know of any.

It seems as though some basic work is being done so hopefully we will get an implementation some day.

**Comment by abishai** [comment]
Very old version of solaar used native hid enumeration that wasn't based on udev, but libusb. If this commit https://github.com/pwr-Solaar/Solaar/commit/f5d2eba can be restored, probably solaar will work on other OSes.

**Comment by pfps** [comment]
Can you make your changes available in GitHub?

**Comment by abishai** [comment]
What was the reason to use linux specific backend instead of more generic way to handle usb devices? I remember we (FreeBSD users) had solaar in ports. We still use version before udev commit because of that.

It would be nice to restore libudev support or make an option to choose implementation on compile time if possible.

**Comment by pfps** [comment]
The switch was before my time, but an advantage of using udev is that there is no need to continually look for new devices.

**Comment by pfps** [comment]
@abishai You might want to see whether the changes by @ja14000 work under FreeBSD.

**Comment by abishai** [comment]
@pfps Wow, looks like we have udev interface to devd indeed. I'll try unmodified Solaar on FreeBSD, but my knowledge of Python is very limited, unfortunately.

**Comment by pfps** [comment]
@ja14000  Thanks.  It appears that with the hid library doesn't provide the ability to control devices that connect after Solaar starts.  Is this correct?

**Comment by pfps** [comment]
@ja14000 Yes, devices paired with a receiver will work OK.  I was thinking of devices that don't use a receiver, and also inserting a new receiver or removing and re-inserting a receiver.

**Comment by pfps** [comment]
@ja14000 Solaar already understands that bluetooth devices only accept long commands.  Some HID libraries only handle USB devices, not bluetooth at all.

The biggest remaining issue, I think is figuring out how to handle new devices.  There are Mac system calls for this but someone is going to have to figure out how to get them working or find a cross-platform library.

**Comment by pfps** [comment]
@ja14000 What is needed is not just sleep and wake notifications but also notifications when a new device shows up.  
Wake notifications are needed because settings need to be pushed to all devices at wakeup time to undo any changes that happened while the system was sleeping.

**Comment by pfps** [comment]
Please check out PR #1971

**Comment by pfps** [comment]
It would be very useful to have more people try PR #1971 or a Mac or under Windows.

**Comment by MattHag** [comment]
I'd like to test it on macOS, but where should _gi_ com from?

**Comment by pfps** [comment]
@markopy Can you answer Matt?

**Comment by MattHag** [comment]
The current issue on macOS 14 (Sonoma) and 1.1.11rc is loading _hidapi_ when starting solaar in GUI mode.

`
ImportError: Unable to load hdiapi library, tried: libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
`

No udev rule is installed as the default path doesn't exist on macOS.

**Comment by markopy** [comment]
@MattHag How did you install hidapi? Did you use `brew install hidapi`?

I'm not using Sonoma so I can't debug this directly. You need to figure out where your hidapi install puts the library and if it matches one of the names in the import error. If you installed via homebrew then this should all work automatically but maybe something changed on Sonoma.

**Comment by markopy** [comment]
Also are you saying the issue only appears when starting in GUI mode but everything works in the CLI? How are you starting it in GUI mode?

**Comment by MattHag** [comment]
> brew install hidapi
Yes, I used that.

> Also are you saying the issue only appears when starting in GUI mode but everything works in the CLI? How are you starting it in GUI mode?

`bin/solaar` for example, misses the library. I can only print the help message without problem.
```
raise ImportError(f"Unable to load hdiapi library, tried: {' '.join(_library_paths)}")

ImportError: Unable to load hdiapi library, tried: libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
```
Okay, that's a good hint, that the path might be wrong 👍

**Comment by markopy** [comment]
You can try checking in `$(brew --prefix)/lib` or run `brew ls hidapi` to see where the files got installed.

**Comment by MattHag** [comment]
Without any paths added there, I am able to import hidapi
```
import hidapi
_hidapi.hid_version()
*** AttributeError: partially initialized module 'hidapi' has no attribute 'hid_version' (most likely due to a circular import)
```
but it says partially initialized.

**Comment by markopy** [comment]
Not sure what you are trying to do there. What python hidapi module are you importing? Solaar is not using any third party python hidapi modules.

You should check where the hidapi dynamic link library is that homebrew installed. That's entirely independent of python,

**Comment by MattHag** [comment]
The path to the hidapi library is `/opt/homebrew/Cellar/hidapi/0.14.0/lib/`, but what do I do with that?

**Comment by markopy** [comment]
Is there a file in that folder that matches one of the names in the original error?
`libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll`

Or a similar one?

**Comment by MattHag** [comment]
The lib/ folder contains other files
```

├── cmake
│   └── hidapi
│       ├── hidapi-config-version.cmake
│       ├── hidapi-config.cmake
│       ├── libhidapi-release.cmake
│       └── libhidapi.cmake
├── libhidapi.0.14.0.dylib
├── libhidapi.0.dylib -> libhidapi.0.14.0.dylib
├── libhidapi.dylib -> libhidapi.0.dylib
└── pkgconfig
    └── hidapi.pc
```

**Comment by markopy** [comment]
Ok that's good, you have the right files. You can further check if there is a file/symlink for libhidapi.dylib in `/opt/homebrew/lib/` or `/usr/local/lib`. If there is not then try running `brew link hidapi` which hopefully will create it.

**Comment by markopy** [comment]
Another thing you can try is prefixing the solar command like so:
```
DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/Cellar/hidapi/0.14.0/lib" bin/solaar
```
If this works then the issue is indeed that homebrew didn't properly add the library path to the environment you are running solaar in.

**Comment by MattHag** [comment]
Even that doesn't work, as that given path is not searched in, but I'll figure out why the paths are so screwed.

**Comment by markopy** [comment]
If prefixing the solaar command in terminal with `DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/Cellar/hidapi/0.14.0/lib` doesn't work that is very strange given the files being in that folder.

Worst case you can copy `/opt/homebrew/Cellar/hidapi/0.14.0/lib/libhidapi.0.14.0.dylib` to the directory from which you launch Solaar (i.e. the current working directory) and rename it to `libhidapi.dylib` but that's kind of a hack and not a solution to why the proper path is not searched when loading the library.

You can also try this simple python script which might give more error details:
```
import ctypes
ctypes.cdll.LoadLibrary("libhidapi.dylib")
```

**Comment by MattHag** [comment]
Yes, that's what I did before and it ignores the `/opt/homebrew/Cellar/hidapi/0.14.0/...` folder, which is quite interesting.

**Comment by markopy** [comment]
Well, the library would actually be searched for in `/opt/homebrew/lib/` or `/usr/local/lib`, not `/opt/homebrew/Cellar/hidapi/0.14.0/lib` directly, so make sure one of those two folders has a symlink to `/opt/homebrew/Cellar/hidapi/0.14.0/lib/libhidapi.dylib`.

**Comment by MattHag** [comment]
Yes, I try that. This could be one of the issues with the ARM chipset ;)

**Comment by MattHag** [comment]
The path issue is gone with
`sudo ln -s /opt/homebrew/Cellar/hidapi/0.14.0/lib/libhidapi.dylib /usr/local/lib/.`

The GUI doesn't start yet, but 
`hidapi.enumerate()`
returns nice data. So hidapi seems to work 👏

**Comment by markopy** [comment]
Great. Would you mind deleting the symlink again and checking if `brew link hidapi` also works? homebrew should normally create that symlink automatically.

**Comment by MattHag** [comment]
It didn't before, but I'll experiment with it, once I see a GUI. I plan to setup a macOS GitHub CI anyway and document the necessary steps then.

**Comment by markopy** [comment]
One thing to consider are the permission on your `/usr/local/lib/` folder. I don't think you would usually need sudo to create the symlink so maybe there was a permission issue that prevented homebrew from creating it.

**Comment by MattHag** [comment]
Permission was not a problem it seems. I only created the symlink using sudo.

**Comment by MattHag** [comment]
Thanks for your help, yes it works 👍 🥇 

The commands there are very helpful
https://github.com/pwr-Solaar/Solaar/pull/1971#issuecomment-1511730733

I can run `Solaar 1.1.10-40-g06209d2`successfully on macOS with ARM.

**Comment by MattHag** [comment]
I tried to setup the macOS test runner, but the installation fails, looks like the same as in
https://github.com/pwr-Solaar/Solaar/pull/1971#issuecomment-1869699895

**Comment by markopy** [comment]
@MattHag `patchelf` is a dependency of `dbus-python` but I don't think it's actually needed on macos. Try limiting it to Linux in `setup.py` like so:
```
    install_requires=[
        'evdev (>= 1.1.2) ; platform_system=="Linux"',
        'pyudev (>= 0.13)',
        'PyYAML (>= 3.12)',
        'python-xlib (>= 0.27)',
        'psutil (>= 5.4.3)',
        'dbus-python ; platform_system=="Linux"',
    ],
```

**Comment by MattHag** [comment]
Yes, that solved the installation issue.

**Comment by MattHag** [comment]
With 1.1.11 
- [ ] Solaar is missing the Solaar icon for the application
- [ ] The application name is shown as _python_

**Comment by timon** [comment]
I tried running Solaar on MacOS today
- The recent changes in `master` are not in `pip` yet, so had to go with git 
- Somehow `brew update` failed for me (on one hand, it might be something of local setup, on other hand I'm not sure this step is needed) — so I just manually run `brew install…` line from the makefile
- An attempt to launch `solaar` failed with an error (expand for stack trace)
  ```
  ModuleNotFoundError: No module named 'typing_extensions'
  ```
  <details>
   <summary>Traceback (most recent call last):</summary>
    <pre>
    File "~/.local/bin/solaar", line 54, in <module>
      import solaar.gtk
    File "~/.local/pipx/venvs/solaar/lib/python3.12/site-packages/solaar/gtk.py", line 31, in <module>
      import solaar.cli as _cli
    File "~/.local/pipx/venvs/solaar/lib/python3.12/site-packages/solaar/cli/__init__.py", line 25, in <module>
      import logitech_receiver.device as _device
    File "~/.local/pipx/venvs/solaar/lib/python3.12/site-packages/logitech_receiver/device.py", line 31, in <module>
      from . import base
    File "~/.local/pipx/venvs/solaar/lib/python3.12/site-packages/logitech_receiver/base.py", line 38, in <module>
      from . import hidpp20
    File "~/.local/pipx/venvs/solaar/lib/python3.12/site-packages/logitech_receiver/hidpp20.py", line 31, in <module>
      from typing_extensions import Protocol
     ModuleNotFoundError: No module named 'typing_extensions'
  </pre>
  </details>

  I had to put `typing_extensions` somewhere in `setup.py` — a little bit confused about that, given [Changelog for 1.1.8](https://github.com/pwr-Solaar/Solaar/blob/cece723ea4fa1b31faed23b12edab2f9e786cca5/CHANGELOG.md?plain=1#L253)
- Complains about `failed to setup dbus`
  ... which is probably expected for MacOS, maybe do an OS check before trying dbus at all?

In the end, I'm able to launch Solaar gui; it sees my Logitech G915 keyboard on lightspeed, 
and I'm able to run "solaar config G915 change-host 2" to switch from lightspeed to bluetooth.

Unfortunately it doesn't see MX Ergo mouse on bluetooth — probably MacOS specific thing.
(Which is a pity as I'm trying to automate away switching between hosts, that is telling monitor, mouse and keyboard to talk to something else. I'm seemingly able to switch everything in linux, on MacOS I only can do 2 out of 3 changes wanted)

**Comment by pfps** [comment]
I think that on MacOS Solaar only sees USB devices.

**Comment by timon** [comment]
OTOH I haven't had any luck with Logitech stuff for mouse either (M1 compatibility problem? I don't know)

Ah, and it seems like I want "diversion" feature which is not supported in MacOS (yet?) — So I'm trying to set up mix of Logitech software and Solaar to give me "Switch 2/3 of gear" hotkey

**Comment by pfps** [comment]
Solaar should be able to divert keys on MacOS but maybe not run rules in response to diverted keys.  (I don't use MacOS so I don't have good knowledge of the state of the MacOS port.)

**Comment by timon** [comment]
Hey, it actually worked, thanks!

**Comment by MattHag** [comment]
The macOS port only works in the GUI with pairing devices and creating rules, but everything else is untested so far and don't expect something to work.

However reports what does not work are welcome.

**Comment by pfps** [comment]
Change host works for me on Linux.   There may be some delay while Solaar figures out that devices have disappeared, and recent changes to Bluez may make this delay be a few seconds.  If you see any problems with change host on Linux, please file a bug report.

**Comment by timon** [comment]
`change host` works for me as well, I'm probably losing my patience too fast for the command to complete :)


So I swapped the order (send mouse off first, then keyboard), and put `timeout -k 3 3` in front of keyboard switch

**Comment by andrewgodman** [comment]
Are there any steps for building the GUI? I'm able to run the CLI app for one automation on changing hosts but it looks like the current port has a lot of work to do?

**Comment by MattHag** [comment]
The GUI itself starts fine already with the solaar command. With the commands from the githib actions and the Makefile it should be possible for you to install all necesary dependencies.

**Comment by enzofrnt** [comment]
Hi, is there any news or tuto ?
Thanks !

**Comment by MattHag** [comment]
Follow the steps from the Github action for macOS. It's the best documentation that exists.

**Comment by MattHag** [comment]
@zeeyado Bluetooth support on macOS just arrived, maybe you want to test #2730

**Comment by timon** [comment]
Just checked 1.1.14 — I'm able to switch MX Ergo on Bluetooth from MacOS to my linux box

**Comment by MattHag** [comment]
There's an env variable that needs to be set. It's shown in github actions yml.

**Comment by farfromrefug** [comment]
@MattHag thanks ! as i am working on making that go. You should add a requirements.txt with all required python plugins. That way we could easily install them but also mostly create a venv for solaar

**Comment by MattHag** [comment]
That‘s all provided in setup.py. It should work well with a venv too. Just run pip install command.

**Comment by farfromrefug** [comment]
@MattHag ok strange it did not work here. will try again. I now have solaar running and working! Working on removing the dock icon. Also need to find a way to make it run on boot. Might try to package it as a macos app

**Comment by zeeyado** [comment]
@MattHag 

Sorry, i was away and did not have the mouse with me.

1.1.14, can confirm that bluetooth now works, all settings working as expected

Thanks

**Comment by landsman** [comment]
Installation:

```bash
sudo ln -s $(which python3) /usr/local/bin/python
make install_macos
```

```bash
make install_macos
Installing Solaar dependencies via brew
brew update
==> Updating Homebrew...
==> Updated Homebrew from 7c514724af to 6291c24004.
No changes to formulae or casks.
brew install hidapi gtk+3 pygobject3 gobject-introspection
Warning: hidapi 0.14.0 is already installed and up-to-date.
To reinstall 0.14.0, run:
  brew reinstall hidapi
Warning: gtk+3 3.24.43 is already installed and up-to-date.
To reinstall 3.24.43, run:
  brew reinstall gtk+3
Warning: pygobject3 3.50.0_1 is already installed and up-to-date.
To reinstall 3.50.0_1, run:
  brew reinstall pygobject3
Warning: gobject-introspection 1.82.0 is already installed and up-to-date.
To reinstall 1.82.0, run:
  brew reinstall gobject-introspection
Installing Solaar via pip
python -m pip install --upgrade pip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.

    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:

    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz

    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with

    brew install pipx

    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.

    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.

    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
make: *** [install_pip] Error 1
```

so I did this:

```bash
python3 -m venv ~/solaar-venv
source ~/solaar-venv/bin/activate
python -m pip install --upgrade pip
python -m pip install solaar
solaar
```

but it failed:

```
Traceback (most recent call last):
  File "/Users/landsman/solaar-venv/bin/solaar", line 53, in <module>
    import solaar.gtk
  File "/Users/landsman/solaar-venv/lib/python3.13/site-packages/solaar/gtk.py", line 34, in <module>
    from solaar import cli
  File "/Users/landsman/solaar-venv/lib/python3.13/site-packages/solaar/cli/__init__.py", line 26, in <module>
    from logitech_receiver import device
  File "/Users/landsman/solaar-venv/lib/python3.13/site-packages/logitech_receiver/device.py", line 35, in <module>
    from . import hidpp10
  File "/Users/landsman/solaar-venv/lib/python3.13/site-packages/logitech_receiver/hidpp10.py", line 22, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

Some kind of packager to create dmg or app would be nice.

**Comment by ekamil** [comment]
@landsman It seems Solaar needs python 3.11 instead of 3.13, I just tested on macOS 15.3.1 with Python 3.11 installed using pyenv

**Comment by landsman** [comment]
@ekamil That's werid. A minor version can't be the deal breaker.

**Comment by pfps** [comment]
There is a MacOS port so I'm closing this issue.

**Comment by coleHafner** [comment]
> With the latest code from GitHub there shouldn't be a typing_extension problem anymore. The way you install from pip directly installs an older version, which has the issue.

@MattHag I'm getting the same issue and I installed using `pipx`: 

```bash
brew update
brew install hidapi gtk+3 pygobject3
brew install pipx
pipx ensurepath
pipx install --system-site-packages solaar
solaar --help
```

And I get:
```bash
Traceback (most recent call last):
  File "/Users/testUser/.local/bin/solaar", line 53, in <module>
    import solaar.gtk
  File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/gtk.py", line 34, in <module>
    from solaar import cli
  File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/cli/__init__.py", line 26, in <module>
    from logitech_receiver import device
  File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/device.py", line 35, in <module>
    from . import hidpp10
  File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/hidpp10.py", line 22, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'

```

How can I install the latest from GitHub, as suggested?

**Comment by Write** [comment]
> > With the latest code from GitHub there shouldn't be a typing_extension problem anymore. The way you install from pip directly installs an older version, which has the issue.
> 
> [@MattHag](https://github.com/MattHag) I'm getting the same issue and I installed using `pipx`:
> 
> brew update
> brew install hidapi gtk+3 pygobject3
> brew install pipx
> pipx ensurepath
> pipx install --system-site-packages solaar
> solaar --help
> And I get:
> 
> Traceback (most recent call last):
>   File "/Users/testUser/.local/bin/solaar", line 53, in <module>
>     import solaar.gtk
>   File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/gtk.py", line 34, in <module>
>     from solaar import cli
>   File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/cli/__init__.py", line 26, in <module>
>     from logitech_receiver import device
>   File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/device.py", line 35, in <module>
>     from . import hidpp10
>   File "/Users/testUser/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/hidpp10.py", line 22, in <module>
>     from typing_extensions import Protocol
> ModuleNotFoundError: No module named 'typing_extensions'
> How can I install the latest from GitHub, as suggested?

Hi, 

 `pipx install --system-site-packages git+https://github.com/pwr-Solaar/Solaar.git`

**Comment by dintort** [comment]
The official installation guide for macOS works well: https://pwr-solaar.github.io/Solaar/installation/#installing-in-macos
However, Solaar was still unusable because devices (at least my K400) do not persist settings and forget everything when they go to sleep, so Solaar needs to be running continuosly in background all the time.
To address this I created a couple of scripts for creating macOS app wrapper and LaunchAgent: #3008

**Comment by denppa** [comment]
Just tested Solaar inside an ARM Linux VM on UTM. Pass the Logitech Unify USB Receiver into the VM, and then Solaar can modify its settings.

**Comment by pfps** [comment]
The macOS port appears to be mostly functional, so I'm closing this issue.

**Comment by dintort** [comment]
> The macOS port appears to be mostly functional, so I'm closing this issue.

The ultimate solution for a proper "macOS port" would be a .dmg package - the current DIY setup is far from user-friendly.

**Comment by pfps** [comment]
That's a job for a packager, and this kind of work is done outside of the Solaar project.
