### ISSUE TITLE
Installation problem - hid-logitech-dj

### ISSUE THREAD

**Issue by ZacharieALES** [pwr-Solaar/Solaar#1266]
I am using Ubuntu 18.04 and I am not able to make solaar work (even if I succeeded on another computer with Ubuntu a few months ago...).
I cloned the repository and followed the installation instructions but I am not able to install one of the dependecies: hid-logitech-dj. The command `sudo apt install hid-logitech-dj` gives me: Unable to locate package hid-logitech-dj. Was this package removed from the repositories recently? 

Do you know how I could install it? I was not able to find any help with google. 
It just lead me to a file [hid-logitech-dj.c](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-logitech-dj.c) but I don't know what to do with it.

Without this package, I get the following error: 
`solaar: error: Traceback (most recent call last):
  File "/home/zach/.local/lib/python3.6/site-packages/solaar/cli/__init__.py", line 198, in run
    c = list(_receivers(hidraw_path))
  File "/home/zach/.local/lib/python3.6/site-packages/solaar/cli/__init__.py", line 104, in _receivers
    from logitech_receiver import Receiver
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/__init__.py", line 36, in <module>
    from . import listener, status  # noqa: F401
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/listener.py", line 28, in <module>
    from . import base as _base
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/base.py", line 39, in <module>
    from .base_usb import ALL as _RECEIVER_USB_IDS
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/base_usb.py", line 32, in <module>
    from .descriptors import DEVICES as _DEVICES
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/descriptors.py", line 27, in <module>
    from .settings_templates import FeatureSettings as _FS
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/settings_templates.py", line 27, in <module>
    from solaar.ui import notify as _notify
  File "/home/zach/.local/lib/python3.6/site-packages/solaar/ui/__init__.py", line 29, in <module>
    from logitech_receiver.status import ALERT  # NOQA: E402 # isort:skip
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/status.py", line 29, in <module>
    from . import settings as _settings
  File "/home/zach/.local/lib/python3.6/site-packages/logitech_receiver/settings.py", line 27, in <module>
    from time import time_ns as _time_ns
ImportError: cannot import name 'time_ns'
`

**Comment by pfps** [comment]
Solaar needs a kernel with certain kernel modules installed.   If your kernel doesn't have these modules the solution is to update your kernel, for example to move from Ubuntu 18.04 to a newer kernel.   But 18.04 should have these modules, and they are not something that can be installed separately.

My suggestion is to use the Ubuntu stable PPA listed in https://github.com/pwr-Solaar/Solaar, which gives you Solaar version 1.0.6, the most recent released version of Solaar.

I do see that the version of Solaar in this repository is not installing correctly in Ubuntu 18.04, but is installing in more recent versions of Ubuntu, due to the missing time_ns.  It appears that time_ns requires Python 3.7, and Solaar should run in Python 3.6, so a fix is needed.

**Comment by pfps** [comment]
Please try PR #1267 

To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1267, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1267/head:pull_1267
git checkout pull_1267
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1267
git fetch origin pull/1267/head
git reset --hard FETCH_HEAD
```

**Comment by ZacharieALES** [comment]
Perfect, it worked. Thanks!

**Comment by ZacharieALES** [comment]
The bug is not solved but pfps's workaround works.

**Comment by pfps** [comment]
Did you try PR #1267

**Comment by ZacharieALES** [comment]
Yes this is the solution that worked

**Comment by pfps** [comment]
So the PR actually fixes the bug - it is not a workaround.

**Comment by ZacharieALES** [comment]
My bad, I thought that pfps made me use an older release of Solaar on which my problem does not occur. I did not realise that it was a new solution! No more bug indeed :)
