### ISSUE TITLE
Big icon in panel

### ISSUE THREAD

**Issue by jkaart** [pwr-Solaar/Solaar#1351]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.0
- Distribution: Ubuntu 20.04 Mate
- Kernel version (ex. `uname -srmo`): Linux 5.11.0-40-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : BFED9A39
    Firmware   : 24.10.B0036
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=189

  1: Wireless Mouse MX Master 2S
     Device path  : /dev/hidraw1
     WPID         : 4069
     Codename     : MX Master 2S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: B467A9FB
     Model ID:      B01940690000
     Unit ID:       FCD51C99
        Bootloader: BOT 56.01.B0006
          Firmware: MPM 12.01.B0006
          Firmware: MPM 12.01.B0006
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 56.01.B0006 406916A9FC5401
            Firmware: Firmware MPM 12.01.B0006 B01916A9FC5401
            Firmware: Firmware MPM 12.01.B0006 406916A9FC5401
            Firmware: Other   
            Unit ID: FCD51C99  Model ID: B01940690000  Transport IDs: {'btleid': 'B019', 'wpid': '4069'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse MX Master 2S
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         8: CONFIG DEVICE PROPS    {1806}   internal, hidden
         9: CHANGE HOST            {1814}   
            Change Host        : 1:Kone1
        10: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions (saved): {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}
            Key/Button Actions        : {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '195': 195, '196': 196}
        11: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        12: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        13: SMART SHIFT            {2110}   
            Scroll Wheel Rachet (saved): 0
            Scroll Wheel Rachet        : 0
        14: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Free wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
        15: GESTURE 2              {6501}   
            Gestures (saved): {'45': True, '46': True}
            Gestures        : {'46': True, '45': True}
        16: DFUCONTROL SIGNED      {00C2}   
        17: unknown:1813           {1813}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:18C0           {18C0}   internal, hidden
        23: unknown:1DF3           {1DF3}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9200           {9200}   internal, hidden
        30: unknown:9202           {9202}   internal, hidden
        31: OOBSTATE               {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Has 2 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled (   0): True
        NaturalScrolling           Enabled (   1): True
        period unit                Spec    (   3): 800
        DVI field width            Spec    (   1): 8
        field widths               Spec    (   2): 8
        resolution                 Spec    (   4): 2048
     Battery: 90%, discharging, next level 50%.
```
</details>

**Describe the bug**
After update to newest 1.1.0 version. Panel icon is very big in Mate panel?!

**To Reproduce**
Bootup system and you can see it in panel.

**Screenshots**

![Screenshot at 2021-11-29 15-41-33](https://user-images.githubusercontent.com/15191183/143878476-1d6df103-e1f8-4cfa-b571-bc8a5e1478d8.png)

**Additional context**
N/A

**Comment by jkaart** [comment]
> I'm assuming that the large icon is the green partial one.
> 
> There are several implementations of the system panel, many of which have bugs. Solaar now sometimes specifies an actual icon file as opposed to an icon name to get around a bug in one of these implementations. The system panel should resize the icon to fit within the panel area but it appears that the Mate panel isn't doing that.
> 
> It might be necessary (but regrettabel) to add an option to Solaar to switch it between using icon files and icon names.
> 
> To see whether changing back to icon names would help, modify line 176 of tray.py to
> 
> ```
>         if not os.path.isfile(icon_name):
> ```

You mean line 177 not 176?
Line 176 is:
`    def _icon_file(icon_name):`
and if edited line 177
`if False and not os.path.isfile(icon_name):`
to you suggested solaar crash in startup:
`solaar: error: Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/solaar/gtk.py", line 155, in main
    import solaar.ui as ui
  File "/home/user/.local/lib/python3.8/site-packages/solaar/ui/__init__.py", line 99, in <module>
    from . import notify, tray, window  # isort:skip  # noqa: E402
  File "/home/juser/.local/lib/python3.8/site-packages/solaar/ui/tray.py", line 179
    icon_info = Gtk.IconTheme.get_default().lookup_icon(icon_name, _TRAY_ICON_SIZE, Gtk.IconLookupFlags.FORCE_SVG)
                                                                                                                 ^
IndentationError: unindent does not match any outer indentation level
`

**Comment by pfps** [comment]
Oops, yes line 177.
You need to ensure that indentation works out correctly, so that the `if' and the 'icon_info' line up vertically.

**Comment by jkaart** [comment]
Yes, now it works and icon is back normal!

**Comment by pfps** [comment]
What appears to be happening is that Solaar (without the patch I suggested) is asking for 64-pixel icons which don't exist so a larger icon is used (256 pixels, probably).  Then the Ubuntu or Mint system tray implementation is not down-scaling these icons (which I believe it should).

The opposite happens under XFCE, where large icons are downscaled but small icons are not.

One path is to add an option to force icons of a particular size.  I'll put together a PR for this.

**Comment by lesliek20** [comment]
This worked for me. If anyone else is as ignorant as I am, they may be helped to know that I found the tray.py file in /usr/share/solaar/lib/solaar/ui.

**Comment by jkaart** [comment]
> 

Yes, this works! :)

**Comment by pfps** [comment]
OK, I'll merge it in and likely get out 1.1.1 in the near future.
