### ISSUE TITLE
Solaar 0.9.2 doesn't start/work on Ubuntu 13.10

### ISSUE THREAD

**Issue by ngc-bg** [pwr-Solaar/Solaar#140]
Hello,

In my case, after installation (using pre-build package for ubuntu), solaar doesn't start via GUI or CLI neither.

lsusb -d 046d:

```
Bus 001 Device 009: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 008: ID 046d:c22a Logitech, Inc. Gaming Keyboard G110
Bus 001 Device 007: ID 046d:c22b Logitech, Inc. Gaming Keyboard G110 G-keys
Bus 005 Device 002: ID 046d:0a1f Logitech, Inc. G930
```

/usr/bin/solaar -dd

```
** (solaar:29480): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (solaar:29480): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
21:36:24,372     INFO [MainThread] root: language en_US (UTF-8), translations path None
21:36:24,379     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/share/solaar/lib
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/ngc/.local/share/solaar/icons
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/ubuntu/solaar/icons
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/gnome/solaar/icons
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
21:36:24,381    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/ngc/.local/share/icons', '/home/ngc/.icons', '/usr/share/ubuntu/icons', '/usr/share/gnome/icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/share/ubuntu/pixmaps', '/usr/share/gnome/pixmaps', '/usr/local/share/pixmaps', '/usr/share/pixmaps']
21:36:24,387    DEBUG [MainThread] solaar.ui.icons: detected icon sets: gpm True, oxygen False, gnome True, elementary True
21:36:24,411     INFO [MainThread] solaar.ui.tray: using AppIndicator3
21:36:24,411     INFO [MainThread] solaar.ui.notify: starting desktop notifications
21:36:24,442     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
21:36:24,443     INFO [MainThread] solaar.listener: starting receiver listening threads
solaar: error: int() can't convert non-string with explicit base
```

/usr/bin/solaar-cli -d show

```
Traceback (most recent call last):
  File "/usr/bin/solaar-cli", line 42, in <module>
    solaar.cli.main()
  File "/usr/share/solaar/lib/solaar/cli.py", line 430, in main
    receiver = _receiver(args.hidraw_path)
  File "/usr/share/solaar/lib/solaar/cli.py", line 53, in _receiver
    for dev_info in receivers():
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 86, in receivers
    for d in _hid.enumerate(*receiver_usb_id):
  File "/usr/share/solaar/lib/hidapi/udev.py", line 199, in enumerate
    dev_info = _match('add', dev, vendor_id, product_id, interface_number, hid_driver)
  File "/usr/share/solaar/lib/hidapi/udev.py", line 87, in _match
    if not ((vendor_id is None or vendor_id == int(vid, 16)) and
TypeError: int() can't convert non-string with explicit base
```

I've tried both solaar and solaar-gnome3 packages, unfortunately without success.
My system is Ubuntu with 3.11.6-031106-generic kernel, Python 2.7.5+

Thanks,
NG

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to age and inactivity.
