### ISSUE TITLE
Running Solaar shuts all the backlights completely off on the G915

### ISSUE THREAD

**Issue by Hubro** [pwr-Solaar/Solaar#1429]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.1.1
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `5.15.13-arch1-1`
- Output of `solaar show`:

```
Solaar version 1.1.1

Unifying Receiver
  Device path  : /dev/hidraw4
  USB id       : 046d:C52B
  Serial       : D8C3B659
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: MX Keys Keyboard
     Device path  : /dev/hidraw8
     WPID         : 408A
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 97624246
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).

Lightspeed Receiver
  Device path  : /dev/hidraw16
  USB id       : 046d:C541
  Serial       : 1E6F6B7F
    Firmware   : 01.02.B0028
    Bootloader : 01.27
    Other      : A6.FD
  Has 1 paired device(s) out of a maximum of 2.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=11

  1: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
     Device path  : None
     WPID         : 407C
     Codename     : G915 KEYBOARD
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 8 ms (125Hz)
     Serial number: 460DF756
     Model ID:      B354407CC33E
     Unit ID:       460DF756
        Bootloader: BOT 77.02.B0039
             Other:
          Firmware: MPK 09.03.B0041
             Other:
             Other:
     The power switch is located on the top left corner.
     Supports 38 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BOT 77.02.B0039 0000EC44D534
            Firmware: Other
            Firmware: Firmware MPK 09.03.B0041 407C3791543D
            Firmware: Other
            Firmware: Other
            Unit ID: 460DF756  Model ID: B354407CC33E  Transport IDs: {'btleid': 'B354', 'wpid': '407C', 'usbid': 'C33E'}
         3: DEVICE NAME            {0005}
            Name: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: DEVICE FRIENDLY NAME   {0007}
            Friendly Name: G915 KEYBOARD
         7: BATTERY VOLTAGE        {1001}
            Battery: 3796mV, discharging, 40.
         8: CHANGE HOST            {1814}
            Change Host        : 1:aura
         9: HOSTS INFO             {1815}
            Host 0 (paired): aura
            Host 1 (paired):
        10: RGB EFFECTS            {8071}
        11: PER KEY LIGHTING V2    {8081}
        12: REPROG CONTROLS V4     {1B04}
            Key/Button Diversion (saved): {'209': 0, '210': 0}
            Key/Button Diversion        : {'209': 0, '210': 0}
        13: REPORT HID USAGE       {1BC0}
        14: ENCRYPTION             {4100}
        15: KEYBOARD DISABLE BY USAGE {4522}
        16: KEYBOARD LAYOUT 2      {4540}
        17: GKEY                   {8010}
            Divert G Keys (saved): False
            Divert G Keys        : False
        18: MKEYS                  {8020}
        19: MR                     {8030}
        20: BRIGHTNESS CONTROL     {8040}
        21: ONBOARD PROFILES       {8100}
            Device Mode: On-Board
        22: REPORT RATE            {8060}
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        23: DFUCONTROL SIGNED      {00C2}
        24: DFU                    {00D0}
        25: DEVICE RESET           {1802}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: CONFIG DEVICE PROPS    {1806}   internal, hidden
        28: unknown:1813           {1813}   internal, hidden
        29: OOBSTATE               {1805}   internal, hidden
        30: unknown:1830           {1830}   internal, hidden
        31: unknown:1890           {1890}   internal, hidden
        32: unknown:1891           {1891}   internal, hidden
        33: unknown:18A1           {18A1}   internal, hidden
        34: unknown:1E00           {1E00}   hidden
        35: unknown:1EB0           {1EB0}   internal, hidden
        36: unknown:1861           {1861}   internal, hidden
        37: unknown:18B0           {18B0}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 3796mV, discharging, 40.

Lightspeed Receiver
  Device path  : /dev/hidraw12
  USB id       : 046d:C545
  Serial       : B745659B
    Firmware   : 02.01.B0006
    Bootloader : 00.01
    Other      : 90.2A
  Has 1 paired device(s) out of a maximum of 2.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=72

solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/cli/__init__.py", line 204, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 289, in run
    _print_device(dev)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 90, in _print_device
    dev.ping()
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 401, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/base.py", line 549, in ping
    raise NoSuchDevice(number=devnumber, request=request_id)
logitech_receiver.base.NoSuchDevice: {'number': 1, 'request': 25}
```

</details>

**Describe the bug**

If I have Solaar running, all the backlights on the G915 are immediately shut completely off. The only key with a backlight still visible is the lightspeed key (the one with 3 waves and a lightning bolt going through it.)

Pressing the backlight key only toggles the backlight for the lightspeed key, no other keys on the entire keyboard have any backlights. Pressing M1/2/3 to change profile has no effect.

Shutting down Solaar and restarting the keyboard, I get the backlights back. If I start Solaar, the backlights of the keyboard shut off the moment the keyboard is listed in the Solaar GUI.

Some times, after a few seconds, the backlight comes back. This happens perhaps 1/20 times. The next time the keyboard goes to sleep though, the backlight is lost again.

**To Reproduce**
(Seee description)

**Screenshots**
![image](https://user-images.githubusercontent.com/597206/149975583-551b995f-2b12-44eb-baa8-19bfe7011dd3.png)
Only the lightspeed key is lit.

![image](https://user-images.githubusercontent.com/597206/149975767-aab92f6a-d6aa-4b5a-8930-17b73dbb8949.png)

**Additional context**
-

**Comment by pfps** [comment]
I expect that this is caused by the interaction between polling rate and onboard profiles, as described in the Known Issues in https://github.com/pwr-Solaar/Solaar

- Many gaming mice and keyboards have both the ONBOARD PROFILES feature and the REPORT RATE feature. On these devices changing the Polling Rate setting requires modifying a setting in the ONBOARD PROFILES feature, which can modify how the device works. Changing the Polling Rate setting to "Ignore this setting" (see above) prevents Solaar from modifying the ONBOARD PROFILES feature. The device has to be reset (e.g., by turning it off and on again) before this fix will take effect.

**Comment by Svenum** [comment]
Same https://github.com/pwr-Solaar/Solaar/issues/1394

**Comment by Hubro** [comment]
Ah cool, it seems you're right. Ignoring the polling rate setting does indeed solve the problem.

Interestingly, I've been using the G915 Lightspeed TKL for several months, and it does not have this issue.

**Comment by pfps** [comment]
If you mean you have the same problem as #1394 you should post there so that you are notified when that issue is addressed.  Otherwise please explain further, and in a new issue if your problem is not related to this issue.

**Comment by pfps** [comment]
Different devices can have very different behaviour.  The TKL might not have onboard profiles or they might not be used to set up lighting or switching to profiles host mode might not affect the backlight.  
This is the joy/agony of working with hardware.

**Comment by pfps** [comment]
Posting output of `solaar show` with the TKL active would be useful.  It might just be better to get around the onboard profiles/report rate glitch by not allowing changes to the report rate if the device has onboard profiles, but if the TKL does have onboard profiles then it might be better to leave things as they are.

**Comment by Hubro** [comment]
@pfps Ah so that's why the command crashed. Here's the output of `solaar show` with all my devices active:

```
Solaar version 1.1.1

Unifying Receiver
  Device path  : /dev/hidraw4
  USB id       : 046d:C52B
  Serial       : D8C3B659
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=133

  1: MX Keys Keyboard
     Device path  : /dev/hidraw8
     WPID         : 408A
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 97624246
     Model ID:      B35B408A0000
     Unit ID:       97624246
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.01.B0013
             Other:
     The power switch is located on the edge of top right corner.
     Supports 33 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BL1 08.00.B0011 00008169E8BB
            Firmware: Firmware MPK 12.01.B0013 408AFE037737
            Firmware: Other
            Unit ID: 97624246  Model ID: B35B408A0000  Transport IDs: {'btleid': 'B35B', 'wpid': '408A'}
         3: DEVICE NAME            {0005}
            Name: MX Keys Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: DEVICE FRIENDLY NAME   {0007}
            Friendly Name: MX Keys
         7: BATTERY STATUS         {1000}
            Battery: 100%, discharging, next level 50%.
         8: REPROG CONTROLS V4     {1B04}
            Key/Button Diversion (saved): {'10': 0, '110': 0, '111': 0, '191': 0, '199': 0, '200': 0, '209': 0, '210': 0, '211': 0, '224': 0, '225': 0, '226': 0, '227': 0, '228': 0, '229': 0, '230': 0, '231': 0, '232': 0, '233': 0, '234': 0, '235': 0, '236': 0}
            Key/Button Diversion        : {'209': 0, '210': 0, '211': 0, '199': 0, '200': 0, '224': 0, '225': 0, '110': 0, '226': 0, '227': 0, '228': 0, '229': 0, '230': 0, '231': 0, '232': 0, '233': 0, '10': 0, '191': 0, '234': 0, '111': 0, '236': 0, '235': 0}
         9: CHANGE HOST            {1814}
            Change Host        : 1:aura
        10: HOSTS INFO             {1815}
            Host 0 (paired): aura
            Host 1 (paired): carbon
            Host 2 (unpaired):
        11: BACKLIGHT2             {1982}
            Backlight (saved): True
            Backlight        : True
        12: K375S FN INVERSION     {40A3}
            Swap Fx function (saved): False
            Swap Fx function        : False
        13: ENCRYPTION             {4100}
        14: LOCK KEY STATE         {4220}
        15: KEYBOARD DISABLE KEYS  {4521}
            Disable keys (saved): {'1': False, '16': False, '2': False, '4': False, '8': False}
            Disable keys        : {'1': False, '2': False, '4': False, '8': False, '16': False}
        16: MULTIPLATFORM          {4531}
            Set OS (saved): 0
            Set OS        : Windows
        17: DFUCONTROL SIGNED      {00C2}
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:1861           {1861}   internal, hidden
        31: unknown:1A20           {1A20}   internal, hidden
        32: unknown:18B0           {18B0}   internal, hidden
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         4: Brightness Up             , default: Brightness Up               => Brightness Up
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Dashboard Launchpad/Action Center, default: Dashboard Launchpad/Action Center => Dashboard Launchpad/Action Center
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: Backlight Down            , default: Backlight Down              => Backlight Down
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Backlight Up              , default: Backlight Up                => Backlight Up
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Previous Fn               , default: Previous                    => Previous
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Play/Pause Fn             , default: Play/Pause                  => Play/Pause
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Next Fn                   , default: Next                        => Next
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Mute Fn                   , default: Mute                        => Mute
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Down Fn            , default: Volume Down                 => Volume Down
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Volume Up Fn              , default: Volume Up                   => Volume Up
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Calculator                , default: Calculator                  => Calculator
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: unknown:0034              , default: Do Nothing One              => Do Nothing One
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.

Lightspeed Receiver
  Device path  : /dev/hidraw16
  USB id       : 046d:C541
  Serial       : 1E6F6B7F
    Firmware   : 01.02.B0028
    Bootloader : 01.27
    Other      : A6.FD
  Has 1 paired device(s) out of a maximum of 2.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=108

  1: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
     Device path  : None
     WPID         : 407C
     Codename     : G915 KEYBOARD
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 8 ms (125Hz)
     Serial number: 460DF756
     Model ID:      B354407CC33E
     Unit ID:       460DF756
        Bootloader: BOT 77.02.B0039
             Other:
          Firmware: MPK 09.03.B0041
             Other:
             Other:
     The power switch is located on the top left corner.
     Supports 38 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BOT 77.02.B0039 0000EC44D534
            Firmware: Other
            Firmware: Firmware MPK 09.03.B0041 407C3791543D
            Firmware: Other
            Firmware: Other
            Unit ID: 460DF756  Model ID: B354407CC33E  Transport IDs: {'btleid': 'B354', 'wpid': '407C', 'usbid': 'C33E'}
         3: DEVICE NAME            {0005}
            Name: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: DEVICE FRIENDLY NAME   {0007}
            Friendly Name: G915 KEYBOARD
         7: BATTERY VOLTAGE        {1001}
            Battery: 3791mV, discharging, 40.
         8: CHANGE HOST            {1814}
            Change Host        : 1:aura
         9: HOSTS INFO             {1815}
            Host 0 (paired): aura
            Host 1 (paired):
        10: RGB EFFECTS            {8071}
        11: PER KEY LIGHTING V2    {8081}
        12: REPROG CONTROLS V4     {1B04}
            Key/Button Diversion (saved): {'209': 0, '210': 0}
            Key/Button Diversion        : {'209': 0, '210': 0}
        13: REPORT HID USAGE       {1BC0}
        14: ENCRYPTION             {4100}
        15: KEYBOARD DISABLE BY USAGE {4522}
        16: KEYBOARD LAYOUT 2      {4540}
        17: GKEY                   {8010}
            Divert G Keys (saved): False
            Divert G Keys        : False
        18: MKEYS                  {8020}
        19: MR                     {8030}
        20: BRIGHTNESS CONTROL     {8040}
        21: ONBOARD PROFILES       {8100}
            Device Mode: On-Board
        22: REPORT RATE            {8060}
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        23: DFUCONTROL SIGNED      {00C2}
        24: DFU                    {00D0}
        25: DEVICE RESET           {1802}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: CONFIG DEVICE PROPS    {1806}   internal, hidden
        28: unknown:1813           {1813}   internal, hidden
        29: OOBSTATE               {1805}   internal, hidden
        30: unknown:1830           {1830}   internal, hidden
        31: unknown:1890           {1890}   internal, hidden
        32: unknown:1891           {1891}   internal, hidden
        33: unknown:18A1           {18A1}   internal, hidden
        34: unknown:1E00           {1E00}   hidden
        35: unknown:1EB0           {1EB0}   internal, hidden
        36: unknown:1861           {1861}   internal, hidden
        37: unknown:18B0           {18B0}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 3791mV, discharging, 40.

Lightspeed Receiver
  Device path  : /dev/hidraw12
  USB id       : 046d:C545
  Serial       : B745659B
    Firmware   : 02.01.B0006
    Bootloader : 00.01
    Other      : 90.2A
  Has 1 paired device(s) out of a maximum of 2.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=122

  1: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
     Device path  : None
     WPID         : 408E
     Codename     : G915 TKL
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 8 ms (125Hz)
     Serial number: E39C9BCF
     Model ID:      B35F408EC343
     Unit ID:       E39C9BCF
        Bootloader: BL1 12.00.B0017
             Other:
          Firmware: MPK 14.01.B0021
             Other:
             Other:
     The power switch is located on the top left corner.
     Supports 38 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BL1 12.00.B0017 00008B79E978
            Firmware: Other
            Firmware: Firmware MPK 14.01.B0021 408E5E599E54
            Firmware: Other
            Firmware: Other
            Unit ID: E39C9BCF  Model ID: B35F408EC343  Transport IDs: {'btleid': 'B35F', 'wpid': '408E', 'usbid': 'C343'}
         3: DEVICE NAME            {0005}
            Name: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: DEVICE FRIENDLY NAME   {0007}
            Friendly Name: G915 TKL
         7: BATTERY VOLTAGE        {1001}
            Battery: 4194mV, full, 100.
         8: CHANGE HOST            {1814}
            Change Host        : 1:aura
         9: HOSTS INFO             {1815}
            Host 0 (paired): aura
            Host 1 (unpaired):
        10: RGB EFFECTS            {8071}
        11: PER KEY LIGHTING V2    {8081}
        12: REPROG CONTROLS V4     {1B04}
            Key/Button Diversion (saved): {'209': 0, '210': 0}
            Key/Button Diversion        : {'209': 0, '210': 0}
        13: REPORT HID USAGE       {1BC0}
        14: ENCRYPTION             {4100}
        15: KEYBOARD DISABLE BY USAGE {4522}
        16: KEYBOARD LAYOUT 2      {4540}
        17: GKEY                   {8010}
            Divert G Keys (saved): False
            Divert G Keys        : False
        18: MKEYS                  {8020}
        19: MR                     {8030}
        20: BRIGHTNESS CONTROL     {8040}
        21: ONBOARD PROFILES       {8100}
            Device Mode: On-Board
        22: REPORT RATE            {8060}
            Polling Rate (ms): 1
        23: DFUCONTROL SIGNED      {00C2}
        24: DFU                    {00D0}
        25: DEVICE RESET           {1802}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: CONFIG DEVICE PROPS    {1806}   internal, hidden
        28: unknown:1813           {1813}   internal, hidden
        29: OOBSTATE               {1805}   internal, hidden
        30: unknown:1830           {1830}   internal, hidden
        31: unknown:1890           {1890}   internal, hidden
        32: unknown:1891           {1891}   internal, hidden
        33: unknown:18A1           {18A1}   internal, hidden
        34: unknown:1E00           {1E00}   hidden
        35: unknown:1EB0           {1EB0}   internal, hidden
        36: unknown:1861           {1861}   internal, hidden
        37: unknown:18B0           {18B0}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 4194mV, full, 100.

Lightspeed Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C539
  Serial       : EDC69B5D
    Firmware   : 39.05.B0040
    Bootloader : 01.08
    Other      : AA.BE
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G900 Chaos Spectrum Gaming Mouse
     Device path  : /dev/hidraw6
     WPID         : 4053
     Codename     : G900
     Kind         : mouse
     Protocol     : HID++ 4.2
     Polling rate : 8 ms (125Hz)
     Serial number: 5BFEBB5F
     Model ID:      C08100000000
     Unit ID:       5BFEBB5F
          Firmware: MPM 01.05.B0023
        Bootloader: BOT 20.02.B0020
             Other:
     The power switch is located on the base.
     Supports 25 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Firmware MPM 01.05.B0023 C081
            Firmware: Bootloader BOT 20.02.B0020 AABA
            Firmware: Other
            Unit ID: 5BFEBB5F  Model ID: C08100000000  Transport IDs: {'usbid': 'C081'}
         3: DEVICE NAME            {0005}
            Name: Gaming Mouse G900
            Kind: mouse
         4: BATTERY VOLTAGE        {1001}
            Battery: 3756mV, discharging, 30.
         5: unknown:1863           {1863}   internal, hidden
         6: unknown:18A1           {18A1}   internal, hidden
         7: unknown:1E00           {1E00}   hidden
         8: unknown:1E20           {1E20}
         9: unknown:1EB0           {1EB0}   internal, hidden
        10: ADJUSTABLE DPI         {2201}
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        11: ANGLE SNAPPING         {2230}
        12: SURFACE TUNING         {2240}
        13: REPORT RATE            {8060}
            Polling Rate (ms): 2
            Polling Rate (ms) (saved): 2
            Polling Rate (ms)        : 2
        14: ONBOARD PROFILES       {8100}
            Device Mode: Host
        15: MOUSE BUTTON SPY       {8110}
        16: unknown:1850           {1850}   internal, hidden
        17: DFUCONTROL SIGNED      {00C2}
        18: unknown:1801           {1801}   internal, hidden
        19: DEVICE RESET           {1802}   internal, hidden
        20: unknown:1890           {1890}   internal, hidden
        21: unknown:1811           {1811}   internal, hidden
        22: LATENCY MONITORING     {8111}
        23: COLOR LED EFFECTS      {8070}
        24: LED CONTROL            {1300}
     Battery: 3756mV, discharging, 30.
```

**Comment by pfps** [comment]
@Hubro I'm not sure what the difference between the two keyboard is but I'll leave report rate as is for now.
