### ISSUE TITLE
SyntaxError: more than 255 arguments with python 3.6 on RHEL 8 and derivatives

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#1570]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): `1.1.3rc2-2-g9ed76b2`
- Distribution: **RHEL 8.5**
- Kernel version (ex. `uname -srmo`): `Linux 4.18.0-348.20.1.el8_5.x86_64 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/solaar/cli/__init__.py", line 196, in run
    c = list(_receivers(hidraw_path))
  File "/usr/lib/python3.6/site-packages/solaar/cli/__init__.py", line 101, in _receivers
    from logitech_receiver import Receiver
  File "/usr/lib/python3.6/site-packages/logitech_receiver/__init__.py", line 33, in <module>
    from . import listener, status  # noqa: F401
  File "/usr/lib/python3.6/site-packages/logitech_receiver/listener.py", line 25, in <module>
    from . import base as _base
  File "/usr/lib/python3.6/site-packages/logitech_receiver/base.py", line 34, in <module>
    from . import hidpp10 as _hidpp10
  File "/usr/lib/python3.6/site-packages/logitech_receiver/hidpp10.py", line 27, in <module>
    from .hidpp20 import BATTERY_STATUS, FIRMWARE_KIND
  File "/usr/lib/python3.6/site-packages/logitech_receiver/hidpp20.py", line 30, in <module>
    from . import special_keys
  File "/usr/lib/python3.6/site-packages/logitech_receiver/special_keys.py", line 27
    Volume_Up=0x0001,
    ^
SyntaxError: more than 255 arguments
```
</details>

**Describe the bug**
After commit 0e1522aa62a9d035453592da7290af808a7bc985 , solaar no longer runs on RHEL 8 with the default python (3.6.8).

**To Reproduce**
1. Run `solaar show`
2. See error

**Screenshots**
N/A

**Comment by pfps** [comment]
PR #1570 should fix this issue.
