### ISSUE TITLE
Sub-rule Execute results in error in subprocess

### ISSUE THREAD

**Issue by GitJer** [pwr-Solaar/Solaar#1659]
- Solaar version: 1.1.4
- Distribution: linux mint 20.3
- Kernel version: `Linux 5.4.0-121-generic x86_64 GNU/Linux`

I made a rule that should execute a binary. Solaar, however, gives an error:
```
Traceback (most recent call last):
  File "/mnt/crucial/source/github/Solaar/lib/logitech_receiver/diversion.py", line 391, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/mnt/crucial/source/github/Solaar/lib/logitech_receiver/diversion.py", line 391, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/mnt/crucial/source/github/Solaar/lib/logitech_receiver/diversion.py", line 391, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  [Previous line repeated 1 more time]
  File "/mnt/crucial/source/github/Solaar/lib/logitech_receiver/diversion.py", line 1042, in evaluate
    subprocess.Popen(self.args)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/flameshot full -p /home/j/Pictures/'
```

If I change line 1042 to the following (added ```shell=True```), everything works as intended:
```subprocess.Popen(self.args, shell=True)``` 

Is there a good reason for not having ```shell=True``` in there?

**Comment by pfps** [comment]
What is the rule?

**Comment by pfps** [comment]
It looks as if you are trying to execute the file '/usr/bin/flameshot full -p /home/j/Pictures/'.  What you should do is make the file name the first argument, `-p' the second, and so on.

There is no need to always use a shell.  If a shell is needed, it can be given as the first argument.

**Comment by GitJer** [comment]
Thanks for your very fast response!
I've solved it by making a short shell script with the full command, which I call from the rule. This works!
Thanks!
