### ISSUE TITLE
Rules can't trigger on non-divertable buttons or keys

### ISSUE THREAD

**Issue by owbosh** [pwr-Solaar/Solaar#1668]
**Information**

- Solaar version: 1.1.4
- Distribution: Arch Linux
- Kernel version: 5.18.11-arch1-1
- Output of `solaar show`:

<details>

```
Solaar version 1.1.4

Lightspeed Receiver
  Device path  : /dev/hidraw8
  USB id       : 046d:C539
  Serial       : C1469DD4
    Firmware   : 39.06.B0040
    Bootloader : 02.09
    Other      : AA.BE
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G502 Gaming Mouse
     Device path  : /dev/hidraw9
     WPID         : 407F
     Codename     : G502
     Kind         : mouse
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: C0B41408
     Model ID:      407FC08D0000
     Unit ID:       C0B41408
        Bootloader: BOT 92.00.B0008
          Firmware: MPM 17.00.B0008
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 92.00.B0008 AAEF21F1FA5F
            Firmware: Firmware MPM 17.00.B0008 407F21F1FA5F
            Firmware: Other   
            Unit ID: C0B41408  Model ID: 407FC08D0000  Transport IDs: {'wpid': '407F', 'usbid': 'C08D'}
         3: DEVICE NAME            {0005}   
            Name: G502 LIGHTSPEED Wireless Gaming Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY VOLTAGE        {1001}   
            Battery: 3971mV, discharging, 70.
         7: COLOR LED EFFECTS      {8070}   
         8: LED CONTROL            {1300}   
         9: ONBOARD PROFILES       {8100}   
            Device Mode: On-Board
            Onboard Profiles (saved): Enable
            Onboard Profiles        : Enable
        10: MOUSE BUTTON SPY       {8110}   
        11: REPORT RATE            {8060}   
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        12: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI) (saved): 600
            Sensitivity (DPI)        : 600
        13: DEVICE RESET           {1802}   internal, hidden
        14: unknown:1803           {1803}   internal, hidden
        15: OOBSTATE               {1805}   internal, hidden
        16: CONFIG DEVICE PROPS    {1806}   internal, hidden
        17: unknown:1811           {1811}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:1801           {1801}   internal, hidden
        23: unknown:18B1           {18B1}   internal, hidden
        24: unknown:1DF3           {1DF3}   internal, hidden
        25: unknown:1E00           {1E00}   hidden
        26: unknown:1EB0           {1EB0}   internal, hidden
        27: unknown:1863           {1863}   internal, hidden
        28: unknown:1E22           {1E22}   internal, hidden
     Battery: 3971mV, discharging, 70.

Lightspeed Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:C545
  Serial       : AD1567FD
    Firmware   : 02.01.B0006
    Bootloader : 00.01
    Other      : 3D.88
  Has 1 paired device(s) out of a maximum of 2.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=22

  1: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
     Device path  : None
     WPID         : 408E
     Codename     : G915 TKL
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: F085CB9D
     Model ID:      B35F408EC343
     Unit ID:       F085CB9D
        Bootloader: BL1 12.00.B0017
             Other: 
          Firmware: MPK 14.01.B0021
             Other: 
             Other: 
     The power switch is located on the top left corner.
     Supports 37 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 12.00.B0017 00008B79E978
            Firmware: Other   
            Firmware: Firmware MPK 14.01.B0021 408E5E599E54
            Firmware: Other   
            Firmware: Other   
            Unit ID: F085CB9D  Model ID: B35F408EC343  Transport IDs: {'btleid': 'B35F', 'wpid': '408E', 'usbid': 'C343'}
         3: DEVICE NAME            {0005}   
            Name: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: G915 TKL
         7: BATTERY VOLTAGE        {1001}   
            Battery: 3923mV, discharging, 70.
         8: CHANGE HOST            {1814}   
            Change Host        : 1:archlinux
         9: HOSTS INFO             {1815}   
            Host 0 (paired): archlinux
            Host 1 (paired): 
        10: RGB EFFECTS            {8071}   
        11: PER KEY LIGHTING V2    {8081}   
        12: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {Host Switch Channel 1:Regular, Host Switch Channel 2:Regular}
            Key/Button Diversion        : {Host Switch Channel 1:Regular, Host Switch Channel 2:Regular}
        13: REPORT HID USAGE       {1BC0}   
        14: ENCRYPTION             {4100}   
        15: KEYBOARD DISABLE BY USAGE {4522}   
        16: KEYBOARD LAYOUT 2      {4540}   
        17: GKEY                   {8010}   
            Divert G Keys (saved): False
            Divert G Keys        : False
        18: MKEYS                  {8020}   
            M-Key LEDs (saved): {M1:False, M2:False, M3:False}
            M-Key LEDs        : {M1:False, M2:False, M3:False}
        19: MR                     {8030}   
            MR-Key LED (saved): False
            MR-Key LED        : False
        20: BRIGHTNESS CONTROL     {8040}   
        21: ONBOARD PROFILES       {8100}   
            Device Mode: On-Board
            Onboard Profiles (saved): Enable
            Onboard Profiles        : Enable
        22: REPORT RATE            {8060}   
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        23: DFUCONTROL SIGNED      {00C2}   
        24: DFU                    {00D0}   
        25: DEVICE RESET           {1802}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: CONFIG DEVICE PROPS    {1806}   internal, hidden
        28: unknown:1813           {1813}   internal, hidden
        29: OOBSTATE               {1805}   internal, hidden
        30: unknown:1830           {1830}   internal, hidden
        31: unknown:1890           {1890}   internal, hidden
        32: unknown:1891           {1891}   internal, hidden
        33: unknown:18A1           {18A1}   internal, hidden
        34: unknown:1E00           {1E00}   hidden
        35: unknown:1EB0           {1EB0}   internal, hidden
        36: unknown:1861           {1861}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 3923mV, discharging, 70.

USB and Bluetooth Devices

  1: Logitech PRO X Wireless Gaming Headset
     Device path  : /dev/hidraw2
     USB id       : 046d:0ABA
     Codename     : PRO Headset
     Kind         : headset
     Protocol     : HID++ 4.2
     Serial number: 
     Model ID:      000000000ABA
     Unit ID:       FFFFFFFF
          Firmware: U1  12.01.B0203
     Supports 6 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware U1  12.01.B0203 0ABA
            Unit ID: FFFFFFFF  Model ID: 000000000ABA  Transport IDs: {'btid': '0000', 'btleid': '0000'}
         3: DEVICE NAME            {0005}   
            Name: PRO X Wireless Gaming Headset
            Kind: None
         4: EQUALIZER              {8310}   
         5: SIDETONE               {8300}   
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/cli/__init__.py", line 205, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 305, in run
    _print_device(d, num=dev_num)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 237, in _print_device
    v = setting.val_to_string(setting.read(False))
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 277, in read
    reply = self._rw.read(self._device)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 764, in read
    return device.feature_request(self.feature, self.read_fnid, self.prefix, self.read_prefix, data_bytes)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 412, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params, no_reply=no_reply)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/hidpp20.py", line 1106, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params, no_reply=no_reply)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 400, in request
    return _base.request(
  File "/usr/lib/python3.10/site-packages/logitech_receiver/base.py", line 456, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 255, 'request': 1289, 'error': 5, 'params': b''}
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.4
- _NAME: G502 Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode, pointer_speed, dpi-sliding, speed-change, mouse-gestures,
    backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys, crown-smooth, divert-crown,
    divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _modelId: 407FC08D0000
  _sensitive: {dpi: true, hires-scroll-mode: false, hires-smooth-resolution: false}
  _serial: C0B41408
  _unitId: C0B41408
  _wpid: 407F
  dpi: 600
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  onboard_profiles: 1
  report_rate: 1
- _NAME: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _modelId: B35F408EC343
  _serial: F085CB9D
  _unitId: F085CB9D
  _wpid: 408E
  change-host: null
  divert-gkeys: false
  divert-keys: {209: 0, 210: 0}
  m-key-leds: {1: false, 2: false, 4: false}
  mr-key-led: false
  onboard_profiles: 1
  report_rate: 1
- _NAME: Logitech PRO X Wireless Gaming Headset
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, backlight, backlight-timed, fn-swap, reprogrammable-keys,
    persistent-remappable-keys, divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host,
    gesture2-gestures, gesture2-divert, gesture2-params, equalizer]
  _modelId: 000000000ABA
  _unitId: FFFFFFFF
```
</details>

- Errors or warrnings from Solaar:

<details>

```
12:19:36,966     INFO [MainThread] root: language en_AU (UTF-8), translations path /usr/share/locale
12:19:37,067     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
12:19:37,068     INFO [MainThread] logitech_receiver.diversion: loaded 1 rules from /home/owbosh/.config/solaar/rules.yaml
12:19:37,077     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
12:19:37,111  WARNING [MainThread] solaar.ui.icons: failed to detect icons
12:19:37,124     INFO [MainThread] solaar.listener: starting receiver listening threads
12:19:37,128     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw8', vendor_id='046D', product_id='C539', serial='', release=None, manufacturer=None, product=None, interface=2, driver='logitech-djreceiver', bus_id=3, isDevice=None)
12:19:37,128     INFO [MainThread] logitech_receiver.base: New lock 12
12:19:37,136     INFO [ReceiverListener:hidraw8] logitech_receiver.listener: started with <LightspeedReceiver(/dev/hidraw8,12)> (12)
12:19:37,137     INFO [ReceiverListener:hidraw8] solaar.listener: <LightspeedReceiver(/dev/hidraw8,12)>: notifications listener has started (12)
12:19:37,137     INFO [ReceiverListener:hidraw8] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw8)>
12:19:37,138     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw5', vendor_id='046D', product_id='C545', serial='', release=None, manufacturer=None, product=None, interface=2, driver='hid-generic', bus_id=3, isDevice=None)
12:19:37,145     INFO [ReceiverListener:hidraw8] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw8,12)>: receiver notifications enabled => ('wireless', 'software present')
12:19:37,149     INFO [ReceiverListener:hidraw8] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw8,12)>: present, No paired devices. (0) 
12:19:37,157     INFO [ReceiverListener:hidraw8] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw8,12)>: found new device 1 (407F)
12:19:37,157     INFO [ReceiverListener:hidraw8] solaar.listener: connection Notification(10,1,41,0C,327F40) for <Device(1,407F,G502 Gaming Mouse,C0B41408)> (mouse)
12:19:37,160     INFO [ReceiverListener:hidraw8] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw8,12)>: present, 1 paired device. (0) 
12:19:37,161     INFO [ReceiverListener:hidraw8] logitech_receiver.base: New lock 14
12:19:37,194     INFO [MainThread] logitech_receiver.base: New lock 13
12:19:37,198     INFO [ReceiverListener:hidraw5] logitech_receiver.listener: started with <LightspeedReceiver(/dev/hidraw5,13)> (13)
12:19:37,199     INFO [ReceiverListener:hidraw5] solaar.listener: <LightspeedReceiver(/dev/hidraw5,13)>: notifications listener has started (13)
12:19:37,199     INFO [ReceiverListener:hidraw5] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw5)>
12:19:37,203     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw2', vendor_id='046D', product_id='0ABA', serial='', release=None, manufacturer=None, product=None, interface=3, driver='hid-generic', bus_id=3, isDevice=True)
12:19:37,203     INFO [MainThread] logitech_receiver.base: New lock 15
12:19:37,204     INFO [ReceiverListener:hidraw5] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw5,13)>: receiver notifications enabled => ('wireless', 'software present')
12:19:37,208     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,13)>: present, No paired devices. (0) 
12:19:37,259     INFO [MainThread] logitech_receiver.status: <Device(255,0ABA,Logitech PRO X Wireless Gaming Headset,)> pushing device settings [<Setting([feature:range] PRO Headset:sidetone=None)>]
12:19:37,264    ERROR [MainThread] logitech_receiver.base: (15) device 255 error on feature request {0508}: 5 = logitech internal
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/ui/__init__.py", line 169, in <lambda>
    application.connect('startup', lambda app, startup_hook: _startup(app, startup_hook, use_tray, show_window), startup_hook)
  File "/usr/lib/python3.10/site-packages/solaar/ui/__init__.py", line 118, in _startup
    startup_hook()
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 315, in start_all
    _process_receiver_event('add', device_info)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 395, in _process_receiver_event
    _start(device_info)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 298, in _start
    rl = ReceiverListener(receiver, _status_callback)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 83, in __init__
    receiver.status.changed(True, reason='initialization')
  File "/usr/lib/python3.10/site-packages/logitech_receiver/status.py", line 311, in changed
    _settings.apply_all_settings(d)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 1419, in apply_all_settings
    s.apply()
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 336, in apply
    value = self.read(self.persist)  # Don't use persisted value if setting doesn't persist
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 277, in read
    reply = self._rw.read(self._device)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 764, in read
    return device.feature_request(self.feature, self.read_fnid, self.prefix, self.read_prefix, data_bytes)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 412, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params, no_reply=no_reply)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/hidpp20.py", line 1106, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params, no_reply=no_reply)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 400, in request
    return _base.request(
  File "/usr/lib/python3.10/site-packages/logitech_receiver/base.py", line 456, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)

12:19:37,298     INFO [ReceiverListener:hidraw8] solaar.listener: status_changed <Device(1,407F,G502 Gaming Mouse,C0B41408)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 70, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3971, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
12:19:37,299  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:37,300  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:37,380     INFO [ReceiverListener:hidraw8] logitech_receiver.status: <Device(1,407F,G502 Gaming Mouse,C0B41408)> pushing device settings [<Setting([feature:toggle] G502:hires-smooth-invert=None)>, <Setting([feature:toggle] G502:hires-smooth-resolution=None)>, <Setting([feature:toggle] G502:hires-scroll-mode=None)>, <Setting([feature:choice] G502:onboard_profiles=None)>, <Setting([feature:choice] G502:report_rate=None)>, <Setting([feature:choice] G502:dpi=None)>]
12:19:37,428    ERROR [ReceiverListener:hidraw8] logitech_receiver.base: (14) device 1 error on feature request {0B2E}: 2 = invalid argument
12:19:37,428  WARNING [ReceiverListener:hidraw8] logitech_receiver.settings: report_rate: error applying value 1 so ignore it (<Device(1,407F,G502 Gaming Mouse,C0B41408)>)
12:19:37,438     INFO [ReceiverListener:hidraw8] solaar.listener: status_changed <Device(1,407F,G502 Gaming Mouse,C0B41408)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 70, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3971, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
12:19:37,439  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:37,440  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:37,440  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:38,213     INFO [ReceiverListener:hidraw5] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw5,13)>: found new device 1 (408E)
12:19:38,213     INFO [ReceiverListener:hidraw5] solaar.listener: connection Notification(10,1,41,11,318E40) for <Device(1,408E,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,F085CB9D)> (keyboard)
12:19:38,214     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,13)>: present, 1 paired device. (0) 
12:19:38,285     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <Device(1,408E,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,F085CB9D)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 70, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3923, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
12:19:38,286  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:38,286  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:38,497     INFO [ReceiverListener:hidraw5] logitech_receiver.status: <Device(1,408E,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,F085CB9D)> pushing device settings [<Setting([feature:choice] G915 TKL:onboard_profiles=None)>, <Setting([feature:choice] G915 TKL:report_rate=None)>, <Setting([feature:map choice] G915 TKL:divert-keys=None)>, <Setting([feature:toggle] G915 TKL:divert-gkeys=None)>, <Setting([feature:multiple toggle] G915 TKL:m-key-leds=None)>, <Setting([feature:toggle] G915 TKL:mr-key-led=None)>, <Setting([feature:choice] G915 TKL:change-host=None)>]
12:19:38,516    ERROR [ReceiverListener:hidraw5] logitech_receiver.base: (13) device 1 error on feature request {162B}: 2 = invalid argument
12:19:38,516  WARNING [ReceiverListener:hidraw5] logitech_receiver.settings: report_rate: error applying value 1 so ignore it (<Device(1,408E,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,F085CB9D)>)
12:19:38,569     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <Device(1,408E,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,F085CB9D)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 70, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3923, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
12:19:38,569  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
12:19:38,569  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
```
</details>

**Describe the bug**
My rules in the rule editor are completely ignored, no matter what I try. I can see that there are some python errors in the debug, but I don't know what they mean or if they are relevant. All other Solaar features seem to be working.

**Comment by pfps** [comment]
It appears that some Headsets have problems with the equalizer setting.  Start Solaar.  In the GUI, open the headset and change the icon on the right hand side to ignore the setting.  But this shouldn't affect the rule system.  You should also do this for Report Rate for your mouse and keyboard as setting the report rate is not consistent with having onboard profiles enabled.

Many of the warnings are complaints about your icon them, which appears to be missing some of the icons that all themes should have.

Without know what the rules are and what you are doing to try to run the rules it is not possible to figure out what is going wrong.

**Comment by owbosh** [comment]
I'm just trying to execute any program on the press of the side buttons on my G502. In xev, they're displayed as button 8 and button 9. They're also the 'forward' and 'back' buttons by default. But setting the rule condition to these buttons does nothing either. Disabling onboard profiles also does nothing. This is my rules.yaml file:

```
%YAML 1.3
---
- Key: [Button 9, pressed]
- Execute: firefox
...
```

**Comment by pfps** [comment]
From https://pwr-solaar.github.io/Solaar/rules:   Solaar’s rules only trigger on HID++ notifications so device actions that normally produce HID output have to be first be set (diverted) to produce HID++ notifications instead of their normal behavior. Currently Solaar can divert some mouse scroll wheels, some mouse thumb wheels, the crown of Craft keyboards, and some keys and buttons. If the scroll wheel, thumb wheel, crown, key, or button is not diverted by setting the appropriate setting then no HID++ notification is generated and rules will not be triggered by manipulating the wheel, crown, key, or button. Look for HID++ or Diversion settings to see what diversion can be done with your devices.

So you have to divert the back button.  But the G502 doesn't have the ability to divert any buttons.  So there is no way to do what you want.  

The only keys or buttons you have that can trigger rule processing are the Host Switch Channel buttons on your keyboard.

**Comment by owbosh** [comment]
That explains it, but shouldn't there be at least a warning that my buttons aren't divertable? Right now it just fails silently without any indication of what's going on.

**Comment by pfps** [comment]
you might have other devices that can divert this key.
