### ISSUE TITLE
MX keys, some buttons doesn't reprogramable

### ISSUE THREAD

**Issue by EUA** [pwr-Solaar/Solaar#1779]
**Information**

- Solaar version: `1.1.5.r21.ga97070e6-1`
- Distribution: `ArchLinux x86-64`
- Kernel version: `Linux 5.19.12-arch1-1 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
[death@Ryzen ~]$ solaar show
Solaar version 1.1.5

Bolt Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:C548
  Serial       : 42343930353342353035323633373134
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=202, 2=151

  1: MX Keys for Business
     Device path  : None
     WPID         : B363
     Codename     : MX Keys B
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Serial number: C8457F05
     Model ID:      B36300000000
     Unit ID:       C8457F05
        Bootloader: BL1 31.00.B0009
          Firmware: RBK 68.00.B0009
             Other: 
     The power switch is located on the (unknown).
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BL1 31.00.B0009 B3636927CBB5
            Firmware: Firmware RBK 68.00.B0009 B3636927CBB5
            Firmware: Other   
            Unit ID: C8457F05  Model ID: B36300000000  Transport IDs: {'btleid': 'B363'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Keys for Business
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Keys B
         7: UNIFIED BATTERY        {1004} V2     
            Battery: 60%, discharging.
         8: REPROG CONTROLS V4     {1B04} V5     
            Key/Button Diversion (saved): {Calculator:Regular, Lock PC:Regular, Brightness Down:Diverted, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular, Voice Dictation:Regular, Open Emoji Panel:Regular, Snipping Tool:Regular, Mute Microphone:Regular}
            Key/Button Diversion        : {Calculator:Regular, Lock PC:Regular, Brightness Down:Diverted, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular, Voice Dictation:Regular, Open Emoji Panel:Regular, Snipping Tool:Regular, Mute Microphone:Regular}
         9: CHANGE HOST            {1814} V1     
            Change Host        : 1:Ryzen
        10: HOSTS INFO             {1815} V1     
            Host 0 (paired): Ryzen
            Host 1 (paired): Ryzen
            Host 2 (paired): Mi 10 Lite 5G
        11: BACKLIGHT2             {1982} V1     
            Backlight (saved): True
            Backlight        : True
        12: K375S FN INVERSION     {40A3} V0     
            Swap Fx function (saved): False
            Swap Fx function        : False
        13: LOCK KEY STATE         {4220} V0     
        14: KEYBOARD DISABLE KEYS  {4521} V0     
            Disable keys (saved): {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
            Disable keys        : {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
        15: MULTIPLATFORM          {4531} V1     
            Set OS (saved): Windows
            Set OS        : Windows
        16: DFUCONTROL             {00C3} V0     
        17: DEVICE RESET           {1802} V0    internal, hidden, unknown:000010 
        18: unknown:1803           {1803} V0    internal, hidden, unknown:000010 
        19: CONFIG DEVICE PROPS    {1806} V8    internal, hidden, unknown:000010 
        20: unknown:1816           {1816} V0    internal, hidden, unknown:000010 
        21: OOBSTATE               {1805} V0    internal, hidden 
        22: unknown:1830           {1830} V0    internal, hidden, unknown:000010 
        23: unknown:1891           {1891} V6    internal, hidden, unknown:000008 
        24: unknown:18A1           {18A1} V0    internal, hidden, unknown:000010 
        25: unknown:1E00           {1E00} V0    hidden 
        26: unknown:1E02           {1E02} V0    internal, hidden 
        27: unknown:1602           {1602} V0     
        28: unknown:1EB0           {1EB0} V0    internal, hidden, unknown:000010 
        29: unknown:1861           {1861} V0    internal, hidden, unknown:000010 
        30: unknown:1A20           {1A20} V0    internal, hidden, unknown:000010 
        31: unknown:18B0           {18B0} V0    internal, hidden, unknown:000010 
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: diverted
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Voice Dictation           , default: Voice Dictation             => Voice Dictation           
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: Open Emoji Panel          , default: Open Emoji Panel            => Open Emoji Panel          
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Mute Microphone           , default: Mute Microphone             => Mute Microphone           
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             nonstandard, reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Snipping Tool             , default: Snipping Tool               => Snipping Tool             
             nonstandard, reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: FN Key                    , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 60%, discharging.

  2: MX Master 3 for Business
     Device path  : None
     WPID         : B028
     Codename     : MX Master 3 B
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 12617690
     Model ID:      B02800000000
     Unit ID:       12617690
        Bootloader: BL1 41.00.B0009
          Firmware: RBM 14.00.B0009
             Other: 
     The power switch is located on the (unknown).
     Supports 35 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BL1 41.00.B0009 B0281D13EFC0
            Firmware: Firmware RBM 14.00.B0009 B0281D13EFC0
            Firmware: Other   
            Unit ID: 12617690  Model ID: B02800000000  Transport IDs: {'btleid': 'B028'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Master 3 for Business
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3 B
         8: UNIFIED BATTERY        {1004} V2     
            Battery: 80%, recharging.
         9: REPROG CONTROLS V4     {1B04} V5     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/cli/__init__.py", line 210, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 296, in run
    _print_device(dev)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 232, in _print_device
    v = setting.val_to_string(setting._device.persister.get(setting.name))
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 238, in val_to_string
    return self._validator.to_string(value)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/settings.py", line 1086, in to_string
    return '{' + ', '.join([element_to_string(k, value[k]) for k in sorted(value)]) + '}'
TypeError: '<' not supported between instances of 'str' and 'int'

[death@Ryzen ~]$ 

```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):
```
cat ~/.config/solaar/config.yaml
- 1.1.5
- _NAME: MX Master 3 for Business
  _absent: [hi-res-scroll, lowres-smooth-scroll, report_rate, pointer_speed, speed-change, backlight, fn-swap, disable-keyboard-keys, divert-crown, crown-smooth,
    divert-gkeys, multiplatform, gesture2-gestures, gesture2-params, onboard_profiles, backlight-timed, persistent-remappable-keys, m-key-leds, mr-key-led,
    gesture2-divert, lowres-scroll-mode, sidetone, equalizer]
  _battery: 4100
  _modelId: B02800000000
  _sensitive: {divert-keys: false, dpi: false, dpi-sliding: false, hires-smooth-invert: false, hires-smooth-resolution: false, mouse-gestures: false, reprogrammable-keys: false,
    smart-shift: false, thumb-scroll-invert: false, thumb-scroll-mode: false}
  _serial: '12617690'
  _unitId: '12617690'
  _wpid: B028
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 1, 196: 0, '195': 2}
  dpi: 2000
  dpi-sliding: 0
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  smart-shift: 0
  thumb-scroll-invert: true
  thumb-scroll-mode: false
- _NAME: MX Keys for Business
  _absent: [hi-res-scroll, lowres-smooth-scroll, hires-smooth-invert, hires-smooth-resolution, smart-shift, thumb-scroll-mode, thumb-scroll-invert, report_rate,
    pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, reprogrammable-keys, divert-crown, crown-smooth, divert-gkeys, gesture2-gestures, gesture2-params,
    onboard_profiles, backlight-timed, persistent-remappable-keys, m-key-leds, mr-key-led, gesture2-divert, lowres-scroll-mode, hires-scroll-mode, sidetone,
    equalizer]
  _battery: 4100
  _modelId: B36300000000
  _sensitive: {backlight: true, change-host: false, divert-keys: false, fn-swap: false, multiplatform: false}
  _serial: C8457F05
  _unitId: C8457F05
  _wpid: B363
  backlight: true
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 111: 0, 199: 1, 200: 0, 209: 0, 210: 0, 211: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0, 233: 0, 234: 0, 235: 0, 236: 0,
    259: 0, 264: 0, 266: 0, 284: 0}
  fn-swap: false
  multiplatform: 0
```

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
Some keys at top doesn't trigger event. So I can't remap. For example I have Brightness keys events but for example can't have any output when I press Fn+Emoji Panel Open (or just Emoji Panel Open key with Fn mode)

**To Reproduce**
1. Run solaar -dd
2. Press Fn+Open Emoji Panel Button

**Screenshots**
This terminal screenshot generated via solaar -dd
F1 generates first lines. Than I enter and press F2,
F2 doesn't fire anything.//
F3 and F4  gives BACKLIGHT2 notifications/
F5 just minimizes the windows.
F6  doesn't fire any event...
F7 same...

```
2022-10-02 01:56:11,169,169    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (17) => r[11 01 0800 00C70000000000000000000000000000]
2022-10-02 01:56:11,169,169    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,B363,MX Keys for Business,C8457F05)>: notification for feature REPROG CONTROLS V4, report 0, data 00C70000000000000000000000000000
2022-10-02 01:56:11,169,169    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,B363,MX Keys for Business,C8457F05)>: diverted controls pressed: 0xc7, 0x0, 0x0, 0x0
2022-10-02 01:56:11,169,169     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['XF86_MonBrightnessDown'] click, group 0, modifiers 16
2022-10-02 01:56:11,169,169    DEBUG [MainThread] logitech_receiver.diversion: uinput simulated input 1 224 1
2022-10-02 01:56:11,169,169    DEBUG [MainThread] logitech_receiver.diversion: uinput simulated input 1 224 0
2022-10-02 01:56:11,282,282    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (17) => r[11 01 0800 00000000000000000000000000000000]
2022-10-02 01:56:11,282,282    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,B363,MX Keys for Business,C8457F05)>: notification for feature REPROG CONTROLS V4, report 0, data 00000000000000000000000000000000
2022-10-02 01:56:11,282,282    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,B363,MX Keys for Business,C8457F05)>: diverted controls pressed: 0x0, 0x0, 0x0, 0x0


2022-10-02 01:56:17,559,559    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (17) => r[11 01 0B00 08050400000000000000000000000000]
2022-10-02 01:56:17,559,559    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,B363,MX Keys for Business,C8457F05)>: notification for feature BACKLIGHT2, report 0, data 08050400000000000000000000000000

2022-10-02 01:56:21,286,286    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (17) => r[11 01 0B00 08060400000000000000000000000000]
2022-10-02 01:56:21,286,286    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,B363,MX Keys for Business,C8457F05)>: notification for feature BACKLIGHT2, report 0, data 08060400000000000000000000000000


```

**Comment by pfps** [comment]
Solaar can only do the reprogramming and diversions that are possible on the device.  For your keyboard none of the keys are reprogrammable, but quite a few are divertable.  I guess that what you want to do is to divert some keys and use Solaar rules to simulate keypresses for them.

For that to happen the keys have to first be diverted.  The output of  `solaar show`  indicates which keys are diverted, which appears to only be Brightness Down:
```
    Key/Button Diversion        : {Calculator:Regular, Lock PC:Regular, Brightness Down:Diverted, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular, Voice Dictation:Regular, Open Emoji Panel:Regular, Snipping Tool:Regular, Mute Microphone:Regular}
```
So you need to use the Solaar GUI to divert more keys.

**Comment by pfps** [comment]
I would like to fix the crash in `solaar show` for your mouse.

**Comment by pfps** [comment]
As far as I can tell the crash in `solaar show` is caused by a problem in your config.yaml file.  Please edit ~/.config/solaar/config.yaml and remove the line 
```
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 1, 196: 0, '195': 2}
```
The problem is that this value is supposed to be a mapping from integers to integers only, with no strings in it.

**Comment by pfps** [comment]
Once you have made this change, please run `solaar show` and post the output here.

**Comment by rattkin** [comment]
I have MX mechanical mini keyboard.
I think I'm trying to do the same thing. 
I can't divert these keys:

- dictation
- emoji
- microphone mute 

I've diverted every unknown entry and I don't get any feedback from solaar.
Is it possible the keys are not in the divert key list?

I was able to divert the screenshot and search keys: https://rattkin.info/logitech-mx-mechanical-linux/

**Comment by pfps** [comment]
@rattkin The Solaar GUI shows what keys can be diverted in the Key/Button Diversion setting.  Only these keys can be diverted.  One problem with some keyboards, including the MX mechanical mini, is that the symbols on the keys are different from the Logitech internal names.  (Yes, this is stupid.)  So for these keys you may have to try diverting different key names until you find the correct one.

By the way, please post the output of `solaar show`.  That also provides the keys that can be diverted, and some more information about them.  The MX mechanical mini appears to have a key (#0141) that is unknown to Solaar.  Finding out the symbol for that key would be useful.   I'm not sure how this key will show up in the GUI.

**Comment by rattkin** [comment]
@pfps `solaar show`
```  1: MX Mechanical Mini
     Device path  : None
     WPID         : B367
     Codename     : MX MCHNCL M
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Serial number: C047EA6C
     Model ID:      B36700000000
     Unit ID:       C047EA6C
        Bootloader: BL1 50.00.B0010
          Firmware: RBK 72.01.B0011
             Other: 
     The power switch is located on the (unknown).
     Supports 33 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 50.00.B0010 B367A91B7FC8
            Firmware: Firmware RBK 72.01.B0011 B3679386D010
            Firmware: Other   
            Unit ID: C047EA6C  Model ID: B36700000000  Transport IDs: {'btleid': 'B367'}
         3: DEVICE NAME            {0005}   
            Name: MX Mechanical Mini
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: MX MCHNCL M
         7: UNIFIED BATTERY        {1004}   
         8: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {'212': 1, '226': 0, '227': 0, '231': 0, '232': 0, '233': 0, '259': 0, '264': 0, '266': 1, '267': 0, '268': 0, '269': 0, '270': 0, '271': 0, '272': 0, '273': 0, '274': 0, '277': 0, '279': 0, '280': 0, '281': 0, '282': 0, '283': 0, '284': 0, '286': 0, '316': 0, '321': 0}
            Key/Button Diversion        : {'226': 0, '227': 0, '259': 0, '264': 0, '266': 1, '284': 0, '212': 1, '321': 0, '231': 0, '232': 0, '233': 0, '267': 0, '268': 0, '269': 0, '270': 0, '271': 0, '272': 0, '273': 0, '274': 0, '316': 0, '277': 0, '286': 0, '279': 0, '280': 0, '281': 0, '282': 0, '283': 0}
         9: CHANGE HOST            {1814}   
            Change Host        : 1:jm-thinkpad-13
        10: HOSTS INFO             {1815}   
            Host 0 (paired): jm-thinkpad-13
            Host 1 (paired): jm-thinkpad-13
            Host 2 (paired): Galaxy Note10 Lite
        11: BACKLIGHT2             {1982}   
            Backlight (saved): True
            Backlight        : True
        12: K375S FN INVERSION     {40A3}   
            Swap Fx function (saved): False
            Swap Fx function        : False
        13: LOCK KEY STATE         {4220}   
        14: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {'1': False, '16': False, '4': False, '8': False}
            Disable keys        : {'1': False, '4': False, '8': False, '16': False}
        15: MULTIPLATFORM          {4531}   
            Set OS (saved): 0
            Set OS        : Windows
        16: KEYBOARD LAYOUT 2      {4540}   
        17: unknown:00C3           {00C3}   
        18: DEVICE RESET           {1802}   internal, hidden, unknown:000010
        19: unknown:1803           {1803}   internal, hidden, unknown:000010
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden, unknown:000010
        21: unknown:1816           {1816}   internal, hidden, unknown:000010
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden, unknown:000010
        24: unknown:1891           {1891}   internal, hidden, unknown:000008
        25: unknown:18A1           {18A1}   internal, hidden, unknown:000010
        26: unknown:1E00           {1E00}   hidden
        27: unknown:1E02           {1E02}   internal, hidden
        28: unknown:1602           {1602}   
        29: unknown:1EB0           {1EB0}   internal, hidden, unknown:000010
        30: unknown:1861           {1861}   internal, hidden, unknown:000010
        31: unknown:1A20           {1A20}   internal, hidden, unknown:000010
        32: unknown:18B0           {18B0}   internal, hidden, unknown:000010
     Has 32 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             is FN, FN sensitive, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             is FN, FN sensitive, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             is FN, FN sensitive, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         3: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         4: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         5: Show Desktop Fn           , default: unknown:00D8                => unknown:00D8              
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         6: Backlight Down Fn         , default: LedToggle                   => LedToggle                 
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
         7: Screenshot                , default: unknown:00DF                => unknown:00DF              
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: diverted
         8: Backlight Up Fn           , default: unknown:00F1                => unknown:00F1              
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
         9: MultiPlatform Search      , default: Multiplatform Search        => Multiplatform Search      
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: diverted
        10: unknown:0141              , default: unknown:00FD                => unknown:00FD              
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        11: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        12: Volume Down Fn            , default: Volume Down                 => Volume Down               
             nonstandard, reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        13: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             nonstandard, reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        14: unknown:010B              , default: unknown:00E0                => unknown:00E0              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        15: unknown:010C              , default: unknown:00E1                => unknown:00E1              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: unknown:010D              , default: unknown:00E2                => unknown:00E2              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: unknown:010E              , default: unknown:00E3                => unknown:00E3              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: unknown:010F              , default: unknown:00E4                => unknown:00E4              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: unknown:0110              , default: unknown:00E5                => unknown:00E5              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: unknown:0111              , default: unknown:00E6                => unknown:00E6              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: unknown:0112              , default: unknown:00E7                => unknown:00E7              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: unknown:013C              , default: unknown:00F8                => unknown:00F8              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: unknown:0115              , default: unknown:00EA                => unknown:00EA              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        24: unknown:011E              , default: unknown:00F3                => unknown:00F3              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        25: Lock Fn                   , default: unknown:00EC                => unknown:00EC              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        26: unknown:0118              , default: unknown:00ED                => unknown:00ED              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        27: unknown:0119              , default: unknown:00EE                => unknown:00EE              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        28: unknown:011A              , default: unknown:00EF                => unknown:00EF              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        29: unknown:011B              , default: unknown:00F0                => unknown:00F0              
             reprogrammable, divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        30: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        31: unknown:0034              , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
```

**Comment by rattkin** [comment]
@pfps 
I diverted the Unknown key 141  it is the play/pause button (F11)

**Comment by pfps** [comment]
@ratkin You appear to be running an older version of Solaar, as evidenced by the many missing key name.   For example, on Solaar 1.1.3 and later the key unknown:0034 is shown as the FN Key.  If you upgrade to the current released version (via `pip install --user solaar`, but then make sure that your path includes the place pip puts commands) you should see the keys you want to divert.

I've added key 141 to Solaar, but this change won't show up until the next distribution.

**Comment by rattkin** [comment]
@pfps I wonder hy ubuntu repo has the packages at all, if they never update them.
Thank you I installed the PPA

**Comment by EUA** [comment]
@pfps thanks for explanation.
I think, when rule is added into rule editor, **GUI should ask us if we also want to enable key/button diversion for that button**.
Otherwise users probably not easily notice that if there are a separate place for it.
Thank you.

**Comment by pfps** [comment]
The tooltip for the Key condition mentions this.

**Comment by rattkin** [comment]
@EUA I was able to get that fairly easily, maybe thanks to my years or ITR experience.
However, I to think it seems redundant.\
Why is it possible to "divert" a key and not set a rule for that?
Why is it possible to set a rule and not have the key diverted?
Maybe those two should be merged into one UI element?
