### ISSUE TITLE
Too few values in _battery_line

### ISSUE THREAD

**Issue by skitt** [pwr-Solaar/Solaar#1791]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.5
- Distribution: Debian 11
- Kernel version (ex. `uname -srmo`): 5.10.140-1
- Output of `solaar show`:

<details>

```
Solaar version 1.1.5

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : D4A19232
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=198

  1: Marathon Mouse M705 (M-R0009)
     Device path  : /dev/hidraw1
     WPID         : 101B
     Codename     : M705 (M-R0009)
     Kind         : mouse
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 23691D3D
          Firmware: 17.01.B0017
        Bootloader: 02.06
             Other: 00.04
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Features: special buttons, scroll accel (0x420000)
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 210, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 296, in run
    _print_device(dev)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 273, in _print_device
    _battery_line(dev)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 72, in _battery_line
    level, nextLevel, status, voltage = battery
ValueError: not enough values to unpack (expected 4, got 3)
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
{
  "101B:23691D3D": {
    "_name": "Marathon Mouse M705 (M-R0009)",
    "_sensitive": {
      "smooth-scroll": true
    },
    "_serial": "23691D3D",
    "side-scroll": true,
    "smooth-scroll": true
  },
  "_version": "1.0.7"
}```
</details>


- Errors or warrnings from Solaar:
<!-- Under normal operation Solaar keeps a log of warning and error messages in ~/.tmp
while it is running as a file starting with 'Solaar'.
If this file is not available or does not have useful information you can
run Solaar as `solaar -dd`, after killing any running Solaar processes to
have Solaar log informational, warning, and error messages to stdout. -->


**Describe the bug**
`solaar show` fails with the following error:

```
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 210, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 296, in run
    _print_device(dev)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 273, in _print_device
    _battery_line(dev)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 72, in _battery_line
    level, nextLevel, status, voltage = battery
ValueError: not enough values to unpack (expected 4, got 3)
```

**To Reproduce**
Steps to reproduce the behavior:
1. Run `solaar show` with a Logitech M705 mouse connected.

**Comment by pfps** [comment]
PR #1792 should fix this issue but it has not been tested, as testing needs hardware with the same registers as the reporter's M705.   Please run this PR and report back the result.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1792, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1792/head:pull_1792
git checkout pull_1792
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1792
git fetch origin pull/1792/head
git reset --hard FETCH_HEAD
```

**Comment by skitt** [comment]
Fantastic, I’ve tested that and it does indeed fix the issue:

```
Solaar version 1.1.5

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : D4A19232
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=104

  1: Marathon Mouse M705 (M-R0009)
     Device path  : /dev/hidraw1
     WPID         : 101B
     Codename     : M705 (M-R0009)
     Kind         : mouse
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 23691D3D
          Firmware: 17.01.B0017
        Bootloader: 02.06
             Other: 00.04
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Features: special buttons, scroll accel (0x420000)
     Battery: 65%, discharging.
```
