### ISSUE TITLE
Brightness Up/Down do not appear to work.

### ISSUE THREAD

**Issue by Laxzal** [pwr-Solaar/Solaar#1874]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.7
- Distribution: Ubuntu 22.04 LTS
- Kernel version (ex. `uname -srmo`): `Linux 5.15.0-53-generic x86_64 GNU/Linux` 
- Output of `solaar show`:

<details>

```
Solaar version 1.1.7

Unifying Receiver
  Device path  : /dev/hidraw4
  USB id       : 046d:C52B
  Serial       : E7A3604D
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=82

  1: MX Keys Keyboard
     Device path  : /dev/hidraw5
     WPID         : 408A
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 9ACDD11D
     Model ID:      B35B408A0000
     Unit ID:       9ACDD11D
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.01.B0013
             Other: 
     The power switch is located on the edge of top right corner.
     Supports 33 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BL1 08.00.B0011 00008169E8BB
            Firmware: Firmware MPK 12.01.B0013 408AFE037737
            Firmware: Other   
            Unit ID: 9ACDD11D  Model ID: B35B408A0000  Transport IDs: {'btleid': 'B35B', 'wpid': '408A'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Keys Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Keys
         7: BATTERY STATUS         {1000} V1     
            Battery: 100%, discharging, next level 50%.
         8: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Diversion (saved): {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Mission Control/Task View:Regular, Dashboard Launchpad/Action Center:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular}
            Key/Button Diversion        : {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Mission Control/Task View:Regular, Dashboard Launchpad/Action Center:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular}
         9: CHANGE HOST            {1814} V1     
            Change Host        : 1:calvin-office-dana-group
        10: HOSTS INFO             {1815} V1     
            Host 0 (paired): calvin-office-dana-group
            Host 1 (unpaired): 
            Host 2 (unpaired): 
        11: BACKLIGHT2             {1982} V1     
            Backlight (saved): True
            Backlight        : True
        12: K375S FN INVERSION     {40A3} V0     
            Swap Fx function (saved): True
            Swap Fx function        : True
        13: ENCRYPTION             {4100} V0     
        14: LOCK KEY STATE         {4220} V0     
        15: KEYBOARD DISABLE KEYS  {4521} V0     
            Disable keys (saved): {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
            Disable keys        : {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
        16: MULTIPLATFORM          {4531} V1     
            Set OS (saved): Windows
            Set OS        : Windows
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: DEVICE RESET           {1802} V0    internal, hidden 
        19: unknown:1803           {1803} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V5    internal, hidden 
        21: unknown:1813           {1813} V0    internal, hidden 
        22: OOBSTATE               {1805} V0    internal, hidden 
        23: unknown:1830           {1830} V0    internal, hidden 
        24: unknown:1890           {1890} V5    internal, hidden 
        25: unknown:1891           {1891} V5    internal, hidden 
        26: unknown:18A1           {18A1} V0    internal, hidden 
        27: unknown:1DF3           {1DF3} V0    internal, hidden 
        28: unknown:1E00           {1E00} V0    hidden 
        29: unknown:1EB0           {1EB0} V0    internal, hidden 
        30: unknown:1861           {1861} V0    internal, hidden 
        31: unknown:1A20           {1A20} V0    internal, hidden 
        32: unknown:18B0           {18B0} V0    internal, hidden 
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Dashboard Launchpad/Action Center, default: Dashboard Launchpad/Action Center => Dashboard Launchpad/Action Center
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: FN Key                    , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.

Bolt Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C548
  Serial       : 30393039323530453537393035353937
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 2=228

  2: MX Master 3S
     Device path  : None
     WPID         : B034
     Codename     : MX Master 3S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: B023AB5A
     Model ID:      B03400000000
     Unit ID:       B023AB5A
        Bootloader: BL1 69.00.B0003
          Firmware: RBM 22.00.B0003
             Other: 
     The power switch is located on the (unknown).
     Supports 36 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BL1 69.00.B0003 B03438FCA4E6
            Firmware: Firmware RBM 22.00.B0003 B03438FCA4E6
            Firmware: Other   
            Unit ID: B023AB5A  Model ID: B03400000000  Transport IDs: {'btleid': 'B034'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Master 3S
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3S
         8: UNIFIED BATTERY        {1004} V3     
            Battery: 90%, discharging.
         9: REPROG CONTROLS V4     {1B04} V5     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
        10: CHANGE HOST            {1814} V1     
            Change Host        : 1:calvin-office-dana-group
        11: HOSTS INFO             {1815} V2     
            Host 0 (paired): calvin-office-dana-group
            Host 1 (unpaired): 
            Host 2 (unpaired): 
        12: XY STATS               {2250} V1     
        13: ADJUSTABLE DPI         {2201} V2     
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        14: SMART SHIFT            {2110} V0     
            Scroll Wheel Ratcheted (saved): Ratcheted
            Scroll Wheel Ratcheted        : Ratcheted
            Scroll Wheel Ratchet Speed (saved): 10
            Scroll Wheel Ratchet Speed        : 10
        15: HIRES WHEEL            {2121} V1     
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            Low resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): False
            Scroll Wheel Resolution        : False
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        16: THUMB WHEEL            {2150} V0     
            Thumb Wheel Direction (saved): False
            Thumb Wheel Direction        : False
            Thumb Wheel Diversion (saved): False
            Thumb Wheel Diversion        : False
        17: WHEEL STATS            {2251} V0     
        18: DFUCONTROL             {00C3} V0     
        19: DEVICE RESET           {1802} V0    internal, hidden, unknown:000010 
        20: unknown:1803           {1803} V0    internal, hidden, unknown:000010 
        21: CONFIG DEVICE PROPS    {1806} V8    internal, hidden, unknown:000010 
        22: unknown:1816           {1816} V0    internal, hidden, unknown:000010 
        23: OOBSTATE               {1805} V0    internal, hidden 
        24: unknown:1830           {1830} V0    internal, hidden, unknown:000010 
        25: unknown:1891           {1891} V7    internal, hidden, unknown:000008 
        26: unknown:18A1           {18A1} V0    internal, hidden, unknown:000010 
        27: unknown:1E00           {1E00} V0    hidden 
        28: unknown:1E02           {1E02} V0    internal, hidden 
        29: unknown:1602           {1602} V0     
        30: unknown:1EB0           {1EB0} V0    internal, hidden, unknown:000010 
        31: unknown:1861           {1861} V1    internal, hidden, unknown:000010 
        32: unknown:9300           {9300} V0    internal, hidden, unknown:000010 
        33: unknown:9001           {9001} V0    internal, hidden, unknown:000010 
        34: unknown:1E22           {1E22} V0    internal, hidden, unknown:000010 
        35: unknown:9205           {9205} V0    internal, hidden, unknown:000010 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 90%, discharging.

```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.7
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, dpi, speed-change, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B35B408A0000
  _sensitive: {backlight: false, divert-keys: false, fn-swap: false}
  _serial: 9ACDD11D
  _unitId: 9ACDD11D
  _wpid: 408A
  backlight: true
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 225: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0,
    233: 0, 234: 0, 235: 0, 236: 0}
  fn-swap: true
  multiplatform: 0
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer]
  _battery: 4100
  _modelId: B03400000000
  _serial: B023AB5A
  _unitId: B023AB5A
  _wpid: B034
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: false
```
</details>

- Errors or warrnings from Solaar:

<details>

```
2022-11-23 11:33:34,009,009     INFO [MainThread] root: language en_IL (UTF-8), translations path None
2022-11-23 11:33:34,081,081     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2022-11-23 11:33:34,082,082     INFO [MainThread] logitech_receiver.diversion: loaded 1 rules from /home/calvin/.config/solaar/rules.yaml
2022-11-23 11:33:34,090,090     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
2022-11-23 11:33:34,118,118     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2022-11-23 11:33:34,143,143     INFO [MainThread] solaar.listener: starting receiver listening threads
2022-11-23 11:33:34,144,144  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C52B: No module named 'hid_parser'
2022-11-23 11:33:34,144,144     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C52B HID++ None None USB 2 2
2022-11-23 11:33:34,144,144     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw4', bus_id=3, vendor_id='046D', product_id='C52B', interface=2, driver='logitech-djreceiver', manufacturer=None, product=None, serial='', release=None, isDevice=None, hidpp_short=None, hidpp_long=None)
2022-11-23 11:33:34,144,144     INFO [MainThread] logitech_receiver.base: New lock 13
2022-11-23 11:33:34,147,147     INFO [ReceiverListener:hidraw4] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw4,13)> (13)
2022-11-23 11:33:34,147,147     INFO [ReceiverListener:hidraw4] solaar.listener: <UnifyingReceiver(/dev/hidraw4,13)>: notifications listener has started (13)
2022-11-23 11:33:34,147,147     INFO [ReceiverListener:hidraw4] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw4)>
2022-11-23 11:33:34,148,148  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C548: No module named 'hid_parser'
2022-11-23 11:33:34,148,148     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C548 HID++ None None USB 0 2
2022-11-23 11:33:34,148,148  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C548: No module named 'hid_parser'
2022-11-23 11:33:34,148,148     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C548 HID++ None None USB 1 2
2022-11-23 11:33:34,148,148  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C548: No module named 'hid_parser'
2022-11-23 11:33:34,148,148     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C548 HID++ None None USB 2 2
2022-11-23 11:33:34,148,148     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw3', bus_id=3, vendor_id='046D', product_id='C548', interface=2, driver='hid-generic', manufacturer=None, product=None, serial='', release=None, isDevice=None, hidpp_short=None, hidpp_long=None)
2022-11-23 11:33:34,209,209     INFO [MainThread] logitech_receiver.base: New lock 14
2022-11-23 11:33:34,211,211     INFO [ReceiverListener:hidraw4] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,13)>: receiver notifications enabled => ('wireless', 'software present')
2022-11-23 11:33:34,212,212     INFO [ReceiverListener:hidraw3] logitech_receiver.listener: started with <BoltReceiver(/dev/hidraw3,14)> (14)
2022-11-23 11:33:34,212,212     INFO [ReceiverListener:hidraw3] solaar.listener: <BoltReceiver(/dev/hidraw3,14)>: notifications listener has started (14)
2022-11-23 11:33:34,212,212     INFO [ReceiverListener:hidraw3] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw3)>
2022-11-23 11:33:34,212,212  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 00000B05 PID 000019AF: No module named 'hid_parser'
2022-11-23 11:33:34,215,215     INFO [ReceiverListener:hidraw4] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw4,13)>: present, No paired devices. (0) 
2022-11-23 11:33:34,215,215     INFO [ReceiverListener:hidraw3] logitech_receiver.receiver: <BoltReceiver(/dev/hidraw3,14)>: receiver notifications enabled => ('wireless', 'software present')
2022-11-23 11:33:34,215,215     INFO [ReceiverListener:hidraw4] solaar.listener: ignoring DJ pairing notification Notification(20,1,41,01,8A401E4000000400000000)
2022-11-23 11:33:34,216,216     INFO [ReceiverListener:hidraw4] solaar.listener: ignoring DJ pairing notification Notification(20,0,41,02,0000000000000000000000)
2022-11-23 11:33:34,221,221     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <BoltReceiver(/dev/hidraw3,14)>: present, No paired devices. (0) 
2022-11-23 11:33:34,226,226     INFO [ReceiverListener:hidraw4] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,13)>: found new device 1 (408A)
2022-11-23 11:33:34,226,226     INFO [ReceiverListener:hidraw4] solaar.listener: connection Notification(10,1,41,04,B18A40) for <Device(1,408A,MX Keys Keyboard,9ACDD11D)> (keyboard)
2022-11-23 11:33:34,229,229     INFO [ReceiverListener:hidraw4] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw4,13)>: present, 1 paired device. (0) 
2022-11-23 11:33:34,234,234     INFO [ReceiverListener:hidraw4] logitech_receiver.base: New lock 24
2022-11-23 11:33:34,471,471     INFO [ReceiverListener:hidraw4] solaar.listener: status_changed <Device(1,408A,MX Keys Keyboard,9ACDD11D)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2022-11-23 11:33:35,226,226     INFO [ReceiverListener:hidraw3] logitech_receiver.receiver: <BoltReceiver(/dev/hidraw3,14)>: found new device 2 (B034)
2022-11-23 11:33:35,226,226     INFO [ReceiverListener:hidraw3] solaar.listener: connection Notification(10,2,41,10,0234B0) for <Device(2,B034,MX Master 3S,B023AB5A)> (mouse)
2022-11-23 11:33:35,909,909     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <BoltReceiver(/dev/hidraw3,14)>: present, 1 paired device. (0) 
2022-11-23 11:33:35,976,976     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <Device(2,B034,MX Master 3S,B023AB5A)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 90, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2022-11-23 11:33:36,227,227     INFO [ReceiverListener:hidraw4] logitech_receiver.status: <Device(1,408A,MX Keys Keyboard,9ACDD11D)> pushing device settings [<Setting([feature:toggle] MX Keys:backlight=None)>, <Setting([feature:toggle] MX Keys:fn-swap=None)>, <Setting([feature:map choice] MX Keys:divert-keys=None)>, <Setting([feature:multiple toggle] MX Keys:disable-keyboard-keys=None)>, <Setting([feature:choice] MX Keys:multiplatform=None)>, <Setting([feature:choice] MX Keys:change-host=None)>]
2022-11-23 11:33:36,381,381     INFO [ReceiverListener:hidraw3] logitech_receiver.status: <Device(2,B034,MX Master 3S,B023AB5A)> pushing device settings [<Setting([feature:toggle] MX Master 3S:hires-smooth-invert=None)>, <Setting([feature:toggle] MX Master 3S:hires-smooth-resolution=None)>, <Setting([feature:toggle] MX Master 3S:hires-scroll-mode=None)>, <Setting([feature:choice] MX Master 3S:scroll-ratchet=None)>, <Setting([feature:range] MX Master 3S:smart-shift=None)>, <Setting([feature:toggle] MX Master 3S:thumb-scroll-invert=None)>, <Setting([feature:toggle] MX Master 3S:thumb-scroll-mode=None)>, <Setting([feature:choice] MX Master 3S:dpi=None)>, <Setting([feature:map choice] MX Master 3S:reprogrammable-keys=None)>, <Setting([feature:map choice] MX Master 3S:divert-keys=None)>, <Setting([feature:choice] MX Master 3S:change-host=None)>]
2022-11-23 11:33:36,936,936     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <Device(2,B034,MX Master 3S,B023AB5A)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 90, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2022-11-23 11:33:37,131,131     INFO [ReceiverListener:hidraw4] solaar.listener: status_changed <Device(1,408A,MX Keys Keyboard,9ACDD11D)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2022-11-23 11:33:37,131,131     INFO [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(1,408A,MX Keys Keyboard,9ACDD11D)>: spurious BATTERY status Notification(11,1,07,10,0404C0060A0000000000000000000000)
2022-11-23 11:33:37,132,132  WARNING [MainThread] logitech_receiver.diversion: XKB display not available - rules cannot access keyboard group
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 150, in xkb_setup
    X11Lib = _ctypes.cdll.LoadLibrary('libX11.so')
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libX11.so: cannot open shared object file: No such file or directory
2022-11-23 11:33:37,139,139     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['XF86_MonBrightnessDown'] click, group None, modifiers 16
2022-11-23 11:33:37,154,154     INFO [MainThread] logitech_receiver.diversion: X11 library loaded and display set up
2022-11-23 11:33:37,170,170     INFO [MainThread] logitech_receiver.diversion: Execute action: ['/home/calvin/Documents/Scripts/dim.sh']
2022-11-23 11:33:37,171,171     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['XF86_MonBrightnessDown'] click, group None, modifiers 16
2022-11-23 11:33:37,190,190     INFO [MainThread] logitech_receiver.diversion: Execute action: ['/home/calvin/Documents/Scripts/dim.sh']
2022-11-23 11:33:37,192,192     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['XF86_MonBrightnessDown'] click, group None, modifiers 16
2022-11-23 11:33:37,203,203     INFO [MainThread] logitech_receiver.diversion: Execute action: ['/home/calvin/Documents/Scripts/dim.sh']
2022-11-23 11:33:37,203,203     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['XF86_MonBrightnessDown'] click, group None, modifiers 16
2022-11-23 11:33:37,214,214     INFO [MainThread] logitech_receiver.diversion: Execute action: ['/home/calvin/Documents/Scripts/dim.sh']
2022-11-23 11:33:48,563,563     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['XF86_MonBrightnessDown'] click, group None, modifiers 16
2022-11-23 11:33:48,574,574     INFO [MainThread] logitech_receiver.diversion: Execute action: ['/home/calvin/Documents/Scripts/dim.sh']
2022-11-23 11:33:49,731,731     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['XF86_MonBrightnessDown'] click, group None, modifiers 16
2022-11-23 11:33:49,747,747     INFO [MainThread] logitech_receiver.diversion: Execute action: ['/home/calvin/Documents/Scripts/dim.sh']
```

</details>

**Describe the bug**
The Brightness buttons do not appear to work, even when attempting to edit the rules. Furthermore, the backlight of the keyboard also does not work.

**To Reproduce**
1. Press Brightness Up/Down
2. No action occurs

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
The brightness keys on the MX Keys do not do anything in Windows OS mode so Solaar has to be involved in getting them to work.  Solaar comes with two built-in rules that simulate XF86 keypresses when the brightness keys are diverted and pressed.   From the log you provide you appear to have diverted the brightness keys, even though the output of solaar show does not so indicate, and written your own rule to simulate XF86 keypresses and also run a shell script.  All this appears to be working correctly.

For the XF86 keypresses to actually have any effect, some program has to capture them and change screen brightness.  Which program this is depends on what you have running - on my machine there is a power manager that does this but a switch has to be set.  If no program handles these keypresses then screen brightness will not change.

You have not provided details about your shell script so there is no way to determine what it does.  All that can be determined from the Solaar log is that the schell script was called.

It also appears that there is a missing library libX11.so that is used by Solaar to determine which keyboard group is active.  The Solaar installation instructions state that the X11 library should be installed.  (It is probably called libX11-devel or libX11-dev.)  This lack should not affect this problem because the XF86 keypresses should be independent of keyboard group.

**Comment by pfps** [comment]
@Laxzal Is there anything to do here?

**Comment by pfps** [comment]
Closing due to no response from submitter.

**Comment by skullmonkey911** [comment]
Hi, for those who have this situation. If you are one Wayland this won't work out of the Box. But you can create custom hotkeys for KDE Engeryoption (e.b. Brightness up), then create custom rules in Solaar and with this hotkey combination. work fine for me.
