### ISSUE TITLE
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1885]
$ cat /home/ejsc1/.cache/pre-commit/pre-commit.log
### version information

```
pre-commit version: 2.20.0
git --version: git version 2.37.2
sys.version:
    3.10.7 (main, Nov  2 2022, 18:49:29) [GCC 12.2.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/ejsc1/.cache/pre-commit/repo0d_gvvle/py_env-python3/bin/python>>
- expected version: 3.10.7.final.0

```

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/lib/python3/dist-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/usr/lib/python3/dist-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/usr/lib/python3/dist-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/usr/lib/python3/dist-packages/pre_commit/repository.py", line 84, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/ejsc1/.cache/pre-commit/repo0d_gvvle/py_env-python3/bin/python>>
- expected version: 3.10.7.final.0
```

**Comment by pfps** [comment]
I don't see a Solaar bug here.  I'm not experiencing this on my machine.

My only suggestion is to remove /home/ejsc1/.cache/pre-commit
