### ISSUE TITLE
Logitech G9x not recognized

### ISSUE THREAD

**Issue by vpelcak** [pwr-Solaar/Solaar#1990]
**Information**

- Solaar version: solaar 1.1.8
- Distribution: openSUSE Tumbleweed
- Kernel version (ex. `uname -srmo`): Linux 6.1.10-1-default x86_64 GNU/Linux
- Output of `solaar show`:

<details>
solaar version 1.1.8

USB and Bluetooth Devices

solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/cli/__init__.py", line 209, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 305, in run
    _print_device(d, num=dev_num)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 85, in _print_device
    dev.ping()
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/base.py", line 556, in ping
    raise NoSuchDevice(number=devnumber, request=request_id)
logitech_receiver.base.NoSuchDevice: {'number': 255, 'request': 28}
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
`~/.config/solaar` doesn't exist
```
</details>


- Errors or warnings from Solaar:
<!-- Under normal operation Solaar keeps a log of warning and error messages in ~/.tmp
while it is running as a file starting with 'Solaar'.
If this file is not available or does not have useful information you can
run Solaar as `solaar -dd`, after killing any running Solaar processes to
have Solaar log informational, warning, and error messages to stdout. -->

> solaar -dd
2023-02-14 09:24:19,412,412     INFO [MainThread] root: language en_US (UTF-8), translations path None
2023-02-14 09:24:19,642,642     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2023-02-14 09:24:19,669,669     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
2023-02-14 09:24:19,802,802     INFO [MainThread] solaar.listener: starting receiver listening threads
2023-02-14 09:24:20,096,096  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0018 VID 0000044E PID 0000120A: Unsupported global tag: 0b101
2023-02-14 09:24:20,119,119     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C066 HID++ True True USB 1 None
2023-02-14 09:24:20,119,119     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw8', bus_id=3, vendor_id='046D', product_id='C066', interface=1, driver='hid-generic', manufacturer=None, product=None, serial='085E959EC40018', release=None, isDevice=True, hidpp_short=True, hidpp_long=True)
2023-02-14 09:24:20,119,119     INFO [MainThread] logitech_receiver.base: New lock 14
2023-02-14 09:24:20,121,121    ERROR [MainThread] logitech_receiver.base: (14) device 255 error on ping request: unknown device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/ui/__init__.py", line 170, in <lambda>
    application.connect('startup', lambda app, startup_hook: _startup(app, startup_hook, use_tray, show_window), startup_hook)
  File "/usr/lib/python3.10/site-packages/solaar/ui/__init__.py", line 119, in _startup
    startup_hook()
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 314, in start_all
    _process_receiver_event('add', device_info)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 394, in _process_receiver_event
    _start(device_info)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 299, in _start
    rl = ReceiverListener(receiver, _status_callback)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 83, in __init__
    if receiver.ping():
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/base.py", line 556, in ping
    raise NoSuchDevice(number=devnumber, request=request_id)
logitech_receiver.base.NoSuchDevice: {'number': 255, 'request': 26}

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Start Solaar with G9x plugged in
2. Mouse is not recognized

**Additional context**

When I unpluch and plug the device back to USB:

2023-02-14 09:25:24,561,561     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C066 HID++ True True USB 1 None
2023-02-14 09:25:24,561,561     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw5', bus_id=3, vendor_id='046D', product_id='C066', interface=1, driver='hid-generic', manufacturer=None, product=None, serial='085E959EC40018', release=None, isDevice=True, hidpp_short=True, hidpp_long=True)
2023-02-14 09:25:24,561,561     INFO [MainThread] logitech_receiver.base: New lock 21
2023-02-14 09:25:24,563,563    ERROR [MainThread] logitech_receiver.base: (21) device 255 error on ping request: unknown device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 394, in _process_receiver_event
    _start(device_info)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 299, in _start
    rl = ReceiverListener(receiver, _status_callback)
  File "/usr/lib/python3.10/site-packages/solaar/listener.py", line 83, in __init__
    if receiver.ping():
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/base.py", line 556, in ping
    raise NoSuchDevice(number=devnumber, request=request_id)
logitech_receiver.base.NoSuchDevice: {'number': 255, 'request': 26}

**Comment by pfps** [comment]
Somehow the mouse isn't responding to ping requests.  It may be that this device can't be supported, but please provide the output of `solaar -ddd show`.  That will output details of the interaction with the mouse.

**Comment by vpelcak** [comment]
> solaar -ddd show
2023-02-14 12:55:18,486,486  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0018 VID 0000044E PID 0000120A: Unsupported global tag: 0b101
2023-02-14 12:55:18,536,536     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C066 HID++ True True USB 1 None
2023-02-14 12:55:18,536,536    DEBUG [MainThread] solaar.cli: [/dev/hidraw5] => <Device(255,C066,Unknown device C066,)>
2023-02-14 12:55:18,538,538  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000413C PID 0000B06F: Expecting 192 usages but got 15
2023-02-14 12:55:18,541,541  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000413C PID 0000B06E: Expecting 192 usages but got 15
solaar version 1.1.8

USB and Bluetooth Devices

2023-02-14 12:55:18,547,547    DEBUG [MainThread] logitech_receiver.base: (4) pinging device 255
2023-02-14 12:55:18,547,547     INFO [MainThread] logitech_receiver.base: New lock 4
2023-02-14 12:55:18,548,548    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 001A 000057]
2023-02-14 12:55:18,550,550    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F00 1A0800]
2023-02-14 12:55:18,550,550    ERROR [MainThread] logitech_receiver.base: (4) device 255 error on ping request: unknown device
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/cli/__init__.py", line 209, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 305, in run
    _print_device(d, num=dev_num)
  File "/usr/lib/python3.10/site-packages/solaar/cli/show.py", line 85, in _print_device
    dev.ping()
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/base.py", line 556, in ping
    raise NoSuchDevice(number=devnumber, request=request_id)
logitech_receiver.base.NoSuchDevice: {'number': 255, 'request': 26}

**Comment by pfps** [comment]
It looks as if all that is needed is a descriptor for this device, as it uses an old version of the HID++ protocol and thus needs a descriptor.   The descriptor needs a name and short name?  Is there an official name for the mouse (something like Logitech G9x Wireless Mouse)?  Running `lsusb -vv` might show something.  Do you know if the G9x and the G9 are different?

**Comment by pfps** [comment]
Also, Solaar needs to know what can be done with the mouse.  This is hard to determine for older devices.  I can assume that it is the same as G9 or you can, if possible, attach the mouse to a Windows machine and run the Logitech software to see what is possible.

**Comment by vpelcak** [comment]
I have actually these Logitech devices.

Bus 003 Device 009: ID 046d:c31c Logitech, Inc. Keyboard K120
Bus 003 Device 013: ID 046d:c066 Logitech, Inc. G9x Laser Mouse

**Comment by pfps** [comment]
OK, I added a descriptor for the G9x with the same settings as the G9.  Please download PR #1991 and see whether your mouse shows up.   Also provide the full output from `bin/solaar show`.

I'm not sure whether the K120 can be supported by Solaar.  It might need its own descriptor or it might just not use the HID++ protocol that Solaar supports.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1991, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1991/head:pull_1991
git checkout pull_1991
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1991
git fetch origin pull/1991/head
git reset --hard FETCH_HEAD
```

**Comment by vpelcak** [comment]
G9 and G9x look the same, but there are notable changes.

G9x has higher max DPI - 5700 while G9 has only 3200.

**Comment by vpelcak** [comment]
I will install Logitech software later and get info from there.

**Comment by pfps** [comment]
This might require some extra changes for Solaar.   Try out the DPI setting that should show up with PR #1991 and see whether it makes sense.

**Comment by vpelcak** [comment]
![obrazek](https://user-images.githubusercontent.com/1659215/218743373-cfafa46f-0f26-4f23-b240-6ba8cc5e229f.png)

It works. But DPI setting does not since the setup is set in profiles inside of the mouse itself.

**Comment by vpelcak** [comment]
BTW it has no battery at all.
Maybe it would be better to indicate that there instead of "unknown".

**Comment by pfps** [comment]
It turns out that there is something that should work most of the time - if there is no battery information found and the device is online, then report that a battery has not been found.

**Comment by pfps** [comment]
There is a new version of PR #1991 that does a bit better in reporting potentially missing batteries.  Please try  it out.  (Instructions above.)

**Comment by vpelcak** [comment]
Yes, it does have profiles. I remember configuring them some years ago in Logitech tool and i can switch among them in the mouse itself with the indicator showing the selected profile.

**Comment by vpelcak** [comment]
> bin/solaar -ddd show
2023-02-14 14:51:19,021,021  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0018 VID 0000044E PID 0000120A: Unsupported global tag: 0b101
2023-02-14 14:51:19,045,045     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C066 HID++ True True USB 1 1
2023-02-14 14:51:19,045,045    DEBUG [MainThread] solaar.cli: [/dev/hidraw5] => <Device(0,C066,G9x Laser Mouse,)>
2023-02-14 14:51:19,047,047  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000413C PID 0000B06F: Expecting 192 usages but got 15
2023-02-14 14:51:19,048,048  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000413C PID 0000B06E: Expecting 192 usages but got 15
solaar version 1.1.8-37-gce922c0

USB and Bluetooth Devices

2023-02-14 14:51:19,056,056    DEBUG [MainThread] logitech_receiver.base: (4) pinging device 0
2023-02-14 14:51:19,056,056     INFO [MainThread] logitech_receiver.base: New lock 4
2023-02-14 14:51:19,056,056    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 001C 000047]
2023-02-14 14:51:19,059,059    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 8F00 1C0100]
  1: G9x Laser Mouse
     Device path  : /dev/hidraw5
     USB id       : 046d:C066
     Codename     : G9x
     Kind         : mouse
     Protocol     : HID++ 1.0
     Serial number: 
2023-02-14 14:51:19,059,059    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 81F1 010000]
2023-02-14 14:51:19,061,061    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 81F1 015802]
2023-02-14 14:51:19,061,061    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 81F1 020000]
2023-02-14 14:51:19,063,063    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 81F1 020018]
2023-02-14 14:51:19,063,063    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 81F1 040000]
2023-02-14 14:51:19,065,065    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 8F81 F10B00]
2023-02-14 14:51:19,065,065    DEBUG [MainThread] logitech_receiver.base: (4) device 0x00 error on request {81F1}: 11 = unsupported parameter value
2023-02-14 14:51:19,065,065    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 81F1 030000]
2023-02-14 14:51:19,067,067    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 8F81 F10B00]
2023-02-14 14:51:19,067,067    DEBUG [MainThread] logitech_receiver.base: (4) device 0x00 error on request {81F1}: 11 = unsupported parameter value
          Firmware: 58.02.B0018
2023-02-14 14:51:19,067,067    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 8100 000000]
2023-02-14 14:51:19,069,069    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 8F81 000200]
2023-02-14 14:51:19,069,069    DEBUG [MainThread] logitech_receiver.base: (4) device 0x00 error on request {8100}: 2 = invalid address
2023-02-14 14:51:19,069,069    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 8101 000000]
2023-02-14 14:51:19,071,071    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 8101 000000]
     Features: (none)
2023-02-14 14:51:19,071,071    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 810D 000000]
2023-02-14 14:51:19,073,073    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 8F81 0D0200]
2023-02-14 14:51:19,073,073    DEBUG [MainThread] logitech_receiver.base: (4) device 0x00 error on request {810D}: 2 = invalid address
2023-02-14 14:51:19,073,073    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 00 8107 000000]
2023-02-14 14:51:19,075,075    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 00 8F81 070200]
2023-02-14 14:51:19,075,075    DEBUG [MainThread] logitech_receiver.base: (4) device 0x00 error on request {8107}: 2 = invalid address
     Battery status unavailable.

**Comment by vpelcak** [comment]
It works.

![obrazek](https://user-images.githubusercontent.com/1659215/218758076-4868e9d0-415a-4eb1-af83-60a539807595.png)

**Comment by vpelcak** [comment]
BTW what is that Wireless link?

It is normal mouse with wire.

**Comment by pfps** [comment]
Solaar was initially set up for devices that connect to a Logitech receiver through a wireless link and show both the receiver and the device.  The HID++ protocol is also set up for that.  Some devices have a dedicated receiver that doesn't show up as a separate piece of equipment but still have a (somewhat hidden) wireless connection.  Solaar can't easily tell the difference between them and devices that are connected via a wire.

But it might be possible to figure out whether there is a wireless link involved.  Please open an enhancement issue for this.

**Comment by pfps** [comment]
If profiles are enabled then it is generally not possible to set things like DPI.  The solution is to change that setting to ignore.  (Click on the lock icon until it becomes something other than a lock.)

**Comment by vpelcak** [comment]
Understood. Thank you for the explanation.
Feel free to close the issue.

**Comment by pfps** [comment]
It turns out not to be difficult to do a decent job of determining whether there is a wireless link or a battery.  The new version of PR #1991 does this.  Please give it a try and report back.

**Comment by vpelcak** [comment]
It works.
Cool.
![image](https://user-images.githubusercontent.com/1659215/219366877-6b2288a1-daa6-4e7b-a683-865e7c9bc2ca.png)

**Comment by pfps** [comment]
Excellent, I'll merge the changes in.
