### ISSUE TITLE
Logitech K780 Keyboard & Logitech MX Ergo Trackball NOT RECOGNIZED

### ISSUE THREAD

**Issue by elrengo81** [pwr-Solaar/Solaar#1992]
**Information**
I'm the owner of Logitech K780 Keyboard and Logitech MX Ergo Trackball, both devices are connected to my Laptop (Lenovo ThinkPad T14 AMD) via Bluetooth. Using Ubuntu 20.04 LTS. Solaar do not recognize any Logitech devices.

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):  **1.0.1**
- Distribution: Ubuntu 20.04 LTS
- Kernel version (ex. `uname -srmo`): `Linux 5.15.0-60-generic x86_64 GNU/Linux`
- Output of `solaar show`:

<details>
(solaar: error: Logitech receiver not found)
[</details>]

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>
* cat: /home/guido.bicocca/.config/solaar/config.yaml: No such file or directory
* cat: /home/guido.bicocca/.config/solaar/config.json: No such file or directory

</details>

- Errors or warrnings from Solaar:

```
solaar -dd
10:56:13,794     INFO [MainThread] root: language en_US (UTF-8), translations path None
10:56:13,864    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
10:56:13,874     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
10:56:13,959    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
10:56:13,959    DEBUG [AsyncUI] solaar.tasks: started
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/share/solaar/lib
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/guido.bicocca/.local/share/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/ubuntu/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: looking for icons in /var/lib/snapd/desktop/solaar/icons
10:56:13,963    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/guido.bicocca/.local/share/icons', '/home/guido.bicocca/.icons', '/usr/share/ubuntu/icons', '/usr/local/share/icons', '/usr/share/icons', '/var/lib/snapd/desktop/icons', '/usr/share/ubuntu/pixmaps', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/var/lib/snapd/desktop/pixmaps']
10:56:13,973    DEBUG [MainThread] solaar.ui.icons: detected icon sets: Mint True, gpm True, oxygen False, gnome True, elementary False
10:56:13,984     INFO [MainThread] solaar.listener: starting receiver listening threads
10:56:14,035    DEBUG [MainThread] solaar.ui: activate
10:56:39,864    DEBUG [MainThread] solaar.ui: shutdown
10:56:39,864    DEBUG [AsyncUI] solaar.tasks: stopped
```

**Describe the bug**
Solaar do not detect my Logitech devices under Bluetooth connection. To configure its.

**Additional context**

```
grep -H . /sys/class/hidraw/hidraw*/device/uevent
/sys/class/hidraw/hidraw0/device/uevent:DRIVER=jabra
/sys/class/hidraw/hidraw0/device/uevent:HID_ID=0003:00000B0E:00000422
/sys/class/hidraw/hidraw0/device/uevent:HID_NAME=Jabra SPEAK 510 USB
/sys/class/hidraw/hidraw0/device/uevent:HID_PHYS=usb-0000:07:00.4-2.2.3/input3
/sys/class/hidraw/hidraw0/device/uevent:HID_UNIQ=50C971FC6CC3022000
/sys/class/hidraw/hidraw0/device/uevent:MODALIAS=hid:b0003g0000v00000B0Ep00000422
/sys/class/hidraw/hidraw1/device/uevent:DRIVER=hid-generic
/sys/class/hidraw/hidraw1/device/uevent:HID_ID=0003:0000256C:0000FFFF
/sys/class/hidraw/hidraw1/device/uevent:HID_NAME=HUION 256C PEN STYLUS
/sys/class/hidraw/hidraw1/device/uevent:HID_PHYS=
/sys/class/hidraw/hidraw1/device/uevent:HID_UNIQ=
/sys/class/hidraw/hidraw1/device/uevent:MODALIAS=hid:b0003g0001v0000256Cp0000FFFF
/sys/class/hidraw/hidraw2/device/uevent:DRIVER=jabra
/sys/class/hidraw/hidraw2/device/uevent:HID_ID=0003:00000B0E:00000300
/sys/class/hidraw/hidraw2/device/uevent:HID_NAME=GN Netcom A/S Jabra EVOLVE 20 SE MS
/sys/class/hidraw/hidraw2/device/uevent:HID_PHYS=usb-0000:07:00.4-2.2.4/input3
/sys/class/hidraw/hidraw2/device/uevent:HID_UNIQ=A009B11014520A
/sys/class/hidraw/hidraw2/device/uevent:MODALIAS=hid:b0003g0000v00000B0Ep00000300
/sys/class/hidraw/hidraw3/device/uevent:DRIVER=hid-generic
/sys/class/hidraw/hidraw3/device/uevent:HID_ID=0005:000017EF:00006038
/sys/class/hidraw/hidraw3/device/uevent:HID_NAME=ThinkPad Bluetooth Laser Mouse
/sys/class/hidraw/hidraw3/device/uevent:HID_PHYS=8c:c6:81:40:3e:03
/sys/class/hidraw/hidraw3/device/uevent:HID_UNIQ=98:fd:b4:72:d0:0d
/sys/class/hidraw/hidraw3/device/uevent:MODALIAS=hid:b0005g0001v000017EFp00006038
/sys/class/hidraw/hidraw4/device/uevent:DRIVER=hid-generic
/sys/class/hidraw/hidraw4/device/uevent:HID_ID=0003:0000256C:0000FFFF
/sys/class/hidraw/hidraw4/device/uevent:HID_NAME=Huion Tablet
/sys/class/hidraw/hidraw4/device/uevent:HID_PHYS=
/sys/class/hidraw/hidraw4/device/uevent:HID_UNIQ=
/sys/class/hidraw/hidraw4/device/uevent:MODALIAS=hid:b0003g0001v0000256Cp0000FFFF
/sys/class/hidraw/hidraw5/device/uevent:DRIVER=hid-generic
/sys/class/hidraw/hidraw5/device/uevent:HID_ID=0003:0000256C:0000FFFF
/sys/class/hidraw/hidraw5/device/uevent:HID_NAME=Huion Tablet
/sys/class/hidraw/hidraw5/device/uevent:HID_PHYS=
/sys/class/hidraw/hidraw5/device/uevent:HID_UNIQ=
/sys/class/hidraw/hidraw5/device/uevent:MODALIAS=hid:b0003g0001v0000256Cp0000FFFF
/sys/class/hidraw/hidraw6/device/uevent:DRIVER=hid-generic
/sys/class/hidraw/hidraw6/device/uevent:HID_ID=0003:00000424:0000284C
/sys/class/hidraw/hidraw6/device/uevent:HID_NAME=Microchip Hub Feature Controller
/sys/class/hidraw/hidraw6/device/uevent:HID_PHYS=usb-0000:07:00.3-1.6/input1
/sys/class/hidraw/hidraw6/device/uevent:HID_UNIQ=
/sys/class/hidraw/hidraw6/device/uevent:MODALIAS=hid:b0003g0001v00000424p0000284C
/sys/class/hidraw/hidraw7/device/uevent:DRIVER=hid-generic
/sys/class/hidraw/hidraw7/device/uevent:HID_ID=0005:0000046D:0000B33B
/sys/class/hidraw/hidraw7/device/uevent:HID_NAME=Keyboard K780
/sys/class/hidraw/hidraw7/device/uevent:HID_PHYS=8c:c6:81:40:3e:03
/sys/class/hidraw/hidraw7/device/uevent:HID_UNIQ=e5:58:5b:7b:13:9d
/sys/class/hidraw/hidraw7/device/uevent:MODALIAS=hid:b0005g0001v0000046Dp0000B33B
/sys/class/hidraw/hidraw8/device/uevent:DRIVER=logitech-hidpp-device
/sys/class/hidraw/hidraw8/device/uevent:HID_ID=0005:0000046D:0000B01D
/sys/class/hidraw/hidraw8/device/uevent:HID_NAME=Logitech MX Ergo Multi-Device Trackball 
/sys/class/hidraw/hidraw8/device/uevent:HID_PHYS=8c:c6:81:40:3e:03
/sys/class/hidraw/hidraw8/device/uevent:HID_UNIQ=c8:6c:65:b9:f5:06
/sys/class/hidraw/hidraw8/device/uevent:MODALIAS=hid:b0005g0001v0000046Dp0000B01D
```

**Comment by pfps** [comment]
Solaar version 1.0.1 is quite old.  Update using one of the PPA's mentioned on https://github.com/pwr-Solaar/Solaar

**Comment by elrengo81** [comment]
I greatly appreciate your help. I upgrade the solar version:

$solaar --version
solaar 1.1.8

$solaar show
solaar: error: [Errno 13] Permission denied: '/dev/hidraw7'

$solaar -ddd
2023-02-15 20:08:01,558,558     INFO [MainThread] root: language en_US (UTF-8), translations path None
2023-02-15 20:08:01,705,705     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2023-02-15 20:08:01,719,719    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
2023-02-15 20:08:01,728,728     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
2023-02-15 20:08:01,817,817    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
2023-02-15 20:08:01,819,819    DEBUG [AsyncUI] solaar.tasks: started
2023-02-15 20:08:01,819,819     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2023-02-15 20:08:01,824,824    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/share/solaar/lib
2023-02-15 20:08:01,824,824    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
2023-02-15 20:08:01,824,824    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/home/guido.bicocca/.local/share/icons', '/home/guido.bicocca/.icons', '/usr/share/ubuntu/icons', '/usr/local/share/icons', '/usr/share/icons', '/var/lib/snapd/desktop/icons', '/usr/share/ubuntu/pixmaps', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/var/lib/snapd/desktop/pixmaps']
2023-02-15 20:08:01,877,877     INFO [MainThread] solaar.listener: starting receiver listening threads
2023-02-15 20:08:01,881,881  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 00000424 PID 0000284C: No module named 'hid_parser'
2023-02-15 20:08:01,883,883  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 00000B0E PID 00000422: No module named 'hid_parser'
2023-02-15 20:08:01,885,885  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 00000B0E PID 00000300: No module named 'hid_parser'
2023-02-15 20:08:01,886,886  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0005 VID 000017EF PID 00006038: No module named 'hid_parser'
2023-02-15 20:08:01,887,887  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000256C PID 0000FFFF: No module named 'hid_parser'
2023-02-15 20:08:01,888,888  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000256C PID 0000FFFF: No module named 'hid_parser'
2023-02-15 20:08:01,888,888  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000256C PID 0000FFFF: No module named 'hid_parser'
2023-02-15 20:08:01,889,889  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0005 VID 0000046D PID 0000B01D: No module named 'hid_parser'
2023-02-15 20:08:01,889,889     INFO [MainThread] hidapi.udev: Found device BID 0005 VID 0000046D PID 0000B01D HID++ None None USB None None
2023-02-15 20:08:01,889,889     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw7', bus_id=5, vendor_id='046D', product_id='B01D', interface=None, driver='logitech-hidpp-device', manufacturer=None, product=None, serial='c8:6c:65:b9:f5:06', release=None, isDevice=True, hidpp_short=None, hidpp_long=None)
2023-02-15 20:08:01,889,889    ERROR [MainThread] logitech_receiver.device: open DeviceInfo(path='/dev/hidraw7', bus_id=5, vendor_id='046D', product_id='B01D', interface=None, driver='logitech-hidpp-device', manufacturer=None, product=None, serial='c8:6c:65:b9:f5:06', release=None, isDevice=True, hidpp_short=None, hidpp_long=None)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 496, in open
    handle = _base.open_path(device_info.path)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 165, in open_path
    return _hid.open_path(path)
  File "/usr/share/solaar/lib/hidapi/udev.py", line 325, in open_path
    return _os.open(device_path, _os.O_RDWR | _os.O_SYNC)
PermissionError: [Errno 13] Permission denied: '/dev/hidraw7'
2023-02-15 20:08:01,901,901  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0005 VID 0000046D PID 0000B33B: No module named 'hid_parser'
2023-02-15 20:08:01,901,901     INFO [MainThread] hidapi.udev: Found device BID 0005 VID 0000046D PID 0000B33B HID++ None None USB None None
2023-02-15 20:08:01,902,902     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw5', bus_id=5, vendor_id='046D', product_id='B33B', interface=None, driver='hid-generic', manufacturer=None, product=None, serial='e5:58:5b:7b:13:9d', release=None, isDevice=True, hidpp_short=None, hidpp_long=None)
2023-02-15 20:08:01,902,902    ERROR [MainThread] logitech_receiver.device: open DeviceInfo(path='/dev/hidraw5', bus_id=5, vendor_id='046D', product_id='B33B', interface=None, driver='hid-generic', manufacturer=None, product=None, serial='e5:58:5b:7b:13:9d', release=None, isDevice=True, hidpp_short=None, hidpp_long=None)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 496, in open
    handle = _base.open_path(device_info.path)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 165, in open_path
    return _hid.open_path(path)
  File "/usr/share/solaar/lib/hidapi/udev.py", line 325, in open_path
    return _os.open(device_path, _os.O_RDWR | _os.O_SYNC)
PermissionError: [Errno 13] Permission denied: '/dev/hidraw5'
2023-02-15 20:08:01,912,912    DEBUG [MainThread] solaar.ui: activate
2023-02-15 20:08:01,921,921    ERROR [MainThread] solaar.ui: error: permissions /dev/hidraw7
2023-02-15 20:08:01,953,953    ERROR [MainThread] solaar.ui: error: permissions /dev/hidraw5
2023-02-15 20:08:11,965,965    DEBUG [MainThread] solaar.ui: shutdown
2023-02-15 20:08:11,965,965    DEBUG [AsyncUI] solaar.tasks: stopped
2023-02-15 20:08:11,966,966     INFO [MainThread] solaar.ui.notify: stopping desktop notifications

![Solaar](https://user-images.githubusercontent.com/37456597/219222041-e2555692-9265-44c5-873c-00a3ce1c6cd6.png)

**Comment by elrengo81** [comment]
More information:

$ls -l /dev/hidraw*
crw------- 1 root root 509, 0 feb 15 09:53 /dev/hidraw0
crw------- 1 root root 509, 1 feb 15 09:53 /dev/hidraw1
crw------- 1 root root 509, 2 feb 15 18:48 /dev/hidraw2
crw------- 1 root root 509, 3 feb 15 18:48 /dev/hidraw3
crw------- 1 root root 509, 4 feb 15 09:54 /dev/hidraw4
crw------- 1 root root 509, 5 feb 15 18:47 /dev/hidraw5
crw------- 1 root root 509, 6 feb 15 09:54 /dev/hidraw6
crw------- 1 root root 509, 7 feb 15 18:48 /dev/hidraw7
crw------- 1 root root 509, 8 feb 15 19:46 /dev/hidraw8

=============================================================
$pwd
/usr/lib/udev/rules.d
[/usr/lib/udev/rules.d]
$cat 42-logitech-unify-permissions.rules 
# This rule was added by Solaar.
#
# Allows non-root users to have raw access to Logitech devices.
# Allowing users to write to the device is potentially dangerous
# because they could perform firmware updates.

ACTION != "add", GOTO="solaar_end"
SUBSYSTEM != "hidraw", GOTO="solaar_end"

# USB-connected Logitech receivers and devices
ATTRS{idVendor}=="046d", GOTO="solaar_apply"

# Lenovo nano receiver
ATTRS{idVendor}=="17ef", ATTRS{idProduct}=="6042", GOTO="solaar_apply"

# Bluetooth-connected Logitech devices
KERNELS == "0005:046D:*", GOTO="solaar_apply"

GOTO="solaar_end"

LABEL="solaar_apply"

# Allow any seated user to access the receiver.
# uaccess: modern ACL-enabled udev
# udev-acl: for Ubuntu 12.10 and older
TAG+="uaccess", TAG+="udev-acl"

# Grant members of the "plugdev" group access to receiver (useful for SSH users)
#MODE="0660", GROUP="plugdev"

LABEL="solaar_end"
# vim: ft=udevrules
==================================================================

$udevadm info /dev/hidraw* 
P: /devices/pci0000:00/0000:00:08.1/0000:07:00.4/usb6/6-2/6-2.2/6-2.2.3/6-2.2.3:1.3/0003:0B0E:0422.0001/hidraw/hidraw0
N: hidraw0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:07:00.4/usb6/6-2/6-2.2/6-2.2.3/6-2.2.3:1.3/0003:0B0E:0422.0001/hidraw/hidraw0
E: DEVNAME=/dev/hidraw0
E: MAJOR=509
E: MINOR=0
E: SUBSYSTEM=hidraw

P: /devices/pci0000:00/0000:00:08.1/0000:07:00.4/usb6/6-2/6-2.2/6-2.2.4/6-2.2.4:1.3/0003:0B0E:0300.0002/hidraw/hidraw1
N: hidraw1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:07:00.4/usb6/6-2/6-2.2/6-2.2.4/6-2.2.4:1.3/0003:0B0E:0300.0002/hidraw/hidraw1
E: DEVNAME=/dev/hidraw1
E: MAJOR=509
E: MINOR=1
E: SUBSYSTEM=hidraw

P: /devices/virtual/misc/uhid/0003:256C:FFFF.0034/hidraw/hidraw2
N: hidraw2
L: 0
E: DEVPATH=/devices/virtual/misc/uhid/0003:256C:FFFF.0034/hidraw/hidraw2
E: DEVNAME=/dev/hidraw2
E: MAJOR=509
E: MINOR=2
E: SUBSYSTEM=hidraw

P: /devices/pci0000:00/0000:00:08.1/0000:07:00.3/usb4/4-1/4-1.6/4-1.6:1.1/0003:0424:284C.0032/hidraw/hidraw3
N: hidraw3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:07:00.3/usb4/4-1/4-1.6/4-1.6:1.1/0003:0424:284C.0032/hidraw/hidraw3
E: DEVNAME=/dev/hidraw3
E: MAJOR=509
E: MINOR=3
E: SUBSYSTEM=hidraw

P: /devices/virtual/misc/uhid/0003:256C:FFFF.0007/hidraw/hidraw4
N: hidraw4
L: 0
E: DEVPATH=/devices/virtual/misc/uhid/0003:256C:FFFF.0007/hidraw/hidraw4
E: DEVNAME=/dev/hidraw4
E: MAJOR=509
E: MINOR=4
E: SUBSYSTEM=hidraw

P: /devices/virtual/misc/uhid/0005:046D:B33B.002D/hidraw/hidraw5
N: hidraw5
L: 0
E: DEVPATH=/devices/virtual/misc/uhid/0005:046D:B33B.002D/hidraw/hidraw5
E: DEVNAME=/dev/hidraw5
E: MAJOR=509
E: MINOR=5
E: SUBSYSTEM=hidraw

P: /devices/virtual/misc/uhid/0003:256C:FFFF.0008/hidraw/hidraw6
N: hidraw6
L: 0
E: DEVPATH=/devices/virtual/misc/uhid/0003:256C:FFFF.0008/hidraw/hidraw6
E: DEVNAME=/dev/hidraw6
E: MAJOR=509
E: MINOR=6
E: SUBSYSTEM=hidraw

P: /devices/virtual/misc/uhid/0005:046D:B01D.0035/hidraw/hidraw7
N: hidraw7
L: 0
E: DEVPATH=/devices/virtual/misc/uhid/0005:046D:B01D.0035/hidraw/hidraw7
E: DEVNAME=/dev/hidraw7
E: MAJOR=509
E: MINOR=7
E: SUBSYSTEM=hidraw

P: /devices/pci0000:00/0000:00:08.1/0000:07:00.4/usb6/6-4/6-4:1.0/bluetooth/hci0/hci0:256/0005:17EF:6038.0037/hidraw/hidraw8
N: hidraw8
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:07:00.4/usb6/6-4/6-4:1.0/bluetooth/hci0/hci0:256/0005:17EF:6038.0037/hidraw/hidraw8
E: DEVNAME=/dev/hidraw8
E: MAJOR=509
E: MINOR=8
E: SUBSYSTEM=hidraw


========================================================================
$getfacl /dev/hidraw*
getfacl: Removing leading '/' from absolute path names
# file: dev/hidraw0
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw1
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw2
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw3
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw4
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw5
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw6
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw7
# owner: root
# group: root
user::rw-
group::---
other::---

# file: dev/hidraw8
# owner: root
# group: root
user::rw-
group::---
other::---

**Comment by pfps** [comment]
Somehow the udev rule has not run.   The rule will only run when new devices show up so you could try to turn your devices off and on again.  If that doesn't work then it may be that the rule has the wrong permissions.  It has to be owned by root and probably only writable by root.  Look at the other files in the directory.  Also check that there is no other file of the same name in other places that udev gets its rules from (like /etc/udev/rules.d).

**Comment by elrengo81** [comment]
Today when I power on my laptop Solaar start to work, like a magic:

![image](https://user-images.githubusercontent.com/37456597/219657475-1a263ea2-a014-481b-9351-5c64d3643eda.png)

**Comment by elrengo81** [comment]
I'm searching for information, but I can't find it. What does “Button Diversion” mean?

**Comment by pfps** [comment]
The udev rule that sets up permissions only runs when new devices are detected, i.e., when they are plugged in or when the system starts up or comes back from sleep.   I expect that this is the first time this has happened since the rule was installed.

**Comment by pfps** [comment]
Look for "diversion" in https://pwr-solaar.github.io/Solaar/capabilities

**Comment by elrengo81** [comment]
Thanks!
