### ISSUE TITLE
Reprogrammable buttons on mouse

### ISSUE THREAD

**Issue by kada49** [pwr-Solaar/Solaar#2018]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.1.8
- Distribution: Fedora 37
- Kernel version (ex. `uname -srmo`): 6.1.18-200.fc37.x86_64
- Output of `solaar show` for the target device (if applicable):

<details>

```
solaar version 1.1.8

USB and Bluetooth Devices

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw1
     USB id       : 046d:B023
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B02340820000
     Unit ID:       4F621272
        Bootloader: BOT 95.00.B0013
          Firmware: MPM 19.01.B0015
             Other: 
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V3     
            Firmware: Bootloader BOT 95.00.B0013 0000D8279515
            Firmware: Firmware MPM 19.01.B0015 B0236A9CA89D
            Firmware: Other   
            Unit ID: 4F621272  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3
         8: BATTERY STATUS         {1000} V1     
            Battery: 100%, discharging, next level 50%.
         9: REPROG CONTROLS V4     {1B04} V4     
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/solaar/cli/__init__.py", line 209, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.11/site-packages/solaar/cli/show.py", line 305, in run
    _print_device(d, num=dev_num)
  File "/usr/lib/python3.11/site-packages/solaar/cli/show.py", line 232, in _print_device
    v = setting.val_to_string(setting._device.persister.get(setting.name))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/settings.py", line 239, in val_to_string
    return self._validator.to_string(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/settings.py", line 1102, in to_string
    return '{' + ', '.join([element_to_string(k, value[k]) for k in sorted(value)]) + '}'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/settings.py", line 1102, in <listcomp>
    return '{' + ', '.join([element_to_string(k, value[k]) for k in sorted(value)]) + '}'
                                                 ~~~~~^^^
TypeError: string indices must be integers, not 'str'

```
</details>

**Is your feature request related to a problem? Please describe.**
Can you reprogram mouse buttons to custom keyboard keys like for example "Forward Button" to press 3 (for games mainly)? If it exists already pls tell me how to do it

**Comment by pfps** [comment]
I notice that `solaar show` produced an error.  I'm not seeing this error with my MX Master 3.  If this persists you might want to file a bug report.

**Comment by pfps** [comment]
There are several ways to change the output for a key or button.  One that is available on the MX Master 3 is using the Key/Button Actions setting in Solaar.  Unfortunately, this only allows changes to a few other outputs, and 3 is not a possible one (on any Logitech device I've seen).  One that is not available on the MX Master 3 is persistent mapping, but this is not available at all on the MX Master 3.  This leaves Solaar rules, which can do what you want.  You need to divert the key and write a rule with a Key condition that checks whether the button was pressed (or released) and, if so, simulates a KeyPress of 3.

Expect noticeable lag sometimes, however, as there is a lot of processing going on, so rules are not recommended for this kind of key or button reprogramming.

**Comment by kada49** [comment]
> I notice that `solaar show` produced an error. I'm not seeing this error with my MX Master 3. If this persists you might want to file a bug report.

I removed the config.yaml file and resent the solaar show command with no errors:


```
solaar version 1.1.8

USB and Bluetooth Devices

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw2
     USB id       : 046d:B023
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B02340820000
     Unit ID:       4F621272
        Bootloader: BOT 95.00.B0013
          Firmware: MPM 19.01.B0015
             Other: 
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V3     
            Firmware: Bootloader BOT 95.00.B0013 0000D8279515
            Firmware: Firmware MPM 19.01.B0015 B0236A9CA89D
            Firmware: Other   
            Unit ID: 4F621272  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3
         8: BATTERY STATUS         {1000} V1     
            Battery: 100%, discharging, next level 50%.
         9: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
        10: CHANGE HOST            {1814} V1     
            Change Host        : 1:acer-swift-1
        11: XY STATS               {2250} V1     
        12: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        13: SMART SHIFT            {2110} V0     
            Scroll Wheel Ratcheted (saved): Ratcheted
            Scroll Wheel Ratcheted        : Ratcheted
            Scroll Wheel Ratchet Speed (saved): 10
            Scroll Wheel Ratchet Speed        : 10
        14: HIRES WHEEL            {2121} V1     
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        15: THUMB WHEEL            {2150} V0     
            Thumb Wheel Direction (saved): False
            Thumb Wheel Direction        : False
            Thumb Wheel Diversion (saved): False
            Thumb Wheel Diversion        : False
        16: WHEEL STATS            {2251} V0     
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: DEVICE RESET           {1802} V0    internal, hidden 
        19: unknown:1803           {1803} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V6    internal, hidden 
        21: unknown:1813           {1813} V0    internal, hidden 
        22: OOBSTATE               {1805} V0    internal, hidden 
        23: unknown:1830           {1830} V0    internal, hidden 
        24: unknown:18A1           {18A1} V0    internal, hidden 
        25: unknown:1E00           {1E00} V0    hidden 
        26: unknown:1EB0           {1EB0} V0    internal, hidden 
        27: unknown:1861           {1861} V0    internal, hidden 
        28: unknown:9300           {9300} V0    internal, hidden 
        29: unknown:9001           {9001} V0    internal, hidden 
        30: unknown:9205           {9205} V0    internal, hidden 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.

```

I will try to see if I am able to do the rules, ty for the response!

**Comment by kada49** [comment]
> 

Is this what the Logitech Options program on windows probably does?

**Comment by Flashwalker** [comment]
[input-remapper](https://github.com/sezanzeb/input-remapper) also able to remap these "Forward Button" and "Back Button" but only if you connected via bluetooth
