### ISSUE TITLE
kde/trayicon: on hover tooltip do not show any information about devices

### ISSUE THREAD

**Issue by pohmelie** [pwr-Solaar/Solaar#2021]
**Information**
- Solaar version (current master): https://github.com/pwr-Solaar/Solaar/commit/63ce2e4485df7317b542dc6e5c67a516305321fd
- Distribution: kubuntu 22.04
- Kernel version (ex. `uname -srmo`): `Linux 5.15.0-67-generic x86_64 GNU/Linux`
- Output of `solaar show`: 
<details><summary>Details</summary>
<p>

solaar version 76e93b07

USB and Bluetooth Devices

  1: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
     Device path  : /dev/hidraw2
     USB id       : 046d:C343
     Codename     : G915 TKL
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: 
     Model ID:      B35F408EC343
     Unit ID:       AB1DEA11
        Bootloader: BL1 12.00.B0017
             Other: 
          Firmware: MPK 14.00.B0017
             Other: 
             Other: 
     Supports 37 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V3     
            Firmware: Bootloader BL1 12.00.B0017 00008B79E978
            Firmware: Other   
            Firmware: Firmware MPK 14.00.B0017 C3438B79E978
            Firmware: Other   
            Firmware: Other   
            Unit ID: AB1DEA11  Model ID: B35F408EC343  Transport IDs: {'btleid': 'B35F', 'wpid': '408E', 'usbid': 'C343'}
         3: DEVICE NAME            {0005} V0     
            Name: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: BATTERY VOLTAGE        {1001} V3     
            Battery: 70% 3950mV , recharging.
         7: CHANGE HOST            {1814} V1     
            Change Host        : 1:notebook
         8: HOSTS INFO             {1815} V1     
            Host 0 (paired): notebook
            Host 1 (unpaired): 
         9: RGB EFFECTS            {8071} V0     
        10: PER KEY LIGHTING V2    {8081} V2     
        11: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Diversion (saved): {Host Switch Channel 1:Regular, Host Switch Channel 2:Regular}
            Key/Button Diversion        : {Host Switch Channel 1:Regular, Host Switch Channel 2:Regular}
        12: REPORT HID USAGE       {1BC0} V1     
        13: ENCRYPTION             {4100} V0     
        14: KEYBOARD DISABLE BY USAGE {4522} V0     
        15: KEYBOARD LAYOUT 2      {4540} V0     
        16: GKEY                   {8010} V0     
            Divert G Keys (saved): False
            Divert G Keys        : False
        17: MKEYS                  {8020} V0     
            M-Key LEDs (saved): {M1:False, M2:False, M3:False}
            M-Key LEDs        : {M1:False, M2:False, M3:False}
        18: MR                     {8030} V0     
            MR-Key LED (saved): False
            MR-Key LED        : False
        19: BRIGHTNESS CONTROL     {8040} V0     
        20: ONBOARD PROFILES       {8100} V0     
            Device Mode: On-Board
            Onboard Profiles (saved): Enable
            Onboard Profiles        : Enable
        21: REPORT RATE            {8060} V0     
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        22: DFUCONTROL SIGNED      {00C2} V0     
        23: DFU                    {00D0} V1     
        24: DEVICE RESET           {1802} V0    internal, hidden 
        25: unknown:1803           {1803} V0    internal, hidden 
        26: CONFIG DEVICE PROPS    {1806} V6    internal, hidden 
        27: unknown:1813           {1813} V0    internal, hidden 
        28: OOBSTATE               {1805} V0    internal, hidden 
        29: unknown:1830           {1830} V0    internal, hidden 
        30: unknown:1890           {1890} V5    internal, hidden 
        31: unknown:1891           {1891} V5    internal, hidden 
        32: unknown:18A1           {18A1} V0    internal, hidden 
        33: unknown:1E00           {1E00} V0    hidden 
        34: unknown:1EB0           {1EB0} V0    internal, hidden 
        35: unknown:1861           {1861} V0    internal, hidden 
        36: unknown:18B0           {18B0} V0    internal, hidden 
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 70% 3950mV , recharging.
Lightspeed Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:C539
  Serial       : 96379C04
    Firmware   : 39.06.B0040
    Bootloader : 02.09
    Other      : AA.BE
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G Pro Wireless Gaming Mouse
     Device path  : /dev/hidraw8
     WPID         : 4079
     Codename     : G Pro 
     Kind         : mouse
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: CA994811
     Model ID:      4079C0880000
     Unit ID:       CA994811
        Bootloader: BOT 74.02.B0026
          Firmware: MPM 15.02.B0026
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BOT 74.02.B0026 AADF85EE714A
            Firmware: Firmware MPM 15.02.B0026 407985EE714A
            Firmware: Other   
            Unit ID: CA994811  Model ID: 4079C0880000  Transport IDs: {'wpid': '4079', 'usbid': 'C088'}
         3: DEVICE NAME            {0005} V0     
            Name: G Pro Wireless Gaming Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: BATTERY VOLTAGE        {1001} V2     
            Battery: 90% 4167mV , discharging.
         7: COLOR LED EFFECTS      {8070} V4     
         8: LED CONTROL            {1300} V0     
         9: ONBOARD PROFILES       {8100} V0     
            Device Mode: On-Board
            Onboard Profiles (saved): Enable
            Onboard Profiles        : Enable
        10: MOUSE BUTTON SPY       {8110} V0     
        11: REPORT RATE            {8060} V0     
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        12: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 800
            Sensitivity (DPI)        : 800
        13: DEVICE RESET           {1802} V0    internal, hidden 
        14: unknown:1803           {1803} V0    internal, hidden 
        15: OOBSTATE               {1805} V0    internal, hidden 
        16: CONFIG DEVICE PROPS    {1806} V4    internal, hidden 
        17: unknown:1811           {1811} V0    internal, hidden 
        18: unknown:1830           {1830} V0    internal, hidden 
        19: unknown:1890           {1890} V2    internal, hidden 
        20: unknown:1891           {1891} V2    internal, hidden 
        21: unknown:18A1           {18A1} V0    internal, hidden 
        22: unknown:1801           {1801} V0    internal, hidden 
        23: unknown:18B1           {18B1} V0    internal, hidden 
        24: unknown:1DF3           {1DF3} V0    internal, hidden 
        25: unknown:1E00           {1E00} V0    hidden 
        26: unknown:1EB0           {1EB0} V0    internal, hidden 
        27: unknown:1863           {1863} V0    internal, hidden 
        28: unknown:1E22           {1E22} V0    internal, hidden 
     Battery: 90% 4167mV , discharging.

</p>
</details> 

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar:
<details><summary>Details</summary>
<p>

2023-03-21 01:56:25,179,179     INFO [MainThread] root: language en_US (UTF-8), translations path None
2023-03-21 01:56:25,327,327     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2023-03-21 01:56:25,344,344  WARNING [MainThread] solaar.upower: failed to register suspend/resume callbacks
2023-03-21 01:56:25,367,367     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2023-03-21 01:56:25,436,436     INFO [MainThread] solaar.listener: starting receiver listening threads
2023-03-21 01:56:25,594,594     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C343 HID++ True True USB 2 2
2023-03-21 01:56:25,595,595     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw2', bus_id=3, vendor_id='046D', product_id='C343', interface=2, driver='hid-generic', manufacturer=None, product=None, serial='AB1DEA11', release=None, isDevice=True, hidpp_short=True, hidpp_long=True)
2023-03-21 01:56:25,652,652     INFO [ReceiverListener:hidraw2] logitech_receiver.listener: started with <Device(255,C343,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,)> (12)
2023-03-21 01:56:25,653,653     INFO [ReceiverListener:hidraw2] solaar.listener: <Device(255,C343,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,)>: notifications listener has started (12)
2023-03-21 01:56:25,653,653     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(255,C343,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,)>: paired offline, {'NOTIFICATION FLAGS': False} (0) 
2023-03-21 01:56:25,653,653     INFO [ReceiverListener:hidraw2] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw2)>
2023-03-21 01:56:25,654,654  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000056A PID 00005193: Unsupported global tag: 0b101
2023-03-21 01:56:25,655,655  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000056A PID 00005193: Unsupported global tag: 0b1010
2023-03-21 01:56:25,673,673     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C539 HID++ True True USB 2 2
2023-03-21 01:56:25,673,673     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw5', bus_id=3, vendor_id='046D', product_id='C539', interface=2, driver='logitech-djreceiver', manufacturer=None, product=None, serial='', release=None, isDevice=None, hidpp_short=True, hidpp_long=True)
2023-03-21 01:56:25,674,674     INFO [MainThread] logitech_receiver.base: New lock 13
2023-03-21 01:56:25,675,675     INFO [ReceiverListener:hidraw5] logitech_receiver.listener: started with <LightspeedReceiver(/dev/hidraw5,13)> (13)
2023-03-21 01:56:25,675,675     INFO [ReceiverListener:hidraw5] solaar.listener: <LightspeedReceiver(/dev/hidraw5,13)>: notifications listener has started (13)
2023-03-21 01:56:25,676,676     INFO [ReceiverListener:hidraw5] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw5)>
2023-03-21 01:56:25,680,680     INFO [ReceiverListener:hidraw5] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw5,13)>: receiver notifications enabled => ('wireless', 'software present')
2023-03-21 01:56:25,682,682     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,13)>: present, No paired devices. (0) 
2023-03-21 01:56:25,682,682     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(255,C343,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,)>: paired online, {'NOTIFICATION FLAGS': False, 'BATTERY LEVEL': 70, 'BATTERY STATUS': NamedInt(1, 'recharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3955, 'BATTERY CHARGING': True, 'ERROR': None} (0) 
2023-03-21 01:56:25,690,690     INFO [ReceiverListener:hidraw5] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw5,13)>: found new device 1 (4079)
2023-03-21 01:56:25,690,690     INFO [ReceiverListener:hidraw5] logitech_receiver.base: New lock 16
2023-03-21 01:56:25,690,690     INFO [ReceiverListener:hidraw5] solaar.listener: connection Notification(10,1,41,0C,327940) for <Device(1,4079,G Pro Wireless Gaming Mouse,CA994811)> (mouse)
2023-03-21 01:56:25,726,726     INFO [ReceiverListener:hidraw2] logitech_receiver.status: <Device(255,C343,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,)> pushing device settings [<Setting([feature:choice] G915 TKL:onboard_profiles=1)>, <Setting([feature:choice] G915 TKL:report_rate=1)>, <Setting([feature:map choice] G915 TKL:divert-keys={209: 0, 210: 0})>, <Setting([feature:toggle] G915 TKL:divert-gkeys=False)>, <Setting([feature:multiple toggle] G915 TKL:m-key-leds={1: False, 2: False, 4: False})>, <Setting([feature:toggle] G915 TKL:mr-key-led=False)>, <Setting([feature:choice] G915 TKL:change-host=1:notebook)>]
2023-03-21 01:56:25,759,759     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,13)>: present, 1 paired device. (0) 
2023-03-21 01:56:25,766,766    ERROR [ReceiverListener:hidraw2] logitech_receiver.base: (12) device 255 error on feature request {152E}: 2 = invalid argument
2023-03-21 01:56:25,766,766  WARNING [ReceiverListener:hidraw2] logitech_receiver.settings: report_rate: error applying value 1 so ignore it (<Device(255,C343,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,)>)
2023-03-21 01:56:25,779,779     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(255,C343,G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard,)>: paired online, {'NOTIFICATION FLAGS': False, 'BATTERY LEVEL': 70, 'BATTERY STATUS': NamedInt(1, 'recharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3955, 'BATTERY CHARGING': True, 'ERROR': None} (0) initialization
2023-03-21 01:56:25,779,779    ERROR [ReceiverListener:hidraw2] logitech_receiver.listener: processing Notification(11,255,10,00,00000000000000000000000000000000)
Traceback (most recent call last):
  File "/home/poh/tmp/Solaar/lib/logitech_receiver/listener.py", line 176, in run
    self._notifications_callback(n)
  File "/home/poh/tmp/Solaar/lib/solaar/listener.py", line 196, in _notifications_handler
    _notifications.process(self.receiver, n)
  File "/home/poh/tmp/Solaar/lib/logitech_receiver/notifications.py", line 61, in process
    return _process_device_notification(device, status, notification)
  File "/home/poh/tmp/Solaar/lib/logitech_receiver/notifications.py", line 201, in _process_device_notification
    return _process_feature_notification(device, status, n, feature)
  File "/home/poh/tmp/Solaar/lib/logitech_receiver/notifications.py", line 448, in _process_feature_notification
    _diversion.process_notification(device, status, n, feature)
  File "/home/poh/tmp/Solaar/lib/logitech_receiver/diversion.py", line 1374, in process_notification
    new_g_keys_down = _unpack('!4I', notification.data[:4])[0]
struct.error: unpack requires a buffer of 16 bytes
2023-03-21 01:56:25,797,797     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <Device(1,4079,G Pro Wireless Gaming Mouse,CA994811)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 90, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 4165, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2023-03-21 01:56:25,849,849     INFO [ReceiverListener:hidraw5] logitech_receiver.status: <Device(1,4079,G Pro Wireless Gaming Mouse,CA994811)> pushing device settings [<Setting([feature:choice] G Pro :onboard_profiles=None)>, <Setting([feature:choice] G Pro :report_rate=None)>, <Setting([feature:choice] G Pro :dpi=None)>]
2023-03-21 01:56:25,877,877    ERROR [ReceiverListener:hidraw5] logitech_receiver.base: (16) device 1 error on feature request {0B2B}: 2 = invalid argument
2023-03-21 01:56:25,877,877  WARNING [ReceiverListener:hidraw5] logitech_receiver.settings: report_rate: error applying value 1 so ignore it (<Device(1,4079,G Pro Wireless Gaming Mouse,CA994811)>)
2023-03-21 01:56:25,887,887     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <Device(1,4079,G Pro Wireless Gaming Mouse,CA994811)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 90, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 4165, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2023-03-21 01:56:25,888,888     INFO [ReceiverListener:hidraw5] solaar.listener: connection Notification(10,1,41,0C,327940) for <Device(1,4079,G Pro Wireless Gaming Mouse,CA994811)> (mouse)
2023-03-21 01:56:25,888,888     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,13)>: present, 1 paired device. (0) 
2023-03-21 01:56:25,891,891     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <Device(1,4079,G Pro Wireless Gaming Mouse,CA994811)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 90, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 4165, 'BATTERY CHARGING': False, 'ERROR': None} (0)

</p>
</details> 

**Describe the bug**
KDE tooltip shows `solaar` text all the time.

**To Reproduce**
1. Add ppa repo
2. Install solaar
3. Start solaar
4. Hold mouse on tray icon

**Additional context**
I did some debug, and found that this three lines:
``` python
tooltip_lines = _generate_tooltip_lines()
tooltip = '\n'.join(tooltip_lines).rstrip('\n')
_icon.set_title(tooltip)
```
Inserted [at start of the function](https://github.com/pwr-Solaar/Solaar/blob/master/lib/solaar/ui/tray.py#L205) will do the job. With exception, that all markup is passed as symbols and you see this `<b></b>` in tooltip as a text. This use [`set_title`](https://lazka.github.io/pgi-docs/AyatanaAppIndicator3-0.1/classes/Indicator.html#AyatanaAppIndicator3.Indicator.set_title) method

I don't exactly now why there are two sets of functions, but this version of [`_update_tray_icon`](https://github.com/pwr-Solaar/Solaar/blob/master/lib/solaar/ui/tray.py#L256) have different behavior than [this one](https://github.com/pwr-Solaar/Solaar/blob/master/lib/solaar/ui/tray.py#L204).

**Comment by pohmelie** [comment]
> What is shown on your system?

This information is on first post: `KDE tooltip shows «solaar» text all the time.`

> However, I don't think that this would be merged into Solaar unless as it looks as if the title is supposed to be for the application itself, not the current icon that is being used.

I'm not familiar with `gobject` and this project codebase, so maybe left this issue open. At least until better days for gnome to kde integration.

**Comment by pfps** [comment]
So it appears that the behaviour of the system tray server you have is to not show the description information when hovering over the tray icon.  Further, using the title to show varying information appears to have problems.  So no bug in Solaar, just a difference in system tray implementations.  If you or someone else finds a good way to show device information then this issue can be reopened.

**Comment by pfps** [comment]
Yes, but the issue is not a bug in Solaar nor an enhancement possibility, as there does not appear to be an accepted way of having variable information display in this application indicator implementation.  So Solaar is doing the best that should be done (and is actually probably already using undocumented behaviour for the application indicator implementation that actually displays icon descriptions when hovering).  Using title for this purpose has the distinct possibility of breaking something.

After all, it's not as if the information in the icon description is hard to find.   Just right-click to see it and more.   So perhaps the best solution is just to not use the icon description for this purpose and not show device information when hovering.

**Comment by pohmelie** [comment]
Or made runtime introspection to find out actual DE. Hovering tooltip is massively used in all user interfaces, so no reason to cut off this feature. I understand the complexity, but there are no reasons to close this issue, maybe add some label.

**Comment by pfps** [comment]
Yes, hovering to provide changeable information is useful, but apparently not an official part of application indicator  https://bugs.launchpad.net/indicator-application/+bug/527458.

**Comment by pfps** [comment]
Closing due to no response from submitter.
