### ISSUE TITLE
Logitech M185 does not get recognized

### ISSUE THREAD

**Issue by Ruskie-it** [pwr-Solaar/Solaar#2180]
Hello, this is somewhat a replica of closed issue https://github.com/pwr-Solaar/Solaar/issues/2052, but it got closed because the request evolved to a (kinda weird) request.

Anyway, my brand new M185 logitech mouse is not working.
Actually the mouse does just fine as far as left and right clicking is concerned. However it stops during play etc, and this not good. Coul you please help?

```

Thanks
Marco

**Comment by pfps** [comment]
Please provide the information requested for bug reports.  Also provide more information on what you think should happen and what you experience that is different.

**Comment by Ruskie-it** [comment]
You're right, I'm sorry: to start from your last question, since M185 is listed among the compatible devices, I would expect to see it among the detected devices. Instead of that, I only see my MX Keys keyboard (Windows version):

![solaar](https://github.com/pwr-Solaar/Solaar/assets/151529988/94bba210-2d81-408b-8e5f-3719bb9a1a71)

I couldn't test anything else because as I said it does not even get detected. My hw info are the same that are in the post I linked but of course I need to add context:

- Solaar version: solaar 1.1.10
- Distribution: Downloaded from Fedora Linux 39 repositories. OS: Fedora Linux 39 with KDE Plasma on X11
- Kernel version (ex. `uname -srmo`): `Linux 6.5.11-300.fc39.x86_64 x86_64 GNU/Linux`
- Output of `solaar show`:
<details>

```
user@localhost-live:~$ solaar show
solaar version 1.1.10

Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C542
  Serial       : None
  Has 0 paired device(s) out of a maximum of 1.

USB and Bluetooth Devices

  1: MX Keys Keyboard
     Device path  : /dev/hidraw2
     USB id       : 046d:B35B
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B35B408A0000
     Unit ID:       DDF2964C
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.01.B0013
             Other: 
     Supports 30 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BL1 08.00.B0011 00008169E8BB
            Firmware: Firmware MPK 12.01.B0013 B35BFE037737
            Firmware: Other   
            Unit ID: DDF2964C  Model ID: B35B408A0000  Transport IDs: {'btleid': 'B35B', 'wpid': '408A'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Keys Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Keys
         7: BATTERY STATUS         {1000} V1     
            Battery: 50%, discharging, next level 20%.
         8: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Diversion (saved): {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Mission Control/Task View:Regular, Dashboard Launchpad/Action Center:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular}
            Key/Button Diversion        : {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Mission Control/Task View:Regular, Dashboard Launchpad/Action Center:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular}
         9: CHANGE HOST            {1814} V1     
            Cambia Host        : 2:localhost-live
        10: HOSTS INFO             {1815} V1     
            Host 0 (paired): -PC
            Host 1 (paired): localhost-live
            Host 2 (paired): CPX-HWLSQOE02BI
        11: BACKLIGHT2             {1982} V1     
            Retroilluminazione (saved): True
            Retroilluminazione        : True
        12: K375S FN INVERSION     {40A3} V0     
            Inverti funzioni Fx (saved): False
            Inverti funzioni Fx        : False
        13: ENCRYPTION             {4100} V0     
        14: LOCK KEY STATE         {4220} V0     
        15: KEYBOARD DISABLE KEYS  {4521} V0     
            Disabilita i pulsanti (saved): {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
            Disabilita i pulsanti        : {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
        16: MULTIPLATFORM          {4531} V1     
            Specifica il sistema operativo (saved): Windows
            Specifica il sistema operativo        : Windows
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: DEVICE RESET           {1802} V0    internal, hidden 
        19: unknown:1803           {1803} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V5    internal, hidden 
        21: unknown:1813           {1813} V0    internal, hidden 
        22: OOBSTATE               {1805} V0    internal, hidden 
        23: unknown:1830           {1830} V0    internal, hidden 
        24: unknown:18A1           {18A1} V0    internal, hidden 
        25: unknown:1E00           {1E00} V0    hidden 
        26: unknown:1EB0           {1EB0} V0    internal, hidden 
        27: unknown:1861           {1861} V0    internal, hidden 
        28: unknown:1A20           {1A20} V0    internal, hidden 
        29: unknown:18B0           {18B0} V0    internal, hidden 
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Dashboard Launchpad/Action Center, default: Dashboard Launchpad/Action Center => Dashboard Launchpad/Action Center
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: FN Key                    , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 50%, discharging, next level 20%.
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
user@localhost-live:~$ cat ~/.config/solaar/config.yaml
- 1.1.10
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, dpi, speed-change, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B35B408A0000
  _sensitive: {disable-keyboard-keys: true, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _unitId: DDF2964C
  backlight: true
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 225: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0,
    233: 0, 234: 0, 235: 0, 236: 0}
  fn-swap: false
  multiplatform: 0
```
</details>


- Errors or warrnings from Solaar:

No log under ~/.tmp
"solaar -dd" reports the following:
<details>
```
root@localhost-live:~# ps -ef | grep solaar
root        4097    4070  0 01:51 pts/2    00:00:00 grep --color=auto solaar
root@localhost-live:~# solaar -dd
2023-11-22 01:52:23,900,900     INFO [MainThread] root: version 1.1.10, language it_IT (UTF-8)
2023-11-22 01:52:24,056,056     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2023-11-22 01:52:24,076,076     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
2023-11-22 01:52:24,187,187     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2023-11-22 01:52:24,225,225     INFO [MainThread] solaar.listener: starting receiver listening threads
2023-11-22 01:52:24,366,366  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C542: Expecting 7 usages but got 1
2023-11-22 01:52:24,366,366     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C542 HID++ None None USB 0 None
2023-11-22 01:52:24,367,367     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw0', bus_id=3, vendor_id='046D', product_id='C542', interface=0, driver='hid-generic', manufacturer=None, product=None, serial='', release=None, isDevice=False, hidpp_short=None, hidpp_long=None)
2023-11-22 01:52:24,367,367     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw0
2023-11-22 01:52:24,367,367  WARNING [MainThread] logitech_receiver.receiver: Unknown receiver type: C542
2023-11-22 01:52:24,367,367     INFO [MainThread] logitech_receiver.base: New lock 14
2023-11-22 01:52:26,169,169  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B5} params [03]
2023-11-22 01:52:26,170,170     INFO [ReceiverListener:hidraw0] logitech_receiver.listener: started with <Receiver(/dev/hidraw0,14)> (14)
2023-11-22 01:52:26,170,170     INFO [ReceiverListener:hidraw0] solaar.listener: <Receiver(/dev/hidraw0,14)>: notifications listener has started (14)
2023-11-22 01:52:26,170,170     INFO [ReceiverListener:hidraw0] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw0)>
2023-11-22 01:52:26,177,177     INFO [MainThread] hidapi.udev: Found device BID 0005 VID 0000046D PID 0000B35B HID++ False True USB None None
2023-11-22 01:52:26,177,177     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw2', bus_id=5, vendor_id='046D', product_id='B35B', interface=None, driver='hid-generic', manufacturer=None, product=None, serial='ea:07:31:e7:ac:5e', release=None, isDevice=True, hidpp_short=False, hidpp_long=True)
2023-11-22 01:52:26,177,177     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw2
2023-11-22 01:52:26,177,177     INFO [ReceiverListener:hidraw2] logitech_receiver.listener: started with <Device(255,B35B,MX Keys Keyboard,)> (15)
2023-11-22 01:52:26,177,177     INFO [ReceiverListener:hidraw2] solaar.listener: <Device(255,B35B,MX Keys Keyboard,)>: notifications listener has started (15)
2023-11-22 01:52:26,178,178     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(255,B35B,MX Keys Keyboard,)>: paired offline, {'NOTIFICATION FLAGS': False} (0) 
2023-11-22 01:52:26,178,178     INFO [ReceiverListener:hidraw2] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw2)>
2023-11-22 01:52:26,181,181     INFO [MainThread] solaar.configuration: not setting up persister for offline device MX Keys Keyboard with missing serial number
2023-11-22 01:52:26,849,849     INFO [ReceiverListener:hidraw2] solaar.configuration: setting up persister for device MX Keys Keyboard
2023-11-22 01:52:26,950,950     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(255,B35B,MX Keys Keyboard,)>: paired online, {'NOTIFICATION FLAGS': False, 'BATTERY LEVEL': 50, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 20, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2023-11-22 01:52:27,071,071  WARNING [ReceiverListener:hidraw0] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8000} params [100900]
2023-11-22 01:52:27,973,973  WARNING [ReceiverListener:hidraw0] logitech_receiver.base: timeout (0.90/0.90) on device 255 request {8100} params []
2023-11-22 01:52:27,973,973     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <Receiver(/dev/hidraw0,14)>: receiver notifications enabled => None
Exception in thread ReceiverListener:hidraw0:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/site-packages/logitech_receiver/listener.py", line 156, in run
    self.has_started()
  File "/usr/lib/python3.12/site-packages/solaar/listener.py", line 93, in has_started
    assert self.receiver.isDevice or ((nfs if nfs else 0) & _hidpp10.NOTIFICATION_FLAG.wireless), \
AssertionError: Receiver on /dev/hidraw0 does not support connection notifications, GUI will not show it
2023-11-22 01:52:30,474,474     INFO [ReceiverListener:hidraw2] logitech_receiver.status: <Device(255,B35B,MX Keys Keyboard,)> pushing device settings [<Setting([feature:toggle] MX Keys:backlight=None)>, <Setting([feature:toggle] MX Keys:fn-swap=None)>, <Setting([feature:map choice] MX Keys:divert-keys=None)>, <Setting([feature:multiple toggle] MX Keys:disable-keyboard-keys=None)>, <Setting([feature:choice] MX Keys:multiplatform=None)>, <Setting([feature:choice] MX Keys:change-host=None)>]
2023-11-22 01:52:30,524,524     INFO [AsyncUI] hidapi.udev: OPEN PATH /dev/hidraw2
2023-11-22 01:52:31,951,951     INFO [MainThread] solaar.configuration: saved ['1.1.10', {'_NAME': 'MX Keys Keyboard', '_modelId': 'B35B408A0000', '_unitId': 'DDF2964C', '_battery': NamedInt(4096, 'BATTERY STATUS'), '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'pointer_speed', 'dpi', 'speed-change', 'backlight-timed', 'reprogrammable-keys', 'persistent-remappable-keys', 'crown-smooth', 'divert-crown', 'divert-gkeys', 'm-key-leds', 'mr-key-led', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params', 'sidetone', 'equalizer', 'adc_power_management'], 'backlight': True, 'fn-swap': False}] to /root/.config/solaar/config.yaml
2023-11-22 01:52:34,324,324     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(255,B35B,MX Keys Keyboard,)>: paired online, {'NOTIFICATION FLAGS': False, 'BATTERY LEVEL': 50, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 20, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) initialization
2023-11-22 01:52:37,877,877     INFO [MainThread] solaar.configuration: saved ['1.1.10', {'_NAME': 'MX Keys Keyboard', '_modelId': 'B35B408A0000', '_unitId': 'DDF2964C', '_battery': NamedInt(4096, 'BATTERY STATUS'), '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'pointer_speed', 'dpi', 'speed-change', 'backlight-timed', 'reprogrammable-keys', 'persistent-remappable-keys', 'crown-smooth', 'divert-crown', 'divert-gkeys', 'm-key-leds', 'mr-key-led', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params', 'sidetone', 'equalizer', 'adc_power_management'], 'backlight': True, 'fn-swap': False, 'divert-keys': {209: 0, 210: 0, 211: 0, 199: 0, 200: 0, 224: 0, 225: 0, 110: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0, 233: 0, 10: 0, 191: 0, 234: 0, 111: 0, 236: 0, 235: 0}, 'disable-keyboard-keys': {1: False, 2: False, 4: False, 8: False, 16: False}, 'multiplatform': NamedInt(0, 'Windows'), 'change-host': None}] to /root/.config/solaar/config.yaml
2023-11-22 01:52:55,084,084     INFO [MainThread] solaar.configuration: saved ['1.1.10', {'_NAME': 'MX Keys Keyboard', '_modelId': 'B35B408A0000', '_unitId': 'DDF2964C', '_battery': NamedInt(4096, 'BATTERY STATUS'), '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'pointer_speed', 'dpi', 'speed-change', 'backlight-timed', 'reprogrammable-keys', 'persistent-remappable-keys', 'crown-smooth', 'divert-crown', 'divert-gkeys', 'm-key-leds', 'mr-key-led', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params', 'sidetone', 'equalizer', 'adc_power_management'], 'backlight': True, 'fn-swap': False, 'divert-keys': {209: 0, 210: 0, 211: 0, 199: 0, 200: 0, 224: 0, 225: 0, 110: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0, 233: 0, 10: 0, 191: 0, 234: 0, 111: 0, 236: 0, 235: 0}, 'disable-keyboard-keys': {1: False, 2: False, 4: False, 8: False, 16: False}, 'multiplatform': NamedInt(0, 'Windows'), 'change-host': None, '_sensitive': {'backlight': False}}] to /root/.config/solaar/config.yaml
2023-11-22 01:52:57,949,949     INFO [MainThread] solaar.listener: stopping receiver listening threads [<ReceiverListener(ReceiverListener:hidraw0, stopped daemon 140621822858944)>, <ReceiverListener(ReceiverListener:hidraw2, started daemon 140621457127104)>]
2023-11-22 01:52:57,952,952     INFO [MainThread] solaar.configuration: saved ['1.1.10', {'_NAME': 'MX Keys Keyboard', '_modelId': 'B35B408A0000', '_unitId': 'DDF2964C', '_battery': NamedInt(4096, 'BATTERY STATUS'), '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'pointer_speed', 'dpi', 'speed-change', 'backlight-timed', 'reprogrammable-keys', 'persistent-remappable-keys', 'crown-smooth', 'divert-crown', 'divert-gkeys', 'm-key-leds', 'mr-key-led', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params', 'sidetone', 'equalizer', 'adc_power_management'], 'backlight': True, 'fn-swap': False, 'divert-keys': {209: 0, 210: 0, 211: 0, 199: 0, 200: 0, 224: 0, 225: 0, 110: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0, 233: 0, 10: 0, 191: 0, 234: 0, 111: 0, 236: 0, 235: 0}, 'disable-keyboard-keys': {1: False, 2: False, 4: False, 8: False, 16: False}, 'multiplatform': NamedInt(0, 'Windows'), 'change-host': None, '_sensitive': {'backlight': False}}] to /root/.config/solaar/config.yaml
2023-11-22 01:52:58,505,505     INFO [ReceiverListener:hidraw2] solaar.listener: <Device(255,B35B,MX Keys Keyboard,)>: notifications listener has stopped
2023-11-22 01:52:58,507,507     INFO [MainThread] solaar.ui.notify: stopping desktop notifications
root@localhost-live:~# 
```
</details>

**Describe the bug**
Logitech mouse M185 does not get recognized. From the above log I can guess the problem is the receiver is unknown.

**To Reproduce**
Steps to reproduce the behavior:
1. Install Soolar
2. Launch the program
3. Turn on and connect your mouse to the system

--> Nothing happens.

**Screenshots**
See attached picture of solaar panel in tray.

**Additional context**
N/A

**Comment by pfps** [comment]
If Solaar doesn't list the device then the problems with the device can't be caused by Solaar.  

What receiver is the device paired with?   Provide the output of `sudo lsusb -vv` for the receiver.

**Comment by Ruskie-it** [comment]
Well, no, maybe the problem is exactly that solaar is not able to recognize the device... Maybe M185 should not be on the compatible device list? After all the mouse works correctly within Linux (and Windows, for what matters), and it is a brand new mouse, bought recently to set this machine up, and the receiver is the original one that ships with the mouse. Maybe M185 should be removed from compatible devices?
Yes, it's the C542, here the output:
```
root@localhost-live:~$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 003: ID 046d:c542 Logitech, Inc. M185 compact wireless mouse
Bus 001 Device 004: ID 058f:6364 Alcor Micro Corp. AU6477 Card Reader Controller
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 8087:8008 Intel Corp. Integrated Rate Matching Hub
```

Now that we're speaking, it just occurred to me that I should have some old unifying device thrown in a drawer somewhere... maybe I can use that with my M185. Anyway, if it is possible to add support for this C542 and I can support, let me know

**Comment by Ruskie-it** [comment]
Aaahh, bummer!
Turns out M185 has a **Nano** receiver, not a Unifying. I found and plugged in my spare Unifying dongle, it got recognized by Solaar (who identified its existing pairing to my work Mx keys keyboard). Unfortunately, when I tried to pair it to the mouse, it could not find it, I guess it's not compatible...
Does this mean Solaar is not compatible with my mouse? Can it handle nano receivers?

**Comment by Ruskie-it** [comment]
"Some Nano receivers are not supported as they do not implement the HID++ protocol at all. Receivers with USB ID 046d:c542 fall into this category."
Found that in your page. That's a shame. Well, I'll get back if I can grab a different nano receiver. :)

**Comment by pfps** [comment]
Yes, that's the determination.   See also Issue #1835.  If you want to dig further you can try to get the report descriptor for the receiver or mouse using the process described there.  What you want is all the report descriptors that might be associated with the receiver or mouse, but not any associated with your MX Keys.

Logitech has the nasty habit of using the same device name (M185) even though the internals of the device have changed.

It is unlikely that your mouse can pair with any other receiver, even another nano receiver.

**Comment by pfps** [comment]
I'm going to add some wording to the page on supported devices.
