### ISSUE TITLE
No rules file by default, not able to make correct rules?

### ISSUE THREAD

**Issue by TooManyStacks** [pwr-Solaar/Solaar#2194]
Hey all,

I am using Ubuntu 22.04 and used the solaar coming with the package manager (version 1.1.1).

In the GUI rule editor, I am not able to select or change anything, so I do not understand the greyed out buttons discard and save changes. I read one should use the rules.yaml file, but there is none in ~/.config/solaar/rules.yaml
No biggie, I made the following rules.yaml:

```
---
- Rule:
  - Key: Brightness Down
  - KeyPress: [Control-L, x]
- Rule:
  - Key: Brightness Up
  - KeyPress: [Control-L, v]
...
---
`

When I run solaar -ddd

`solaar -ddd
16:11:40,242     INFO [MainThread] root: language en_US (UTF-8), translations path None
16:11:40,339    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
16:11:40,339    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
16:11:40,340    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
16:11:40,340  WARNING [MainThread] logitech_receiver.diversion: rule KeyPress argument not sequence of key names ['Control-L', 'x']
16:11:40,340    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
16:11:40,340  WARNING [MainThread] logitech_receiver.diversion: rule KeyPress argument not sequence of key names ['Control-L', 'v']
16:11:40,340    DEBUG [MainThread] logitech_receiver.diversion: load rule: Rule(/home/TooManyStacks /.config/solaar/rules.yaml)[Rule[Key: Brightness Down (pressed), KeyPress: Control-L x], Rule[Key: Brightness Up (pressed), KeyPress: Control-L v]]
16:11:40,340    ERROR [MainThread] logitech_receiver.diversion: failed to load from /home/TooManyStacks /.config/solaar/rules.yaml
'NoneType' object is not iterable
16:11:40,342    DEBUG [MainThread] solaar.ui.tray: using Ayatana AppIndicator3
16:11:40,347     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
```

So, what is this nonetype I am getting reported?

**Comment by TooManyStacks** [comment]
I now used the PPA as provided in this repo, version 1.1.8, I have this now:



`%YAML 1.3
---
- Rule:
  - Key: [Brightness Down, pressed]
  - KeyPress:
    - [Control_L, x]
    - click
- Rule:
  - Key: [Brightness Up, pressed]
  - KeyPress:
    - [Control_L, v]
    - click
...
`




`solaar -d
2023-12-06 12:17:31,302,302  WARNING [MainThread] logitech_receiver.diversion: rules cannot access active process or modifier keys in Wayland
2023-12-06 12:17:31,303,303  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
2023-12-06 12:17:31,372,372  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046A PID 00000702: No module named 'hid_parser'
2023-12-06 12:17:31,373,373  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 00000B05 PID 000019AF: No module named 'hid_parser'
2023-12-06 12:17:31,373,373  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C52B: No module named 'hid_parser'
2023-12-06 12:17:40,767,767  WARNING [MainThread] logitech_receiver.diversion: XKB display not available - rules cannot access keyboard group
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 151, in xkb_setup
    X11Lib = _ctypes.cdll.LoadLibrary('libX11.so')
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libX11.so: cannot open shared object file: No such file or directory
2023-12-06 12:17:40,768,768  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
2023-12-06 12:17:40,768,768  WARNING [MainThread] logitech_receiver.diversion: no way to simulate key input
`

**Comment by pfps** [comment]
The warnings are as expected if you are running Wayland and have not installed the Wayland udev rule.  From https://github.com/pwr-Solaar/Solaar/ under known issues: 

> Solaar will try to use uinput to simulate input from rules under Wayland or if Xtest is not available but this needs write permission on /dev/uinput. For more information see [the rules page](https://pwr-solaar.github.io/Solaar/rules).

If this doesn't solve the issue provide the output of `solaar -ddd` as you try to edit rules.

**Comment by TooManyStacks** [comment]
The 1.1.8 version works on X, not on wayland, I can make cool rules now. Thanks for staying with me.
