### ISSUE TITLE
Write failure on solaar config, solaar show...

### ISSUE THREAD

**Issue by chimps-ahoy** [pwr-Solaar/Solaar#2220]
**Information**

- Solaar version : 1.1.10
- Distribution: Arch
- Kernel version ; Linux 6.7.0-arch3-1 x86_64 GNU/Linux
- Output of `solaar show`:
<details>

```
solaar version 1.1.10

USB and Bluetooth Devices

solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/logitech_receiver/base.py", line 221, in write
    _hid.write(int(handle), wdata)
  File "/usr/lib/python3.11/site-packages/hidapi/udev.py", line 385, in write
    raise OSError(_errno.EIO, 'written %d bytes out of expected %d' % (bytes_written, len(data)))
OSError: [Errno 5] written 0 bytes out of expected 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/solaar/cli/__init__.py", line 211, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.11/site-packages/solaar/cli/show.py", line 305, in run
    _print_device(d, num=dev_num)
  File "/usr/lib/python3.11/site-packages/solaar/cli/show.py", line 85, in _print_device
    dev.ping()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/base.py", line 519, in ping
    write(int(handle), devnumber, request_data, long_message)
  File "/usr/lib/python3.11/site-packages/logitech_receiver/base.py", line 225, in write
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': OSError(5, 'written 0 bytes out of expected 7')}

```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.10
- _name: mx master 3s
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelid: b03400000000
  _sensitive: {change-host: false, divert-keys: false, dpi: false, reprogrammable-keys: false, thumb-scroll-invert: false}
  _unitid: d852dff1
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 1500
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 10
  thumb-scroll-invert: true
  thumb-scroll-mode: false
```
</details>

- Errors or warrnings from Solaar:
<details>
2024-01-20 01:41:41,975,975     INFO [MainThread] root: version 1.1.10, language en_US (UTF-8)
2024-01-20 01:41:42,156,156     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2024-01-20 01:41:42,159,159    ERROR [MainThread] logitech_receiver.diversion: failed to load from /home/Sebastien/.config/solaar/rules.yaml
expected '<document start>', but found '<stream end>'
  in "/home/Sebastien/.config/solaar/rules.yaml", line 2, column 1
2024-01-20 01:41:42,175,175     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
2024-01-20 01:41:42,205,205     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2024-01-20 01:41:42,239,239  WARNING [MainThread] solaar.ui.icons: failed to detect icons
2024-01-20 01:41:42,260,260     INFO [MainThread] solaar.listener: starting receiver listening threads
2024-01-20 01:41:42,465,465  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 001F VID 00000000 PID 00000000: unpack requires a buffer of 2 bytes
2024-01-20 01:41:42,466,466  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 001F VID 00008086 PID 00000001: unpack requires a buffer of 2 bytes
2024-01-20 01:41:42,467,467  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 001F VID 00008086 PID 00000001: unpack requires a buffer of 2 bytes
2024-01-20 01:41:42,476,476  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C341: Expecting 104 usages but got 112
2024-01-20 01:41:42,477,477     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C341 HID++ None None USB 1 2
2024-01-20 01:41:42,477,477  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C341: Expecting 64 usages but got 1
2024-01-20 01:41:42,477,477     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C341 HID++ None None USB 2 2
2024-01-20 01:41:42,478,478     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw2', bus_id=3, vendor_id='046D', product_id='C341', interface=2, driver='hid-generic', manufacturer=None, product=None, serial='KG511U00000A', release=None, isDevice=True, hidpp_short=None, hidpp_long=None)
2024-01-20 01:41:42,478,478     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw2
2024-01-20 01:41:42,535,535     INFO [ReceiverListener:hidraw2] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw2)>
2024-01-20 01:41:42,839,839    ERROR [ReceiverListener:hidraw2] logitech_receiver.base: write failed, assuming handle 13 no longer available
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/logitech_receiver/base.py", line 221, in write
    _hid.write(int(handle), wdata)
  File "/usr/lib/python3.11/site-packages/hidapi/udev.py", line 385, in write
    raise OSError(_errno.EIO, 'written %d bytes out of expected %d' % (bytes_written, len(data)))
OSError: [Errno 5] written 0 bytes out of expected 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 482, in __str__
    self.number, self.wpid or self.product_id, self.name or self.codename or '?', self.serial
                                               ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 198, in name
    self.ping()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/base.py", line 519, in ping
    write(int(handle), devnumber, request_data, long_message)
  File "/usr/lib/python3.11/site-packages/logitech_receiver/base.py", line 225, in write
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': OSError(5, 'written 0 bytes out of expected 7')}
Call stack:
  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/listener.py", line 155, in run
    _log.info('started with %s (%d)', self.receiver, int(self.receiver.handle))
2024-01-20 01:41:42,842,842    ERROR [ReceiverListener:hidraw2] logitech_receiver.base: read failed, assuming receiver 13 no longer available
2024-01-20 01:41:42,842,842  WARNING [ReceiverListener:hidraw2] logitech_receiver.base: device or receiver disconnected
Message: 'started with %s (%d)'
Arguments: (<Device(255,C341,Unknown device C341,)>, 13)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 482, in __str__
    self.number, self.wpid or self.product_id, self.name or self.codename or '?', self.serial
                                               ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 198, in name
    self.ping()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'handle'
Call stack:
  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/listener.py", line 155, in run
    _log.info('started with %s (%d)', self.receiver, int(self.receiver.handle))
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 482, in __str__
    self.number, self.wpid or self.product_id, self.name or self.codename or '?', self.serial
                                               ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 198, in name
    self.ping()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
                                         ^^^^^^^^^^^^^^^^^^^^
2024-01-20 01:41:42,540,540  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000056A PID 0000509C: Unsupported global tag: 0b101
AttributeError: 'NoneType' object has no attribute 'handle'
Call stack:
  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/listener.py", line 156, in run
    self.has_started()
  File "/usr/lib/python3.11/site-packages/solaar/listener.py", line 91, in has_started
    _log.info('%s: notifications listener has started (%s)', self.receiver, self.receiver.handle)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 482, in __str__
    self.number, self.wpid or self.product_id, self.name or self.codename or '?', self.serial
                                               ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 198, in name
    self.ping()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'handle'
Call stack:
  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/listener.py", line 156, in run
    self.has_started()
  File "/usr/lib/python3.11/site-packages/solaar/listener.py", line 91, in has_started
    _log.info('%s: notifications listener has started (%s)', self.receiver, self.receiver.handle)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
Exception in thread ReceiverListener:hidraw2:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/listener.py", line 156, in run
    self.has_started()
  File "/usr/lib/python3.11/site-packages/solaar/listener.py", line 97, in has_started
    self._status_changed(self.receiver)  # , _status.ALERT.NOTIFICATION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/solaar/listener.py", line 157, in _status_changed
    if device.kind is None:
       ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 250, in kind
2024-01-20 01:41:42,846,846  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000056A PID 0000509C: unpack requires a buffer of 2 bytes
    if not self._kind and self.protocol >= 2.0:
                          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 174, in protocol
    self.ping()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 455, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=long)
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'handle'
2024-01-20 01:41:42,847,847     INFO [MainThread] hidapi.udev: Found device BID 0005 VID 0000046D PID 0000B034 HID++ False True USB None None
2024-01-20 01:41:42,848,848     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw8', bus_id=5, vendor_id='046D', product_id='B034', interface=None, driver='logitech-hidpp-device', manufacturer=None, product=None, serial='d3:67:90:e6:53:72', release=None, isDevice=True, hidpp_short=False, hidpp_long=True)
2024-01-20 01:41:42,848,848     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw8
2024-01-20 01:41:42,848,848     INFO [ReceiverListener:hidraw8] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw8)>
2024-01-20 01:41:42,848,848     INFO [ReceiverListener:hidraw8] logitech_receiver.listener: started with <Device(255,B034,MX Master 3S,)> (13)
2024-01-20 01:41:43,629,629     INFO [ReceiverListener:hidraw8] solaar.listener: <Device(255,B034,MX Master 3S,)>: notifications listener has started (13)
2024-01-20 01:41:43,661,661     INFO [ReceiverListener:hidraw8] solaar.listener: status_changed <Device(255,B034,MX Master 3S,)>: paired online, {'NOTIFICATION FLAGS': False} (0) 
2024-01-20 01:41:43,661,661  WARNING [MainThread] solaar.ui.icons: icon battery-missing not found in current theme
2024-01-20 01:41:43,694,694     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw8
2024-01-20 01:41:43,925,925     INFO [ReceiverListener:hidraw8] solaar.listener: status_changed <Device(255,B034,MX Master 3S,)>: paired online, {'NOTIFICATION FLAGS': False, 'BATTERY LEVEL': 85, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
2024-01-20 01:41:43,957,957  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-01-20 01:41:44,689,689     INFO [ReceiverListener:hidraw8] logitech_receiver.status: <Device(255,B034,MX Master 3S,)> pushing device settings [<Setting([feature:toggle] MX Master 3S:hires-smooth-invert=None)>, <Setting([feature:toggle] MX Master 3S:hires-smooth-resolution=None)>, <Setting([feature:toggle] MX Master 3S:hires-scroll-mode=None)>, <Setting([feature:choice] MX Master 3S:scroll-ratchet=None)>, <Setting([feature:range] MX Master 3S:smart-shift=None)>, <Setting([feature:toggle] MX Master 3S:thumb-scroll-invert=None)>, <Setting([feature:toggle] MX Master 3S:thumb-scroll-mode=None)>, <Setting([feature:choice] MX Master 3S:dpi=None)>, <Setting([feature:map choice] MX Master 3S:reprogrammable-keys=None)>, <Setting([feature:map choice] MX Master 3S:divert-keys=None)>, <Setting([feature:choice] MX Master 3S:change-host=None)>]
2024-01-20 01:41:44,714,714     INFO [AsyncUI] hidapi.udev: OPEN PATH /dev/hidraw8
2024-01-20 01:41:44,739,739  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-01-20 01:41:44,740,740  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-01-20 01:41:44,740,740  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-01-20 01:41:45,494,494     INFO [ReceiverListener:hidraw8] solaar.listener: status_changed <Device(255,B034,MX Master 3S,)>: paired online, {'NOTIFICATION FLAGS': False, 'BATTERY LEVEL': 85, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) initialization
2024-01-20 01:41:45,494,494  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-01-20 01:41:45,495,495  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-01-20 01:41:45,495,495  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-01-20 01:41:48,660,660     INFO [MainThread] solaar.listener: stopping receiver listening threads [<ReceiverListener(ReceiverListener:hidraw2, stopped daemon 126967049356992)>, <ReceiverListener(ReceiverListener:hidraw8, started daemon 126967049356992)>]
2024-01-20 01:41:48,662,662     INFO [MainThread] solaar.configuration: saved ['1.1.10', {'_NAME': 'MX Master 3S', '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'onboard_profiles', 'report_rate', 'pointer_speed', 'speed-change', 'backlight', 'backlight-timed', 'fn-swap', 'persistent-remappable-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'divert-gkeys', 'm-key-leds', 'mr-key-led', 'multiplatform', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params', 'sidetone', 'equalizer', 'adc_power_management'], '_battery': 4100, '_modelId': 'B03400000000', '_sensitive': {'change-host': False, 'divert-keys': False, 'dpi': False, 'reprogrammable-keys': False, 'thumb-scroll-invert': False}, '_unitId': 'D852DFF1', 'change-host': None, 'divert-keys': {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}, 'dpi': 1500, 'hires-scroll-mode': False, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}, 'scroll-ratchet': 2, 'smart-shift': 10, 'thumb-scroll-invert': True, 'thumb-scroll-mode': False}] to /home/Sebastien/.config/solaar/config.yaml
2024-01-20 01:41:48,927,927     INFO [ReceiverListener:hidraw8] solaar.listener: <Device(255,B034,MX Master 3S,)>: notifications listener has stopped
2024-01-20 01:41:48,928,928     INFO [MainThread] solaar.ui.notify: stopping desktop notifications
</details>

**Describe the bug**
Upon running most commands solaar show, or solaar config with any other arguments, I just get this stacktrace for some write exception

**To Reproduce**
Steps to reproduce the behavior:
1. Go to terminal
2. Type 'solaar show'

**Comment by pfps** [comment]
The first thing to do is to fix your rule.yaml file.

```
2024-01-20 01:41:42,159,159    ERROR [MainThread] logitech_receiver.diversion: failed to load from /home/Sebastien/.config/solaar/rules.yaml
expected '<document start>', but found '<stream end>'
  in "/home/Sebastien/.config/solaar/rules.yaml", line 2, column 1
```

but that is not the cause of the crash.

**Comment by pfps** [comment]
What Logitech devices do you have?

**Comment by pfps** [comment]
Does `solaar` work?   What devices does it show?  Please run `solaar -ddd` (after killing any running Solaar) and report the output unless that is what you provided above.

**Comment by pfps** [comment]
This is likely a known problem.  Solaar tries hard to work with all appropriate Logitech devices but for some devices Solaar can't work without some code to tell it how to communicate with the device.  Without that code Solaar cannot write to the device.  Recent changes to Solaar have made the resultant errors easier to see.   As well, it is likely that the needed information has been added to Solaar to support your device.

So clone Solaar from this repository and run `bin/solaar show` and report back the output.   If there is no error then you should be able to run Solaar as `/bin/solaar` with no problems.

**Comment by chimps-ahoy** [comment]
> This is likely a known problem. Solaar tries hard to work with all appropriate Logitech devices but for some devices Solaar can't work without some code to tell it how to communicate with the device. Without that code Solaar cannot write to the device. Recent changes to Solaar have made the resultant errors easier to see. As well, it is likely that the needed information has been added to Solaar to support your device.
> 
> So clone Solaar from this repository and run `bin/solaar show` and report back the output. If there is no error then you should be able to run Solaar as `/bin/solaar` with no problems.

My apolocheese. When cloning from the github it works, it must just be that the AUR package is out of date. Btw, I use an MX Master 3S, so maybe it is a newer product and that is the reason why.

Thanks for the help :>

**Comment by pfps** [comment]
The current code works because there is an explicit descriptor for your device.   Can you provide the output of `solaar show` to add more information on this device to the Solaar documentation?

**Comment by pfps** [comment]
The MX Master 3S should have been fine.   I think you have a K845 Mechanical Keyboard that was causing the problem.

It may be possible to better support this device.  Can you provide the report descriptor(s) for it using the instructions in https://pwr-solaar.github.io/Solaar/devices?  I want the actual descriptor file(s), not a report on their contents.  There should be two descriptor files for your device.   You should be able to find the hidrawN numbers by running `bin/solaar -d` and looking for 
```
... WARNING [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidrawN BID 0003 VID 0000046D PID 0000C341: ...
```
lines with N replaced by some number.

**Comment by chimps-ahoy** [comment]
[k845.zip](https://github.com/pwr-Solaar/Solaar/files/14059194/k845.zip)
I have included all the descriptor files, as well as a file containing the output of lsusb -vv with the ID of the device.

There was not a descriptor file for the mouse, only the keyboard, so I assumed that's what you wanted. There were 3 files for the keyboard, but they were not listed by the output of solaar -d (where it should have said /dev/hidrawN was just blank, so it just said `Descriptor not processed for BID 0003 .... etc`

Additionally, I couldn't get hdrid working to convert the files, and I wasn't sure what you meant by copying their contents into a txt file (even if I cat'd the output into a file with a txt extension, it would still be a binary file with a txt extension), so I just included those files as is.

If it is of any worth as well, I noticed an additional issue where `solaar config MX change-host` still does not work, but only so long as the keyboard is connected. once I disconnect the keyboard, the command runs fine, so I figure it has something to do with the keyboard interferring in some way?

**Comment by pfps** [comment]
USB devices can have multiple interfaces.  The K845 has three - one as a generic keyboard, one that looks like a keypad, and one that is private to Logitech but does not appear to be HID++.  I'll have to ask to see what it actually is and whether Solaar can use it.

If Solaar isn't working at all for you now I can produce a version that ignores the K845.

**Comment by chimps-ahoy** [comment]
A version that ignores the K845 would work for my workflow (I only use solaar for my mouse. the issue is that I have `solaar config MX change-host` bound to a key combination in my window manager to switch between multiple devices), but the issue right now isn't detrimental to me (I can just find a different keyboard to use or manually switch with the button on the bottom of the mouse), so I couldn't ask you to go through that work.

Good luck on the development. I hope this is able to help you :)

**Comment by pfps** [comment]
OK.  Hopefully I'll get an answer on whether the K845 can be supported in Solaar soon.   If it can't, the fix is very simple.  If it can, the fix might be somewhat more complex.
