### ISSUE TITLE
Issues with version 1.1.11rc2

### ISSUE THREAD

**Issue by Svenum** [pwr-Solaar/Solaar#2276]
**Information**
Newest Prerelease of Solaar

**Describe the bug**
Error message at start (dont know if this causes issues):
```
Traceback (most recent call last):
  File "/nix/store/wccgl5lxhvc9k1994jrka1qd9k8yn35b-solaar-flake-1.1.11rc2/lib/python3.11/site-packages/solaar/ui/config_panel.py", line 830, in _record_setting
    assert device == setting._device
                     ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_device'
```

The "About solaar" button do not work, here is the error message:
```
Traceback (most recent call last):
  File "/nix/store/wccgl5lxhvc9k1994jrka1qd9k8yn35b-solaar-flake-1.1.11rc2/lib/python3.11/site-packages/solaar/ui/about.py", line 99, in show_window
    _dialog = _create()
              ^^^^^^^^^
  File "/nix/store/wccgl5lxhvc9k1994jrka1qd9k8yn35b-solaar-flake-1.1.11rc2/lib/python3.11/site-packages/solaar/ui/about.py", line 37, in _create
    about.setloggero_icon_name(NAME.lower())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AboutDialog' object has no attribute 'setloggero_icon_name'. Did you mean: 'set_logo_icon_name'?
```

Else the version works fine for me. :smile: :+1:

**Comment by pfps** [comment]
The first error appears to be a timing problem.   Some low-level Solaar code is trying to change the value of a setting being displayed in the GUI but the setting was not found, probably because Solaar is just starting up.  This is likely due to a notification coming in from a device.   The result is that the GUI might not be showing the actual value for a setting, but there should not be any other effects.

This code is slated for improvements as soon as 1.1.11 goes out, so the solution for now is to just improve the message generated.

**Comment by Svenum** [comment]
Thanks for the quick fix of one issue and for the explanation for the other error. 😄
