### ISSUE TITLE
hid_parser library now mandatory

### ISSUE THREAD

**Issue by mkyral** [pwr-Solaar/Solaar#2324]
Current git version does not start on Gentoo due to missing hid_parser python library.

```shell
$ solaar
Traceback (most recent call last):
  File "/usr/bin/solaar", line 54, in <module>
    import solaar.gtk
  File "/usr/lib/python3.11/site-packages/solaar/gtk.py", line 33, in <module>
    import solaar.cli as _cli
  File "/usr/lib/python3.11/site-packages/solaar/cli/__init__.py", line 26, in <module>
    import logitech_receiver.device as _device
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 25, in <module>
    import hidapi as _hid
  File "/usr/lib/python3.11/site-packages/hidapi/__init__.py", line 38, in <module>
    from hidapi.udev import (
  File "/usr/lib/python3.11/site-packages/hidapi/udev.py", line 41, in <module>
    from hid_parser import ReportDescriptor as _ReportDescriptor
ModuleNotFoundError: No module named 'hid_parser'
```

It is caused by commit https://github.com/pwr-Solaar/Solaar/commit/d1c899d6da664d22f22c4b5f4fe3b0790ed54410 that made this library mandatory. But in documentation it is still listed as optional.

As this library is not packed by Gentoo, I had to install it manually via pip.

**Comment by pfps** [comment]
Solaar works much better with hid_parser, but the import should be moved back inside the try block.   A fix is in the works.

**Comment by pfps** [comment]
PR #2327 moves the import back inside the try block, making it optional again.

Solaar will correctly handle more devices with hid_parser installed.
