### ISSUE TITLE
Logitech CIDs and TIDs are not X11 keysyms

### ISSUE THREAD

**Issue by Inocious** [pwr-Solaar/Solaar#2342]
I have my main here with an issue with print_cid_reporting():
```
def main():
    buttons = SpecialKeysMseButtons()
    cids = print_cid_info(buttons)
    print()
    print_cid_reporting(buttons, cids)
```

My print_cid_info() function gives me back this:
```
### CID INFO ###
  CID    TID  virtual persist divert reprog fntog hotkey fkey  mouse pos group gmask      rawXY
0x00C7 0x00A3 False   False   True   True   True  False  True  False 1   0     0b00000000 False
0x00C8 0x00A4 False   False   True   True   True  False  True  False 2   0     0b00000000 False
0x00E2 0x00C1 False   False   True   True   True  False  True  False 3   0     0b00000000 False
0x00E3 0x00C2 False   False   True   True   True  False  True  False 4   0     0b00000000 False
0x0103 0x00D8 False   False   True   True   True  False  True  False 5   0     0b00000000 False
0x0108 0x00DD False   False   True   True   True  False  True  False 6   0     0b00000000 False
0x010A 0x00DF False   False   True   True   True  False  True  False 7   0     0b00000000 False
0x011C 0x00F1 False   False   True   True   True  False  True  False 8   0     0b00000000 False
0x00E4 0x0006 False   False   True   True   True  False  True  False 9   0     0b00000000 False
0x00E5 0x0004 False   False   True   True   True  False  True  False 10  0     0b00000000 False
0x00E6 0x0005 False   False   True   True   True  False  True  False 11  0     0b00000000 False
0x00E7 0x0003 False   False   True   True   True  False  True  False 12  0     0b00000000 False
0x00E8 0x0002 False   False   True   True   False True   False False 0   0     0b00000000 False
0x00E9 0x0001 False   False   True   True   False True   False False 0   0     0b00000000 False
0x010B 0x00E0 False   False   True   True   False False  False False 0   0     0b00000000 False
0x010C 0x00E1 False   False   True   True   False False  False False 0   0     0b00000000 False
0x010D 0x00E2 False   False   True   True   False False  False False 0   0     0b00000000 False
0x010E 0x00E3 False   False   True   True   False False  False False 0   0     0b00000000 False
0x010F 0x00E4 False   False   True   True   False False  False False 0   0     0b00000000 False
0x0110 0x00E5 False   False   True   True   False False  False False 0   0     0b00000000 False
0x0111 0x00E6 False   False   True   True   False False  False False 0   0     0b00000000 False
0x0112 0x00E7 False   False   True   True   False False  False False 0   0     0b00000000 False
0x0113 0x00E8 False   False   True   True   False False  False False 0   0     0b00000000 False
0x0114 0x00E9 False   False   True   True   False False  False False 0   0     0b00000000 False
0x0115 0x00EA False   False   True   True   False False  False False 0   0     0b00000000 False
0x011E 0x00F3 False   False   True   True   False False  False False 0   0     0b00000000 False
0x0116 0x00EB False   False   True   True   False False  False False 0   0     0b00000000 False
0x0117 0x00EC False   False   True   True   False False  False False 0   0     0b00000000 False
0x0118 0x00ED False   False   True   True   False False  False False 0   0     0b00000000 False
0x0119 0x00EE False   False   True   True   False False  False False 0   0     0b00000000 False
0x011A 0x00EF False   False   True   True   False False  False False 0   0     0b00000000 False
0x011B 0x00F0 False   False   True   True   False False  False False 0   0     0b00000000 False
0x000A 0x000A False   False   True   True   False True   False False 0   0     0b00000000 False
0x006E 0x0043 False   False   True   True   False True   False False 0   0     0b00000000 False
0x00D4 0x00B1 False   False   True   True   False True   False False 0   0     0b00000000 False
0x006F 0x0044 False   False   True   True   False True   False False 0   0     0b00000000 False
0x00D1 0x00AE False   False   False  False  False True   False False 0   0     0b00000000 False
0x00D2 0x00AF False   False   False  False  False True   False False 0   0     0b00000000 False
0x00D3 0x00B0 False   False   False  False  False True   False False 0   0     0b00000000 False
0x00DE 0x0062 False   False   False  False  False False  True  False 0   0     0b00000000 False
0x0034 0x0062 False   False   False  False  False True   False False 0   0     0b00000000 False
```

When I'm calling print_cid_reporting function at my fifth CID a traceback is raised:
```
def print_cid_reporting(buttons, cids):
    print("### CID REPORTING ###")
    print("  CID  rawXY persist divert remap")
    for cid in cids:
        if cid > 255:
            print("Issue is here.Traceback Raised Here.")
        cid_reporting = buttons.get_cid_reporting(cid)
        print(
            "0x{cid:04X} {rawXY!r:<5} {persist!r:<7} {divert!r:<6} 0x{remap:04X}".format(**cid_reporting)
        )
```
Traceback:
```
Traceback (most recent call last):
  File "/home/user/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/user/Downloads/logitech-mxmechanical-config/mxmechanical_config/__init__.py", line 117, in get_cid_reporting
    response = int.from_bytes(self.mxmechanical.request(
  File "/home/user/Downloads/logitech-mxmechanical-config/venv/lib/python3.10/site-packages/logitech_receiver/device.py", line 468, in request
    return _base.request(
  File "/home/user/Downloads/logitech-mxmechanical-config/venv/lib/python3.10/site-packages/logitech_receiver/base.py", line 456, in request
    params = b''.join(_pack('B', p) if isinstance(p, int) else p for p in params)
  File "/home/user/Downloads/logitech-mxmechanical-config/venv/lib/python3.10/site-packages/logitech_receiver/base.py", line 456, in <genexpr>
    params = b''.join(_pack('B', p) if isinstance(p, int) else p for p in params)
struct.error: ubyte format requires 0 <= number <= 255
```

And my 5th CID 0x0103 reported in my `print_cid_info()` function  is indeed higher than 255 (`0x0103 0x00D8 False   False   True   True   True  False  True  False 5   0     0b00000000 False`) it's 259 here. And number of others are reported as with a CID higher than 255. Why do I have a CID reported higher than 255, is it normal ? If yes how can I deal with this issue ?

**Comment by pfps** [comment]
Those CID numbers are internal to the device and are not fed into Linux input processing.   So they are not keysyms that are fed through X11 and thus have to be less than 255 or so.  Look in CONTROL in special_keys.py for their interpretation.  

The TID numbers are fed into Linux input processing.  These are USB HID controls, I believe.  But there are also not X11 keysyms, I believe.  Linux input processing maps these numbers into an internal form.  Look in TASKS in special_keys.py for their interpretation.

Welcome to the wild and wacky world of Linux input processing.

**Comment by Inocious** [comment]
> If you want to find out the current state of a key on your keyboard then you have to know the CID for that key, which for some keys can only be done by pressing the key and seeing what TASK id is sent.

That's what I want. Issue is that in this function, it fails if my Control_id (=CID) is higher than 255:
```
int.from_bytes(self.mxmechanical.request(
            (self.feature_index_bolt << 8) + (2 << 4) + self.software_id_bolt,
            control_id & 0xFF00, control_id & 0x00FF
        ), byteorder='big')

```

So I can't get the current state by calling this function this way.
There was a misunderstanding probably, my only point here is getting the current state for each key. That's all.

> If you want to find out the current state of a key on your keyboard then you have to know the CID for that key, which for some keys can only be done by pressing the key and seeing what TASK id is sent.

So I do have the CID. But then I don't know how to use it to get the current state of the key as I'm having issue everytime this CID is higher than 255.
