### ISSUE TITLE
set_cid_reporting fails with 2 = invalid argument

### ISSUE THREAD

**Issue by Inocious** [pwr-Solaar/Solaar#2370]
I'm calling my function set_cid_reporting device.request:
```
class SpecialKeysMseButtons:
    def set_cid_reporting(self, cid, divert, dvalid, persist, pvalid, rawXY, rvalid, remap):
        self.mxmechanical.request(
            (self.feature_index_bolt << 8) + (3 << 4) + self.software_id_bolt,
            cid & 0xFF00,
            cid & 0x00FF,
            (divert << 0) | (dvalid << 1) | (persist << 2) | (pvalid << 3) | (rawXY << 4) | (rvalid << 5),
            remap & 0xFF00,
            remap & 0x00FF
        )
```

```
buttons = SpecialKeysMseButtons()
print("### REMAP CID 0xD4 TO 0xD1 ###")
buttons.set_cid_reporting(cid=0xD4, divert=False, dvalid=False, persist=True, pvalid=True, rawXY=False, rvalid=False, remap=0xD1
```

I then have an issue no matter the parameters I'm giving as :
```
### REMAP CID 0xD4 TO 0xD1 ###
INFO:root:Call of "self.mxmechanical.request(2110,0,212,12,0,209)"...
INFO:root:Call of "_base.request(handle :6,devnumber: 1,request_id:2110,*params: (0, 212, 12, 0, 209),no_reply=False,long_message=True,protocol=4.5
DEBUG:root:(6) device 1 request_id {083B} params [00D40C00D1]
DEBUG:root:params: b'\x00\xd4\x0c\x00\xd1'
DEBUG:root:type(params): <class 'bytes'>
ERROR:logitech_receiver.base:(6) device 1 error on feature request {083B}: 2 = invalid argument
Traceback (most recent call last):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/Downloads/logitech-mxmechanical-config/venv/lib/python3.10/site-packages/logitech_receiver/base.py", line 421, in acquire_timeout
    yield result
  File "/home/user/Downloads/logitech-mxmechanical-config/venv/lib/python3.10/site-packages/logitech_receiver/base.py", line 512, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 1, 'request': 2107, 'error': 2, 'params': b'\x00\xd4\x0c\x00\xd1'}
```

Do I miss something here ? Am I supposed to call it differently ?

**Comment by pfps** [comment]
The params are supposed to be bytes, but some of them are ints with their data not in the low-order byte.

**Comment by Inocious** [comment]
I can't do the set_cid_reporting with solaar gui as I'm aware. I'm either trying to remap a key (this example), or set "divert" flag to True on a key (another thing that I didn't present here).
So I can't compare it.
Something is being wrongly handled somewhere but I can't figure out where.

**Comment by pfps** [comment]
Try a remapping and see how the messages compare.  Just seeing the messages your code produces would probably help.   Also look at the output of `solaar show` to see whether what you want to do is possible.

In any case
```
            cid & 0xFF00,
            cid & 0x00FF,
```
is obviously wrong.

**Comment by pfps** [comment]
Closing due to no response.
