### ISSUE TITLE
Logitech G502 Hero not being discovered

### ISSUE THREAD

**Issue by UnconnectedBedna** [pwr-Solaar/Solaar#2468]
- Solaar version (`solaar --version`): 1.1.12
- Distribution: Arch linux
- Kernel version (ex. `uname -srmo`): `Linux 6.8.9-arch1-1 x86_64 GNU/Linux`
- Output of `solaar show`: 

```
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/solaar/cli/__init__.py", line 217, in run
    raise Exception(
Exception: No supported device found.  Use "lsusb" and "bluetoothctl devices Connected" to list connected devices.
```

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

There is no solaar directory created in .config

- Errors or warrnings from Solaar:

```
$ solaar -dd

rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
2024-05-07 17:26:56,352,352     INFO [MainThread] solaar.gtk: version 1.1.12, language en_US (UTF-8)
2024-05-07 17:26:56,354,354     INFO [MainThread] solaar.dbus: connected to system dbus, watching for suspend/resume events
2024-05-07 17:26:56,375,375     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2024-05-07 17:26:56,395,395     INFO [MainThread] solaar.listener: starting receiver listening threads
2024-05-07 17:26:56,460,460     INFO [MainThread] hidapi.udev: Found device /dev/hidraw2 BID 0003 VID 0000046D PID 0000C08B HID++ True True USB 1 1
2024-05-07 17:26:56,460,460     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw2', bus_id=3, vendor_id='046D', product_id='C08B', interface=1, driver='hid-generic', manufacturer=None, product=None, serial='0F72326E3730', release=None, isDevice=True, hidpp_short=True, hidpp_long=True)
2024-05-07 17:26:56,460,460     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw2
2024-05-07 17:26:56,460,460     INFO [MainThread] hidapi.udev: OPEN PATH FAILED /dev/hidraw2 ERROR 13 [Errno 13] Permission denied: '/dev/hidraw2'
2024-05-07 17:26:56,560,560     INFO [MainThread] hidapi.udev: OPEN PATH FAILED /dev/hidraw2 ERROR 13 [Errno 13] Permission denied: '/dev/hidraw2'
2024-05-07 17:26:56,660,660     INFO [MainThread] hidapi.udev: OPEN PATH FAILED /dev/hidraw2 ERROR 13 [Errno 13] Permission denied: '/dev/hidraw2'
2024-05-07 17:26:56,761,761  WARNING [MainThread] solaar.listener: failed to open DeviceInfo(path='/dev/hidraw2', bus_id=3, vendor_id='046D', product_id='C08B', interface=1, driver='hid-generic', manufacturer=None, product=None, serial='0F72326E3730', release=None, isDevice=True, hidpp_short=True, hidpp_long=True)
^CThread 0x00007bb3060006c0 (most recent call first):
  File "/usr/lib/python3.12/threading.py", line 355 in wait
  File "/usr/lib/python3.12/queue.py", line 171 in get
  File "/usr/lib/python3.12/site-packages/solaar/tasks.py", line 57 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Current thread 0x00007bb313c84740 (most recent call first):
  File "/usr/lib/python3.12/site-packages/solaar/gtk.py", line 137 in _handlesig
  File "/usr/lib/python3.12/site-packages/gi/_ossighelper.py", line 92 in signal_notify
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gio.py", line 42 in run
  File "/usr/lib/python3.12/site-packages/solaar/ui/__init__.py", line 104 in run_loop
  File "/usr/lib/python3.12/site-packages/solaar/gtk.py", line 182 in main
  File "/usr/bin/solaar", line 56 in <module>
solaar: exit due to keyboard interrupt
```

Application opens fine, but can not find my mouse.
Using kde, wayland.

```
Bus 009 Device 003: ID 046d:c08b Logitech, Inc. G502 SE HERO Gaming Mouse
```

**Comment by pfps** [comment]
It appears that the Solaar udev rule is not installed or is not active (yet).  For more information see https://pwr-solaar.github.io/Solaar/installation

One way to make the rule active if it is not is via `sudo udevadm control --reload-rules`

**Comment by UnconnectedBedna** [comment]
You are correct sir, it was a package thing on arch it seems. It did not reload the udev rules even though:
```
[2024-05-07T12:20:11+0200] [PACMAN] Running 'pacman -S solaar'
[2024-05-07T12:20:17+0200] [ALPM] transaction started
[2024-05-07T12:20:17+0200] [ALPM] installed python-pyudev (0.24.1-4)
[2024-05-07T12:20:17+0200] [ALPM] installed python-xlib (0.33-3)
[2024-05-07T12:20:17+0200] [ALPM] installed solaar (1.1.12-1)
[2024-05-07T12:20:17+0200] [ALPM] transaction completed
[2024-05-07T12:20:17+0200] [ALPM] running '30-systemd-udev-reload.hook'...
[2024-05-07T12:20:18+0200] [ALPM] running '30-systemd-update.hook'...
[2024-05-07T12:20:18+0200] [ALPM] running 'gtk-update-icon-cache.hook'...
[2024-05-07T12:20:18+0200] [ALPM] running 'update-desktop-database.hook'...
```

Instead of manually reloading I just rebooted, and that fixed it.
Strange...

**Comment by UnconnectedBedna** [comment]
I think you missed where I pointed out: `[2024-05-07T12:20:17+0200] [ALPM] running '30-systemd-udev-reload.hook'...` xD

Should have been reloaded right after installation, but it's all good...

**Comment by pfps** [comment]
Ah then the simplest remedy may have been to disconnect and reconnect the device or receiver.
