### ISSUE TITLE
Logitech G915 G keys error

### ISSUE THREAD

**Issue by mcmikecreations** [pwr-Solaar/Solaar#2499]
**Information**
- Solaar version: 1.1.9+dfsg-1
- Distribution: apt package for Ubuntu 23.10
- Kernel version: Linux 6.5.0-35-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
solaar version 1.1.9+dfsg-1

Lightspeed Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:C547
  Serial       : D685966B
    Firmware   : 04.02.B0009
    Bootloader : 02.09
    Other      : 7B.3C
  Has 1 paired device(s) out of a maximum of 2.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=23

  1: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
     Device path  : None
     WPID         : 407C
     Codename     : G915 KEYBOARD
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: 5D323A2E
     Model ID:      B354407CC33E
     Unit ID:       5D323A2E
        Bootloader: BOT 77.04.B0042
             Other: 
          Firmware: MPK 09.04.B0042
             Other: 
             Other: 
     The power switch is located on the top left corner.
     Supports 38 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BOT 77.04.B0042 00008A23A76B
            Firmware: Other   
            Firmware: Firmware MPK 09.04.B0042 407C8A23A76B
            Firmware: Other   
            Firmware: Other   
            Unit ID: 5D323A2E  Model ID: B354407CC33E  Transport IDs: {'btleid': 'B354', 'wpid': '407C', 'usbid': 'C33E'}
         3: DEVICE NAME            {0005} V0     
            Name: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: G915 KEYBOARD
         7: BATTERY VOLTAGE        {1001} V3     
            Battery: 60% 3921mV , discharging.
         8: CHANGE HOST            {1814} V1     
            Change Host        : 1:atkemper14
         9: HOSTS INFO             {1815} V1     
            Host 0 (paired): atkemper14
            Host 1 (unpaired): 
        10: RGB EFFECTS            {8071} V0     
        11: PER KEY LIGHTING V2    {8081} V2     
        12: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Diversion (saved): {Host Switch Channel 1:Regular, Host Switch Channel 2:Diverted}
            Key/Button Diversion        : {Host Switch Channel 1:Regular, Host Switch Channel 2:Diverted}
        13: REPORT HID USAGE       {1BC0} V1     
        14: ENCRYPTION             {4100} V0     
        15: KEYBOARD DISABLE BY USAGE {4522} V0     
        16: KEYBOARD LAYOUT 2      {4540} V0     
        17: GKEY                   {8010} V0     
            Divert G Keys (saved): True
            Divert G Keys        : False
        18: MKEYS                  {8020} V0     
            M-Key LEDs (saved): {M1:False, M2:False, M3:False}
            M-Key LEDs        : {M1:False, M2:False, M3:False}
        19: MR                     {8030} V0     
            MR-Key LED (saved): False
            MR-Key LED        : False
        20: BRIGHTNESS CONTROL     {8040} V0     
        21: ONBOARD PROFILES       {8100} V0     
            Device Mode: On-Board
            Onboard Profiles (saved): Enable
            Onboard Profiles        : Enable
        22: REPORT RATE            {8060} V0     
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        23: DFUCONTROL SIGNED      {00C2} V0     
        24: DFU                    {00D0} V3     
        25: DEVICE RESET           {1802} V0    internal, hidden 
        26: unknown:1803           {1803} V0    internal, hidden 
        27: CONFIG DEVICE PROPS    {1806} V8    internal, hidden 
        28: unknown:1813           {1813} V0    internal, hidden 
        29: OOBSTATE               {1805} V0    internal, hidden 
        30: unknown:1830           {1830} V0    internal, hidden 
        31: unknown:1890           {1890} V9    internal, hidden 
        32: unknown:1891           {1891} V9    internal, hidden 
        33: unknown:18A1           {18A1} V0    internal, hidden 
        34: unknown:1E00           {1E00} V0    hidden 
        35: unknown:1EB0           {1EB0} V0    internal, hidden 
        36: unknown:1861           {1861} V0    internal, hidden 
        37: unknown:18B0           {18B0} V0    internal, hidden 
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: diverted
     Battery: 60% 3921mV , discharging.
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.9+dfsg-1
- _NAME: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, pointer_speed, dpi, speed-change, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4097
  _modelId: B354407CC33E
  _sensitive: {divert-gkeys: true, divert-keys: true, m-key-leds: false, mr-key-led: false, onboard_profiles: false}
  _serial: 5D323A2E
  _unitId: 5D323A2E
  _wpid: 407C
  change-host: null
  divert-gkeys: true
  divert-keys: {209: 0, 210: 1}
  m-key-leds: {1: false, 2: false, 4: false}
  mr-key-led: false
  onboard_profiles: 1
  report_rate: 1
```
</details>

- Errors or warrnings from Solaar:
**gotten from `solaar -ddd`**
```
2024-05-27 11:55:54,607,607    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (13) => r[11 01 1100 10000000000000000000000000000000]
2024-05-27 11:55:54,607,607    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,5D323A2E)>: notification for feature GKEY, report 0, data 10000000000000000000000000000000
2024-05-27 11:55:54,607,607    ERROR [ReceiverListener:hidraw2] logitech_receiver.listener: processing Notification(11,1,11,00,10000000000000000000000000000000)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 176, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 268, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 61, in process
    return _process_device_notification(device, status, notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 201, in _process_device_notification
    return _process_feature_notification(device, status, n, feature)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 448, in _process_feature_notification
    _diversion.process_notification(device, status, n, feature)
  File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 1374, in process_notification
    new_g_keys_down = _unpack('!4I', notification.data[:4])[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 16 bytes
2024-05-27 11:55:54,703,703    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (13) => r[11 01 1100 00000000000000000000000000000000]
2024-05-27 11:55:54,703,703    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,5D323A2E)>: notification for feature GKEY, report 0, data 00000000000000000000000000000000
2024-05-27 11:55:54,704,704    ERROR [ReceiverListener:hidraw2] logitech_receiver.listener: processing Notification(11,1,11,00,00000000000000000000000000000000)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 176, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 268, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 61, in process
    return _process_device_notification(device, status, notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 201, in _process_device_notification
    return _process_feature_notification(device, status, n, feature)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 448, in _process_feature_notification
    _diversion.process_notification(device, status, n, feature)
  File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 1374, in process_notification
    new_g_keys_down = _unpack('!4I', notification.data[:4])[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 16 bytes
```

**Describe the bug**
The app throws an error instead of properly handling me pressing the G key (G5 in the trace above). From what I assume, one error for pressing the key and one for releasing.

**To Reproduce**
1. Go to `solaar -ddd` with the keyboard plugged in.
2. Click on Divert G keys.
3. Maybe add a rule for that key?
4. See error in console

**Additional context**
Editing the "Host Switch Channel" doesn't affect the issue.

**Comment by pfps** [comment]
I think this is a known problem in older versions of Solaar.   Please try the current version and see whether the problem persists.   As you are running Solaar already you should be able to clone Solaar from this repository and run it from the download directory as `bin/solaar`.

**Comment by mcmikecreations** [comment]
Had some errors while doing a manual install, but adding the ppa with version 1.13 solved the issue. Thank you
