### ISSUE TITLE
Gesture button does not work

### ISSUE THREAD

**Issue by janekgithubek** [pwr-Solaar/Solaar#2525]
Hi,

Since some time (03.06.2024) on new build of solaar the gesture button does not work. Last working version 1.1.13-23-g104556e

My mouse is MX Master 3s

My rules.yaml
- Rule:
  - MouseGesture: Mouse Gesture Button
  - KeyPress:
    - F
    - click

So on any newer version than 1.1.13-23-g104556e, my configuration regarding gesture button does not work all other functions are working correctly.

**Comment by pfps** [comment]
Please post output of `solaar -ddd` when trying to perform the gesture.

**Comment by janekgithubek** [comment]
on Version 1.1.13-32-gdb93e9a got this error:
2024-06-13 15:19:47,100,100    DEBUG [SolaarListener:hidraw4] logitech_receiver.base: (17) => r[11 01 0900 00000000000000000000000000000000]
2024-06-13 15:19:47,101,101     INFO [SolaarListener:hidraw4] logitech_receiver.settings_templates: mouse gesture notification [NamedInt(195, 'Mouse Gesture Button')]
2024-06-13 15:19:47,101,101    ERROR [SolaarListener:hidraw4] logitech_receiver.listener: processing Notification(11,1,09,00,00000000000000000000000000000000)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/logitech_receiver/listener.py", line 153, in run
    self._notifications_callback(n)
  File "/usr/lib/python3.11/site-packages/solaar/listener.py", line 215, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/lib/python3.11/site-packages/logitech_receiver/notifications.py", line 55, in process
    return _process_device_notification(device, notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/notifications.py", line 157, in _process_device_notification
    handling_ret = device.handle_notification(n)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/device.py", line 505, in handle_notification
    ret = h(self, n)
          ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/logitech_receiver/settings.py", line 1501, in handler
    self.release_action()
  File "/usr/lib/python3.11/site-packages/logitech_receiver/settings_templates.py", line 819, in release_action
    notification = base._HIDPP_Notification(0, 0, 0, 0, payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logitech_receiver.base' has no attribute '_HIDPP_Notification'



On Working version just this info:
2024-06-13 15:24:23,639,639    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule(/home/user/.config/solaar/rules.yaml)[Rule[MouseGesture: Mouse Gesture Button, KeyPress: F click]]
2024-06-13 15:24:23,639,639    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule[MouseGesture: Mouse Gesture Button, KeyPress: F click]
2024-06-13 15:24:23,639,639    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: MouseGesture: Mouse Gesture Button
2024-06-13 15:24:23,640,640     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['F'] click, group 0, modifiers 16
2024-06-13 15:24:23,640,640    DEBUG [MainThread] logitech_receiver.diversion: uinput simulated input 1 42 1
2024-06-13 15:24:23,640,640    DEBUG [MainThread] logitech_receiver.diversion: uinput simulated input 1 33 1
2024-06-13 15:24:23,641,641    DEBUG [MainThread] logitech_receiver.diversion: uinput simulated input 1 33 0
2024-06-13 15:24:23,641,641    DEBUG [MainThread] logitech_receiver.diversion: uinput simulated input 1 42 0
F2024-06-13 15:24:23,651,651    DEBUG [MainThread] logitech_receiver.diversion: evaluating rules on Notification(11,1,09,00,00000000000000000000000000000000)

**Comment by pfps** [comment]
So it looks as if the most-recent version has the action working correctly, right?

**Comment by pfps** [comment]
Or is the working version you mention the older one?

**Comment by pfps** [comment]
PR #2526 should fix your problem.   Please give it a try.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2526, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2526/head:pull_2526
git checkout pull_2526
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2526
git fetch origin pull/2526/head
git reset --hard FETCH_HEAD
```

**Comment by janekgithubek** [comment]
That was it!! Thank you very much for quick fix!
