### ISSUE TITLE
"Exception: pairing failed: failed" when pairing logitech mx master 3s

### ISSUE THREAD

**Issue by jim4067** [pwr-Solaar/Solaar#2534]
**Information**

- Solaar version: `solaar 1.1.13`
- Distribution: `Pop OS`
- Kernel version: `Linux 6.9.3-76060903-generic x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
solaar version 1.1.13

Bolt Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C548
  Serial       : 36463033424332363535313036443435
  Has 0 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

```
</details>

 

- Errors or warrnings from Solaar:

```bash
Bolt Pairing: long-press the pairing key or button on your device (timing out in 30 seconds).
Bolt Pairing: discovered MX Master 3S
Bolt Pairing: press left, right, right, left, right, left, right, left, left, right
and then press left and right buttons simultaneously
solaar: error: Traceback (most recent call last):
  File "/home/jimii/Solaar/lib/solaar/cli/__init__.py", line 221, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/home/jimii/Solaar/lib/solaar/cli/pair.py", line 134, in run
    raise Exception(f"pairing failed: {error}")
Exception: pairing failed: failed
```

**Describe the bug**
Getting the error above when trying to pair MX Master 3s mouse using the bolt receiver

**To Reproduce**
1. Install solaar from git instruction, from tag 1.1.13
2. Try pairing new device(in my case mx master 3s)
3. After pressing click combinations it errors our with error shown above.

**Screenshots**
![image](https://github.com/pwr-Solaar/Solaar/assets/30603522/b147ffa5-1e23-4f83-8c3d-cf04e0a85cc1)

**Additional context**

**Comment by pfps** [comment]
I have been able to successfully pair.   The double press is rather finicky, if I remember correctly.

If you still can't pair, run Solaar with `-ddd` flag and post output

**Comment by jim4067** [comment]
Yes, It always fails at the last step. I've tried my hardest to be as precise as possible during the double press but nothing seems to work.

Here's the verbose output 

```bash
2024-06-24 12:31:35,858,858    DEBUG [MainThread] hidapi.udev: Starting dbus enumeration
2024-06-24 12:31:35,859,859    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:03:00.3/usb1/1-2/1-2:1.0/0003:0D62:06EB.0006/hidraw/hidraw5')
2024-06-24 12:31:35,966,966     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw5 BID 0003 VID 00000D62 PID 000006EB: Expecting 9 usages but got 257
2024-06-24 12:31:35,966,966    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:03:00.3/usb1/1-2/1-2:1.1/0003:0D62:06EB.0007/hidraw/hidraw6')
2024-06-24 12:31:35,967,967    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:03:00.3/usb1/1-2/1-2:1.2/0003:0D62:06EB.0008/hidraw/hidraw7')
2024-06-24 12:31:35,968,968    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:03:00.4/usb3/3-2/3-2:1.0/0003:046D:C548.0002/hidraw/hidraw1')
2024-06-24 12:31:35,969,969    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:03:00.4/usb3/3-2/3-2:1.1/0003:046D:C548.0003/hidraw/hidraw2')
2024-06-24 12:31:35,971,971    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:03:00.4/usb3/3-2/3-2:1.2/0003:046D:C548.0004/hidraw/hidraw3')
2024-06-24 12:31:35,972,972     INFO [MainThread] hidapi.udev: Found device /dev/hidraw3 BID 0003 VID 0000046D PID 0000C548 HID++ True True USB 2 2
2024-06-24 12:31:35,972,972     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw3
2024-06-24 12:31:35,972,972     INFO [MainThread] logitech_receiver.base: New lock 13
2024-06-24 12:31:35,972,972    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 83FB 000000]
2024-06-24 12:31:35,974,974    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 83FB 36463033424332363535313036443435]
2024-06-24 12:31:35,974,974    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 8003 FF0000]
2024-06-24 12:31:35,977,977    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 8F80 030200]
2024-06-24 12:31:35,977,977    DEBUG [MainThread] logitech_receiver.base: (13) device 0xFF error on request {8003}: 2 = invalid address
2024-06-24 12:31:35,977,977    DEBUG [MainThread] solaar.cli: [/dev/hidraw3] => <BoltReceiver(/dev/hidraw3,13)>
2024-06-24 12:31:35,977,977    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:03:00.4/usb3/3-2/3-2:1.3/0003:046D:C548.0005/hidraw/hidraw4')
2024-06-24 12:31:35,979,979    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/platform/AMDI0010:03/i2c-0/i2c-QXTP7868:00/0018:27C6:01E8.0001/hidraw/hidraw0')
2024-06-24 12:31:35,983,983     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw0 BID 0018 VID 000027C6 PID 000001E8: Expecting 64 usages but got 257
2024-06-24 12:31:35,983,983    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/virtual/misc/uhid/0005:0000:0000.0017/hidraw/hidraw8')
2024-06-24 12:31:35,984,984     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw8 BID 0005 VID 00000000 PID 00000000: Expecting 120 usages but got 121
2024-06-24 12:31:35,984,984    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 8100 000000]
2024-06-24 12:31:35,987,987    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 8100 000900]
2024-06-24 12:31:35,987,987    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 8102 000000]
2024-06-24 12:31:35,990,990    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 8102 000000]
2024-06-24 12:31:35,990,990    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 80C0 1E0100]
2024-06-24 12:31:35,993,993    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 5300 000000]
2024-06-24 12:31:35,993,993     INFO [MainThread] logitech_receiver.notifications: <BoltReceiver(/dev/hidraw3,13)>: discovery lock is open
2024-06-24 12:31:35,994,994    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 80C0 000000]
Bolt Pairing: long-press the pairing key or button on your device (timing out in 30 seconds).
2024-06-24 12:31:38,579,579    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4F00 0000100234B0983788BE3CD3010102C3]
2024-06-24 12:31:38,580,580    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4F00 00010C4D58204D617374657220335300]
Bolt Pairing: discovered MX Master 3S
2024-06-24 12:31:38,580,580    DEBUG [MainThread] logitech_receiver.base: (13) <= w[11 FF 82C1 0100983788BE3CD3020A000000000000]
2024-06-24 12:31:38,582,582    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 82C1 000000]
2024-06-24 12:31:38,583,583    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 5302 000000]
2024-06-24 12:31:38,583,583     INFO [MainThread] logitech_receiver.notifications: <BoltReceiver(/dev/hidraw3,13)>: discovery lock is closed
2024-06-24 12:31:38,584,584    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 5400 00983788BE3CD3000000000000000000]
2024-06-24 12:31:38,584,584     INFO [MainThread] logitech_receiver.notifications: <BoltReceiver(/dev/hidraw3,13)>: pairing lock is open
2024-06-24 12:31:40,678,678    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4D06 303030383938983788BE3CD300000000]
Bolt Pairing: press right, right, right, left, left, left, left, left, right, left
and then press left and right buttons simultaneously
2024-06-24 12:31:40,678,678    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E00 983788BE3CD300000000000000000000]
2024-06-24 12:31:45,863,863    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:46,215,215    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:46,724,724    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:47,707,707    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:48,413,413    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:49,193,193    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:49,890,890    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:50,842,842    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:51,915,915    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:52,545,545    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E01 983788BE3CD300000000000000000000]
2024-06-24 12:31:56,775,775    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 4E04 983788BE3CD300000000000000000000]
2024-06-24 12:31:56,798,798    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 5402 02983788BE3CD3000000000000000000]
2024-06-24 12:31:56,798,798     INFO [MainThread] logitech_receiver.notifications: <BoltReceiver(/dev/hidraw3,13)>: pairing lock is closed
2024-06-24 12:31:56,799,799  WARNING [MainThread] logitech_receiver.notifications: pairing error 2: failed
solaar: error: Traceback (most recent call last):
  File "/home/jimii/Solaar/lib/solaar/cli/__init__.py", line 221, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/home/jimii/Solaar/lib/solaar/cli/pair.py", line 134, in run
    raise Exception(f"pairing failed: {error}")
Exception: pairing failed: failed

```

**Comment by pfps** [comment]
Did you try pairing from the GUI?   Run Solaar as `solaar -ddd`, clidk on the Bolt receiver, and then on the Pair button.

I won't have access to a Bolt mouse for about a month so I can't test pairing out myself until then.

**Comment by pfps** [comment]
OK.   I'll see if I can trigger an error when I have access to the device.

Looking at the logs it appears that everything is going OK until the end.   There are ten button presses and then the termination press, but there is no information available about what buttons were pressed.

**Comment by chrisequalsdev** [comment]
I was able to pair a 3s on Ubuntu 22.04 with Solaar 1.1.1. Discovered this issue because I couldn't get it to detect but then realized I had to hold the pair button down. After that it was detected and I (somehow) got the key button sequence right the first time.

**Comment by MysticPyro91** [comment]
Late follow-up for anyone who lands here from a search: I hit this on an MX Master 4 (Solaar 1.1.20) and found the cause.

**The displayed click sequence has left and right inverted.** Click the *inverse* of what Solaar shows and it pairs first try.

The trace in this issue is consistent with that — passkey `000898` = `1110000010`, displayed as `right, right, right, left, left, left, left, left, right, left`, i.e. bit `1` mapped to `right`. The device appears to want bit `1` = **left**.

Worth noting the ten `4E01` events in the log above: the receiver *did* receive all ten bits plus the `4E04` terminator, then rejected them. So this was never a timing or "finicky double press" problem — the bits themselves were wrong. `4E01` carries no direction byte, so the receiver can only reject the whole passkey at the end, which makes a polarity bug look exactly like a mis-click.

Filed as #3290 with full packet traces of a failing and a succeeding attempt.
