### ISSUE TITLE
Help with diversion with g502 lightspeed

### ISSUE THREAD

**Issue by MrHillss** [pwr-Solaar/Solaar#2553]
Solaar version 1.1.13

Arch linux + KDE plasma on wayland (Nvidia GPU)
Kernel 6.9.9-arch1-1

- Output of `solaar show`:
<details>

```
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar version 1.1.13

Unifying Receiver
  Device path  : /dev/hidraw8
  USB id       : 046d:C52B
  Serial       : FDB69717
  C Pending    : ff
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 4 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=62

  1: Wireless Keyboard K360
     Device path  : /dev/hidraw9
     WPID         : 4004
     Codename     : K360
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Report Rate : 20ms
     Serial number: 902B2DE8
     Model ID:      000000000000
     Unit ID:       00000000
                 0: RQK 36.00.B0007
     The power switch is located on the top case.
     Supports 13 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V0     
            Firmware: Firmware RQK 36.00.B0007 4004
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Keyboard K360
            Kind: keyboard
         4: BATTERY STATUS         {1000} V0     
            Battery: 90%, discharging, next level 70%.
         5: unknown:1820           {1820} V0    hidden 
         6: REPROG CONTROLS        {1B00} V0     
         7: WIRELESS DEVICE STATUS {1D4B} V0     
         8: REMAINING PAIRING      {1DF0} V0    hidden 
            Remaining Pairings: 54
         9: unknown:1DF3           {1DF3} V0    hidden 
        10: FN INVERSION           {40A0} V0     
            Swap Fx function        : False
        11: ENCRYPTION             {4100} V0     
        12: KEYBOARD LAYOUT        {4520} V0     
     Battery: 90%, discharging, next level 70%.

  2: Wireless Mouse MX Master
     Device path  : /dev/hidraw10
     WPID         : 4041
     Codename     : MX Master
     Kind         : mouse
     Protocol     : HID++ 4.5
     Report Rate : 8ms
     Serial number: 2A7CEB05
     The power switch is located on the base.
     Battery: unknown (device is offline).

  3: Wireless Keyboard K360
     Device path  : /dev/hidraw11
     WPID         : 4004
     Codename     : K360
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Report Rate : 20ms
     Serial number: C7C1AB81
     The power switch is located on the top case.
     Battery: unknown (device is offline).

  4: Wireless Keyboard K360
     Device path  : /dev/hidraw12
     WPID         : 4004
     Codename     : K360
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Report Rate : 20ms
     Serial number: ABF349DA
     The power switch is located on the top case.
     Battery: unknown (device is offline).

Lightspeed Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C53A
  Serial       : D81197ED
  C Pending    : ff
    Firmware   : 40.03.B0014
    Bootloader : 02.09
    Other      : AA.CA
  Has 2 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G502 Gaming Mouse
     Device path  : /dev/hidraw4
     WPID         : 407F
     Codename     : G502
     Kind         : mouse
     Protocol     : HID++ 4.2
     Report Rate : 1ms
     Serial number: 96168826
     Model ID:      407FC08D0000
     Unit ID:       96168826
                 1: BOT 92.00.B0008
                 0: MPM 17.00.B0008
                 3: 
     The power switch is located on the base.
     Supports 30 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BOT 92.00.B0008 AAEF21F1FA5F
            Firmware: Firmware MPM 17.00.B0008 407F21F1FA5F
            Firmware: Other   
            Unit ID: 96168826  Model ID: 407FC08D0000  Transport IDs: {'wpid': '407F', 'usbid': 'C08D'}
         3: DEVICE NAME            {0005} V0     
            Name: G502 LIGHTSPEED Wireless Gaming Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
            Configuration: 11000000000000000000000000000000
         6: BATTERY VOLTAGE        {1001} V2     
            Battery: 80% 4054mV , discharging.
         7: COLOR LED EFFECTS      {8070} V4     
            LED Control (saved): Device
            LED Control        : Device
            LEDs Primary        : None
            LEDs Logo        : None
         8: LED CONTROL            {1300} V0     
         9: ONBOARD PROFILES       {8100} V0     
            Device Mode: On-Board
            Onboard Profiles (saved): Profile 1
            Onboard Profiles        : Profile 1
        10: MOUSE BUTTON SPY       {8110} V0     
        11: REPORT RATE            {8060} V0     
            Report Rate: 1ms
            Report Rate (saved): 1ms
            Report Rate        : 1ms
        12: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 3200
            Sensitivity (DPI)        : 3200
        13: DEVICE RESET           {1802} V0    internal, hidden 
        14: unknown:1803           {1803} V0    internal, hidden 
        15: OOBSTATE               {1805} V0    internal, hidden 
        16: CONFIG DEVICE PROPS    {1806} V4    internal, hidden 
        17: unknown:1811           {1811} V0    internal, hidden 
        18: unknown:1830           {1830} V0    internal, hidden 
        19: unknown:1890           {1890} V4    internal, hidden 
        20: unknown:1891           {1891} V4    internal, hidden 
        21: unknown:18A1           {18A1} V0    internal, hidden 
        22: unknown:1801           {1801} V0    internal, hidden 
        23: unknown:18B1           {18B1} V0    internal, hidden 
        24: unknown:1DF3           {1DF3} V0    internal, hidden 
        25: unknown:1E00           {1E00} V0    hidden 
        26: unknown:1EB0           {1EB0} V0    internal, hidden 
        27: unknown:1863           {1863} V0    internal, hidden 
        28: unknown:1E22           {1E22} V0    internal, hidden 
        29: HIRES WHEEL            {2121} V0     
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
     Battery: 80% 4054mV , discharging.

```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.13
- _NAME: G502 Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode, report_rate_extended, pointer_speed,
    dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed,
    rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer, adc_power_management]
  _battery: 4097
  _modelId: 407FC08D0000
  _sensitive: {dpi: true, hires-scroll-mode: false, led_control: false, report_rate: true}
  _serial: '96168826'
  _unitId: '96168826'
  _wpid: 407F
  dpi: 3200
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  led_control: 0
  onboard_profiles: 1
  report_rate: 1
- _NAME: Wireless Keyboard K360
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_,
    brightness_control, per-key-lighting, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys, crown-smooth, divert-crown,
    divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: Wireless Keyboard K360
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 902B2DE8
  _unitId: 902B2DE8
  _wpid: '4004'
  fn-swap: false
```
</details>

- Errors or warrnings from Solaar:

<details>

2024-07-15 18:22:41,366,366    ERROR [SolaarListener:hidraw3] logitech_receiver.base: (26) device 1 error on feature request {0B2F}: 2 = invalid argument
2024-07-15 18:22:41,366,366  WARNING [SolaarListener:hidraw3] logitech_receiver.settings: report_rate: error applying 1 so ignore it (<Device(1,407F,G502 Gaming Mouse,96168826)>): FeatureCallError({'number': 1, 'request': 2863, 'error': 2, 'params': b'\x01'})
2024-07-15 18:22:41,504,504  WARNING [SolaarListener:hidraw3] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,T21)> device 7 error read pairing information - non-unifying
2024-07-15 18:22:41,504,504  WARNING [SolaarListener:hidraw3] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,T21)>: looked for device 7, not found
2024-07-15 18:22:41,504,504  WARNING [SolaarListener:hidraw3] solaar.listener: <LightspeedReceiver(/dev/hidraw3,T21)>: received Notification(10,7,41,0C,B95F40) for invalid device 7: None
2024-07-15 18:22:42,628,628    ERROR [SolaarListener:hidraw8] logitech_receiver.listener: processing Notification(10,1,41,04,310440)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/logitech_receiver/listener.py", line 153, in run
    self._notifications_callback(n)
  File "/usr/lib/python3.12/site-packages/solaar/listener.py", line 215, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/lib/python3.12/site-packages/logitech_receiver/notifications.py", line 55, in process
    return _process_device_notification(device, notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/notifications.py", line 164, in _process_device_notification
    return _process_hidpp10_notification(device, n)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/notifications.py", line 268, in _process_hidpp10_notification
    device.changed(active=link_established)
  File "/usr/lib/python3.12/site-packages/logitech_receiver/device.py", line 412, in changed
    settings.apply_all_settings(self)
  File "/usr/lib/python3.12/site-packages/logitech_receiver/settings.py", line 1563, in apply_all_settings
    for s in device.settings:
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/device.py", line 339, in settings
    raise e
  File "/usr/lib/python3.12/site-packages/logitech_receiver/device.py", line 335, in settings
    setting = sclass.build(self)
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/settings.py", line 93, in build
    assert rw.kind == FeatureRW.kind
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
2024-07-15 18:38:17,337,337  WARNING [SolaarListener:hidraw3] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,T21)> device 7 error read pairing information - non-unifying
2024-07-15 18:38:17,338,338  WARNING [SolaarListener:hidraw3] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,T21)>: looked for device 7, not found
2024-07-15 18:38:17,338,338  WARNING [SolaarListener:hidraw3] solaar.listener: <LightspeedReceiver(/dev/hidraw3,T21)>: received Notification(10,7,41,0C,B95F40) for invalid device 7: None

2024-07-15 18:42:08,205,205    ERROR [SolaarListener:hidraw3] logitech_receiver.base: (26) device 1 error on feature request {0B28}: 2 = invalid argument
2024-07-15 18:42:08,205,205  WARNING [SolaarListener:hidraw3] logitech_receiver.settings: report_rate: error applying 1 so ignore it (<Device(1,407F,G502 Gaming Mouse,96168826)>): FeatureCallError({'number': 1, 'request': 2856, 'error': 2, 'params': b'\x01'})
2024-07-15 18:42:08,350,350  WARNING [SolaarListener:hidraw3] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,T21)> device 7 error read pairing information - non-unifying
2024-07-15 18:42:08,350,350  WARNING [SolaarListener:hidraw3] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,T21)>: looked for device 7, not found
2024-07-15 18:42:08,350,350  WARNING [SolaarListener:hidraw3] solaar.listener: <LightspeedReceiver(/dev/hidraw3,T21)>: received Notification(10,7,41,0C,B95F40) for invalid device 7: None
2024-07-15 18:42:09,159,159    ERROR [SolaarListener:hidraw8] logitech_receiver.listener: processing Notification(10,1,41,04,310440)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/logitech_receiver/listener.py", line 153, in run
    self._notifications_callback(n)
  File "/usr/lib/python3.12/site-packages/solaar/listener.py", line 215, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/lib/python3.12/site-packages/logitech_receiver/notifications.py", line 55, in process
    return _process_device_notification(device, notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/notifications.py", line 164, in _process_device_notification
    return _process_hidpp10_notification(device, n)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/notifications.py", line 268, in _process_hidpp10_notification
    device.changed(active=link_established)
  File "/usr/lib/python3.12/site-packages/logitech_receiver/device.py", line 412, in changed
    settings.apply_all_settings(self)
  File "/usr/lib/python3.12/site-packages/logitech_receiver/settings.py", line 1563, in apply_all_settings
    for s in device.settings:
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/device.py", line 339, in settings
    raise e
  File "/usr/lib/python3.12/site-packages/logitech_receiver/device.py", line 335, in settings
    setting = sclass.build(self)
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/settings.py", line 93, in build
    assert rw.kind == FeatureRW.kind
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-07-15 18:38:53,682,682  WARNING [MainThread] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,18)> device 2 error read pairing information - non-unifying
2024-07-15 18:38:53,682,682  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,18)>: looked for device 2, not found
2024-07-15 18:38:53,737,737  WARNING [MainThread] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,18)> device 3 error read pairing information - non-unifying
2024-07-15 18:38:53,737,737  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,18)>: looked for device 3, not found
2024-07-15 18:38:53,792,792  WARNING [MainThread] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,18)> device 4 error read pairing information - non-unifying
2024-07-15 18:38:53,792,792  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,18)>: looked for device 4, not found
2024-07-15 18:38:53,847,847  WARNING [MainThread] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,18)> device 5 error read pairing information - non-unifying
2024-07-15 18:38:53,847,847  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,18)>: looked for device 5, not found
2024-07-15 18:38:53,902,902  WARNING [MainThread] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,18)> device 6 error read pairing information - non-unifying
2024-07-15 18:38:53,902,902  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,18)>: looked for device 6, not found
2024-07-15 18:38:53,957,957  WARNING [MainThread] logitech_receiver.receiver: register new device failed for <LightspeedReceiver(/dev/hidraw3,18)> device 7 error read pairing information - non-unifying
2024-07-15 18:38:53,957,957  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,18)>: looked for device 7, not found

</details>

**Describe the bug**
I've seen other people using solaar just fine with this mouse, but i can't get it to work.
The problem is that i don't see how to divert buttons so that solaar can read them.
In the screenshots i've seen there is an option to divert buttons, but i can only divert the scroll wheel.
Is the g502 unsupported on wayland?

**Screenshots**
![2024-07-15-182504_screenshot](https://github.com/user-attachments/assets/6b8731e1-a137-4bd4-a182-d52f4c96c313)

**Comment by pfps** [comment]
This mouse does not have the ability to divert buttons.  This is unrelated to whether you are on Wayland or X11.

**Comment by MrHillss** [comment]
> This mouse does not have the ability to divert buttons. This is unrelated to whether you are on Wayland or X11.

So I cannot remap buttons at all?

**Comment by pfps** [comment]
Not using Solaar.   You could use facilities of the Linux input system, but that would modify all the mice you are using.
