### ISSUE TITLE
Fx swap not working after some time

### ISSUE THREAD

**Issue by Bryan2333** [pwr-Solaar/Solaar#2567]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.1.13
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 6.9.7-zen1-1-zen-cjktty x86_64 GNU/Linux`
- Output of `solaar show`: 

<details>

```
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar version 1.1.13


Signature Plus M750
     Device path  : /dev/hidraw2
     USB id       : 046d:B02C
     Codename     : Logi M750
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B02C00000000
     Unit ID:       67BCC075
                 1: BL1 40.02.B0013
                 0: RBM 18.02.B0013
                 3: 
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BL1 40.02.B0013 B02CB0706FCD
            Firmware: Firmware RBM 18.02.B0013 B02CB0706FCD
            Firmware: Other   
            Unit ID: 67BCC075  Model ID: B02C00000000  Transport IDs: {'btleid': 'B02C'}
         3: DEVICE NAME            {0005} V0     
            Name: Signature Plus M750
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
            Configuration: 11000000000000000000000000000000
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: Logi M750
         8: UNIFIED BATTERY        {1004} V3     
            Battery: 95%, discharging.
         9: REPROG CONTROLS V4     {1B04} V5     
            按键/按钮操作 (saved): {Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:DPI Switch}
            按键/按钮操作        : {Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:DPI Switch}
            按键/按钮改道 (saved): {Middle Button:常规, Back Button:常规, Forward Button:常规, DPI Switch:常规}
            按键/按钮改道        : {Middle Button:常规, Back Button:常规, Forward Button:常规, DPI Switch:常规}
        10: CHANGE HOST            {1814} V1     
            改变主机        : 1:Bryan-YOGA14s
        11: HOSTS INFO             {1815} V2     
            Host 0 (paired): Bryan-YOGA14s
            Host 1 (paired): Bryan-YOGA14s
            Host 2 (unpaired): 
        12: XY STATS               {2250} V1     
        13: LOWRES WHEEL           {2130} V0     
            Wheel Reports: HID
            滚轮改道 (saved): False
            滚轮改道        : False
        14: ADJUSTABLE DPI         {2201} V2     
            灵敏度 (DPI) (saved): 1300
            灵敏度 (DPI)        : 1300
        15: DFUCONTROL             {00C3} V0     
        16: DEVICE RESET           {1802} V0    internal, hidden, unknown:000010 
        17: unknown:1803           {1803} V0    internal, hidden, unknown:000010 
        18: CONFIG DEVICE PROPS    {1806} V8    internal, hidden, unknown:000010 
        19: unknown:1816           {1816} V0    internal, hidden, unknown:000010 
        20: OOBSTATE               {1805} V0    internal, hidden 
        21: unknown:1830           {1830} V0    internal, hidden, unknown:000010 
        22: unknown:1891           {1891} V7    internal, hidden, unknown:000008 
        23: unknown:18A1           {18A1} V0    internal, hidden, unknown:000010 
        24: unknown:1E00           {1E00} V0    hidden 
        25: unknown:1E02           {1E02} V0    internal, hidden 
        26: unknown:1E22           {1E22} V1    internal, hidden, unknown:000010 
        27: unknown:1602           {1602} V0     
        28: unknown:1EB0           {1EB0} V0    internal, hidden, unknown:000010 
        29: unknown:1861           {1861} V1    internal, hidden, unknown:000010 
        30: unknown:18B1           {18B1} V0    internal, hidden, unknown:000010 
        31: unknown:920A           {920A} V0    internal, hidden, unknown:000010 
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: DPI Switch                , default: DPI Switch                  => DPI Switch                
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 95%, discharging.

solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/solaar/cli/__init__.py", line 221, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.12/site-packages/solaar/cli/show.py", line 327, in run
    _print_device(d)
  File "/usr/lib/python3.12/site-packages/solaar/cli/show.py", line 101, in _print_device
    print(f"{dev.name}")
             ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/logitech_receiver/device.py", line 204, in name
    return self._name or self._codename or ("Unknown device %s" % (self.wpid or hex(self.product_id)[2:].upper()))
                                                                                ^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer


```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.13
- _NAME: Signature Plus M750
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting,
    fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures,
    gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B02C00000000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _unitId: 67BCC075
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 253: 0}
  dpi: 1300
  lowres-scroll-mode: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86, 253: 253}
- _NAME: K780 Multi-Device Wireless Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_,
    brightness_control, per-key-lighting, reprogrammable-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert,
    gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B33B405B0000
  _sensitive: {fn-swap: false, multiplatform: false}
  _unitId: BE529ECE
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 189: 0, 190: 0, 191: 0, 192: 0, 193: 0, 194: 0, 209: 0, 210: 0, 211: 0, 212: 0, 213: 0, 214: 0}
  fn-swap: false
  multiplatform: 0
  persistent-remappable-keys: null

```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
The Fn key swap function is not working on my K780 keyboard after some time. I quit the solaar and launch it again, it does not recognize K780 anymore until I reboot my computer.

**To Reproduce**
1. Quit the solaar
2. Launch the solaar again

**Screenshots**

**Additional context**

**Comment by Bryan2333** [comment]
I tried to use the solaar from the git repo. The solaar find the keyboard, but treat it as unknown device. And It also reports that my keyboard is offline, however my keyboard is working fine except fx swap.

Here is the output from the `solaar show`:

```
solaar version 1.1.13-43-gce197b70


Signature Plus M750
     Device path  : /dev/hidraw2
     USB id       : 046d:B02C
     Codename     : Logi M750
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B02C00000000
     Unit ID:       67BCC075
                 1: BL1 40.02.B0013
                 0: RBM 18.02.B0013
                 3: 
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BL1 40.02.B0013 B02CB0706FCD
            Firmware: Firmware RBM 18.02.B0013 B02CB0706FCD
            Firmware: Other   
            Unit ID: 67BCC075  Model ID: B02C00000000  Transport IDs: {'btleid': 'B02C'}
         3: DEVICE NAME            {0005} V0     
            Name: Signature Plus M750
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
            Configuration: 11000000000000000000000000000000
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: Logi M750
         8: UNIFIED BATTERY        {1004} V3     
            Battery: 95%, 0.
         9: REPROG CONTROLS V4     {1B04} V5     
            按键/按钮操作 (saved): {Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:DPI Switch}
            按键/按钮操作        : {Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:DPI Switch}
            按键/按钮改道 (saved): {Middle Button:常规, Back Button:常规, Forward Button:常规, DPI Switch:常规}
            按键/按钮改道        : {Middle Button:常规, Back Button:常规, Forward Button:常规, DPI Switch:常规}
        10: CHANGE HOST            {1814} V1     
            改变主机        : 1:Bryan-YOGA14s
        11: HOSTS INFO             {1815} V2     
            Host 0 (paired): Bryan-YOGA14s
            Host 1 (paired): Bryan-YOGA14s
            Host 2 (unpaired): 
        12: XY STATS               {2250} V1     
        13: LOWRES WHEEL           {2130} V0     
            Wheel Reports: HID
            滚轮改道 (saved): False
            滚轮改道        : False
        14: ADJUSTABLE DPI         {2201} V2     
            灵敏度 (DPI) (saved): 1300
            灵敏度 (DPI)        : 1300
        15: DFUCONTROL             {00C3} V0     
        16: DEVICE RESET           {1802} V0    internal, hidden, unknown:000010 
        17: unknown:1803           {1803} V0    internal, hidden, unknown:000010 
        18: CONFIG DEVICE PROPS    {1806} V8    internal, hidden, unknown:000010 
        19: unknown:1816           {1816} V0    internal, hidden, unknown:000010 
        20: OOBSTATE               {1805} V0    internal, hidden 
        21: unknown:1830           {1830} V0    internal, hidden, unknown:000010 
        22: unknown:1891           {1891} V7    internal, hidden, unknown:000008 
        23: unknown:18A1           {18A1} V0    internal, hidden, unknown:000010 
        24: unknown:1E00           {1E00} V0    hidden 
        25: unknown:1E02           {1E02} V0    internal, hidden 
        26: unknown:1E22           {1E22} V1    internal, hidden, unknown:000010 
        27: unknown:1602           {1602} V0     
        28: unknown:1EB0           {1EB0} V0    internal, hidden, unknown:000010 
        29: unknown:1861           {1861} V1    internal, hidden, unknown:000010 
        30: unknown:18B1           {18B1} V0    internal, hidden, unknown:000010 
        31: unknown:920A           {920A} V0    internal, hidden, unknown:000010 
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: DPI Switch                , default: DPI Switch                  => DPI Switch                
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 95%, 0.

Unknown device B33B
     Device path  : /dev/hidraw3
     USB id       : 046d:B33B
     Codename     : ?? (B33B)
     Kind         : ?
     Protocol     : unknown (device is offline)
     Serial number: 
     Battery: unknown (device is offline).
```

**Comment by pfps** [comment]
Solaar can only contact devices when they are active.  Run `solaar show` when you are typing at that keyboard.  The error on the first `solaar show` appears to be from a bug in 1.1.13 that has since been fixed.

**Comment by Bryan2333** [comment]
I tried running `solaar show` while typing in another terminal tab. Now the solaar from the git repo can recognize the keyboard normally.

**Comment by Bryan2333** [comment]
Yes, I launch the solaar again after that and everything works fine now.

**Comment by Bryan2333** [comment]
The issue happen again today, but this time no matter how I type while I run `solaar show`, it just reports 

```
Unknown device B33B
     Device path  : /dev/hidraw3
     USB id       : 046d:B33B
     Codename     : ?? (B33B)
     Kind         : ?
     Protocol     : unknown (device is offline)
     Serial number: 
     Battery: unknown (device is offline).
```
