### ISSUE TITLE
Error pairing with unusual receiver

### ISSUE THREAD

**Issue by carabao72** [pwr-Solaar/Solaar#2638]
Hello
![Copie d'écran_20241017_083019](https://github.com/user-attachments/assets/65a5e5e9-b995-441d-979f-27b3440af5a1)

**Information**

Unable to paring my master mx mouse and k800 keyboard

- Solaar version : solaar 1.1.13
- Distribution: fedora 40 (kde) wayland
- kernel: Linux 6.11.3-200.fc40.x86_64 x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
sudo solaar pair
Pairing: turn your new device on (timing out in 30 seconds).
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/solaar/cli/__init__.py", line 221, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.12/site-packages/solaar/cli/pair.py", line 134, in run
    raise Exception(f"pairing failed: {error}")
Exception: pairing failed: device timeout
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
no file config.yaml
no file config.json
```
</details>

- Errors or warrnings from Solaar:

$mm solaar
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed

$mm 
![Copie d'écran_20241017_083019](https://github.com/user-attachments/assets/46f48acf-64dd-4945-a531-8cccc31d3142)
sudo solaar -dd
2024-10-17 08:24:50,421,421     INFO [MainThread] solaar.gtk: version 1.1.13, language fr_FR (UTF-8)
2024-10-17 08:24:50,425,425     INFO [MainThread] solaar.dbus: connected to system dbus, watching for suspend/resume events
2024-10-17 08:24:50,586,586     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2024-10-17 08:24:50,641,641     INFO [MainThread] solaar.listener: starting receiver listening threads
2024-10-17 08:24:50,838,838     INFO [MainThread] hidapi.udev: Found device /dev/hidraw1 BID 0003 VID 0000046D PID 0000C52B HID++ True True USB 2 2
2024-10-17 08:24:50,838,838     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw1', bus_id=3, vendor_id='046D', product_id='C52B', interface=2, driver='logitech-djreceiver', manufacturer=None, product=None, serial='', release=None, isDevice=None, hidpp_short=True, hidpp_long=True)
2024-10-17 08:24:50,838,838     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw1
2024-10-17 08:24:50,839,839     INFO [MainThread] logitech_receiver.base: New lock 14
2024-10-17 08:24:50,845,845     INFO [SolaarListener:hidraw1] logitech_receiver.listener: started with <RécepteurUnifying(/dev/hidraw1,T14)> (14)
2024-10-17 08:24:50,845,845     INFO [SolaarListener:hidraw1] solaar.listener: <RécepteurUnifying(/dev/hidraw1,T14)>: notifications listener has started (14)
2024-10-17 08:24:50,846,846     INFO [SolaarListener:hidraw1] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw1)>
2024-10-17 08:24:50,846,846     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw0 BID 0003 VID 00001770 PID 0000FF00: Expecting 7 usages but got 1
2024-10-17 08:24:50,851,851     INFO [SolaarListener:hidraw1] logitech_receiver.receiver: <RécepteurUnifying(/dev/hidraw1,T14)>: receiver notifications enabled => ('wireless', 'software present')
2024-10-17 08:24:50,853,853     INFO [SolaarListener:hidraw1] solaar.listener: status_changed <RécepteurUnifying(/dev/hidraw1,T14)>: present (0) 
2024-10-17 08:24:56,976,976     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw1
2024-10-17 08:24:59,839,839     INFO [SolaarListener:hidraw1] logitech_receiver.notifications: <RécepteurUnifying(/dev/hidraw1,T14)>: le verrou de jumelage est ouvert
2024-10-17 08:24:59,839,839     INFO [SolaarListener:hidraw1] solaar.listener: status_changed <RécepteurUnifying(/dev/hidraw1,T14)>: present (1) le verrou de jumelage est ouvert
2024-10-17 08:25:08,315,315     INFO [SolaarListener:hidraw1] logitech_receiver.notifications: <RécepteurUnifying(/dev/hidraw1,T14)>: le verrou de jumelage est fermé
2024-10-17 08:25:08,315,315  WARNING [SolaarListener:hidraw1] logitech_receiver.notifications: pairing error 1: device timeout
2024-10-17 08:25:08,315,315     INFO [SolaarListener:hidraw1] solaar.listener: status_changed <RécepteurUnifying(/dev/hidraw1,T14)>: present (1) le verrou de jumelage est fermé
2024-10-17 08:25:24,904,904    ERROR [MainThread] solaar.ui.notify: showing <Notify.Notification object at 0x7f616b2498c0 (NotifyNotification at 0x564d855c0900)>
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/solaar/ui/notify.py", line 139, in show
    n.show()
gi.repository.GLib.GError: g-io-error-quark: Erreur lors de l’appel de StartServiceByName pour org.freedesktop.Notifications : Le délai d’attente est dépassé (24)
2024-10-17 08:25:49,937,937    ERROR [MainThread] solaar.ui.notify: showing <Notify.Notification object at 0x7f616b2498c0 (NotifyNotification at 0x564d855c0900)>
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/solaar/ui/notify.py", line 139, in show
    n.show()
gi.repository.GLib.GError: g-io-error-quark: Erreur lors de l’appel de StartServiceByName pour org.freedesktop.Notifications : Le délai d’attente est dépassé (24)
^CThread 0x00007f61610006c0 (most recent call first):
  File "/usr/lib/python3.12/site-packages/hidapi/udev.py", line 421 in read
  File "/usr/lib/python3.12/site-packages/logitech_receiver/base.py", line 293 in _read
  File "/usr/lib/python3.12/site-packages/logitech_receiver/base.py", line 264 in read
  File "/usr/lib/python3.12/site-packages/logitech_receiver/listener.py", line 142 in run
  File "/usr/lib64/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/lib64/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x00007f61694006c0 (most recent call first):
  File "/usr/lib64/python3.12/threading.py", line 355 in wait
  File "/usr/lib64/python3.12/queue.py", line 171 in get
  File "/usr/lib/python3.12/site-packages/solaar/tasks.py", line 56 in run
  File "/usr/lib64/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/lib64/python3.12/threading.py", line 1032 in _bootstrap

Current thread 0x00007f617d1e6740 (most recent call first):
  File "/usr/lib/python3.12/site-packages/solaar/gtk.py", line 136 in _handlesig
  File "/usr/lib64/python3.12/site-packages/gi/_ossighelper.py", line 92 in signal_notify
  File "/usr/lib64/python3.12/site-packages/gi/overrides/Gio.py", line 42 in run
  File "/usr/lib/python3.12/site-packages/solaar/ui/__init__.py", line 104 in run_loop
  File "/usr/lib/python3.12/site-packages/solaar/gtk.py", line 181 in main
  File "/usr/bin/solaar", line 56 in <module>
solaar: exit due to keyboard interrupt

(solaar:19376): GLib-GIO-CRITICAL **: 08:26:18.871: Error while sending AddMatch() message: La connexion est fermée

(solaar:19376): GLib-GIO-CRITICAL **: 08:26:18.872: Error while sending GetNameOwner() message: La connexion est fermée

(solaar:19376): GLib-GIO-CRITICAL **: 08:26:18.872: Error while sending AddMatch() message: La connexion est fermée

(solaar:19376): libappindicator-WARNING **: 08:26:18.872: Unable to send signal for NewStatus: La connexion est fermée

**Describe the bug**

**To Reproduce**
start solaar
initiate the pairing
Turn on mouse and keyboard
error 

Thank you

**Comment by pfps** [comment]
Solaar just sets up the receiver to listen for new devices.  Everything else happens at the hardware level.  So there are lots of things that might prevent pairing that cannot be affected by Solaar.   

It looks as if you are running Solaar as root.  That is not recommended.

Please provide the output of `solaar show`, as requested in the bug template.

**Comment by carabao72** [comment]
solaar show
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
cannot create uinput device: "/dev/uinput" cannot be opened for writing
solaar version 1.1.13

Récepteur Unifying
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : 00000000
  C Pending    : ff
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 0 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

I started as root because I had this error message

_rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
cannot create uinput device: "/dev/uinput" cannot be opened for writing_

**Comment by pfps** [comment]
The message that you received should be addressed by installing the Solaar udev rule for Wayland.

Receivers with ID C52B should be able to pair with different devices, and several devices at the same time.  But Solaar is saying that the receiver can only one paired device, which is unexpected.   

Please run `solaar -ddd show` to show the complete interaction with the device.

**Comment by pfps** [comment]
The log is showing that Solaar is querying the receiver and getting strange results.   In particular, the receiver is responding that it can pair with 0 devices.  Solaar doesn't believe that and uses 1 instead, but it looks as if 0 is correct and the receiver will not pair with anything.   I don't know how the receiver ended up in this state.

If you have access to a Windows machine install the Logitech software on that machine, plug in the receiver, and try to pair there.  Please reply whether that works and, if it does, put the receiver back on a Linux machine, run `solaar -ddd show`, and post the results.

**Comment by carabao72** [comment]
I just tested the installation of the unyfing receiver on my computer running with windows 10.

The receiver seems to be recognized randomly, when I move it in the usb port. Bad contact in the receiver? Is it possible that the receiver is defective by being constantly plugged into a usb port even when I carry the PC in a backpack.

**Comment by pfps** [comment]
That's possible.  I don't think that there is anything that can be done on the Solaar end.

**Comment by carabao72** [comment]
Well, direction my supplier then. Sorry for the inconvenience

**Comment by carabao72** [comment]
Hello, I will contact you again, after testing the new Unifying receiver on my PC, everything works perfectly. Sorry for the inconvenience.
