### ISSUE TITLE
G733 has a new hardware ID

### ISSUE THREAD

**Issue by tom-ricci** [pwr-Solaar/Solaar#2658]
**Information**

- Solaar version: 1.1.13
- Distribution: Ubuntu 24.04
- Kernel version (ex. `uname -srmo`): `Linux 6.8.0-47-generic x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
G733 Gaming Headset
     Device path  : /dev/hidraw0
     USB id       : 046d:0B1F
     Codename     : G733
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 221, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 327, in run
    _print_device(d)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 108, in _print_device
    print("     Kind         :", dev.kind)
                                 ^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 234, in kind
    self._kind = _hidpp20.get_kind(self)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/hidpp20.py", line 1432, in get_kind
    return KIND_MAP[DEVICE_KIND[kind]]
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: None
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present): Neither file exists on my system
- Errors or warrnings from Solaar:
<details>

```
2024-11-02 04:30:02,615,615     INFO [MainThread] solaar.gtk: version 1.1.13, language en_US (UTF-8)
2024-11-02 04:30:02,616,616     INFO [MainThread] solaar.dbus: connected to system dbus, watching for suspend/resume events
2024-11-02 04:30:02,652,652     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2024-11-02 04:30:02,658,658  WARNING [MainThread] solaar.ui.icons: failed to detect icons
2024-11-02 04:30:02,696,696     INFO [MainThread] solaar.listener: starting receiver listening threads
2024-11-02 04:30:02,807,807     INFO [MainThread] hidapi.udev: Found device /dev/hidraw0 BID 0003 VID 0000046D PID 00000B1F HID++ False True USB 3 None
2024-11-02 04:30:02,807,807     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw0', bus_id=3, vendor_id='046D', product_id='0B1F', interface=3, driver='hid-generic', manufacturer=None, product=None, serial='0000000000000000', release=None, isDevice=True, hidpp_short=False, hidpp_long=True)
2024-11-02 04:30:02,807,807     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw0
2024-11-02 04:30:02,807,807     INFO [MainThread] logitech_receiver.base: New lock 13
2024-11-02 04:30:02,810,810     INFO [SolaarListener:hidraw0] logitech_receiver.listener: started with <Device(255,0B1F,?,)> (13)
2024-11-02 04:30:02,810,810     INFO [SolaarListener:hidraw0] solaar.listener: <Device(255,0B1F,?,)>: notifications listener has started (13)
2024-11-02 04:30:02,810,810     INFO [SolaarListener:hidraw0] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw0)>
2024-11-02 04:30:02,811,811     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw2 BID 0003 VID 0000093A PID 0000821D: VariableItem.__init__() missing 1 required positional argument: 'logical_min'
2024-11-02 04:30:02,813,813     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw4 BID 0003 VID 00003434 PID 0000D030: Expecting 20 usages but got 256
2024-11-02 04:30:02,816,816     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw5 BID 0003 VID 00003434 PID 0000D030: Expecting 3 usages but got 6
2024-11-02 04:30:02,818,818     INFO [SolaarListener:hidraw0] solaar.listener: status_changed for unknown device: None
Exception in thread SolaarListener:hidraw0:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 133, in run
    self.has_started()
  File "/usr/share/solaar/lib/solaar/listener.py", line 79, in has_started
    self._status_changed(self.receiver)
  File "/usr/share/solaar/lib/solaar/listener.py", line 123, in _status_changed
    if device.kind is None:
       ^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 234, in kind
    self._kind = _hidpp20.get_kind(self)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/hidpp20.py", line 1432, in get_kind
    return KIND_MAP[DEVICE_KIND[kind]]
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: None
2024-11-02 04:30:03,909,909     INFO [MainThread] solaar.listener: stopping receiver listening threads [<SolaarListener(SolaarListener:hidraw0, stopped daemon 140706781857472)>]
2024-11-02 04:30:03,910,910     INFO [MainThread] solaar.ui.notify: stopping desktop notifications
```
</details>

**Describe the bug**
The G733 has a new hardware ID, and Solaar doesn't support it. The ID is `0x0B1F`

**To Reproduce**
1. Open Solaar
2. See the headset isn't there :(

**Screenshots**
![image](https://github.com/user-attachments/assets/7bb7bb2e-86bf-463a-8ae4-53ac3fdba473)

**Comment by pfps** [comment]
It looks as if the problem is not the hardware ID but the kind.

Please try cloning and running Solaar directly from this repository to see if the problem still occurs.

**Comment by tom-ricci** [comment]
That worked!

Here's the `-dd` log if its useful:

```
2024-11-03 00:00:32,453,453     INFO [MainThread] solaar.gtk: version 1.1.13-118-ga19461b2, language en_US (UTF-8)
2024-11-03 00:00:32,454,454     INFO [MainThread] solaar.dbus: connected to system dbus, watching for suspend/resume events
2024-11-03 00:00:32,491,491     INFO [MainThread] solaar.ui.desktop_notifications: starting desktop notifications
2024-11-03 00:00:32,497,497  WARNING [MainThread] solaar.ui.icons: failed to detect icons
2024-11-03 00:00:32,532,532     INFO [MainThread] solaar.listener: starting receiver listening threads
2024-11-03 00:00:32,646,646     INFO [MainThread] hidapi.udev_impl: Found device /dev/hidraw0 BID 0003 VID 0000046D PID 00000B1F HID++ False True USB 3 None
2024-11-03 00:00:32,646,646     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw0', bus_id=3, vendor_id='046D', product_id='0B1F', interface=3, driver='hid-generic', manufacturer=None, product=None, serial='0000000000000000', release=None, isDevice=True, hidpp_short=False, hidpp_long=True)
2024-11-03 00:00:32,646,646     INFO [MainThread] hidapi.udev_impl: OPEN PATH /dev/hidraw0
2024-11-03 00:00:32,646,646     INFO [MainThread] logitech_receiver.base: New lock 13
2024-11-03 00:00:32,649,649     INFO [SolaarListener:hidraw0] logitech_receiver.listener: started with <Device(255,0B1F,?,)> (13)
2024-11-03 00:00:32,649,649     INFO [SolaarListener:hidraw0] solaar.listener: <Device(255,0B1F,?,)>: notifications listener has started (13)
2024-11-03 00:00:32,649,649     INFO [SolaarListener:hidraw0] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw0)>
2024-11-03 00:00:32,651,651     INFO [MainThread] hidapi.udev_impl: Report Descriptor not processed for DEVICE /dev/hidraw2 BID 0003 VID 0000093A PID 0000821D: VariableItem.__init__() missing 1 required positional argument: 'logical_min'
2024-11-03 00:00:32,653,653     INFO [MainThread] hidapi.udev_impl: Report Descriptor not processed for DEVICE /dev/hidraw4 BID 0003 VID 00003434 PID 0000D030: Expecting 20 usages but got 256
2024-11-03 00:00:32,655,655     INFO [MainThread] hidapi.udev_impl: Report Descriptor not processed for DEVICE /dev/hidraw5 BID 0003 VID 00003434 PID 0000D030: Expecting 3 usages but got 6
2024-11-03 00:00:32,661,661     INFO [SolaarListener:hidraw0] solaar.listener: status_changed <Device(255,0B1F,?,)>: paired online (0) 
2024-11-03 00:00:32,665,665     INFO [MainThread] hidapi.udev_impl: OPEN PATH /dev/hidraw0
2024-11-03 00:00:32,668,668    ERROR [SolaarListener:hidraw0] solaar.configuration: failed to load from /home/thomas/.config/solaar/config.yaml: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:logitech_receiver.hidpp20_constants.SupportedFeature'
  in "/home/thomas/.config/solaar/config.yaml", line 8, column 13
2024-11-03 00:00:32,675,675  WARNING [MainThread] solaar.ui.icons: icon battery-missing not found in current theme
2024-11-03 00:00:32,679,679     INFO [SolaarListener:hidraw0] solaar.configuration: setting up persister for device G733 Gaming Headset
2024-11-03 00:00:32,929,929     INFO [MainThread] solaar.listener: status_changed <Device(255,0B1F,G733 Gaming Headset,)>: paired online (0) 
2024-11-03 00:00:32,953,953  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-11-03 00:00:33,017,017     INFO [SolaarListener:hidraw0] logitech_receiver.device: <Device(255,0B1F,G733 Gaming Headset,)> pushing device settings [<Setting([feature:choice] G733:led_control=None)>, <Setting([feature:hetero] G733:led_zone_2=None)>, <Setting([feature:hetero] G733:led_zone_1=None)>, <Setting([feature:toggle] G733:divert-gkeys=None)>, <Setting([feature:range] G733:sidetone=None)>, <Setting([feature:packed range] G733:equalizer=None)>, <Setting([feature:range] G733:adc_power_management=None)>]
2024-11-03 00:00:33,033,033     INFO [AsyncUI] hidapi.udev_impl: OPEN PATH /dev/hidraw0
2024-11-03 00:00:33,105,105  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-11-03 00:00:33,177,177  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-11-03 00:00:33,255,255    ERROR [SolaarListener:hidraw0] logitech_receiver.base: (13) device 255 error on feature request {063C}: 2 = 2
2024-11-03 00:00:33,255,255  WARNING [SolaarListener:hidraw0] logitech_receiver.settings: equalizer: error applying {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0} so ignore it (<Device(255,0B1F,G733 Gaming Headset,)>): FeatureCallError({'number': 255, 'request': 1596, 'error': 2, 'params': b'\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'})
2024-11-03 00:00:33,259,259  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-11-03 00:00:33,295,295     INFO [SolaarListener:hidraw0] solaar.listener: status_changed <Device(255,0B1F,G733 Gaming Headset,)>: paired online (0) initialization
2024-11-03 00:00:33,299,299  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-11-03 00:00:33,303,303  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-11-03 00:00:33,307,307  WARNING [MainThread] solaar.ui.icons: icon battery-good not found in current theme
2024-11-03 00:00:37,879,879     INFO [Thread-1] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': NamedInt(0, 'Device'), 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7f50>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7c50>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:01,303,303     INFO [Thread-12] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': NamedInt(0, 'Device'), 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7f50>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7c50>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:06,393,393     INFO [Thread-13] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7f50>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7c50>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:19,484,484     INFO [Thread-14] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7f50>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7c50>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:30,030,030     INFO [Thread-16] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7f50>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507ecaab6b0>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:36,182,182     INFO [Thread-21] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9fa7f50>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f36810>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True, 'led_zone_2': 'ignore'}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:41,554,554     INFO [Thread-23] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507ed9b35f0>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f36810>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True, 'led_zone_2': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:46,747,747     INFO [Thread-26] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f76060>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f36810>, 'divert-gkeys': False, 'sidetone': 0, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True, 'led_zone_2': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:01:52,167,167     INFO [Thread-28] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f76060>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f36810>, 'divert-gkeys': False, 'sidetone': 100, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True, 'led_zone_2': True, 'sidetone': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:02:31,288,288     INFO [Thread-90] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f76060>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f36810>, 'divert-gkeys': False, 'sidetone': 81, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True, 'led_zone_2': True, 'sidetone': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:03:04,954,954     INFO [MainThread] solaar.listener: stopping receiver listening threads [<SolaarListener(SolaarListener:hidraw0, started daemon 128676330997440)>]
2024-11-03 00:03:04,956,956     INFO [MainThread] solaar.configuration: saved ['1.1.13-118-ga19461b2', {'_NAME': 'G733 Gaming Headset', '_modelId': '0B1F00000000', '_unitId': 'FFFFFFFF', '_battery': <SupportedFeature.ADC_MEASUREMENT: 7968>, '_absent': ['hi-res-scroll', 'lowres-scroll-mode', 'hires-smooth-invert', 'hires-smooth-resolution', 'hires-scroll-mode', 'scroll-ratchet', 'smart-shift', 'thumb-scroll-invert', 'thumb-scroll-mode', 'onboard_profiles', 'report_rate', 'report_rate_extended', 'pointer_speed', 'dpi', 'dpi_extended', 'speed-change', 'backlight', 'backlight_level', 'backlight_duration_hands_out', 'backlight_duration_hands_in', 'backlight_duration_powered', 'backlight-timed', 'rgb_control', 'rgb_zone_', 'brightness_control', 'per-key-lighting', 'fn-swap', 'reprogrammable-keys', 'persistent-remappable-keys', 'divert-keys', 'disable-keyboard-keys', 'crown-smooth', 'divert-crown', 'm-key-leds', 'mr-key-led', 'multiplatform', 'change-host', 'gesture2-gestures', 'gesture2-divert', 'gesture2-params'], 'led_control': 1, 'led_zone_2': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f76060>, 'led_zone_1': <logitech_receiver.hidpp20.LEDEffectSetting object at 0x7507e9f36810>, 'divert-gkeys': False, 'sidetone': 81, 'equalizer': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, 'adc_power_management': 30, '_sensitive': {'led_control': True, 'led_zone_1': True, 'led_zone_2': True, 'sidetone': True}}] to /home/thomas/.config/solaar/config.yaml
2024-11-03 00:03:05,622,622     INFO [SolaarListener:hidraw0] solaar.listener: <Device(255,0B1F,G733 Gaming Headset,)>: notifications listener has stopped
2024-11-03 00:03:05,623,623     INFO [MainThread] solaar.ui.desktop_notifications: stopping desktop notifications
```

**Comment by pfps** [comment]
Excellent.  There should be a new version of Solaar out in the near future.
