### ISSUE TITLE
Solaar won't open on macOS

### ISSUE THREAD

**Issue by creativetags** [pwr-Solaar/Solaar#2738]
Following the instructions here https://pwr-solaar.github.io/Solaar/installation/ 

```
brew update
brew install hidapi gtk+3 pygobject3
pipx install --system-site-packages solaar
```

running solaar gives:
```
Traceback (most recent call last):
  File "/Users/mark/.local/bin/solaar", line 54, in <module>
    import solaar.gtk
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/gtk.py", line 31, in <module>
    import solaar.cli as _cli
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/cli/__init__.py", line 25, in <module>
    import logitech_receiver.device as _device
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/device.py", line 38, in <module>
    from .settings_templates import check_feature_settings as _check_feature_settings
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/settings_templates.py", line 39, in <module>
    from .diversion import process_notification as _process_notification
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/diversion.py", line 32, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

**Comment by pfps** [comment]
@MattHag Can you take a look at this?

**Comment by MattHag** [comment]
Yes, there is no dbus at this place in the latest version. That must be quite old. 

@creativetags Did you try it with the latest main branch?

**Comment by creativetags** [comment]
I haven't tried the latest source, just from pip. Will see if I can figure out how to do that instead.

**Comment by pfps** [comment]
There is a new version on PyPi today so please use that.

**Comment by creativetags** [comment]
Thanks, I tried updating to 1.1.14 but now I get:
```
Traceback (most recent call last):
  File "/Users/mark/.local/bin/solaar", line 53, in <module>
    import solaar.gtk
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/gtk.py", line 34, in <module>
    from solaar import cli
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/solaar/cli/__init__.py", line 26, in <module>
    from logitech_receiver import device
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/device.py", line 35, in <module>
    from . import hidpp10
  File "/Users/mark/.local/pipx/venvs/solaar/lib/python3.13/site-packages/logitech_receiver/hidpp10.py", line 22, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```
Tried installing typing_extensions with python3 -m pip install typing_extensions but still get the error

**Comment by MattHag** [comment]
Use Python 3.12 for the tests.

**Comment by MattHag** [comment]
Run `pip install typing-extensions`

**Comment by creativetags** [comment]
I installed it in a venv and it doesn't work. I don't know Python well enough to figure this out

**Comment by MattHag** [comment]
You can try the following, which should install all dependencies, including the typing_extension

```
git clone git@github.com:pwr-Solaar/Solaar.git
cd solaar
# activate your venv
pipx install --system-site-packages .["test"]
```

**Comment by creativetags** [comment]
I cloned the repo. 
pipx install --system-site-packages .["test"] gives:
no matches found: .[test]

**Comment by MattHag** [comment]
MacOS seems uses different quotes, try `pipx install --system-site-packages '.[test]'`

**Comment by creativetags** [comment]
I had to add --force but that actually worked! Thanks

**Comment by MattHag** [comment]
Great, if you `git pull` later on, you will even have Bluetooth support #2730.
