### ISSUE TITLE
AttributeError: "'Receiver' object has no attribute '_devices'" (No Logitech receiver found)

### ISSUE THREAD

**Issue by Justin-Maxwell** [pwr-Solaar/Solaar#334]
Hi.

Old receiver went flaky, new one is okay in dmesg, but Solaar doesn't see it.

```
[192934.390055] usb 5-1.2.4: new full-speed USB device number 35 using xhci_hcd
[192934.502153] usb 5-1.2.4: New USB device found, idVendor=046d, idProduct=c52b
[192934.502157] usb 5-1.2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[192934.502159] usb 5-1.2.4: Product: USB Receiver
[192934.502161] usb 5-1.2.4: Manufacturer: Logitech
[192934.524219] logitech-djreceiver 0003:046D:C52B.001F: hiddev0,hidraw7: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:06:00.0-1.2.4/input2
```

```
 $ solaar-cli show
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
Traceback (most recent call last):
  File "/usr/bin/solaar-cli", line 42, in <module>
    solaar.cli.main()
  File "/usr/share/solaar/lib/solaar/cli.py", line 431, in main
    args.cmd(receiver, args)
  File "/usr/share/solaar/lib/solaar/cli.py", line 203, in show_devices
    _print_receiver(receiver, args.verbose)
  File "/usr/share/solaar/lib/solaar/cli.py", line 98, in _print_receiver
    paired_count = receiver.count()
AttributeError: 'NoneType' object has no attribute 'count'
```

**Comment by jwkokc** [comment]
See my comment just before yours. I had to patch two files to get the receiver recognized (in /usr/share/solaar/lib/*) and add one to /etc/udev/rules.d. I'm using Xubuntu 16.04.1; your paths may be different.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
