### ISSUE TITLE
My keaboard is sometimes missing from the solaar Unifying Receiver list.

### ISSUE THREAD

**Issue by JulianLai** [pwr-Solaar/Solaar#340]
Mouse: M545
Keyboard: K330
![deepinscreenshot20170301152327](https://cloud.githubusercontent.com/assets/20014762/23449840/0daaaa6e-fe93-11e6-893a-3100fa56b314.png)

**Comment by jrbenito** [comment]
Hi,

What version of Solaar are you using? If you are using the distribution package, please try latest master branch on this repo, I observed this on Ubuntu package but not in the latest version.

Thanks,
Benito

**Comment by Osndok** [comment]
I experienced this to in the fedora package: solaar-0.9.2-4.20150528gitcf27328.fc25.4.noarch

In case it helps, I noticed that the *FIRST* time I launched solar, the two keyboards were present, but that subsequent launches do not show them (even though it *does* say "3 devices paired")... it only shows the (currently offline) mouse.

Also, the keyboards *are* listed in the configuration file, and *are* present in the "solaar show" output, and I assume that this stack trace has something to do with it:

```
23:35:44,852    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(1,41,04,312440)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/lib/python2.7/site-packages/solaar/listener.py", line 207, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/notifications.py", line 54, in process
    return _process_device_notification(device, status, notification)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/notifications.py", line 97, in _process_device_notification
    return _process_hidpp10_notification(device, status, n)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/notifications.py", line 174, in _process_hidpp10_notification
    status.changed(active=link_established)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/status.py", line 265, in changed
    for s in d.settings:
  File "/usr/lib/python2.7/site-packages/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/settings_templates.py", line 190, in check_feature_settings
    already_known.append(smooth_scroll(device))
  File "/usr/lib/python2.7/site-packages/logitech_receiver/settings.py", line 63, in __call__
    assert self.device_kind is None or self.device_kind == device.kind
```

Perhaps the lack of "kind" in the configuration file is throwing it off? I haven't had time to dig into the source yet.

**Comment by Lekensteyn** [comment]
@Osndok Do you happen to have a combo device? git master contains a fix for that

**Comment by lasers** [comment]
I ran into this issue and was investigating. I draw a conclusion that Logitech keyboards are tripping something in the code when they are active during `solaar` startup. I am using `K400r` with `M570`.
##### k400r (sleeping)
```
lasers~ solaar show                                                                           :(
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : --------
    Firmware   : 12.01.B0019
    Bootloader : 02.14
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=42

  1: Wireless Touch Keyboard K400
     Codename     : K400
     Kind         : keyboard
     Wireless PID : 4024
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: --------
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).

  2: Wireless Trackball M570
     Codename     : M570
     Kind         : trackball
     Wireless PID : 1028
     Protocol     : unknown (device is offline)
     Polling rate : 8 ms (125Hz)
     Serial number: --------
     The power switch is located on the base.
     Battery: unknown (device is offline).
```
##### k400r (active)
```
lasers~ solaar show
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : --------
    Firmware   : 12.01.B0019
    Bootloader : 02.14
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=44

  1: Wireless Touch Keyboard K400
     Codename     : K400
     Kind         : keyboard
     Wireless PID : 4024
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: --------
          Firmware: RQK 50.01.B0013
     The power switch is located on the edge of top right corner.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: FEATURE INFO           {0002}
         3: DEVICE FW VERSION      {0003}
         4: DEVICE NAME            {0005}
         5: BATTERY STATUS         {1000}
         6: REPROG CONTROLS        {1B00}
         7: REPROG CONTROLS V3     {1B03}
         8: WIRELESS DEVICE STATUS {1D4B}
         9: unknown:1DF0           {1DF0}   hidden
        10: unknown:1DF3           {1DF3}   internal, hidden
        11: unknown:1E00           {1E00}   hidden
        12: VERTICAL SCROLLING     {2100}
        13: HI RES SCROLLING       {2120}
        14: MOUSE POINTER          {2200}
        15: FN INVERSION           {40A0}
        16: NEW FN INVERSION       {40A2}
        17: ENCRYPTION             {4100}
        18: KEYBOARD LAYOUT        {4520}
        19: TOUCHPAD FW ITEMS      {6010}
        20: TOUCHPAD SW ITEMS      {6011}
        21: TOUCHPAD WIN8 FW ITEMS {6012}
     Has 18 reprogrammable keys:
         0: SHOW DESKTOP               => ShowDesktop                   is FN, reprogrammable
         1: METRO APPSWITCH            => MetroAppSwitch                is FN, reprogrammable
         2: METRO SEARCH               => MetroSearch                   is FN, reprogrammable
         3: METRO SHARE                => MetroShare                    is FN, reprogrammable
         4: METRO DEVICES              => MetroDevices                  is FN, reprogrammable
         5: METRO SETTINGS             => MetroSettings                 is FN, reprogrammable
         6: Previous                   => Previous                      is FN
         7: Play/Pause                 => Play/Pause                    is FN
         8: Next                       => Next                          is FN
         9: Mute                       => Mute                          is FN
        10: Volume Down                => Volume Down                   is FN
        11: Volume Up                  => Volume Up                     is FN
        12: MEDIA PLAYER               => Music                         nonstandard, reprogrammable
        13: Lock PC                    => WindowsLock                   nonstandard, reprogrammable
        14: SLEEP                      => Sleep                         nonstandard, reprogrammable
        15: LEFT CLICK                 => LeftClick                     mse
        16: LEFT CLICK                 => LeftClick                     mse
        17: RIGHT CLICK                => RightClick                    mse
     Battery: 90%, discharging.

  2: Wireless Trackball M570
     Codename     : M570
     Kind         : trackball
     Wireless PID : 1028
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: --------
          Firmware: 26.00.B0003
        Bootloader: 02.06
             Other: 00.01
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: 60%, discharging.
```
The `Supports 22 HID++ 2.0 features:` and/or `Has 18 reprogrammable keys:` stuffs might have something to do with it because I sometimes will see `1` instead of `2` for pair devices. Please let me know if you need anything more. Many thanks. :-)

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
