### ISSUE TITLE
Future support for the K850 and M720 Triathlon (MK850 bundle)?

### ISSUE THREAD

**Issue by philippeboyd** [pwr-Solaar/Solaar#413]
So I just bought the MK850 which comes with a K850 keyboard and a M720 Triathlon mouse. They work out of the box with the Nano receiver that comes with it. When I login, I get a notification displaying the amount of battery left in my Keyboard as well as the bottom notification tray icon. 

However, a couple of seconds later, solaar doesn't show any information about them (No Logitech receiver found) in the tray.

Here's what `solaar -d show` gives me (using **solaar 0.9.2**)

```bash
Unifying Receiver [/dev/hidraw1:F11590BF] with 2 devices
18:29:38,395     INFO logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: found new device 1 (405E)
1: M720 Triathlon Multi-Device Mouse [M720 Triathlon:F52D69E5] 
18:29:38,958     INFO logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: found new device 2 (4062)
2: K850 Performance Wireless Keyboard [K850:C3E8B178] 
18:29:40,042    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 3 of <UnifyingReceiver(/dev/hidraw1,3)>
18:29:40,042    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 3, 'receiver': <UnifyingReceiver(/dev/hidraw1,3)>}
18:29:40,043  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: looked for device 3, not found
18:29:40,046    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 4 of <UnifyingReceiver(/dev/hidraw1,3)>
18:29:40,046    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 4, 'receiver': <UnifyingReceiver(/dev/hidraw1,3)>}
18:29:40,046  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: looked for device 4, not found
18:29:40,051    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 5 of <UnifyingReceiver(/dev/hidraw1,3)>
18:29:40,051    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 5, 'receiver': <UnifyingReceiver(/dev/hidraw1,3)>}
18:29:40,051  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: looked for device 5, not found
18:29:40,056    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 6 of <UnifyingReceiver(/dev/hidraw1,3)>
18:29:40,056    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 6, 'receiver': <UnifyingReceiver(/dev/hidraw1,3)>}
18:29:40,056  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: looked for device 6, not found
```

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
