### ISSUE TITLE
Python errors while pairing, dialog doesn't close although pairing succeeded. Deprecated Gobject stuff

### ISSUE THREAD

**Issue by ageis** [pwr-Solaar/Solaar#415]
```/usr/local/lib/python2.7/dist-packages/solaar/gtk.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py:38: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GLib.threads_init()
/usr/local/lib/python2.7/dist-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/local/lib/python2.7/dist-packages/solaar/ui/action.py:36: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "name, label, tooltip, stock_id" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  action = Gtk.Action(name, label, label, None)
/usr/local/lib/python2.7/dist-packages/solaar/ui/tray.py:148: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py:220: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  p._title = Gtk.Label(' ')
/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py:110: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  p._scanning = Gtk.Label(_("Scanning") + '...')
/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py:114: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  bp.pack_start(Gtk.Label(' '), True, True, 0)
/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py:129: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b._label = Gtk.Label(label_text)
/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py:175: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  bb = Gtk.ButtonBox(Gtk.Orientation.HORIZONTAL)
/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py:83: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button(label) if label else Gtk.Button()
/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py:319: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  bottom_buttons_box = Gtk.ButtonBox(Gtk.Orientation.HORIZONTAL)

(solaar:5489): Gdk-CRITICAL **: 05:42:10.845: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/local/lib/python2.7/dist-packages/solaar/ui/config_panel.py:95: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  sbox.pack_start(Gtk.Label(s.label), False, False, 0)
/usr/local/lib/python2.7/dist-packages/solaar/ui/action.py:95: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "parent, flags, message_type, buttons, message_format" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  _("Unpair") + ' ' + device.name + ' ?')
/usr/local/lib/python2.7/dist-packages/solaar/ui/action.py:95: PyGTKDeprecationWarning: The keyword(s) "message_format" have been deprecated in favor of "text" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  _("Unpair") + ' ' + device.name + ' ?')
/usr/local/lib/python2.7/dist-packages/gi/overrides/Gtk.py:542: PyGTKDeprecationWarning: The keyword(s) "parent" have been deprecated in favor of "transient_for" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self._init(*args, **new_kwargs)
/usr/local/lib/python2.7/dist-packages/solaar/ui/pair_window.py:41: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "homogeneous, spacing" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  p = Gtk.VBox(False, 8)
/usr/local/lib/python2.7/dist-packages/solaar/ui/pair_window.py:46: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "homogeneous, spacing" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item = Gtk.HBox(False, 16)
/usr/local/lib/python2.7/dist-packages/solaar/ui/pair_window.py:49: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(header)
/usr/local/lib/python2.7/dist-packages/solaar/ui/pair_window.py:60: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(text)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 775, in update
    assert item
AssertionError
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/pair_window.py", line 75, in _check_lock_state
    if receiver.status.get(_K.ERROR):
AttributeError: 'unicode' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/pair_window.py", line 120, in _finish
    receiver.status.new_device = None
AttributeError: 'unicode' object has no attribute 'new_device'
Gtk-Message: 05:43:27.100: GtkDialog mapped without a transient parent. This is discouraged.
```

Separate question: how to increase encrypt the wireless link and increase/decrease polling frequently? Are those sysvars in Linux?

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
