### ISSUE TITLE
Solaar Issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by ratherDashing** [pwr-Solaar/Solaar#432]
solaar-cli -d show displays this:
```
Unifying Receiver [/dev/hidraw4:410A94F5] with 1 devices
09:11:23,432     INFO logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,3)>: found new device 1 (101A)
1: Performance Mouse MX [Performance MX:3F36D1FB] offline
09:11:23,440    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 2 of <UnifyingReceiver(/dev/hidraw4,3)>
09:11:23,440    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 2, 'receiver': <UnifyingReceiver(/dev/hidraw4,3)>}
09:11:23,441  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,3)>: looked for device 2, not found
09:11:23,446    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 3 of <UnifyingReceiver(/dev/hidraw4,3)>
09:11:23,446    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 3, 'receiver': <UnifyingReceiver(/dev/hidraw4,3)>}
09:11:23,446  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,3)>: looked for device 3, not found
09:11:23,452    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 4 of <UnifyingReceiver(/dev/hidraw4,3)>
09:11:23,452    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 4, 'receiver': <UnifyingReceiver(/dev/hidraw4,3)>}
09:11:23,453  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,3)>: looked for device 4, not found
09:11:23,458    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 5 of <UnifyingReceiver(/dev/hidraw4,3)>
09:11:23,458    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 5, 'receiver': <UnifyingReceiver(/dev/hidraw4,3)>}
09:11:23,459  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,3)>: looked for device 5, not found
09:11:23,464    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 6 of <UnifyingReceiver(/dev/hidraw4,3)>
09:11:23,464    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 6, 'receiver': <UnifyingReceiver(/dev/hidraw4,3)>}
09:11:23,465  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw4,3)>: looked for device 6, not found

```

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
