### ISSUE TITLE
Solaar keeps "forgetting" the receiver after minutes

### ISSUE THREAD

**Issue by eera5607** [pwr-Solaar/Solaar#444]
Hi! Thank you for your work on this app. I have the following issue:

1. No Logitech receiver found 
![solaar1](https://user-images.githubusercontent.com/5403536/42423112-e9e81f18-82b1-11e8-9d16-f68044a5d0b3.png)
2. Disconnect and connect again the Unifying Receiver.
3. Turn the Logitech K800 off and on. Everything works fine now. 
![selection_001](https://user-images.githubusercontent.com/5403536/42423141-5f2a1286-82b2-11e8-83b2-7ec3f407fcac.png)
4. Minutes later the first point again. No suspension involved. 
5. `solaar --debug` results with only hidrawX chaning between cases (hidraw3, hidraw4 etc.):

```
/usr/share/solaar/lib/solaar/gtk.py:33:
 PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
13:12:07,820     INFO [MainThread] root: language en_US (UTF-8), translations path None
13:12:07,850     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
/usr/share/solaar/lib/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/share/solaar/lib/solaar/ui/tray.py:72: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
13:12:07,868     INFO [MainThread] solaar.ui.tray: using AppIndicator3
13:12:07,869     INFO [MainThread] solaar.ui.notify: starting desktop notifications
13:12:07,879     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
13:12:07,880     INFO [MainThread] solaar.listener: starting receiver listening threads
13:12:07,881     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw3', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1207', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
13:12:07,884     INFO [ReceiverListener:hidraw3] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw3,12)> (12)
13:12:07,884     INFO [ReceiverListener:hidraw3] solaar.listener: <UnifyingReceiver(/dev/hidraw3,12)>: notifications listener has started (12)
13:12:07,888     INFO [ReceiverListener:hidraw3] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,12)>: receiver notifications enabled => ('wireless', 'software present')
13:12:07,892     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw3,12)>: present, No paired devices. (0) 
13:12:07,893     INFO [ReceiverListener:hidraw3] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,12)>: found new device 3 (2010)
13:12:07,893     INFO [ReceiverListener:hidraw3] solaar.listener: Notification(3,41,04,311020) triggered new device <PairedDevice(3,2010,K800)> (keyboard)
13:12:07,894     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw3,12)>: present, 1 paired device. (0) 
13:12:07,940    ERROR [ReceiverListener:hidraw3] logitech_receiver.base: write failed, assuming handle 12 no longer available
13:12:07,941    ERROR [ReceiverListener:hidraw3] logitech_receiver.listener: processing Notification(3,41,04,311020)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 207, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 54, in process
    return _process_device_notification(device, status, notification)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 97, in _process_device_notification
    return _process_hidpp10_notification(device, status, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 174, in _process_hidpp10_notification
    status.changed(active=link_established)
  File "/usr/share/solaar/lib/logitech_receiver/status.py", line 255, in changed
    self[KEYS.NOTIFICATION_FLAGS] = d.enable_notifications()
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 274, in enable_notifications
    flag_bits = _hidpp10.get_notification_flags(self)
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 310, in get_notification_flags
    flags = read_register(device, REGISTERS.notifications)
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 142, in read_register
    return device.request(request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Broken pipe')}
13:12:07,941    ERROR [ReceiverListener:hidraw3] logitech_receiver.base: read failed, assuming handle 12 no longer available
13:12:07,941  WARNING [ReceiverListener:hidraw3] logitech_receiver.listener: receiver disconnected
13:12:07,941     INFO [ReceiverListener:hidraw3] solaar.listener: <UnifyingReceiver(/dev/hidraw3,12)>: notifications listener has stopped
```

What can it be? Thanks for the help. 

Edit: forgot to mention that I'm on Ubuntu 18.04. Recent fresh install.

**Comment by arigit** [comment]
I am running ubuntu 18.04 as well.

This is trace back, looks similar to the OP's

```
0:28:02,672  WARNING [ReceiverListener:hidraw2] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S)>: unrecognized Notification(1,02,00,0000000000000000000000) for feature DEVICE FW VERSION (index 02)
00:28:04,120     INFO [ReceiverListener:hidraw2] solaar.listener: Notification(1,41,04,326940) triggered new device <PairedDevice(1,4069,MX Master 2S)> (mouse)
00:28:04,120    ERROR [ReceiverListener:hidraw2] logitech_receiver.base: write failed, assuming handle 13 no longer available
00:28:04,121    ERROR [ReceiverListener:hidraw2] logitech_receiver.listener: processing Notification(1,41,04,326940)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 213, in _notifications_handler
    configuration.attach_to(dev)
  File "/usr/share/solaar/lib/solaar/configuration.py", line 130, in attach_to
    for s in device.settings:
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/usr/share/solaar/lib/logitech_receiver/settings_templates.py", line 376, in check_feature_settings
    check_feature(_SMOOTH_SCROLL[0], _F.HI_RES_SCROLLING)
  File "/usr/share/solaar/lib/logitech_receiver/settings_templates.py", line 366, in check_feature
    if not featureId in device.features:
  File "/usr/share/solaar/lib/logitech_receiver/hidpp20.py", line 260, in __contains__
    reply = self.device.request(0x0000, _pack('!H', ivalue))
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Broken pipe')}
00:28:04,121    ERROR [ReceiverListener:hidraw2] logitech_receiver.base: read failed, assuming handle 13 no longer available
00:28:04,121  WARNING [ReceiverListener:hidraw2] logitech_receiver.listener: receiver disconnected
00:28:04,121     INFO [ReceiverListener:hidraw2] solaar.listener: <UnifyingReceiver(/dev/hidraw2,13)>: notifications listener has stopped
```

**Comment by eera5607** [comment]
I just tested the latest version available on default Ubuntu 18.04 repositories and everything seems to be working fine now. I don't know what's the difference between this version and the latest master.

**Comment by arigit** [comment]
Ubuntu's default is a copy of debian's, which is based on the last official solaar release (several years old), a very ancient release. This could work just fine for a keyboard, but does not cut it for new hardware (my case)

**Comment by eera5607** [comment]
Oh I'm sorry. Yes, it is an old version. I'm still having the issue I first posted.

**Comment by jgsqware** [comment]
I'm experiencing this too on arch linux `solaar 0.9.2`

**Comment by Narrat** [comment]
Have seen the same issue on different systems while using a build from master

**Comment by pfps** [comment]
I suspect that this problem is no longer active in the version of Solaar currently in this repository.  If you are experiencing problems with Solaar not showing connected receivers please clone this repository and run solaar from it.

**Comment by pfps** [comment]
Closing due to no response from submitters.
