### ISSUE TITLE
GUI doesn't work under Pop OS

### ISSUE THREAD

**Issue by ire-and-curses** [pwr-Solaar/Solaar#455]
`Running` solaar under Pop OS (Ubuntu-based), GUI doesn't work at all.

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Pop!_OS 18.04 LTS"
```

Version:
```
$ solaar -V
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
solaar 0.9.2
```
Run command, and then move the mouse:
```
$ solaar -d
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
09:33:05,037     INFO [MainThread] root: language en_US (UTF-8), translations path None
09:33:05,074     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
/usr/share/solaar/lib/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/share/solaar/lib/solaar/ui/tray.py:72: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
09:33:05,282     INFO [MainThread] solaar.ui.tray: using AppIndicator3
09:33:05,283     INFO [MainThread] solaar.ui.notify: starting desktop notifications
09:33:05,303     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
09:33:05,305     INFO [MainThread] solaar.listener: starting receiver listening threads
09:33:05,306     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw0', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='2401', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
09:33:05,312     INFO [ReceiverListener:hidraw0] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw0,12)> (12)
09:33:05,313     INFO [ReceiverListener:hidraw0] solaar.listener: <UnifyingReceiver(/dev/hidraw0,12)>: notifications listener has started (12)
09:33:05,319     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,12)>: receiver notifications enabled => ('wireless', 'software present')
09:33:05,323     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,12)>: present, No paired devices. (0) 
09:33:05,327     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,12)>: found new device 1 (1028)
09:33:05,327     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,04,122810) triggered new device <PairedDevice(1,1028,M570)> (mouse)
09:33:05,329     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,12)>: present, 1 paired device. (0) 
09:33:05,379     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <PairedDevice(1,1028,M570)>: device notifications enabled ('battery status',)
09:33:05,393     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,1028,M570)>: paired online, Battery: 95% (discharging) (1) 
09:33:05,395     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,1028,M570)>: paired online, Battery: 95% (discharging) (0) 
09:33:08,786    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(1,02,00,0000100000002E00000000)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 207, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 54, in process
    return _process_device_notification(device, status, notification)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 105, in _process_device_notification
    return _process_hidpp10_custom_notification(device, status, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 130, in _process_hidpp10_custom_notification
    if n.sub_id == _R.illumination:
AttributeError: 'NamedInts' object has no attribute 'illumination'
```

**Comment by Lekensteyn** [comment]
Can you try with the latest version from git master?

**Comment by brianfinley** [comment]
I was having the same issue on Ubuntu 18.10:
```
[$] cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
```

The latest version from git master worked fine (as of commit cc010cb653b4d118b911c01839257ab71fc40f8a on Thu Sep 21 01:52:22 2017).

So I built the packages, but they had a theme conflict and Ubuntu had a higher version number, so I revved the version number to 0.9.2+dfsg-8bef1 (Ubuntu's was 0.9.2+dfsg-8) and made the changes that I've captured here with this diff:
```
[$] git diff -u
diff --git a/packaging/debian/substvars.theme.ubuntu b/packaging/debian/substvars.theme.ubuntu
index 10958ea..7798db0 100644
--- a/packaging/debian/substvars.theme.ubuntu
+++ b/packaging/debian/substvars.theme.ubuntu
@@ -1,2 +1,2 @@
-Desktop-Icon-Theme=gnome-icon-theme-full | oxygen-icon-theme-complete
-Gnome-Icon-Theme=gnome-icon-theme-full
+Desktop-Icon-Theme=gnome-icon-theme-full | oxygen-icon-theme-complete | gnome-icon-theme
+Gnome-Icon-Theme=gnome-icon-theme-full | gnome-icon-theme
```

After that, I re-built the packages, which then installed fine.  And all is working very nicely, including the "Swap FX Function" toggle switch in the gnome3 GUI piece.  :-)

**Comment by pfps** [comment]
Is this still a problem with the version of Solaar in this repository?

**Comment by ire-and-curses** [comment]
I just re-tried with version 1.0.1 from the Ubuntu PPA [here](https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable). It works for me, thanks!
