### ISSUE TITLE
G903

### ISSUE THREAD

**Issue by yurwpjt** [pwr-Solaar/Solaar#466]
Is that possible to see battery level of G903 under linux by this software?

**Comment by Katana-Steel** [comment]
after updating base_usb.py and udev rules from #362 
```
$ solaar -dd
...
21:52:17,875     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c539', serial=u'', release='3904', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')
21:52:17,876    DEBUG [MainThread] logitech_receiver.base: (15) <= w[10 FF 83B5 030000]
21:52:17,878    ERROR [MainThread] logitech_receiver.base: write failed, assuming handle 15 no longer available
21:52:17,878    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c539', serial=u'', release='3904', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 525, in open
    return Receiver(handle, device_info)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 339, in __init__
    serial_reply = self.read_register(_R.receiver_info, 0x03)
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 142, in read_register
    return device.request(request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 438, in request
    return _base.request(self.handle, 0xFF, request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Broken pipe')}
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
21:52:17,879  WARNING [MainThread] solaar.listener: failed to open DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c539', serial=u'', release='3904', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')
```

**Comment by pfps** [comment]
It may be that the device does not report battery levels.
Please include output of
solaar show
when the device is active.

**Comment by pfps** [comment]
Closed due to no response from submitters.
