### ISSUE TITLE
M330 mouse needs to be added to "Supported Devices" list

### ISSUE THREAD

**Issue by ckrzen** [pwr-Solaar/Solaar#480]
Please add the "M330" mouse under the:  "Mice (Nano)" section of the https://github.com/pwr/Solaar/blob/master/docs/devices.md list as working:

$ solaar-cli show
Unifying Receiver [/dev/hidraw0:3E2E9E01] with 2 devices
1: Wireless Keyboard K360 [K360:BF4BC36D] 
2: Wireless Mouse B330/M330/M331 [B330/M330/M331:5A999C3A] 

I was able to pair it to the "Unifying" receiver that came with the K360 keyboard. The M330 ships with a "Nano" receiver which also works out-of-the-box.

$ solaar-cli -dd show
16:20:04,727    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
16:20:04,730    DEBUG logitech_receiver.base: (3) => r[11 FF 83B5 033E2E9E010506080000000000000000]
16:20:04,730    DEBUG logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
16:20:04,732    DEBUG logitech_receiver.base: (3) => r[10 FF 8F80 B20300]
16:20:04,732    DEBUG logitech_receiver.base: (3) device 0xFF error on request {80B2}: 3 = invalid value
16:20:04,732    DEBUG logitech_receiver.base: (3) <= w[10 FF 8102 000000]
16:20:04,734    DEBUG logitech_receiver.base: (3) => r[10 FF 8102 000200]
Unifying Receiver [/dev/hidraw0:3E2E9E01] with 2 devices
16:20:04,734    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 200000]
16:20:04,736    DEBUG logitech_receiver.base: (3) => r[11 FF 83B5 20071440040402010D1A000000000000]
16:20:04,736     INFO logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,3)>: found new device 1 (4004)
16:20:04,736    DEBUG logitech_receiver.base: (3) pinging device 1
16:20:04,736    DEBUG logitech_receiver.base: (3) <= w[10 01 001A 0000BF]
16:20:04,776    DEBUG logitech_receiver.base: (3) => r[11 01 001A 0200BF00000000000000000000000000]
16:20:04,776    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 300000]
16:20:04,778    DEBUG logitech_receiver.base: (3) => r[11 FF 83B5 30BF4BC36D1A40000002000000000000]
1: Wireless Keyboard K360 [K360:BF4BC36D] 
16:20:04,778    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 210000]
16:20:04,782    DEBUG logitech_receiver.base: (3) => r[11 FF 83B5 21080840570402020C00000000000000]
16:20:04,782    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 410000]
16:20:04,784    DEBUG logitech_receiver.base: (3) => r[11 FF 83B5 410E423333302F4D3333302F4D333331]
16:20:04,784     INFO logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,3)>: found new device 2 (4057)
16:20:04,784    DEBUG logitech_receiver.base: (3) pinging device 2
16:20:04,785    DEBUG logitech_receiver.base: (3) <= w[10 02 001D 00006C]
16:20:04,818    DEBUG logitech_receiver.base: (3) => r[20 01 0100 0000000000000000000000]
16:20:04,838    DEBUG logitech_receiver.base: (3) => r[11 02 001D 04056C00000000000000000000000000]
16:20:04,838    DEBUG logitech_receiver.base: (3) <= w[10 02 000B 000100]
16:20:04,930    DEBUG logitech_receiver.base: (3) => r[11 02 000B 01000100000000000000000000000000]
16:20:04,930    DEBUG logitech_receiver.base: (3) <= w[10 02 010E 000000]
16:20:05,022    DEBUG logitech_receiver.base: (3) => r[11 02 010E 15000000000000000000000000000000]
16:20:05,022    DEBUG logitech_receiver.base: (3) <= w[10 02 000B 000500]
16:20:05,116    DEBUG logitech_receiver.base: (3) => r[11 02 000B 03000000000000000000000000000000]
16:20:05,116    DEBUG logitech_receiver.base: (3) <= w[10 02 030B 000000]
16:20:05,208    DEBUG logitech_receiver.base: (3) => r[11 02 030B 1D000000000000000000000000000000]
16:20:05,208    DEBUG logitech_receiver.base: (3) <= w[10 02 031C 000000]
16:20:05,300    DEBUG logitech_receiver.base: (3) => r[11 02 031C 576972656C657373204D6F7573652042]
16:20:05,300    DEBUG logitech_receiver.base: (3) <= w[10 02 031C 100000]
16:20:05,394    DEBUG logitech_receiver.base: (3) => r[11 02 031C 3333302F4D3333302F4D333331000000]
16:20:05,395    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 310000]
16:20:05,398    DEBUG logitech_receiver.base: (3) => r[11 FF 83B5 315A999C3A0400000001000000000000]
2: Wireless Mouse B330/M330/M331 [B330/M330/M331:5A999C3A] 
16:20:05,399    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 220000]
16:20:05,400    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,400    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,400    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
16:20:05,402    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,402    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,402    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 3 of <UnifyingReceiver(/dev/hidraw0,3)>
16:20:05,402    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 3, 'receiver': <UnifyingReceiver(/dev/hidraw0,3)>}
16:20:05,403  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,3)>: looked for device 3, not found
16:20:05,404    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 230000]
16:20:05,406    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,406    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,406    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
16:20:05,408    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,408    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,408    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 4 of <UnifyingReceiver(/dev/hidraw0,3)>
16:20:05,409    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 4, 'receiver': <UnifyingReceiver(/dev/hidraw0,3)>}
16:20:05,409  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,3)>: looked for device 4, not found
16:20:05,409    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 240000]
16:20:05,412    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,412    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,412    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
16:20:05,414    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,414    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,414    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 5 of <UnifyingReceiver(/dev/hidraw0,3)>
16:20:05,414    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 5, 'receiver': <UnifyingReceiver(/dev/hidraw0,3)>}
16:20:05,415  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,3)>: looked for device 5, not found
16:20:05,415    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 250000]
16:20:05,418    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,418    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,419    DEBUG logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
16:20:05,420    DEBUG logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
16:20:05,420    DEBUG logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
16:20:05,420    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 6 of <UnifyingReceiver(/dev/hidraw0,3)>
16:20:05,420    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 6, 'receiver': <UnifyingReceiver(/dev/hidraw0,3)>}
16:20:05,421  WARNING logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,3)>: looked for device 6, not found

**Comment by ckrzen** [comment]
#594 has been submitted for review.
