### ISSUE TITLE
Failed pairing bug and solution for M585 and M590

### ISSUE THREAD

**Issue by lakano** [pwr-Solaar/Solaar#508]
Hello,
Thanks a lot for your program !
For my M590, the GUI was have failed, show paired but not connected, the cli show on line protocol "not connected". I'm under Fedora 29.

But, from command line, you can unpair it, and re-pair it from cli:
```
% solaar unpair M585/M590 
Unpaired 1: M585/M590 (M585/M590) [406B:CB15BC3D]
guillaume@dev-box:/www/iw/web/public % solaar show               
Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c52b
  Serial       : 0D4A9B52
    Firmware   : 12.07.B0029
    Bootloader : 02.15
    Other      : AA.AA
  Has 0 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: (empty)

```

Pairing seems to report a python bug, but the pairing works.
```
% solaar -d pair
10:07:43,465    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 1 of <UnifyingReceiver(/dev/hidraw2,3)>
10:07:43,465    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
logitech_receiver.base.NoSuchDevice: {'number': 1, 'receiver': <UnifyingReceiver(/dev/hidraw2,3)>, 'error': 'read Nano wpid'}
10:07:43,466  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,3)>: looked for device 1, not found
10:07:43,469    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 2 of <UnifyingReceiver(/dev/hidraw2,3)>
10:07:43,469    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
logitech_receiver.base.NoSuchDevice: {'number': 2, 'receiver': <UnifyingReceiver(/dev/hidraw2,3)>, 'error': 'read Nano wpid'}
10:07:43,469  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,3)>: looked for device 2, not found
10:07:43,473    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 3 of <UnifyingReceiver(/dev/hidraw2,3)>
10:07:43,473    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
logitech_receiver.base.NoSuchDevice: {'number': 3, 'receiver': <UnifyingReceiver(/dev/hidraw2,3)>, 'error': 'read Nano wpid'}
10:07:43,473  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,3)>: looked for device 3, not found
10:07:43,477    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 4 of <UnifyingReceiver(/dev/hidraw2,3)>
10:07:43,477    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
logitech_receiver.base.NoSuchDevice: {'number': 4, 'receiver': <UnifyingReceiver(/dev/hidraw2,3)>, 'error': 'read Nano wpid'}
10:07:43,478  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,3)>: looked for device 4, not found
10:07:43,481    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 5 of <UnifyingReceiver(/dev/hidraw2,3)>
10:07:43,481    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
logitech_receiver.base.NoSuchDevice: {'number': 5, 'receiver': <UnifyingReceiver(/dev/hidraw2,3)>, 'error': 'read Nano wpid'}
10:07:43,482  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,3)>: looked for device 5, not found
10:07:43,485    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 6 of <UnifyingReceiver(/dev/hidraw2,3)>
10:07:43,485    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
logitech_receiver.base.NoSuchDevice: {'number': 6, 'receiver': <UnifyingReceiver(/dev/hidraw2,3)>, 'error': 'read Nano wpid'}
10:07:43,485  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,3)>: looked for device 6, not found
10:07:43,487     INFO [MainThread] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw2,3)>: pairing lock is open
Pairing: turn your new device on (timing out in 20 seconds).
10:07:51,363     INFO [MainThread] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw2,3)>: pairing lock is closed
10:07:51,367    ERROR [MainThread] logitech_receiver.base: write failed, assuming handle 3 no longer available
solaar: error: {'reason': BrokenPipeError(32, 'Relais brisé (pipe)')}

```

```
% solaar show   
Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c52b
  Serial       : 0D4A9B52
    Firmware   : 12.07.B0029
    Bootloader : 02.15
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=15

  1: M585/M590 Multi-Device Mouse
     Codename     : M585/M590
     Kind         : mouse
     Wireless PID : 406B
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: CB15BC3D
        Bootloader: BOT 48.00.B0001
          Firmware: MPM 05.02.B0007
             Other: 
     The power switch is located on the base.
     Supports 34 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: unknown:0021           {0021}   
         7: unknown:0007           {0007}   
         8: BATTERY STATUS         {1000}   
         9: CHANGE HOST            {1814}   
        10: unknown:1815           {1815}   
        11: REPROG CONTROLS V4     {1B04}   
        12: unknown:1C00           {1C00}   
        13: POINTER SPEED          {2205}   
        14: VERTICAL SCROLLING     {2100}   
        15: unknown:00C2           {00C2}   
        16: unknown:1802           {1802}   internal, hidden
        17: unknown:1803           {1803}   internal, hidden
        18: unknown:1806           {1806}   internal, hidden
        19: unknown:1805           {1805}   internal, hidden
        20: unknown:1813           {1813}   internal, hidden
        21: unknown:1830           {1830}   internal, hidden
        22: unknown:1861           {1861}   internal, hidden
        23: unknown:1890           {1890}   internal, hidden
        24: unknown:1891           {1891}   internal, hidden
        25: unknown:18A1           {18A1}   internal, hidden
        26: unknown:1DF3           {1DF3}   internal, hidden
        27: unknown:1E00           {1E00}   hidden
        28: unknown:1EB0           {1EB0}   internal, hidden
        29: unknown:18B1           {18B1}   internal, hidden
        30: unknown:1850           {1850}   internal, hidden
        31: unknown:1F03           {1F03}   internal, hidden
        32: unknown:18C0           {18C0}   internal, hidden
        33: LOWRES WHEEL           {2130}   
     Has 8 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         5: LEFT SCROLL AS AC PAN     , default: HorzScrollLeftSet           => LEFT SCROLL AS AC PAN     
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         6: RIGHT SCROLL AS AC PAN    , default: HorzScrollRightSet          => RIGHT SCROLL AS AC PAN    
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         7: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:3, gmask:0
     Battery: 90%, discharging.


```

**Comment by pfps** [comment]
Those traces are not bugs but are instead debugging messages showing an internal exception used when a pairing slot is empty.

**Comment by pfps** [comment]
Is this still a problem after #532 was merged?

**Comment by 3dotssolution** [comment]
I have the issue mentioned above, but after update to the 1.0.1 Version the craft keyboard an MX Master 2S connecting without any problem...

**Comment by pfps** [comment]
OK, this issue appears to be solved.
