### ISSUE TITLE
Pango-CRITICAL Error? - MX Master 2S Lag in every version of Ubuntu and Solaar

### ISSUE THREAD

**Issue by alfonsoler** [pwr-Solaar/Solaar#517]
I installed both from App Store and Master from github and both MX Master 1st Version and 2S lag like hell. This is my second 2S (I changed the first one as if that would be the solution).
I would love to debug but do not know how. The lag is really impressive.

Solaar shows on the top but with its own symbol and there is no device found (although my mouse moves). I tried killall solaar and then start again. This brings Solaar again with the right symbol (battery) and gives me infos about my device. No DPI menu or so. After some seconds it breaks and Solaar will not recognize my mouse anymore.

I detached my bluetooth USB dongle to avoid double connection.

I even reinstalled Ubuntu in several versions to see how it works out of the box. Same. Windows 10 ok, no problems so far (I do not use it anyway).

**Comment by alfonsoler** [comment]
Before and after
![Captura de pantalla de 2019-03-29 14-00-58](https://user-images.githubusercontent.com/45216255/55234364-4c60e280-522b-11e9-8ce1-c4970d29786b.png)
![Captura de pantalla de 2019-03-29 11-56-35](https://user-images.githubusercontent.com/45216255/55234371-4ec33c80-522b-11e9-8ddb-378b7183561f.png)

**Comment by alfonsoler** [comment]
Now using the master version (I had installed it wrongly) some interesting wrong behaviour appeared after starting my computer:

`(solaar:4039): Pango-CRITICAL **: 18:54:36.633: pango_font_description_set_size: assertion 'size >= 0' failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 822, in update
    _update_info_panel(device, full=full_update)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 703, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 674, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/config_panel.py", line 206, in update
    for s in device.settings:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 376, in check_feature_settings
    check_feature(_SMOOTH_SCROLL[0], _F.HI_RES_SCROLLING)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 366, in check_feature
    if not featureId in device.features:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/hidpp20.py", line 260, in __contains__
    reply = self.device.request(0x0000, _pack('!H', ivalue))
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 337, in request
    ihandle = int(handle)
TypeError: __int__ returned non-int (type NoneType)
`

**Comment by alfonsoler** [comment]
It hung a lot (still is while wrinting this). Here is a capture of what I did to try to make it work again:
![Captura de pantalla de 2019-04-07 18-58-53](https://user-images.githubusercontent.com/45216255/55686911-470c4200-5967-11e9-90de-081edfc357c8.png)

**Comment by alfonsoler** [comment]
`(solaar:3946): Pango-CRITICAL **: 19:59:16.019: pango_font_description_set_size: assertion 'size >= 0' failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 822, in update
    _update_info_panel(device, full=full_update)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 703, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 674, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/config_panel.py", line 206, in update
    for s in device.settings:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 377, in check_feature_settings
    check_feature(_SMOOTH_SCROLL[0], _F.LOWRES_WHEEL)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 366, in check_feature
    if not featureId in device.features:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/hidpp20.py", line 260, in __contains__
    reply = self.device.request(0x0000, _pack('!H', ivalue))
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': OSError(32, 'Tuber\xc3\xada rota')}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 822, in update
    _update_info_panel(device, full=full_update)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 703, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 674, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/config_panel.py", line 206, in update
    for s in device.settings:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 376, in check_feature_settings
    check_feature(_SMOOTH_SCROLL[0], _F.HI_RES_SCROLLING)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 366, in check_feature
    if not featureId in device.features:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/hidpp20.py", line 260, in __contains__
    reply = self.device.request(0x0000, _pack('!H', ivalue))
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 339, in request
    _skip_incoming(handle, ihandle, notifications_hook)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 246, in _skip_incoming
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': error(9, 'Descriptor de archivo err\xc3\xb3neo')}
`

**Comment by alfonsoler** [comment]
![Captura de pantalla de 2019-04-16 20-01-14](https://user-images.githubusercontent.com/45216255/56233016-69e2d880-6082-11e9-9776-91275c76cbf9.png)

**Comment by alfonsoler** [comment]
[Possible solution?]
I take out Solaar from the apps that have to start automatically with the system. I have used until now the normal "aplicaciones al inicio" app from Ubuntu. Then I added it again using Gnome Tweak tool. Do not ask me why, but now it worked 2 days in a raw with zero problems.
I do not know if the developers are still reading these issues but I just wanted to leave here a possible interesting solution - which anyway sounds like a stupid coincidence to me, but who knows!

**Comment by alfonsoler** [comment]
solaar --restart-on-wake-up & disown
[1] 4038
alfonso@diplodocus:~$ Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 822, in update
    _update_info_panel(device, full=full_update)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 703, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 674, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/config_panel.py", line 206, in update
    for s in device.settings:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 381, in check_feature_settings
    check_feature(_FN_SWAP[0],       _F.NEW_FN_INVERSION, 'new_fn_swap')
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 366, in check_feature
    if not featureId in device.features:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/hidpp20.py", line 260, in __contains__
    reply = self.device.request(0x0000, _pack('!H', ivalue))
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': OSError(32, 'Tuber\xc3\xada rota')}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 822, in update
    _update_info_panel(device, full=full_update)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 703, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 674, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/config_panel.py", line 206, in update
    for s in device.settings:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 376, in check_feature_settings
    check_feature(_SMOOTH_SCROLL[0], _F.HI_RES_SCROLLING)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py", line 366, in check_feature
    if not featureId in device.features:
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/hidpp20.py", line 260, in __contains__
    reply = self.device.request(0x0000, _pack('!H', ivalue))
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 339, in request
    _skip_incoming(handle, ihandle, notifications_hook)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py", line 246, in _skip_incoming
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': error(9, 'Descriptor de archivo err\xc3\xb3neo')}
^C

**Comment by pfps** [comment]
Is this still a problem after the merge of #525

**Comment by alfonsoler** [comment]
It never appeared again. I saw that the distance of my Bluetooth dongle was producing most of the issues (it was close, but needed to be even closer). I had it changed into an extra USB hole close to the mouse, avoiding wifi signals.

**Comment by pfps** [comment]
OK, closing.

**Comment by CapsAdmin** [comment]
Coming from google, I'm having the same issue but I don't think it has to do with Solaar. Having installed Solaar I can see my mouse disconnecting in its UI when this happens.

USB3 is has been shown to interference with.  https://www.reddit.com/r/technology/comments/136g7y/usb_30_has_been_found_to_cause_interference_that/


So it might help to use the dongle in a usb section of your motherboard that doesn't have usb3 devices connected to it.

I personally bought a usb3 storage drive and when the dongle was connected right next to it, it caused major lag when the drive was busy.
