### ISSUE TITLE
Device support: MX Anywhere 2S

### ISSUE THREAD

**Issue by yochananmarqos** [pwr-Solaar/Solaar#535]
I'm using the `solaar-git` AUR package on Manjaro GNOME.

```
$ solaar show
Exception ignored in: <function Receiver.__del__ at 0x7fddf8dc5158>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 370, in __del__
    self.close()
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 366, in close
    self._devices.clear()
AttributeError: 'Receiver' object has no attribute '_devices'
solaar: error: Logitech receiver not found
```

```
$ solaar -d
15:23:32,564     INFO [MainThread] root: language en_US (UTF-8), translations path None
15:23:32,686     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
15:23:32,855     INFO [MainThread] solaar.listener: starting receiver listening threads
15:23:32,863     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw1', vendor_id='046d', product_id='c52b', serial='', release=b'2407', manufacturer=b'Logitech', product=b'USB Receiver', interface=2, driver='logitech-djreceiver')
15:23:32,866    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path='/dev/hidraw1', vendor_id='046d', product_id='c52b', serial='', release=b'2407', manufacturer=b'Logitech', product=b'USB Receiver', interface=2, driver='logitech-djreceiver')
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 348, in __init__
    if self.product_id == 'c539' or slef.product_id == 'c53a':
NameError: name 'slef' is not defined
Exception ignored in: <function Receiver.__del__ at 0x7fea6d488510>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 370, in __del__
    self.close()
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 366, in close
    self._devices.clear()
AttributeError: 'Receiver' object has no attribute '_devices'
15:23:32,867  WARNING [MainThread] solaar.listener: failed to open DeviceInfo(path='/dev/hidraw1', vendor_id='046d', product_id='c52b', serial='', release=b'2407', manufacturer=b'Logitech', product=b'USB Receiver', interface=2, driver='logitech-djreceiver')
^C
```

```
$ lsusb | grep Logitech
Bus 003 Device 009: ID 046d:c52b Logitech, Inc. Unifying Receiver
```

```
# dmesg | grep Logitech
[    5.355267] usb 3-1: Manufacturer: Logitech
[    5.413446] logitech-djreceiver 0003:046D:C52B.0003: hiddev0,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:04:00.4-1/input2
[    5.529699] input: Logitech Unifying Device. Wireless PID:406a Keyboard as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input7
[    5.529730] input: Logitech Unifying Device. Wireless PID:406a Mouse as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input8
[    5.529771] input: Logitech Unifying Device. Wireless PID:406a Consumer Control as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input9
[    5.529796] input: Logitech Unifying Device. Wireless PID:406a System Control as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input10
[    5.529875] hid-generic 0003:046D:406A.0004: input,hidraw1: USB HID v1.11 Keyboard [Logitech Unifying Device. Wireless PID:406a] on usb-0000:04:00.4-1:1
[    5.625438] input: Logitech MX Anywhere 2S as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input14
[    5.625716] logitech-hidpp-device 0003:046D:406A.0004: input,hidraw1: USB HID v1.11 Keyboard [Logitech MX Anywhere 2S] on usb-0000:04:00.4-1:1
[ 8153.705210] usb 3-1: Manufacturer: Logitech
[ 8153.754268] logitech-djreceiver 0003:046D:C52B.0009: hiddev0,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:04:00.4-1/input2
[ 8153.879475] input: Logitech MX Anywhere 2S as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0009/0003:046D:406A.000A/input/input33
[ 8153.880012] logitech-hidpp-device 0003:046D:406A.000A: input,hidraw1: USB HID v1.11 Keyboard [Logitech MX Anywhere 2S] on usb-0000:04:00.4-1:1
[ 8213.055182] usb 3-1: Manufacturer: Logitech
[ 8213.106178] logitech-djreceiver 0003:046D:C52B.000D: hiddev0,hidraw1: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:04:00.4-1/input2
[ 8213.231454] input: Logitech MX Anywhere 2S as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.000D/0003:046D:406A.000E/input/input34
[ 8213.231802] logitech-hidpp-device 0003:046D:406A.000E: input,hidraw4: USB HID v1.11 Keyboard [Logitech MX Anywhere 2S] on usb-0000:04:00.4-1:1
[ 8404.993068] usb 3-1: Manufacturer: Logitech
[ 8405.041796] logitech-djreceiver 0003:046D:C52B.0011: hiddev0,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:04:00.4-1/input2
[ 8405.257302] input: Logitech MX Anywhere 2S as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0011/0003:046D:406A.0012/input/input35
[ 8405.257721] logitech-hidpp-device 0003:046D:406A.0012: input,hidraw1: USB HID v1.11 Keyboard [Logitech MX Anywhere 2S] on usb-0000:04:00.4-1:1
```

**Comment by DonkZZ** [comment]
https://github.com/pwr-Solaar/Solaar/pull/534/files

**Comment by yochananmarqos** [comment]
Merging that PR worked, thanks for pointing it out!

**Comment by AlexandreBonneau** [comment]
Using solaar version `1.0.1` (`1.0.1+dfsg-3` from Debian to be exact), the MX Anywhere 2S dongle is shown in the solaar window, however it stays grayed out.
Am I missing something?
