### ISSUE TITLE
cannot see settings on K800 - solaar-cli crashes

### ISSUE THREAD

**Issue by badpenguin** [pwr-Solaar/Solaar#558]
I want to programmatically change settings. I'm trying to light the keyboard. I tried with xev and evtest but FN+F6 is not recognized. Then i hoped that at least i could use solaar-cli.
I run first:
```
$ solaar-cli show 
Unifying Receiver [/dev/hidraw4:3F1D977E] with 2 devices
1: Wireless Illuminated Keyboard K800 [K800:C6D50F66] 
2: Wireless Mouse MX Master [MX Master:C7C1A453] 
```
Then if i run:
```
$ solaar-cli show -v 1
1: Wireless Illuminated Keyboard K800
   Codename     : K800
   Kind         : keyboard
   Wireless PID : 2010
   Protocol     : HID++ 1.0
   Polling rate : 20 ms
   Serial number: C6D50F66
        Firmware: 22.01.B0019
      Bootloader: 02.01
           Other: 00.07
   The power switch is located on the top right corner.
   Notifications: 0x100000 = battery status.
Traceback (most recent call last):
  File "/usr/bin/solaar-cli", line 42, in <module>
    solaar.cli.main()
  File "/usr/share/solaar/lib/solaar/cli.py", line 431, in main
    args.cmd(receiver, args)
  File "/usr/share/solaar/lib/solaar/cli.py", line 213, in show_devices
    _print_device(dev, args.verbose)
  File "/usr/share/solaar/lib/solaar/cli.py", line 190, in _print_device
    text = '%d%%' % level
TypeError: %d format: a number is required, not NoneType
```

Its working for the mouse anyway. I tried to uncomment the offending line of code (it was about batteris) but still it show no available settings.

**Comment by rathann** [comment]
Please try updating to the latest solaar (1.0.1) first. `solaar-cli` doesn't exist in the latest release (you can use the main `solaar` executable from CLI, too.

**Comment by pfps** [comment]
Closing due to no response.
