### ISSUE TITLE
M510 Error

### ISSUE THREAD

**Issue by JohnnyDevNull** [pwr-Solaar/Solaar#567]
After startup the M510 mouse is not recognized along with my K540/K545.

When i run `sudo solaar -d` it gets connected but displayed as battery unknown with smoot scrolling and side scrolling disabled read/write operation failed...

OS: XUbuntu 18.04

```
 $ sudo solaar -d
[sudo] password for philipp: 
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
21:59:16,613     INFO [MainThread] root: language en_US (UTF-8), translations path None
21:59:16,654     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
/usr/share/solaar/lib/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/share/solaar/lib/solaar/ui/tray.py:72: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
21:59:16,679     INFO [MainThread] solaar.ui.tray: using AppIndicator3
21:59:16,679     INFO [MainThread] solaar.ui.notify: starting desktop notifications
21:59:16,694     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
21:59:16,695     INFO [MainThread] solaar.listener: starting receiver listening threads
21:59:16,697     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw0', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1211', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
21:59:16,702     INFO [ReceiverListener:hidraw0] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw0,12)> (12)
21:59:16,702     INFO [ReceiverListener:hidraw0] solaar.listener: <UnifyingReceiver(/dev/hidraw0,12)>: notifications listener has started (12)
21:59:16,706     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,12)>: receiver notifications enabled => ('wireless', 'software present')
21:59:16,712     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,12)>: present, No paired devices. (0) 
21:59:16,714     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,12)>: found new device 1 (4051)
21:59:16,714     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,04,125140) triggered new device <PairedDevice(1,4051,M510)> (mouse)
21:59:16,716     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,12)>: present, 1 paired device. (0) 

(solaar:3661): Gdk-CRITICAL **: 21:59:16.855: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
21:59:17,552     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <PairedDevice(1,4051,M510)>: device notifications enabled None
21:59:17,569     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {u'4076:14A4418D': {u'_name': u'K540/K545'}, u'_version': u'0.9.2', u'4051:B339CD07': {u'_name': u'Wireless Mouse M510'}} to /home/philipp/.config/solaar/config.json
21:59:17,582     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {u'4076:14A4418D': {u'_name': u'K540/K545'}, u'_version': u'0.9.2', u'4051:B339CD07': {u'_name': u'Wireless Mouse M510'}} to /home/philipp/.config/solaar/config.json
21:59:17,598    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(1,41,04,125140)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 207, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 54, in process
    return _process_device_notification(device, status, notification)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 97, in _process_device_notification
    return _process_hidpp10_notification(device, status, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 174, in _process_hidpp10_notification
    status.changed(active=link_established)
  File "/usr/share/solaar/lib/logitech_receiver/status.py", line 271, in changed
    self.read_battery(timestamp)
  File "/usr/share/solaar/lib/logitech_receiver/status.py", line 228, in read_battery
    if battery is None and _hidpp20.FEATURE.SOLAR_DASHBOARD in d.features:
TypeError: argument of type 'NoneType' is not iterable
21:59:17,602     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,12)>: found new device 2 (4076)
21:59:17,602     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(2,41,04,317640) triggered new device <PairedDevice(2,4076,K540/K545)> (keyboard)
21:59:17,606     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,12)>: present, 2 paired devices. (0) 
```

```
$ sudo solaar --version
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
solaar 0.9.2
```

**Comment by rathann** [comment]
Please update to 1.0.1 and retry.

**Comment by pfps** [comment]
Closing due to no response.
If you are still experiencing this problem, update to the version of Solaar from this repository and reopen this issue with the new information.
