### ISSUE TITLE
DJ notifications not handled correctly

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#645]
**Information**
- Solaar version: current version from github

I'm receiving DJ notifications, which look different from other notifications and cause problems in Solaar such as 

09:05:33,047    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(1,41,01,4D401E4000000400000000)
Traceback (most recent call last):
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/listener.py", line 225, in _notifications_handler
    _notifications.process(dev, n)
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/notifications.py", line 54, in process
    return _process_device_notification(device, status, notification)
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/notifications.py", line 97, in _process_device_notification
    return _process_hidpp10_notification(device, status, n)
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/notifications.py", line 172, in _process_hidpp10_notification
    assert wpid == device.wpid, "%s wpid mismatch, got %s" % (device, wpid)
AssertionError: <PairedDevice(1,404D,K400 Plus)> wpid mismatch, got 1E40

I'll try to hunt down some of the changes needed to fix these problems.

**Comment by pfps** [comment]
Closed by PR #646
