### ISSUE TITLE
MX Master 3 receiver not being picked up by Solaar

### ISSUE THREAD

**Issue by Jamesking56** [pwr-Solaar/Solaar#681]
**Information**

- Solaar version: 1.0.1
- Distribution: Ubuntu 18.04
- Kernel version (ex. `uname -srmo`): `Linux 5.3.0-28-generic x86_64 GNU/Linux`
- Output of `solaar show`:
```
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <bound method Receiver.__del__ of <UnifyingReceiver(/dev/hidraw4,3)>> ignored
solaar: error: Logitech receiver not found
```

**Describe the bug**
MX Master 3 receiver not being picked up by GUI or CLI

**To Reproduce**

Not sure

**Screenshots**
N/A

**Additional context**
`solar -dd show` does seem to try to pick up the receiver:

```
19:57:28,415    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
19:57:28,418    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 03CF6B94AC0106070000000000000000]
19:57:28,419    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
19:57:28,420    ERROR [MainThread] logitech_receiver.base: write failed, assuming handle 3 no longer available
19:57:28,421    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw4', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1211', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 359, in __init__
    self.may_unpair = self.write_register(_R.receiver_pairing) is None
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 149, in write_register
    return device.request(request_id, *value)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 444, in request
    return _base.request(self.handle, 0xFF, request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Broken pipe')}
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <bound method Receiver.__del__ of <UnifyingReceiver(/dev/hidraw4,3)>> ignored
19:57:28,424    DEBUG [MainThread] solaar.cli: [/dev/hidraw4] => None
solaar: error: Logitech receiver not found
```

**Comment by pfps** [comment]
This might be the result of running a version of Solaar that has python3-only code but doesn't enforce running with python3.  To check, try `python3 solaar` and see if the error still occurs.  If so, the solution is to clone Solaar from this repository and run it.

**Comment by pfps** [comment]
Almost certainly this is from a slightly old version of Solaar where the transition to python3 isn't complete.  See #685

**Comment by pfps** [comment]
@Jamesking56 Did you try with python3?

**Comment by Jamesking56** [comment]
It worked after I rebooted the machine

**Comment by pfps** [comment]
So all is well?

**Comment by Jamesking56** [comment]
Yeah its all working now :+1:
