### ISSUE TITLE
Exception: no settings for Wireless Trackball M570

### ISSUE THREAD

**Issue by scottwn** [pwr-Solaar/Solaar#923]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.0.2
- Distribution: RHEL 7.8
- Kernel version (ex. `uname -srmo`): `3.10.0-1127.13.1.el7.x86_64`
- Output of `solaar show`:
```
scott@oc5862681154 ~/S/bin (master)> ./solaar show
Unifying Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:c52b
  Serial       : D32F971E
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=118

  1: Wireless Trackball M570
     Codename     : M570
     Kind         : trackball
     Wireless PID : 1028
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 5C12D858
          Firmware: 26.00.B0003
        Bootloader: 02.06
             Other: 00.01
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: 75%, discharging.
```

**Describe the bug**
When I run `solaar config` I get an exception that says "no settings". Not sure if Solaar just doesn't work with the M570 or this is an unexpected bug.

```
scott@oc5862681154 ~/S/bin (master)> ./solaar config 1
solaar: error: Traceback (most recent call last):
  File "/home/scott/Solaar/lib/solaar/cli/__init__.py", line 175, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/home/scott/Solaar/lib/solaar/cli/config.py", line 61, in run
    raise Exception('no settings for %s' % dev.name)
Exception: no settings for Wireless Trackball M570
```

**Comment by pfps** [comment]
The M570 uses HID++ 1.0, which doesn't have any way to discover the settings of the device.  So Solaar has to depend on a list of the settings in a file (lib/logitech_receiver/descriptors.py).  The M570 is in that file, but there are no settings listed for it.

If there are are any relevant settings for the device then you will have to discover them yourself.  The easiest way to do so would be to run the Logitech software for the device under windows and see what it does with the M570.
