### ISSUE TITLE
can't pair G613 with receiver 

### ISSUE THREAD

**Issue by seddikalaouiismaili** [pwr-Solaar/Solaar#949]
Hi 
i have a problem to pairing my keyboard G613 with receiver on my fedora workstation .
see below the output of pair :

```
0:51:50,015    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
00:51:50,016    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 03660D6DDA0101070000000000000000]
00:51:50,017    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
00:51:50,018    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F80 B20300]
00:51:50,019    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {80B2}: 3 = invalid value
00:51:50,019    DEBUG [MainThread] solaar.cli: [/dev/hidraw5] => <LightspeedReceiver(/dev/hidraw5,3)>
00:51:50,035    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8100 000000]
00:51:50,038    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8100 000900]
00:51:50,038    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 200000]
00:51:50,040    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
00:51:50,040    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
00:51:50,040    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
00:51:50,042    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
00:51:50,042    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
00:51:50,042    ERROR [MainThread] logitech_receiver.device: failed to read Nano wpid for device 1 of <LightspeedReceiver(/dev/hidraw5,3)>
00:51:50,042    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/tmp/Solaar/lib/logitech_receiver/receiver.py", line 150, in register_new_device
    dev = Device(self, number, notification)
  File "/tmp/Solaar/lib/logitech_receiver/device.py", line 111, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='read Nano wpid')
logitech_receiver.base.NoSuchDevice: {'number': 1, 'receiver': <LightspeedReceiver(/dev/hidraw5,3)>, 'error': 'read Nano wpid'}
00:51:50,043  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw5,3)>: looked for device 1, not found
00:51:50,044    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 010014]
00:51:50,046    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 4A01 000000]
00:51:50,046     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw5,3)>: pairing lock is open
00:51:50,047    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 80B2 000000]
Pairing: turn your new device on (timing out in 20 seconds).
00:51:50,049    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8102 000000]
00:52:09,702    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 4A00 010000]
00:52:09,702     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw5,3)>: pairing lock is closed
00:52:09,703  WARNING [MainThread] logitech_receiver.notifications: pairing error 1: device timeout
solaar: error: Traceback (most recent call last):
  File "/tmp/Solaar/lib/solaar/cli/__init__.py", line 196, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/tmp/Solaar/lib/solaar/cli/pair.py", line 92, in run
    raise Exception('pairing failed: %s' % error)
Exception: pairing failed: device timeout

```

do you have any suggestion ? 

many thanks

**Comment by pfps** [comment]
Which version of Solaar are you using?
This is a keyboard that has a dedicated receiver (i.e., not one with the Logitech Unifying logo on it)?
Is your keyboard actually paired, but you are getting an error saying that pairing failed?  (Check by doing `solaar show` afterwards.)

**Comment by pfps** [comment]
Also, this two exceptions you are seeing are expected.  The first arises when Solaar tries to check for a paired device - there is none so Solaar raises an exception that is handled inside Solaar.   The second is just saying that no pairing happened.

One thing to try is to get on a Windows PC or Mac and try pairing there.

**Comment by seddikalaouiismaili** [comment]
hi,

thanks for replying ...
i have installed the last version of solaar from GIT repository.

i will put the solaar show when i got home.
thanks

**Comment by seddikalaouiismaili** [comment]
> Also, this two exceptions you are seeing are expected. The first arises when Solaar tries to check for a paired device - there is none so Solaar raises an exception that is handled inside Solaar. The second is just saying that no pairing happened.
> 
> One thing to try is to get on a Windows PC or Mac and try pairing there.

I did it yet, try to paring keyborad , and it works

**Comment by pfps** [comment]
So the exact same pairing works on Windows using the Logitech software but fails on Linux using Solaar.  Is this correct?
If so, there is probably something special that needs to be done to get this receiver to pair.  I'll try to find out more about this.

**Comment by seddikalaouiismaili** [comment]
> So the exact same pairing works on Windows using the Logitech software but fails on Linux using Solaar. Is this correct?
> If so, there is probably something special that needs to be done to get this receiver to pair. I'll try to find out more about this.

Yep exactly what i meant ...
in my fedora workstation (f32, kernel : 5.8.8 ) it deosn't work !! 
i will put more debug aboit this ... (solaar show   etc ... )

**Comment by pfps** [comment]
I have hacked in a quick change to see whether the problem is the pairing lock opening message that solaar is sending.   Please test out PR #950 (which also has some other fixes, but ones that probably won't affect your problem).  The relevant change is line 70 in lib/solaar/cli/pair.py

To run PR #950, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/950/head:pull_950
git checkout pull_950
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_950
git fetch origin pull/950/head
git reset --hard FETCH_HEAD
```

**Comment by seddikalaouiismaili** [comment]
ok i will try this now

**Comment by seddikalaouiismaili** [comment]
hello 
i have the same PB 
here what i did for fetching PR 
```
464  git fetch origin pull/950/head:pull_950
  465  git checkout pull_950
  466  git fetch origin pull/950/head
  467  git branch 
  468  git reset --hard FETCH_HEAD

```
The output log : 
```
1:12:31,976    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
21:12:31,978    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 03660D6DDA0101070000000000000000]
21:12:31,978    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
21:12:31,980    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F80 B20300]
21:12:31,980    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {80B2}: 3 = invalid value
21:12:31,980    DEBUG [MainThread] solaar.cli: [/dev/hidraw5] => <LightspeedReceiver(/dev/hidraw5,3)>
21:12:31,997    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8100 000000]
21:12:31,998    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8100 000900]
21:12:31,998    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 200000]
21:12:32,000    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
21:12:32,000    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
21:12:32,000    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
21:12:32,002    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
21:12:32,002    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
21:12:32,002    ERROR [MainThread] logitech_receiver.device: failed to read Nano wpid for device 1 of <LightspeedReceiver(/dev/hidraw5,3)>
21:12:32,002    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/tmp/Solaar/lib/logitech_receiver/receiver.py", line 150, in register_new_device
    dev = Device(self, number, notification)
  File "/tmp/Solaar/lib/logitech_receiver/device.py", line 111, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='read Nano wpid')
logitech_receiver.base.NoSuchDevice: {'number': 1, 'receiver': <LightspeedReceiver(/dev/hidraw5,3)>, 'error': 'read Nano wpid'}
21:12:32,003  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw5,3)>: looked for device 1, not found
21:12:32,004    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 010114]
21:12:32,006    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 4A01 000000]
21:12:32,006     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw5,3)>: pairing lock is open
21:12:32,007    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 80B2 000000]
Pairing: turn your new device on (timing out in 20 seconds).
21:12:51,048    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 4A00 010000]
21:12:51,049     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw5,3)>: pairing lock is closed
21:12:51,049  WARNING [MainThread] logitech_receiver.notifications: pairing error 1: device timeout
solaar: error: Traceback (most recent call last):
  File "/tmp/Solaar/lib/solaar/cli/__init__.py", line 196, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/tmp/Solaar/lib/solaar/cli/pair.py", line 95, in run
    raise Exception('pairing failed: %s' % error)
Exception: pairing failed: device timeout

```

**Comment by seddikalaouiismaili** [comment]
+

my result of solaar show 
```
Lightspeed Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:c53d
  Serial       : 660D6DDA
    Firmware   : 43.00.B0006
    Bootloader : 02.10
    Other      : AA.D2
  Has 0 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

```

**Comment by pfps** [comment]
OK, no change, even though the pairing unlock message was different.

So even though you are doing everything correctly - running `solaar pair`, turning your mouse (off and) on - no pairing is happening. Your receiver is reporting that it turned its pairing lock on and about 20 seconds later that it turned its pairing lock off, indicating that it was looking for a device to pair with.  This happens even with the slightly changed message that Solaar sends to turn the pairing lock on.

So I'm stumped.

**Comment by seddikalaouiismaili** [comment]
thanks for replying ...
you need more log for solaar pairing ?..

regards

**Comment by pfps** [comment]
The logs that you have provided give all the available information from Solaar.  Solaar is waiting for the receiver to send some information to Linux but nothing is happening.  The only other information that would be useful is the actual RF communications that the receiver hears from devices, but I don't think there is any way to get that information.

**Comment by pfps** [comment]
I have asked someone who might know more about pairing with Lightspeed receivers, so we are waiting for a response to my question.

**Comment by seddikalaouiismaili** [comment]
ok many thanks...
i will be available for debug.

regards
sai

**Comment by pfps** [comment]
The G613, and other similar keyboards, pair differently from other Logitech devices.  Instead of turning on your device when the receiver is ready to pair you long-press the lightspeed connect button (the one next to the bluetooth button).   I think that you had to have short-pressed the lightspeed button beforehand so the keyboard is in lightspeed mode.

Is this what you were doing to pair under Windows/Mac?

**Comment by seddikalaouiismaili** [comment]
on Windows,  i don't to press for long time in button ... 2 sec is enough.
And after that i have paired it from wireless setting.
that's so bad from logitech... it doesn't provide any support for GNU/LINUX
os.
:(
regards

regards..

**Comment by pfps** [comment]
I think you misunderstood.   On Linux under Solaar I think you should be able to pair by pressing the lightspeed connect button after opening up pairing, just like you do in Windows.

**Comment by seddikalaouiismaili** [comment]
i have pressed on button for long time !!! 

```
1:02:09,996    ERROR [MainThread] logitech_receiver.device: failed to read Nano wpid for device 1 of <LightspeedReceiver(/dev/hidraw2,3)>
21:02:09,996    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/tmp/Solaar/lib/logitech_receiver/receiver.py", line 150, in register_new_device
    dev = Device(self, number, notification)
  File "/tmp/Solaar/lib/logitech_receiver/device.py", line 111, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='read Nano wpid')
logitech_receiver.base.NoSuchDevice: {'number': 1, 'receiver': <LightspeedReceiver(/dev/hidraw2,3)>, 'error': 'read Nano wpid'}
21:02:09,997  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw2,3)>: looked for device 1, not found
21:02:09,999     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw2,3)>: pairing lock is open
Pairing: turn your new device on (timing out in 20 seconds).
21:02:29,808     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw2,3)>: pairing lock is closed
21:02:29,808  WARNING [MainThread] logitech_receiver.notifications: pairing error 1: device timeout
solaar: error: Traceback (most recent call last):
  File "/tmp/Solaar/lib/solaar/cli/__init__.py", line 196, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/tmp/Solaar/lib/solaar/cli/pair.py", line 95, in run
    raise Exception('pairing failed: %s' % error)
Exception: pairing failed: device timeout

```

Regards

**Comment by pfps** [comment]
Hmm.  Then something else is wrong.  So I'm stumped (again).
If you can pair under Windows or Mac then I don't think that you will get any help from Logitech.

**Comment by seddikalaouiismaili** [comment]
any suggestion plz ?

**Comment by seddikalaouiismaili** [comment]
I am surprised, it works now ,,
i have done the same thing, but now i have lunched  the solaar after turn off my device ...and then i turned on , and it works fine now .
thanks for helping :)

**Comment by pfps** [comment]
Weird, but if you're happy then I'm happy.

Is there anything more to be done here?

**Comment by seddikalaouiismaili** [comment]
no many thanks man :) 
glade it works :+1:
